package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgAccionesdatos generated by hbm2java
 */
public class CfgAccionesdatos  implements java.io.Serializable {


     private boolean cadIdacciondato;
     private String cadCodigoaccion;
     private String cadDescripcion;
     private Set logCfgtablases = new HashSet(0);
     private Set logSistematablases = new HashSet(0);

    public CfgAccionesdatos() {
    }

	
    public CfgAccionesdatos(boolean cadIdacciondato) {
        this.cadIdacciondato = cadIdacciondato;
    }
    public CfgAccionesdatos(boolean cadIdacciondato, String cadCodigoaccion, String cadDescripcion, Set logCfgtablases, Set logSistematablases) {
       this.cadIdacciondato = cadIdacciondato;
       this.cadCodigoaccion = cadCodigoaccion;
       this.cadDescripcion = cadDescripcion;
       this.logCfgtablases = logCfgtablases;
       this.logSistematablases = logSistematablases;
    }
   
    public boolean isCadIdacciondato() {
        return this.cadIdacciondato;
    }
    
    public void setCadIdacciondato(boolean cadIdacciondato) {
        this.cadIdacciondato = cadIdacciondato;
    }
    public String getCadCodigoaccion() {
        return this.cadCodigoaccion;
    }
    
    public void setCadCodigoaccion(String cadCodigoaccion) {
        this.cadCodigoaccion = cadCodigoaccion;
    }
    public String getCadDescripcion() {
        return this.cadDescripcion;
    }
    
    public void setCadDescripcion(String cadDescripcion) {
        this.cadDescripcion = cadDescripcion;
    }
    public Set getLogCfgtablases() {
        return this.logCfgtablases;
    }
    
    public void setLogCfgtablases(Set logCfgtablases) {
        this.logCfgtablases = logCfgtablases;
    }
    public Set getLogSistematablases() {
        return this.logSistematablases;
    }
    
    public void setLogSistematablases(Set logSistematablases) {
        this.logSistematablases = logSistematablases;
    }




}


