package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgAntecedentestest generated by hbm2java
 */
public class CfgAntecedentestest  implements java.io.Serializable {


     private CfgAntecedentestestId id;
     private CfgAntecedentes cfgAntecedentes;

    public CfgAntecedentestest() {
    }

    public CfgAntecedentestest(CfgAntecedentestestId id, CfgAntecedentes cfgAntecedentes) {
       this.id = id;
       this.cfgAntecedentes = cfgAntecedentes;
    }
   
    public CfgAntecedentestestId getId() {
        return this.id;
    }
    
    public void setId(CfgAntecedentestestId id) {
        this.id = id;
    }
    public CfgAntecedentes getCfgAntecedentes() {
        return this.cfgAntecedentes;
    }
    
    public void setCfgAntecedentes(CfgAntecedentes cfgAntecedentes) {
        this.cfgAntecedentes = cfgAntecedentes;
    }




}


