package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgBacantibiogramasantibiot generated by hbm2java
 */
public class CfgBacantibiogramasantibiot  implements java.io.Serializable {


     private CfgBacantibiogramasantibiotId id;
     private CfgBacantibioticos cfgBacantibioticos;
     private CfgBacantibiogramas cfgBacantibiogramas;
     private String cbadActivo;
     private String cbadOpcional;
     private Short cbadSort;
     private String cbadResultadoomision;
     private String cbadHost;

    public CfgBacantibiogramasantibiot() {
    }

	
    public CfgBacantibiogramasantibiot(CfgBacantibiogramasantibiotId id, CfgBacantibioticos cfgBacantibioticos, CfgBacantibiogramas cfgBacantibiogramas) {
        this.id = id;
        this.cfgBacantibioticos = cfgBacantibioticos;
        this.cfgBacantibiogramas = cfgBacantibiogramas;
    }
    public CfgBacantibiogramasantibiot(CfgBacantibiogramasantibiotId id, CfgBacantibioticos cfgBacantibioticos, CfgBacantibiogramas cfgBacantibiogramas, String cbadActivo, String cbadOpcional, Short cbadSort, String cbadResultadoomision, String cbadHost) {
       this.id = id;
       this.cfgBacantibioticos = cfgBacantibioticos;
       this.cfgBacantibiogramas = cfgBacantibiogramas;
       this.cbadActivo = cbadActivo;
       this.cbadOpcional = cbadOpcional;
       this.cbadSort = cbadSort;
       this.cbadResultadoomision = cbadResultadoomision;
       this.cbadHost = cbadHost;
    }
   
    public CfgBacantibiogramasantibiotId getId() {
        return this.id;
    }
    
    public void setId(CfgBacantibiogramasantibiotId id) {
        this.id = id;
    }
    public CfgBacantibioticos getCfgBacantibioticos() {
        return this.cfgBacantibioticos;
    }
    
    public void setCfgBacantibioticos(CfgBacantibioticos cfgBacantibioticos) {
        this.cfgBacantibioticos = cfgBacantibioticos;
    }
    public CfgBacantibiogramas getCfgBacantibiogramas() {
        return this.cfgBacantibiogramas;
    }
    
    public void setCfgBacantibiogramas(CfgBacantibiogramas cfgBacantibiogramas) {
        this.cfgBacantibiogramas = cfgBacantibiogramas;
    }
    public String getCbadActivo() {
        return this.cbadActivo;
    }
    
    public void setCbadActivo(String cbadActivo) {
        this.cbadActivo = cbadActivo;
    }
    public String getCbadOpcional() {
        return this.cbadOpcional;
    }
    
    public void setCbadOpcional(String cbadOpcional) {
        this.cbadOpcional = cbadOpcional;
    }
    public Short getCbadSort() {
        return this.cbadSort;
    }
    
    public void setCbadSort(Short cbadSort) {
        this.cbadSort = cbadSort;
    }
    public String getCbadResultadoomision() {
        return this.cbadResultadoomision;
    }
    
    public void setCbadResultadoomision(String cbadResultadoomision) {
        this.cbadResultadoomision = cbadResultadoomision;
    }
    public String getCbadHost() {
        return this.cbadHost;
    }
    
    public void setCbadHost(String cbadHost) {
        this.cbadHost = cbadHost;
    }




}


