package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.util.Set;

import javax.persistence.Transient;

/**
 * CfgBacrecuentocolonias generated by hbm2java
 */
public class CfgBacrecuentocolonias implements java.io.Serializable {

	private int cbrcIdbacrecuentocolonia;
	private String cbrcCodigo;
	private String cbrcDescripcion;
	private Integer cbrcSort;
	private String cbrcActivo;
	private String cbrcHost;
	@Transient
	private Set datosFichasexamenesmicroorgs;

	public CfgBacrecuentocolonias() {
	}

	public CfgBacrecuentocolonias(int cbrcIdbacrecuentocolonia) {
		this.cbrcIdbacrecuentocolonia = cbrcIdbacrecuentocolonia;
	}

	public CfgBacrecuentocolonias(int cbrcIdbacrecuentocolonia, String cbrcCodigo, String cbrcDescripcion,
			Integer cbrcSort, String cbrcActivo, String cbrcHost, Set datosFichasexamenesmicroorgs) {
		this.cbrcIdbacrecuentocolonia = cbrcIdbacrecuentocolonia;
		this.cbrcCodigo = cbrcCodigo;
		this.cbrcDescripcion = cbrcDescripcion;
		this.cbrcSort = cbrcSort;
		this.cbrcActivo = cbrcActivo;
		this.cbrcHost = cbrcHost;
		this.datosFichasexamenesmicroorgs = datosFichasexamenesmicroorgs;
	}

	public int getCbrcIdbacrecuentocolonia() {
		return this.cbrcIdbacrecuentocolonia;
	}

	public void setCbrcIdbacrecuentocolonia(int cbrcIdbacrecuentocolonia) {
		this.cbrcIdbacrecuentocolonia = cbrcIdbacrecuentocolonia;
	}

	public String getCbrcCodigo() {
		return this.cbrcCodigo;
	}

	public void setCbrcCodigo(String cbrcCodigo) {
		this.cbrcCodigo = cbrcCodigo;
	}

	public String getCbrcDescripcion() {
		return this.cbrcDescripcion;
	}

	public void setCbrcDescripcion(String cbrcDescripcion) {
		this.cbrcDescripcion = cbrcDescripcion;
	}

	public Integer getCbrcSort() {
		return this.cbrcSort;
	}

	public void setCbrcSort(Integer cbrcSort) {
		this.cbrcSort = cbrcSort;
	}

	public String getCbrcActivo() {
		return this.cbrcActivo;
	}

	public void setCbrcActivo(String cbrcActivo) {
		this.cbrcActivo = cbrcActivo;
	}

	public String getCbrcHost() {
		return this.cbrcHost;
	}

	public void setCbrcHost(String cbrcHost) {
		this.cbrcHost = cbrcHost;
	}

	public Set getDatosFichasexamenesmicroorgs() {
		return this.datosFichasexamenesmicroorgs;
	}

	public void setDatosFichasexamenesmicroorgs(Set datosFichasexamenesmicroorgs) {
		this.datosFichasexamenesmicroorgs = datosFichasexamenesmicroorgs;
	}

}
