package com.grupobios.bioslis.entity;


/**
 * CfgBacmedioscultivos generated by hbm2java
 */
public class CfgBacmedioscultivos  implements java.io.Serializable {


     private byte cbmcIdmediocultivo;
     private String cbmcCodigo;
     private String cbmcDescripcion;
     private String cbmcPrefijo;
     private String cbmcActivo;
     private Byte cbmcSort;

    public CfgBacmedioscultivos() {
    }

	
    public CfgBacmedioscultivos(byte cbmcIdmediocultivo) {
        this.cbmcIdmediocultivo = cbmcIdmediocultivo;
    }
    public CfgBacmedioscultivos(byte cbmcIdmediocultivo, String cbmcCodigo, String cbmcDescripcion, String cbmcPrefijo, String cbmcActivo, Byte cbmcSort) {
       this.cbmcIdmediocultivo = cbmcIdmediocultivo;
       this.cbmcCodigo = cbmcCodigo;
       this.cbmcDescripcion = cbmcDescripcion;
       this.cbmcPrefijo = cbmcPrefijo;
       this.cbmcActivo = cbmcActivo;
       this.cbmcSort = cbmcSort;
    }
   
    public byte getCbmcIdmediocultivo() {
        return this.cbmcIdmediocultivo;
    }
    
    public void setCbmcIdmediocultivo(byte cbmcIdmediocultivo) {
        this.cbmcIdmediocultivo = cbmcIdmediocultivo;
    }
    public String getCbmcCodigo() {
        return this.cbmcCodigo;
    }
    
    public void setCbmcCodigo(String cbmcCodigo) {
        this.cbmcCodigo = cbmcCodigo;
    }
    public String getCbmcDescripcion() {
        return this.cbmcDescripcion;
    }
    
    public void setCbmcDescripcion(String cbmcDescripcion) {
        this.cbmcDescripcion = cbmcDescripcion;
    }
    public String getCbmcPrefijo() {
        return this.cbmcPrefijo;
    }
    
    public void setCbmcPrefijo(String cbmcPrefijo) {
        this.cbmcPrefijo = cbmcPrefijo;
    }
    public String getCbmcActivo() {
        return this.cbmcActivo;
    }
    
    public void setCbmcActivo(String cbmcActivo) {
        this.cbmcActivo = cbmcActivo;
    }
    public Byte getCbmcSort() {
        return this.cbmcSort;
    }
    
    public void setCbmcSort(Byte cbmcSort) {
        this.cbmcSort = cbmcSort;
    }




}


