package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgBacantibiogramasantibiotId generated by hbm2java
 */
public class CfgBacantibiogramasantibiotId  implements java.io.Serializable {


     private short cbadIdbacantibiograma;
     private short cbadIdbacantibiotico;

    public CfgBacantibiogramasantibiotId() {
    }

    public CfgBacantibiogramasantibiotId(short cbadIdbacantibiograma, short cbadIdbacantibiotico) {
       this.cbadIdbacantibiograma = cbadIdbacantibiograma;
       this.cbadIdbacantibiotico = cbadIdbacantibiotico;
    }
   
    public short getCbadIdbacantibiograma() {
        return this.cbadIdbacantibiograma;
    }
    
    public void setCbadIdbacantibiograma(short cbadIdbacantibiograma) {
        this.cbadIdbacantibiograma = cbadIdbacantibiograma;
    }
    public short getCbadIdbacantibiotico() {
        return this.cbadIdbacantibiotico;
    }
    
    public void setCbadIdbacantibiotico(short cbadIdbacantibiotico) {
        this.cbadIdbacantibiotico = cbadIdbacantibiotico;
    }




}


