package com.grupobios.bioslis.entity;


// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgBacantibioticoshalo generated by hbm2java
 */
public class CfgBacantibioticoshalo  implements java.io.Serializable {


     private short cbahIdantibioticohalo;
     private Short cbahIdbacmicroorganismo;
     private Short cbahIdbacantibiotico;
     private Short cbahSensiblevalor;
     private String cbahSensibleintermediosigno;
     private Short cbahResistentevalor;
     private String cbahIntermedioresistentesigno;
     private Boolean cbahIdmetodoevaluacionr;

    public CfgBacantibioticoshalo() {
    }

	
    public CfgBacantibioticoshalo(short cbahIdantibioticohalo) {
        this.cbahIdantibioticohalo = cbahIdantibioticohalo;
    }
    public CfgBacantibioticoshalo(short cbahIdantibioticohalo, Short cbahIdbacmicroorganismo, Short cbahIdbacantibiotico, Short cbahSensiblevalor, String cbahSensibleintermediosigno, Short cbahResistentevalor, String cbahIntermedioresistentesigno, Boolean cbahIdmetodoevaluacionr) {
       this.cbahIdantibioticohalo = cbahIdantibioticohalo;
       this.cbahIdbacmicroorganismo = cbahIdbacmicroorganismo;
       this.cbahIdbacantibiotico = cbahIdbacantibiotico;
       this.cbahSensiblevalor = cbahSensiblevalor;
       this.cbahSensibleintermediosigno = cbahSensibleintermediosigno;
       this.cbahResistentevalor = cbahResistentevalor;
       this.cbahIntermedioresistentesigno = cbahIntermedioresistentesigno;
       this.cbahIdmetodoevaluacionr = cbahIdmetodoevaluacionr;
    }
   
    public short getCbahIdantibioticohalo() {
        return this.cbahIdantibioticohalo;
    }
    
    public void setCbahIdantibioticohalo(short cbahIdantibioticohalo) {
        this.cbahIdantibioticohalo = cbahIdantibioticohalo;
    }
    public Short getCbahIdbacmicroorganismo() {
        return this.cbahIdbacmicroorganismo;
    }
    
    public void setCbahIdbacmicroorganismo(Short cbahIdbacmicroorganismo) {
        this.cbahIdbacmicroorganismo = cbahIdbacmicroorganismo;
    }
    public Short getCbahIdbacantibiotico() {
        return this.cbahIdbacantibiotico;
    }
    
    public void setCbahIdbacantibiotico(Short cbahIdbacantibiotico) {
        this.cbahIdbacantibiotico = cbahIdbacantibiotico;
    }
    public Short getCbahSensiblevalor() {
        return this.cbahSensiblevalor;
    }
    
    public void setCbahSensiblevalor(Short cbahSensiblevalor) {
        this.cbahSensiblevalor = cbahSensiblevalor;
    }
    public String getCbahSensibleintermediosigno() {
        return this.cbahSensibleintermediosigno;
    }
    
    public void setCbahSensibleintermediosigno(String cbahSensibleintermediosigno) {
        this.cbahSensibleintermediosigno = cbahSensibleintermediosigno;
    }
    public Short getCbahResistentevalor() {
        return this.cbahResistentevalor;
    }
    
    public void setCbahResistentevalor(Short cbahResistentevalor) {
        this.cbahResistentevalor = cbahResistentevalor;
    }
    public String getCbahIntermedioresistentesigno() {
        return this.cbahIntermedioresistentesigno;
    }
    
    public void setCbahIntermedioresistentesigno(String cbahIntermedioresistentesigno) {
        this.cbahIntermedioresistentesigno = cbahIntermedioresistentesigno;
    }
    public Boolean getCbahIdmetodoevaluacionr() {
        return this.cbahIdmetodoevaluacionr;
    }
    
    public void setCbahIdmetodoevaluacionr(Boolean cbahIdmetodoevaluacionr) {
        this.cbahIdmetodoevaluacionr = cbahIdmetodoevaluacionr;
    }




}


