package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgBacantibiogramas generated by hbm2java
 */
public class CfgBacantibiogramas  implements java.io.Serializable {


     private byte cbaIdbacantibiograma;
     private String cbaCodigo;
     private String cbaDescripcion;
     private String cbaActivo;
     private Byte cbaSort;
     private String cbaHost;
     private Set cfgBacantibiogramasantibiots = new HashSet(0);

    public CfgBacantibiogramas() {
    }

	
    public CfgBacantibiogramas(byte cbaIdbacantibiograma, String cbaCodigo) {
        this.cbaIdbacantibiograma = cbaIdbacantibiograma;
        this.cbaCodigo = cbaCodigo;
    }
    public CfgBacantibiogramas(byte cbaIdbacantibiograma, String cbaCodigo, String cbaDescripcion, String cbaActivo, Byte cbaSort, String cbaHost, Set cfgBacantibiogramasantibiots) {
       this.cbaIdbacantibiograma = cbaIdbacantibiograma;
       this.cbaCodigo = cbaCodigo;
       this.cbaDescripcion = cbaDescripcion;
       this.cbaActivo = cbaActivo;
       this.cbaSort = cbaSort;
       this.cbaHost = cbaHost;
       this.cfgBacantibiogramasantibiots = cfgBacantibiogramasantibiots;
    }
   
    public byte getCbaIdbacantibiograma() {
        return this.cbaIdbacantibiograma;
    }
    
    public void setCbaIdbacantibiograma(byte cbaIdbacantibiograma) {
        this.cbaIdbacantibiograma = cbaIdbacantibiograma;
    }
    public String getCbaCodigo() {
        return this.cbaCodigo;
    }
    
    public void setCbaCodigo(String cbaCodigo) {
        this.cbaCodigo = cbaCodigo;
    }
    public String getCbaDescripcion() {
        return this.cbaDescripcion;
    }
    
    public void setCbaDescripcion(String cbaDescripcion) {
        this.cbaDescripcion = cbaDescripcion;
    }
    public String getCbaActivo() {
        return this.cbaActivo;
    }
    
    public void setCbaActivo(String cbaActivo) {
        this.cbaActivo = cbaActivo;
    }
    public Byte getCbaSort() {
        return this.cbaSort;
    }
    
    public void setCbaSort(Byte cbaSort) {
        this.cbaSort = cbaSort;
    }
    public String getCbaHost() {
        return this.cbaHost;
    }
    
    public void setCbaHost(String cbaHost) {
        this.cbaHost = cbaHost;
    }
    public Set getCfgBacantibiogramasantibiots() {
        return this.cfgBacantibiogramasantibiots;
    }
    
    public void setCfgBacantibiogramasantibiots(Set cfgBacantibiogramasantibiots) {
        this.cfgBacantibiogramasantibiots = cfgBacantibiogramasantibiots;
    }




}


