package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgBactiposinfecciones generated by hbm2java
 */
public class CfgBactiposinfecciones  implements java.io.Serializable {


     private byte cbtiIdbactipoinfeccion;
     private String cbtiCodigo;
     private String cbtiDescripcion;
     private String cbtiActivo;
     private Byte cbtiSort;

    public CfgBactiposinfecciones() {
    }

	
    public CfgBactiposinfecciones(byte cbtiIdbactipoinfeccion) {
        this.cbtiIdbactipoinfeccion = cbtiIdbactipoinfeccion;
    }
    public CfgBactiposinfecciones(byte cbtiIdbactipoinfeccion, String cbtiCodigo, String cbtiDescripcion, String cbtiActivo, Byte cbtiSort) {
       this.cbtiIdbactipoinfeccion = cbtiIdbactipoinfeccion;
       this.cbtiCodigo = cbtiCodigo;
       this.cbtiDescripcion = cbtiDescripcion;
       this.cbtiActivo = cbtiActivo;
       this.cbtiSort = cbtiSort;
    }
   
    public byte getCbtiIdbactipoinfeccion() {
        return this.cbtiIdbactipoinfeccion;
    }
    
    public void setCbtiIdbactipoinfeccion(byte cbtiIdbactipoinfeccion) {
        this.cbtiIdbactipoinfeccion = cbtiIdbactipoinfeccion;
    }
    public String getCbtiCodigo() {
        return this.cbtiCodigo;
    }
    
    public void setCbtiCodigo(String cbtiCodigo) {
        this.cbtiCodigo = cbtiCodigo;
    }
    public String getCbtiDescripcion() {
        return this.cbtiDescripcion;
    }
    
    public void setCbtiDescripcion(String cbtiDescripcion) {
        this.cbtiDescripcion = cbtiDescripcion;
    }
    public String getCbtiActivo() {
        return this.cbtiActivo;
    }
    
    public void setCbtiActivo(String cbtiActivo) {
        this.cbtiActivo = cbtiActivo;
    }
    public Byte getCbtiSort() {
        return this.cbtiSort;
    }
    
    public void setCbtiSort(Byte cbtiSort) {
        this.cbtiSort = cbtiSort;
    }




}


