package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgBaczonacuerpo generated by hbm2java
 */
public class CfgBaczonacuerpo implements java.io.Serializable {

  private short cbzcIdzonacuerpo;
  private String cbzcDescripcion;
  private String cbzcActivo;
  private Short cbzcSort;
  private String cbzcHost;
  @JsonIgnore
  private Set datosFichasmuestrases = new HashSet(0);

  public CfgBaczonacuerpo() {
  }
  public CfgBaczonacuerpo(short cbzcIdzonacuerpo) {
  	this.cbzcIdzonacuerpo = cbzcIdzonacuerpo;
  }
  public short getCbzcIdzonacuerpo() {
    return this.cbzcIdzonacuerpo;
  }

  public void setCbzcIdzonacuerpo(short cbzcIdzonacuerpo) {
    this.cbzcIdzonacuerpo = cbzcIdzonacuerpo;
  }

  public String getCbzcDescripcion() {
    return this.cbzcDescripcion;
  }

  public void setCbzcDescripcion(String cbzcDescripcion) {
    this.cbzcDescripcion = cbzcDescripcion;
  }

  public String getCbzcActivo() {
    return this.cbzcActivo;
  }

  public void setCbzcActivo(String cbzcActivo) {
    this.cbzcActivo = cbzcActivo;
  }

  public Short getCbzcSort() {
    return this.cbzcSort;
  }

  public void setCbzcSort(Short cbzcSort) {
    this.cbzcSort = cbzcSort;
  }

  public String getCbzcHost() {
    return this.cbzcHost;
  }

  public void setCbzcHost(String cbzcHost) {
    this.cbzcHost = cbzcHost;
  }

  public Set getDatosFichasmuestrases() {
    return this.datosFichasmuestrases;
  }

  public void setDatosFichasmuestrases(Set datosFichasmuestrases) {
    this.datosFichasmuestrases = datosFichasmuestrases;
  }

  @Override
  public String toString() {
    return "CfgBaczonacuerpo [cbzcIdzonacuerpo=" + cbzcIdzonacuerpo + "]";
  }

}
