package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgBacmarcadoresresistencia generated by hbm2java
 */
public class CfgBacmarcadoresresistencia  implements java.io.Serializable {


     private short cbmrIdmarcadorresistencia;
     private String cbmrCodigo;
     private String cbmrDescripcion;
     private String cbmrActivo;
     private Short cbmrSort;

    public CfgBacmarcadoresresistencia() {
    }

	
    public CfgBacmarcadoresresistencia(short cbmrIdmarcadorresistencia) {
        this.cbmrIdmarcadorresistencia = cbmrIdmarcadorresistencia;
    }
    public CfgBacmarcadoresresistencia(short cbmrIdmarcadorresistencia, String cbmrCodigo, String cbmrDescripcion, String cbmrActivo, Short cbmrSort) {
       this.cbmrIdmarcadorresistencia = cbmrIdmarcadorresistencia;
       this.cbmrCodigo = cbmrCodigo;
       this.cbmrDescripcion = cbmrDescripcion;
       this.cbmrActivo = cbmrActivo;
       this.cbmrSort = cbmrSort;
    }
   
    public short getCbmrIdmarcadorresistencia() {
        return this.cbmrIdmarcadorresistencia;
    }
    
    public void setCbmrIdmarcadorresistencia(short cbmrIdmarcadorresistencia) {
        this.cbmrIdmarcadorresistencia = cbmrIdmarcadorresistencia;
    }
    public String getCbmrCodigo() {
        return this.cbmrCodigo;
    }
    
    public void setCbmrCodigo(String cbmrCodigo) {
        this.cbmrCodigo = cbmrCodigo;
    }
    public String getCbmrDescripcion() {
        return this.cbmrDescripcion;
    }
    
    public void setCbmrDescripcion(String cbmrDescripcion) {
        this.cbmrDescripcion = cbmrDescripcion;
    }
    public String getCbmrActivo() {
        return this.cbmrActivo;
    }
    
    public void setCbmrActivo(String cbmrActivo) {
        this.cbmrActivo = cbmrActivo;
    }
    public Short getCbmrSort() {
        return this.cbmrSort;
    }
    
    public void setCbmrSort(Short cbmrSort) {
        this.cbmrSort = cbmrSort;
    }




}


