package com.grupobios.bioslis.entity;
// Generated 14-07-2022 0:17:28 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgBacgrupostest generated by hbm2java
 */
public class CfgBacgrupostest  implements java.io.Serializable {


     private byte cbgtIdbacgrupotest;
     private String cbgtDescripcion;
     private String cbgtActivo;
     private byte cbgtSort;
     @JsonIgnore
     private Set<CfgTest> cfgTests = new HashSet<CfgTest>(0);

    public CfgBacgrupostest() {
    }

	
    public CfgBacgrupostest(byte cbgtIdbacgrupotest, String cbgtDescripcion, String cbgtActivo, byte cbgtSort) {
        this.cbgtIdbacgrupotest = cbgtIdbacgrupotest;
        this.cbgtDescripcion = cbgtDescripcion;
        this.cbgtActivo = cbgtActivo;
        this.cbgtSort = cbgtSort;
    }
    public CfgBacgrupostest(byte cbgtIdbacgrupotest, String cbgtDescripcion, String cbgtActivo, byte cbgtSort, Set<CfgTest> cfgTests) {
       this.cbgtIdbacgrupotest = cbgtIdbacgrupotest;
       this.cbgtDescripcion = cbgtDescripcion;
       this.cbgtActivo = cbgtActivo;
       this.cbgtSort = cbgtSort;
       this.cfgTests = cfgTests;
    }
    
    public byte getCbgtIdbacgrupotest() {
        return this.cbgtIdbacgrupotest;
    }
    
    public void setCbgtIdbacgrupotest(byte cbgtIdbacgrupotest) {
        this.cbgtIdbacgrupotest = cbgtIdbacgrupotest;
    }

    
    public String getCbgtDescripcion() {
        return this.cbgtDescripcion;
    }
    
    public void setCbgtDescripcion(String cbgtDescripcion) {
        this.cbgtDescripcion = cbgtDescripcion;
    }

    
    public String getCbgtActivo() {
        return this.cbgtActivo;
    }
    
    public void setCbgtActivo(String cbgtActivo) {
        this.cbgtActivo = cbgtActivo;
    }

    
    public byte getCbgtSort() {
        return this.cbgtSort;
    }
    
    public void setCbgtSort(byte cbgtSort) {
        this.cbgtSort = cbgtSort;
    }

    public Set<CfgTest> getCfgTests() {
        return this.cfgTests;
    }
    
    public void setCfgTests(Set<CfgTest> cfgTests) {
        this.cfgTests = cfgTests;
    }




}


