package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.sql.Blob;
import java.util.Set;

import javax.persistence.Transient;

/**
 * CfgBacmicroorganismos generated by hbm2java
 */
public class CfgBacmicroorganismos implements java.io.Serializable {

	private short cboIdbacmicroorganismo;
	private String cboCodigo;
	private String cboDescripcion;
	private Boolean cboIdbacgram;
	private Byte cboIdbacmorfologia;
	private Byte cboIdbacespecie;
	private String cboActivo;
	private String cboHost;
	private String cboNota;
	private Blob cboImagenespecie;
	@Transient
	private Set datosFichasexamenesmicroorgs;

	public CfgBacmicroorganismos() {
	}

	public CfgBacmicroorganismos(short cboIdbacmicroorganismo) {
		this.cboIdbacmicroorganismo = cboIdbacmicroorganismo;
	}

	public CfgBacmicroorganismos(short cboIdbacmicroorganismo, String cboCodigo, String cboDescripcion,
			Boolean cboIdbacgram, Byte cboIdbacmorfologia, Byte cboIdbacespecie, String cboActivo, String cboHost,
			String cboNota, Blob cboImagenespecie, Set datosFichasexamenesmicroorgs) {
		this.cboIdbacmicroorganismo = cboIdbacmicroorganismo;
		this.cboCodigo = cboCodigo;
		this.cboDescripcion = cboDescripcion;
		this.cboIdbacgram = cboIdbacgram;
		this.cboIdbacmorfologia = cboIdbacmorfologia;
		this.cboIdbacespecie = cboIdbacespecie;
		this.cboActivo = cboActivo;
		this.cboHost = cboHost;
		this.cboNota = cboNota;
		this.cboImagenespecie = cboImagenespecie;
		this.datosFichasexamenesmicroorgs = datosFichasexamenesmicroorgs;
	}

	public short getCboIdbacmicroorganismo() {
		return this.cboIdbacmicroorganismo;
	}

	public void setCboIdbacmicroorganismo(short cboIdbacmicroorganismo) {
		this.cboIdbacmicroorganismo = cboIdbacmicroorganismo;
	}

	public String getCboCodigo() {
		return this.cboCodigo;
	}

	public void setCboCodigo(String cboCodigo) {
		this.cboCodigo = cboCodigo;
	}

	public String getCboDescripcion() {
		return this.cboDescripcion;
	}

	public void setCboDescripcion(String cboDescripcion) {
		this.cboDescripcion = cboDescripcion;
	}

	public Boolean getCboIdbacgram() {
		return this.cboIdbacgram;
	}

	public void setCboIdbacgram(Boolean cboIdbacgram) {
		this.cboIdbacgram = cboIdbacgram;
	}

	public Byte getCboIdbacmorfologia() {
		return this.cboIdbacmorfologia;
	}

	public void setCboIdbacmorfologia(Byte cboIdbacmorfologia) {
		this.cboIdbacmorfologia = cboIdbacmorfologia;
	}

	public Byte getCboIdbacespecie() {
		return this.cboIdbacespecie;
	}

	public void setCboIdbacespecie(Byte cboIdbacespecie) {
		this.cboIdbacespecie = cboIdbacespecie;
	}

	public String getCboActivo() {
		return this.cboActivo;
	}

	public void setCboActivo(String cboActivo) {
		this.cboActivo = cboActivo;
	}

	public String getCboHost() {
		return this.cboHost;
	}

	public void setCboHost(String cboHost) {
		this.cboHost = cboHost;
	}

	public String getCboNota() {
		return this.cboNota;
	}

	public void setCboNota(String cboNota) {
		this.cboNota = cboNota;
	}

	public Blob getCboImagenespecie() {
		return this.cboImagenespecie;
	}

	public void setCboImagenespecie(Blob cboImagenespecie) {
		this.cboImagenespecie = cboImagenespecie;
	}

	public Set getDatosFichasexamenesmicroorgs() {
		return this.datosFichasexamenesmicroorgs;
	}

	public void setDatosFichasexamenesmicroorgs(Set datosFichasexamenesmicroorgs) {
		this.datosFichasexamenesmicroorgs = datosFichasexamenesmicroorgs;
	}

}
