package com.grupobios.bioslis.entity;




/**
 * CfgBacpruebas generated by hbm2java
 */
public class CfgBacpruebas  implements java.io.Serializable {


     private short cbpIdprueba;
     private String cbpCodigo;
     private String cbpDescripcion;
     private String cbpTipo;
     private String cbpActivo;
     private Short cbpSort;

    public CfgBacpruebas() {
    }

	
    public CfgBacpruebas(short cbpIdprueba) {
        this.cbpIdprueba = cbpIdprueba;
    }
    public CfgBacpruebas(short cbpIdprueba, String cbpCodigo, String cbpDescripcion, String cbpTipo, String cbpActivo, Short cbpSort) {
       this.cbpIdprueba = cbpIdprueba;
       this.cbpCodigo = cbpCodigo;
       this.cbpDescripcion = cbpDescripcion;
       this.cbpTipo = cbpTipo;
       this.cbpActivo = cbpActivo;
       this.cbpSort = cbpSort;
    }
   
    public short getCbpIdprueba() {
        return this.cbpIdprueba;
    }
    
    public void setCbpIdprueba(short cbpIdprueba) {
        this.cbpIdprueba = cbpIdprueba;
    }
    public String getCbpCodigo() {
        return this.cbpCodigo;
    }
    
    public void setCbpCodigo(String cbpCodigo) {
        this.cbpCodigo = cbpCodigo;
    }
    public String getCbpDescripcion() {
        return this.cbpDescripcion;
    }
    
    public void setCbpDescripcion(String cbpDescripcion) {
        this.cbpDescripcion = cbpDescripcion;
    }
    public String getCbpTipo() {
        return this.cbpTipo;
    }
    
    public void setCbpTipo(String cbpTipo) {
        this.cbpTipo = cbpTipo;
    }
    public String getCbpActivo() {
        return this.cbpActivo;
    }
    
    public void setCbpActivo(String cbpActivo) {
        this.cbpActivo = cbpActivo;
    }
    public Short getCbpSort() {
        return this.cbpSort;
    }
    
    public void setCbpSort(Short cbpSort) {
        this.cbpSort = cbpSort;
    }




}


