package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgCellcounter generated by hbm2java
 */
public class CfgCellcounter  implements java.io.Serializable {


     private byte cccIdcellcounter;
     private String cccTeclabas;
     private Short cccTestbas;
     private String cccTeclaeos;
     private Short cccTesteos;
     private String cccTeclamie;
     private Short cccTestmie;
     private String cccTeclajuv;
     private Short cccTestjuv;
     private String cccTeclabac;
     private Short cccTestbac;
     private String cccTeclaseg;
     private Short cccTestseg;
     private String cccTeclalin;
     private Short cccTestlin;
     private String cccTeclamon;
     private Short cccTestmon;
     private String cccTeclapro;
     private Short cccTestpro;
     private String cccTeclabla;
     private Short cccTestbla;
     private String cccSonidocelulas;
     private String cccSonidototal;
     private String cccSonidograbar;
     private String cccSonidosalir;
     private String cccSonidoerror;

    public CfgCellcounter() {
    }

	
    public CfgCellcounter(byte cccIdcellcounter) {
        this.cccIdcellcounter = cccIdcellcounter;
    }
    public CfgCellcounter(byte cccIdcellcounter, String cccTeclabas, Short cccTestbas, String cccTeclaeos, Short cccTesteos, String cccTeclamie, Short cccTestmie, String cccTeclajuv, Short cccTestjuv, String cccTeclabac, Short cccTestbac, String cccTeclaseg, Short cccTestseg, String cccTeclalin, Short cccTestlin, String cccTeclamon, Short cccTestmon, String cccTeclapro, Short cccTestpro, String cccTeclabla, Short cccTestbla, String cccSonidocelulas, String cccSonidototal, String cccSonidograbar, String cccSonidosalir, String cccSonidoerror) {
       this.cccIdcellcounter = cccIdcellcounter;
       this.cccTeclabas = cccTeclabas;
       this.cccTestbas = cccTestbas;
       this.cccTeclaeos = cccTeclaeos;
       this.cccTesteos = cccTesteos;
       this.cccTeclamie = cccTeclamie;
       this.cccTestmie = cccTestmie;
       this.cccTeclajuv = cccTeclajuv;
       this.cccTestjuv = cccTestjuv;
       this.cccTeclabac = cccTeclabac;
       this.cccTestbac = cccTestbac;
       this.cccTeclaseg = cccTeclaseg;
       this.cccTestseg = cccTestseg;
       this.cccTeclalin = cccTeclalin;
       this.cccTestlin = cccTestlin;
       this.cccTeclamon = cccTeclamon;
       this.cccTestmon = cccTestmon;
       this.cccTeclapro = cccTeclapro;
       this.cccTestpro = cccTestpro;
       this.cccTeclabla = cccTeclabla;
       this.cccTestbla = cccTestbla;
       this.cccSonidocelulas = cccSonidocelulas;
       this.cccSonidototal = cccSonidototal;
       this.cccSonidograbar = cccSonidograbar;
       this.cccSonidosalir = cccSonidosalir;
       this.cccSonidoerror = cccSonidoerror;
    }
   
    public byte getCccIdcellcounter() {
        return this.cccIdcellcounter;
    }
    
    public void setCccIdcellcounter(byte cccIdcellcounter) {
        this.cccIdcellcounter = cccIdcellcounter;
    }
    public String getCccTeclabas() {
        return this.cccTeclabas;
    }
    
    public void setCccTeclabas(String cccTeclabas) {
        this.cccTeclabas = cccTeclabas;
    }
    public Short getCccTestbas() {
        return this.cccTestbas;
    }
    
    public void setCccTestbas(Short cccTestbas) {
        this.cccTestbas = cccTestbas;
    }
    public String getCccTeclaeos() {
        return this.cccTeclaeos;
    }
    
    public void setCccTeclaeos(String cccTeclaeos) {
        this.cccTeclaeos = cccTeclaeos;
    }
    public Short getCccTesteos() {
        return this.cccTesteos;
    }
    
    public void setCccTesteos(Short cccTesteos) {
        this.cccTesteos = cccTesteos;
    }
    public String getCccTeclamie() {
        return this.cccTeclamie;
    }
    
    public void setCccTeclamie(String cccTeclamie) {
        this.cccTeclamie = cccTeclamie;
    }
    public Short getCccTestmie() {
        return this.cccTestmie;
    }
    
    public void setCccTestmie(Short cccTestmie) {
        this.cccTestmie = cccTestmie;
    }
    public String getCccTeclajuv() {
        return this.cccTeclajuv;
    }
    
    public void setCccTeclajuv(String cccTeclajuv) {
        this.cccTeclajuv = cccTeclajuv;
    }
    public Short getCccTestjuv() {
        return this.cccTestjuv;
    }
    
    public void setCccTestjuv(Short cccTestjuv) {
        this.cccTestjuv = cccTestjuv;
    }
    public String getCccTeclabac() {
        return this.cccTeclabac;
    }
    
    public void setCccTeclabac(String cccTeclabac) {
        this.cccTeclabac = cccTeclabac;
    }
    public Short getCccTestbac() {
        return this.cccTestbac;
    }
    
    public void setCccTestbac(Short cccTestbac) {
        this.cccTestbac = cccTestbac;
    }
    public String getCccTeclaseg() {
        return this.cccTeclaseg;
    }
    
    public void setCccTeclaseg(String cccTeclaseg) {
        this.cccTeclaseg = cccTeclaseg;
    }
    public Short getCccTestseg() {
        return this.cccTestseg;
    }
    
    public void setCccTestseg(Short cccTestseg) {
        this.cccTestseg = cccTestseg;
    }
    public String getCccTeclalin() {
        return this.cccTeclalin;
    }
    
    public void setCccTeclalin(String cccTeclalin) {
        this.cccTeclalin = cccTeclalin;
    }
    public Short getCccTestlin() {
        return this.cccTestlin;
    }
    
    public void setCccTestlin(Short cccTestlin) {
        this.cccTestlin = cccTestlin;
    }
    public String getCccTeclamon() {
        return this.cccTeclamon;
    }
    
    public void setCccTeclamon(String cccTeclamon) {
        this.cccTeclamon = cccTeclamon;
    }
    public Short getCccTestmon() {
        return this.cccTestmon;
    }
    
    public void setCccTestmon(Short cccTestmon) {
        this.cccTestmon = cccTestmon;
    }
    public String getCccTeclapro() {
        return this.cccTeclapro;
    }
    
    public void setCccTeclapro(String cccTeclapro) {
        this.cccTeclapro = cccTeclapro;
    }
    public Short getCccTestpro() {
        return this.cccTestpro;
    }
    
    public void setCccTestpro(Short cccTestpro) {
        this.cccTestpro = cccTestpro;
    }
    public String getCccTeclabla() {
        return this.cccTeclabla;
    }
    
    public void setCccTeclabla(String cccTeclabla) {
        this.cccTeclabla = cccTeclabla;
    }
    public Short getCccTestbla() {
        return this.cccTestbla;
    }
    
    public void setCccTestbla(Short cccTestbla) {
        this.cccTestbla = cccTestbla;
    }
    public String getCccSonidocelulas() {
        return this.cccSonidocelulas;
    }
    
    public void setCccSonidocelulas(String cccSonidocelulas) {
        this.cccSonidocelulas = cccSonidocelulas;
    }
    public String getCccSonidototal() {
        return this.cccSonidototal;
    }
    
    public void setCccSonidototal(String cccSonidototal) {
        this.cccSonidototal = cccSonidototal;
    }
    public String getCccSonidograbar() {
        return this.cccSonidograbar;
    }
    
    public void setCccSonidograbar(String cccSonidograbar) {
        this.cccSonidograbar = cccSonidograbar;
    }
    public String getCccSonidosalir() {
        return this.cccSonidosalir;
    }
    
    public void setCccSonidosalir(String cccSonidosalir) {
        this.cccSonidosalir = cccSonidosalir;
    }
    public String getCccSonidoerror() {
        return this.cccSonidoerror;
    }
    
    public void setCccSonidoerror(String cccSonidoerror) {
        this.cccSonidoerror = cccSonidoerror;
    }




}


