package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgConvenios generated by hbm2java
 */
public class CfgConvenios  implements java.io.Serializable {


     private short ccIdconvenio;
     private String ccDescripcion;
     private String ccAbreviado;
     private String ccActivo;
     private Short ccSort;
     private String ccImed;
     private String ccEsparticular;
     private String ccGrupo;
     private String ccRestringidoimpresion;
     private String ccHost;
     private String ccHost2;
     private String ccHost3;
     @JsonIgnore
     private Set cfgProcedenciases = new HashSet(0);
     @JsonIgnore
     private Set datosFichases = new HashSet(0);

    public CfgConvenios() {
    }

	
    public CfgConvenios(short ccIdconvenio) {
        this.ccIdconvenio = ccIdconvenio;
    }
    public CfgConvenios(short ccIdconvenio, String ccDescripcion, String ccAbreviado, String ccActivo, Short ccSort, String ccImed, String ccEsparticular, String ccGrupo, String ccRestringidoimpresion, String ccHost, String ccHost2, String ccHost3, Set cfgProcedenciases, Set datosFichases) {
       this.ccIdconvenio = ccIdconvenio;
       this.ccDescripcion = ccDescripcion;
       this.ccAbreviado = ccAbreviado;
       this.ccActivo = ccActivo;
       this.ccSort = ccSort;
       this.ccImed = ccImed;
       this.ccEsparticular = ccEsparticular;
       this.ccGrupo = ccGrupo;
       this.ccRestringidoimpresion = ccRestringidoimpresion;
       this.ccHost = ccHost;
       this.ccHost2 = ccHost2;
       this.ccHost3 = ccHost3;
       this.cfgProcedenciases = cfgProcedenciases;
       this.datosFichases = datosFichases;
    }
   
    public short getCcIdconvenio() {
        return this.ccIdconvenio;
    }
    
    public void setCcIdconvenio(short ccIdconvenio) {
        this.ccIdconvenio = ccIdconvenio;
    }
    public String getCcDescripcion() {
        return this.ccDescripcion;
    }
    
    public void setCcDescripcion(String ccDescripcion) {
        this.ccDescripcion = ccDescripcion;
    }
    public String getCcAbreviado() {
        return this.ccAbreviado;
    }
    
    public void setCcAbreviado(String ccAbreviado) {
        this.ccAbreviado = ccAbreviado;
    }
    public String getCcActivo() {
        return this.ccActivo;
    }
    
    public void setCcActivo(String ccActivo) {
        this.ccActivo = ccActivo;
    }
    public Short getCcSort() {
        return this.ccSort;
    }
    
    public void setCcSort(Short ccSort) {
        this.ccSort = ccSort;
    }
    public String getCcImed() {
        return this.ccImed;
    }
    
    public void setCcImed(String ccImed) {
        this.ccImed = ccImed;
    }
    public String getCcEsparticular() {
        return this.ccEsparticular;
    }
    
    public void setCcEsparticular(String ccEsparticular) {
        this.ccEsparticular = ccEsparticular;
    }
    public String getCcGrupo() {
        return this.ccGrupo;
    }
    
    public void setCcGrupo(String ccGrupo) {
        this.ccGrupo = ccGrupo;
    }
    public String getCcRestringidoimpresion() {
        return this.ccRestringidoimpresion;
    }
    
    public void setCcRestringidoimpresion(String ccRestringidoimpresion) {
        this.ccRestringidoimpresion = ccRestringidoimpresion;
    }
    public String getCcHost() {
        return this.ccHost;
    }
    
    public void setCcHost(String ccHost) {
        this.ccHost = ccHost;
    }
    public String getCcHost2() {
        return this.ccHost2;
    }
    
    public void setCcHost2(String ccHost2) {
        this.ccHost2 = ccHost2;
    }
    public String getCcHost3() {
        return this.ccHost3;
    }
    
    public void setCcHost3(String ccHost3) {
        this.ccHost3 = ccHost3;
    }
    public Set getCfgProcedenciases() {
        return this.cfgProcedenciases;
    }
    
    public void setCfgProcedenciases(Set cfgProcedenciases) {
        this.cfgProcedenciases = cfgProcedenciases;
    }
    public Set getDatosFichases() {
        return this.datosFichases;
    }
    
    public void setDatosFichases(Set datosFichases) {
        this.datosFichases = datosFichases;
    }




}


