package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


/**
 * CfgCentrosdesalud generated by hbm2java
 */
public class CfgCentrosdesalud implements java.io.Serializable {

	private short ccdsIdcentrodesalud;
	private short ccdsIdinstituciondesalud;
	private String ccdsDescripcion;
	private String ccdsCodigo;
	private String ccdsActivo;
	private String ccdsDireccion;
	private String ccdsTelefono;

	public CfgCentrosdesalud() {
	}

	public String getCcdsDescripcion() {
		return ccdsDescripcion;
	}

	public void setCcdsDescripcion(String ccdsDescripcion) {
		this.ccdsDescripcion = ccdsDescripcion;
	}

	public String getCcdsCodigo() {
		return ccdsCodigo;
	}

	public void setCcdsCodigo(String ccdsCodigo) {
		this.ccdsCodigo = ccdsCodigo;
	}

	public String getCcdsActivo() {
		return ccdsActivo;
	}

	public void setCcdsActivo(String ccdsActivo) {
		this.ccdsActivo = ccdsActivo;
	}

	public String getCcdsDireccion() {
		return ccdsDireccion;
	}

	public void setCcdsDireccion(String ccdsDireccion) {
		this.ccdsDireccion = ccdsDireccion;
	}

	public String getCcdsTelefono() {
		return ccdsTelefono;
	}

	public void setCcdsTelefono(String ccdsTelefono) {
		this.ccdsTelefono = ccdsTelefono;
	}

	public short getCcdsIdcentrodesalud() {
		return ccdsIdcentrodesalud;
	}

	public void setCcdsIdcentrodesalud(short ccdsIdcentrodesalud) {
		this.ccdsIdcentrodesalud = ccdsIdcentrodesalud;
	}

	public short getCcdsIdinstituciondesalud() {
		return ccdsIdinstituciondesalud;
	}

	public void setCcdsIdinstituciondesalud(short ccdsIdinstituciondesalud) {
		this.ccdsIdinstituciondesalud = ccdsIdinstituciondesalud;
	}

}
