package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgComunasregiones generated by hbm2java
 */
public class CfgComunasregiones  implements java.io.Serializable {


     private int ccrIdcomuna;
     private LdvComunas ldvComunas;
     private LdvRegiones ldvRegiones;

    public CfgComunasregiones() {
    }

    public CfgComunasregiones(LdvComunas ldvComunas, LdvRegiones ldvRegiones) {
       this.ldvComunas = ldvComunas;
       this.ldvRegiones = ldvRegiones;
    }
   
    public int getCcrIdcomuna() {
        return this.ccrIdcomuna;
    }
    
    public void setCcrIdcomuna(int ccrIdcomuna) {
        this.ccrIdcomuna = ccrIdcomuna;
    }
    public LdvComunas getLdvComunas() {
        return this.ldvComunas;
    }
    
    public void setLdvComunas(LdvComunas ldvComunas) {
        this.ldvComunas = ldvComunas;
    }
    public LdvRegiones getLdvRegiones() {
        return this.ldvRegiones;
    }
    
    public void setLdvRegiones(LdvRegiones ldvRegiones) {
        this.ldvRegiones = ldvRegiones;
    }




}


