package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * CfgCondicionesformulasId generated by hbm2java
 */
public class CfgCondicionesformulasId implements java.io.Serializable {

  private Long ccfIdtest;
  private Byte ccfNumerocondicion;

  public byte getCcfNumerocondicion() {
    return ccfNumerocondicion;
  }

  public void setCcfNumerocondicion(Byte ccfNumerocondicion) {
    this.ccfNumerocondicion = ccfNumerocondicion;
  }

  public CfgCondicionesformulasId() {
  }

  public CfgCondicionesformulasId(Long ccfIdtest, Byte ccfNumerocondicion) {
    this.ccfIdtest = ccfIdtest;
    this.ccfNumerocondicion = ccfNumerocondicion;
  }

  public Long getCcfIdtest() {
    return this.ccfIdtest;
  }

  public void setCcfIdtest(Long ccfIdtest) {
    this.ccfIdtest = ccfIdtest;
  }

}
