package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgCamassalas generated by hbm2java
 */
public class CfgCamassalas  implements java.io.Serializable {


     private int ccsIdcamasala;
     private CfgSalasservicios cfgSalasservicios;
     private String ccsCodigocama;
     private String ccsDescripcion;

    public CfgCamassalas() {
    }

	
    public CfgCamassalas(int ccsIdcamasala, CfgSalasservicios cfgSalasservicios) {
        this.ccsIdcamasala = ccsIdcamasala;
        this.cfgSalasservicios = cfgSalasservicios;
    }
    public CfgCamassalas(int ccsIdcamasala, CfgSalasservicios cfgSalasservicios, String ccsCodigocama, String ccsDescripcion) {
       this.ccsIdcamasala = ccsIdcamasala;
       this.cfgSalasservicios = cfgSalasservicios;
       this.ccsCodigocama = ccsCodigocama;
       this.ccsDescripcion = ccsDescripcion;
    }
   
    public int getCcsIdcamasala() {
        return this.ccsIdcamasala;
    }
    
    public void setCcsIdcamasala(int ccsIdcamasala) {
        this.ccsIdcamasala = ccsIdcamasala;
    }
    public CfgSalasservicios getCfgSalasservicios() {
        return this.cfgSalasservicios;
    }
    
    public void setCfgSalasservicios(CfgSalasservicios cfgSalasservicios) {
        this.cfgSalasservicios = cfgSalasservicios;
    }
    public String getCcsCodigocama() {
        return this.ccsCodigocama;
    }
    
    public void setCcsCodigocama(String ccsCodigocama) {
        this.ccsCodigocama = ccsCodigocama;
    }
    public String getCcsDescripcion() {
        return this.ccsDescripcion;
    }
    
    public void setCcsDescripcion(String ccsDescripcion) {
        this.ccsDescripcion = ccsDescripcion;
    }




}


