package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * CfgCondicionesformulas generated by hbm2java
 */
public class CfgCondicionesformulas implements java.io.Serializable {

  private CfgCondicionesformulasId id;
  private CfgTest cfgTest;
  private String ccfTestoantecedente;
  private Long ccfCondicionvar1;
  private String ccfCondicionoperador;
  private BigDecimal ccfCondicionvar2;
  private String ccfFallaresultado;
  private String ccfFallaestado;
  private String ccfFallanota;
  private Byte ccfNrcondicionanidada;

  public CfgCondicionesformulas() {
  }

  public CfgCondicionesformulasId getId() {
    return this.id;
  }

  public void setId(CfgCondicionesformulasId id) {
    this.id = id;
  }

  public CfgTest getCfgTest() {
    return this.cfgTest;
  }

  public void setCfgTest(CfgTest cfgTest) {
    this.cfgTest = cfgTest;
  }

  public String getCcfTestoantecedente() {
    return this.ccfTestoantecedente;
  }

  public void setCcfTestoantecedente(String ccfTestoantecedente) {
    this.ccfTestoantecedente = ccfTestoantecedente;
  }

  public Long getCcfCondicionvar1() {
    return this.ccfCondicionvar1;
  }

  public void setCcfCondicionvar1(Long ccfCondicionvar1) {
    this.ccfCondicionvar1 = ccfCondicionvar1;
  }

  public String getCcfCondicionoperador() {
    return this.ccfCondicionoperador;
  }

  public void setCcfCondicionoperador(String ccfCondicionoperador) {
    this.ccfCondicionoperador = ccfCondicionoperador;
  }

  public BigDecimal getCcfCondicionvar2() {
    return this.ccfCondicionvar2;
  }

  public void setCcfCondicionvar2(BigDecimal ccfCondicionvar2) {
    this.ccfCondicionvar2 = ccfCondicionvar2;
  }

  public String getCcfFallaresultado() {
    return this.ccfFallaresultado;
  }

  public void setCcfFallaresultado(String ccfFallaresultado) {
    this.ccfFallaresultado = ccfFallaresultado;
  }

  public String getCcfFallaestado() {
    return this.ccfFallaestado;
  }

  public void setCcfFallaestado(String ccfFallaestado) {
    this.ccfFallaestado = ccfFallaestado;
  }

  public String getCcfFallanota() {
    return this.ccfFallanota;
  }

  public void setCcfFallanota(String ccfFallanota) {
    this.ccfFallanota = ccfFallanota;
  }

  public Byte getCcfNrcondicionanidada() {
    return this.ccfNrcondicionanidada;
  }

  public void setCcfNrcondicionanidada(Byte ccfNrcondicionanidada) {
    this.ccfNrcondicionanidada = ccfNrcondicionanidada;
  }

}
