package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgDerivadores generated by hbm2java
 */
public class CfgDerivadores  implements java.io.Serializable {


     private short cderivIdderivador;
     private String cderivCodigo;
     private String cderivDescripcion;
     private Short cderivSort;
     private String cderivActivo;
     private String cderivHost;
     private String cderivHorarioatencion;
     private String cderivTelefono;
     private String cderivDireccion;
     private String cderivEmail;
     private String cderivNombreencargado;
     @JsonIgnore
     private Set cfgExameneses = new HashSet(0);

    public CfgDerivadores() {
    }

    public CfgDerivadores(short cderivIdderivador) {
        this.cderivIdderivador = cderivIdderivador;
    }
    
    public short getCderivIdderivador() {
        return this.cderivIdderivador;
    }
    
    public void setCderivIdderivador(short cderivIdderivador) {
        this.cderivIdderivador = cderivIdderivador;
    }
    public String getCderivCodigo() {
        return this.cderivCodigo;
    }
    
    public void setCderivCodigo(String cderivCodigo) {
        this.cderivCodigo = cderivCodigo;
    }
    public String getCderivDescripcion() {
        return this.cderivDescripcion;
    }
    
    public void setCderivDescripcion(String cderivDescripcion) {
        this.cderivDescripcion = cderivDescripcion;
    }
    public Short getCderivSort() {
        return this.cderivSort;
    }
    
    public void setCderivSort(Short cderivSort) {
        this.cderivSort = cderivSort;
    }
    public String getCderivActivo() {
        return this.cderivActivo;
    }
    
    public void setCderivActivo(String cderivActivo) {
        this.cderivActivo = cderivActivo;
    }
    public String getCderivHost() {
        return this.cderivHost;
    }
    
    public void setCderivHost(String cderivHost) {
        this.cderivHost = cderivHost;
    }
    public Set getCfgExameneses() {
        return this.cfgExameneses;
    }
    
    public void setCfgExameneses(Set cfgExameneses) {
        this.cfgExameneses = cfgExameneses;
    }

    public String getCderivHorarioatencion() {
        return cderivHorarioatencion;
    }

    public void setCderivHorarioatencion(String cderivHorarioatencion) {
        this.cderivHorarioatencion = cderivHorarioatencion;
    }

    public String getCderivTelefono() {
        return cderivTelefono;
    }

    public void setCderivTelefono(String cderivTelefono) {
        this.cderivTelefono = cderivTelefono;
    }

    public String getCderivDireccion() {
        return cderivDireccion;
    }

    public void setCderivDireccion(String cderivDireccion) {
        this.cderivDireccion = cderivDireccion;
    }

    public String getCderivEmail() {
        return cderivEmail;
    }

    public void setCderivEmail(String cderivEmail) {
        this.cderivEmail = cderivEmail;
    }

    public String getCderivNombreencargado() {
        return cderivNombreencargado;
    }

    public void setCderivNombreencargado(String cderivNombreencargado) {
        this.cderivNombreencargado = cderivNombreencargado;
    }




}


