package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgExamenestestId generated by hbm2java
 */
public class CfgExamenestestId  implements java.io.Serializable {


     private int cetIdexamen;
     private int cetIdtest;

    public CfgExamenestestId() {
    }

    public CfgExamenestestId(int cetIdexamen, int cetIdtest) {
       this.cetIdexamen = cetIdexamen;
       this.cetIdtest = cetIdtest;
    }
   
    public int getCetIdexamen() {
        return this.cetIdexamen;
    }
    
    public void setCetIdexamen(int cetIdexamen) {
        this.cetIdexamen = cetIdexamen;
    }
    public int getCetIdtest() {
        return this.cetIdtest;
    }
    
    public void setCetIdtest(int cetIdtest) {
        this.cetIdtest = cetIdtest;
    }




}


