package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgEventos generated by hbm2java
 */
public class CfgEventos  implements java.io.Serializable {


     private short cevenIdevento;
     private String cevenDescripcion;
     private Set logEventosfichases = new HashSet(0);
     private Set logEventosusuarioses = new HashSet(0);

    public CfgEventos() {
    }

	
    public CfgEventos(short cevenIdevento) {
        this.cevenIdevento = cevenIdevento;
    }
    public CfgEventos(short cevenIdevento, String cevenDescripcion, Set logEventosfichases, Set logEventosusuarioses) {
       this.cevenIdevento = cevenIdevento;
       this.cevenDescripcion = cevenDescripcion;
       this.logEventosfichases = logEventosfichases;
       this.logEventosusuarioses = logEventosusuarioses;
    }
   
    public short getCevenIdevento() {
        return this.cevenIdevento;
    }
    
    public void setCevenIdevento(short cevenIdevento) {
        this.cevenIdevento = cevenIdevento;
    }
    public String getCevenDescripcion() {
        return this.cevenDescripcion;
    }
    
    public void setCevenDescripcion(String cevenDescripcion) {
        this.cevenDescripcion = cevenDescripcion;
    }
    public Set getLogEventosfichases() {
        return this.logEventosfichases;
    }
    
    public void setLogEventosfichases(Set logEventosfichases) {
        this.logEventosfichases = logEventosfichases;
    }
    public Set getLogEventosusuarioses() {
        return this.logEventosusuarioses;
    }
    
    public void setLogEventosusuarioses(Set logEventosusuarioses) {
        this.logEventosusuarioses = logEventosusuarioses;
    }




}


