package com.grupobios.bioslis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 * generated by cristian
 */

public class CfgEtiquetacodigobarras {

  private String cecbCodigo;
  private String cecbDescripcion;
  private String cecbFontcodigobarra;
  private BigDecimal cecbTamanofontcodigobarras;
  private BigDecimal cecbFilacodigobarras;
  private BigDecimal cecbColumnacodigobarras;
  private String cecbActivocodigobarras;
  private BigDecimal cecbTexto0fila;
  private BigDecimal cecbTexto0columna;
  private String cecbActivotexto0;
  private String cecbNegrita0;
  private String cecbtamano0;
  private BigDecimal cecbTexto1fila;
  private BigDecimal cecbTexto1columna;
  private BigDecimal cecbTexto1largo;
  private BigDecimal cecbTexto1tamano;
  private String cecbActivotexto1;
  private String cecbNegrita1;
  private BigDecimal cecbTexto2fila;
  private BigDecimal cecbTexto2columna;
  private BigDecimal cecbTexto2largo;
  private BigDecimal cecbTexto2tamano;
  private String cecbActivotexto2;
  private String cecbNegrita2;
  private BigDecimal cecbTexto3fila;
  private BigDecimal cecbTexto3columna;
  private BigDecimal cecbTexto3largo;
  private BigDecimal cecbTexto3tamano;
  private String cecbActivotexto3;
  private String cecbNegrita3;
  private BigDecimal cecbTexto4fila;
  private BigDecimal cecbTexto4columna;
  private BigDecimal cecbTexto4largo;
  private BigDecimal cecbTexto4tamano;
  private String cecbActivotexto4;
  private String cecbNegrita4;
  private BigDecimal cecbTexto5fila;
  private BigDecimal cecbTexto5columna;
  private BigDecimal cecbTexto5largo;
  private BigDecimal cecbTexto5tamano;
  private String cecbActivotexto5;
  private String cecbNegrita5;
  private BigDecimal cecbTexto6fila;
  private BigDecimal cecbTexto6columna;
  private BigDecimal cecbTexto6largo;
  private BigDecimal cecbTexto6tamano;
  private String cecbActivotexto6;
  private String cecbNegrita6;
  private BigDecimal cecbTexto7fila;
  private BigDecimal cecbTexto7columna;
  private BigDecimal cecbTexto7largo;
  private BigDecimal cecbTexto7tamano;
  private String cecbActivotexto7;
  private String cecbNegrita7;
  private BigDecimal cecbTexto8fila;
  private BigDecimal cecbTexto8columna;
  private BigDecimal cecbTexto8largo;
  private BigDecimal cecbTexto8tamano;
  private String cecbActivotexto8;
  private String cecbNegrita8;
  private BigDecimal cecbTexto9fila;
  private BigDecimal cecbTexto9columna;
  private BigDecimal cecbTexto9largo;
  private BigDecimal cecbTexto9tamano;
  private String cecbActivotexto9;
  private String cecbNegrita9;
  private BigDecimal cecbTexto10fila;
  private BigDecimal cecbTexto10columna;
  private BigDecimal cecbTexto10largo;
  private BigDecimal cecbTexto10tamano;
  private String cecbActivotexto10;
  private String cecbNegrita10;
  private BigDecimal cecbTexto11fila;
  private BigDecimal cecbTexto11columna;
  private BigDecimal cecbTexto11largo;
  private BigDecimal cecbTexto11tamano;
  private String cecbActivotexto11;
  private String cecbNegrita11;
  private BigDecimal cecbTexto12fila;;
  private BigDecimal cecbTexto12columna;;
  private BigDecimal cecbTexto12largo;
  private BigDecimal cecbTexto12tamano;
  private String cecbActivotexto12;
  private String cecbNegrita12;
  private BigDecimal cecbSort;
  private String cecbNota;
  private String cecbUsuarioregistro;
  private Date cecbFecharegistro;
  private String cecbProcedencia;
  private String cecbServicio;
  private String cecbTipopacprefijo;
  private String cecbTipopacsufijo;
  private String cecbProceprefijo;
  private String cecbProcesufijo;
  private String cecbServprefijo;
  private String cecbServsufijo;
  private String cecbNombprefijo;
  private String cecbNombsufijo;
  private String cecbSexoprefijo;
  private String cecbSexosufijo;
  private String cecbEdadprefijo;
  private String cecbEdadsufijo;
  private String cecbTipmueprefijo;
  private String cecbTipmuesufijo;
  private String cecbEnvaprefijo;
  private String cecbEnvasufijo;
  private String cecbFechaprefijo;
  private String cecbFechasufijo;
  private String cecbParametrizada;
  private String cecbRutprefijo;
  private String cecbRutsufijo;
  private BigDecimal cecbFilaNorden;
  private BigDecimal cecbColumnaNorden;
  private BigDecimal cecbTextoNorden;
  private BigDecimal cecbTamanoNorden;
  private String cecbActivoNorden;
  private String cecbNegritaNorden;

  public BigDecimal getCecbFilaNorden() {
    return cecbFilaNorden;
  }

  public void setCecbFilaNorden(BigDecimal cecbFilaNorden) {
    this.cecbFilaNorden = cecbFilaNorden;
  }

  public BigDecimal getCecbColumnaNorden() {
    return cecbColumnaNorden;
  }

  public void setCecbColumnaNorden(BigDecimal cecbColumnaNorden) {
    this.cecbColumnaNorden = cecbColumnaNorden;
  }

  public BigDecimal getCecbTextoNorden() {
    return cecbTextoNorden;
  }

  public void setCecbTextoNorden(BigDecimal cecbTextoNorden) {
    this.cecbTextoNorden = cecbTextoNorden;
  }

  public BigDecimal getCecbTamanoNorden() {
    return cecbTamanoNorden;
  }

  public void setCecbTamanoNorden(BigDecimal cecbTamanoNorden) {
    this.cecbTamanoNorden = cecbTamanoNorden;
  }

  public String getCecbActivoNorden() {
    return cecbActivoNorden;
  }

  public void setCecbActivoNorden(String cecbActivoNorden) {
    this.cecbActivoNorden = cecbActivoNorden;
  }

  public String getCecbNegritaNorden() {
    return cecbNegritaNorden;
  }

  public void setCecbNegritaNorden(String cecbNegritaNorden) {
    this.cecbNegritaNorden = cecbNegritaNorden;
  }

  public CfgEtiquetacodigobarras() {
  }

  public String getCecbCodigo() {
    return cecbCodigo;
  }

  public void setCecbCodigo(String cecbCodigo) {
    this.cecbCodigo = cecbCodigo;
  }

  public String getCecbDescripcion() {
    return cecbDescripcion;
  }

  public void setCecbDescripcion(String cecbDescripcion) {
    this.cecbDescripcion = cecbDescripcion;
  }

  public String getCecbFontcodigobarra() {
    return cecbFontcodigobarra;
  }

  public void setCecbFontcodigobarra(String cecbFontcodigobarra) {
    this.cecbFontcodigobarra = cecbFontcodigobarra;
  }

  public BigDecimal getCecbTamanofontcodigobarras() {
    return cecbTamanofontcodigobarras;
  }

  public void setCecbTamanofontcodigobarras(BigDecimal cecbTamanofontcodigobarras) {
    this.cecbTamanofontcodigobarras = cecbTamanofontcodigobarras;
  }

  public BigDecimal getCecbFilacodigobarras() {
    return cecbFilacodigobarras;
  }

  public void setCecbFilacodigobarras(BigDecimal cecbFilacodigobarras) {
    this.cecbFilacodigobarras = cecbFilacodigobarras;
  }

  public BigDecimal getCecbColumnacodigobarras() {
    return cecbColumnacodigobarras;
  }

  public void setCecbColumnacodigobarras(BigDecimal cecbColumnacodigobarras) {
    this.cecbColumnacodigobarras = cecbColumnacodigobarras;
  }

  public String getCecbActivocodigobarras() {
    return cecbActivocodigobarras;
  }

  public void setCecbActivocodigobarras(String cecbActivocodigobarras) {
    this.cecbActivocodigobarras = cecbActivocodigobarras;
  }

  public BigDecimal getCecbTexto0fila() {
    return cecbTexto0fila;
  }

  public void setCecbTexto0fila(BigDecimal cecbTexto0fila) {
    this.cecbTexto0fila = cecbTexto0fila;
  }

  public BigDecimal getCecbTexto0columna() {
    return cecbTexto0columna;
  }

  public void setCecbTexto0columna(BigDecimal cecbTexto0columna) {
    this.cecbTexto0columna = cecbTexto0columna;
  }

  public String getCecbActivotexto0() {
    return cecbActivotexto0;
  }

  public void setCecbActivotexto0(String cecbActivotexto0) {
    this.cecbActivotexto0 = cecbActivotexto0;
  }

  public String getCecbNegrita0() {
    return cecbNegrita0;
  }

  public void setCecbNegrita0(String cecbNegrita0) {
    this.cecbNegrita0 = cecbNegrita0;
  }

  public String getCecbtamano0() {
    return cecbtamano0;
  }

  public void setCecbtamano0(String cecbtamano0) {
    this.cecbtamano0 = cecbtamano0;
  }

  public BigDecimal getCecbTexto1fila() {
    return cecbTexto1fila;
  }

  public void setCecbTexto1fila(BigDecimal cecbTexto1fila) {
    this.cecbTexto1fila = cecbTexto1fila;
  }

  public BigDecimal getCecbTexto1columna() {
    return cecbTexto1columna;
  }

  public void setCecbTexto1columna(BigDecimal cecbTexto1columna) {
    this.cecbTexto1columna = cecbTexto1columna;
  }

  public BigDecimal getCecbTexto1largo() {
    return cecbTexto1largo;
  }

  public void setCecbTexto1largo(BigDecimal cecbTexto1largo) {
    this.cecbTexto1largo = cecbTexto1largo;
  }

  public BigDecimal getCecbTexto1tamano() {
    return cecbTexto1tamano;
  }

  public void setCecbTexto1tamano(BigDecimal cecbTexto1tamano) {
    this.cecbTexto1tamano = cecbTexto1tamano;
  }

  public String getCecbActivotexto1() {
    return cecbActivotexto1;
  }

  public void setCecbActivotexto1(String cecbActivotexto1) {
    this.cecbActivotexto1 = cecbActivotexto1;
  }

  public String getCecbNegrita1() {
    return cecbNegrita1;
  }

  public void setCecbNegrita1(String cecbNegrita1) {
    this.cecbNegrita1 = cecbNegrita1;
  }

  public BigDecimal getCecbTexto2fila() {
    return cecbTexto2fila;
  }

  public void setCecbTexto2fila(BigDecimal cecbTexto2fila) {
    this.cecbTexto2fila = cecbTexto2fila;
  }

  public BigDecimal getCecbTexto2columna() {
    return cecbTexto2columna;
  }

  public void setCecbTexto2columna(BigDecimal cecbTexto2columna) {
    this.cecbTexto2columna = cecbTexto2columna;
  }

  public BigDecimal getCecbTexto2largo() {
    return cecbTexto2largo;
  }

  public void setCecbTexto2largo(BigDecimal cecbTexto2largo) {
    this.cecbTexto2largo = cecbTexto2largo;
  }

  public BigDecimal getCecbTexto2tamano() {
    return cecbTexto2tamano;
  }

  public void setCecbTexto2tamano(BigDecimal cecbTexto2tamano) {
    this.cecbTexto2tamano = cecbTexto2tamano;
  }

  public String getCecbActivotexto2() {
    return cecbActivotexto2;
  }

  public void setCecbActivotexto2(String cecbActivotexto2) {
    this.cecbActivotexto2 = cecbActivotexto2;
  }

  public String getCecbNegrita2() {
    return cecbNegrita2;
  }

  public void setCecbNegrita2(String cecbNegrita2) {
    this.cecbNegrita2 = cecbNegrita2;
  }

  public BigDecimal getCecbTexto3fila() {
    return cecbTexto3fila;
  }

  public void setCecbTexto3fila(BigDecimal cecbTexto3fila) {
    this.cecbTexto3fila = cecbTexto3fila;
  }

  public BigDecimal getCecbTexto3columna() {
    return cecbTexto3columna;
  }

  public void setCecbTexto3columna(BigDecimal cecbTexto3columna) {
    this.cecbTexto3columna = cecbTexto3columna;
  }

  public BigDecimal getCecbTexto3largo() {
    return cecbTexto3largo;
  }

  public void setCecbTexto3largo(BigDecimal cecbTexto3largo) {
    this.cecbTexto3largo = cecbTexto3largo;
  }

  public BigDecimal getCecbTexto3tamano() {
    return cecbTexto3tamano;
  }

  public void setCecbTexto3tamano(BigDecimal cecbTexto3tamano) {
    this.cecbTexto3tamano = cecbTexto3tamano;
  }

  public String getCecbActivotexto3() {
    return cecbActivotexto3;
  }

  public void setCecbActivotexto3(String cecbActivotexto3) {
    this.cecbActivotexto3 = cecbActivotexto3;
  }

  public String getCecbNegrita3() {
    return cecbNegrita3;
  }

  public void setCecbNegrita3(String cecbNegrita3) {
    this.cecbNegrita3 = cecbNegrita3;
  }

  public BigDecimal getCecbTexto4fila() {
    return cecbTexto4fila;
  }

  public void setCecbTexto4fila(BigDecimal cecbTexto4fila) {
    this.cecbTexto4fila = cecbTexto4fila;
  }

  public BigDecimal getCecbTexto4columna() {
    return cecbTexto4columna;
  }

  public void setCecbTexto4columna(BigDecimal cecbTexto4columna) {
    this.cecbTexto4columna = cecbTexto4columna;
  }

  public BigDecimal getCecbTexto4largo() {
    return cecbTexto4largo;
  }

  public void setCecbTexto4largo(BigDecimal cecbTexto4largo) {
    this.cecbTexto4largo = cecbTexto4largo;
  }

  public BigDecimal getCecbTexto4tamano() {
    return cecbTexto4tamano;
  }

  public void setCecbTexto4tamano(BigDecimal cecbTexto4tamano) {
    this.cecbTexto4tamano = cecbTexto4tamano;
  }

  public String getCecbActivotexto4() {
    return cecbActivotexto4;
  }

  public void setCecbActivotexto4(String cecbActivotexto4) {
    this.cecbActivotexto4 = cecbActivotexto4;
  }

  public String getCecbNegrita4() {
    return cecbNegrita4;
  }

  public void setCecbNegrita4(String cecbNegrita4) {
    this.cecbNegrita4 = cecbNegrita4;
  }

  public BigDecimal getCecbTexto5fila() {
    return cecbTexto5fila;
  }

  public void setCecbTexto5fila(BigDecimal cecbTexto5fila) {
    this.cecbTexto5fila = cecbTexto5fila;
  }

  public BigDecimal getCecbTexto5columna() {
    return cecbTexto5columna;
  }

  public void setCecbTexto5columna(BigDecimal cecbTexto5columna) {
    this.cecbTexto5columna = cecbTexto5columna;
  }

  public BigDecimal getCecbTexto5largo() {
    return cecbTexto5largo;
  }

  public void setCecbTexto5largo(BigDecimal cecbTexto5largo) {
    this.cecbTexto5largo = cecbTexto5largo;
  }

  public BigDecimal getCecbTexto5tamano() {
    return cecbTexto5tamano;
  }

  public void setCecbTexto5tamano(BigDecimal cecbTexto5tamano) {
    this.cecbTexto5tamano = cecbTexto5tamano;
  }

  public String getCecbActivotexto5() {
    return cecbActivotexto5;
  }

  public void setCecbActivotexto5(String cecbActivotexto5) {
    this.cecbActivotexto5 = cecbActivotexto5;
  }

  public String getCecbNegrita5() {
    return cecbNegrita5;
  }

  public void setCecbNegrita5(String cecbNegrita5) {
    this.cecbNegrita5 = cecbNegrita5;
  }

  public BigDecimal getCecbTexto6fila() {
    return cecbTexto6fila;
  }

  public void setCecbTexto6fila(BigDecimal cecbTexto6fila) {
    this.cecbTexto6fila = cecbTexto6fila;
  }

  public BigDecimal getCecbTexto6columna() {
    return cecbTexto6columna;
  }

  public void setCecbTexto6columna(BigDecimal cecbTexto6columna) {
    this.cecbTexto6columna = cecbTexto6columna;
  }

  public BigDecimal getCecbTexto6largo() {
    return cecbTexto6largo;
  }

  public void setCecbTexto6largo(BigDecimal cecbTexto6largo) {
    this.cecbTexto6largo = cecbTexto6largo;
  }

  public BigDecimal getCecbTexto6tamano() {
    return cecbTexto6tamano;
  }

  public void setCecbTexto6tamano(BigDecimal cecbTexto6tamano) {
    this.cecbTexto6tamano = cecbTexto6tamano;
  }

  public String getCecbActivotexto6() {
    return cecbActivotexto6;
  }

  public void setCecbActivotexto6(String cecbActivotexto6) {
    this.cecbActivotexto6 = cecbActivotexto6;
  }

  public String getCecbNegrita6() {
    return cecbNegrita6;
  }

  public void setCecbNegrita6(String cecbNegrita6) {
    this.cecbNegrita6 = cecbNegrita6;
  }

  public BigDecimal getCecbTexto7fila() {
    return cecbTexto7fila;
  }

  public void setCecbTexto7fila(BigDecimal cecbTexto7fila) {
    this.cecbTexto7fila = cecbTexto7fila;
  }

  public BigDecimal getCecbTexto7columna() {
    return cecbTexto7columna;
  }

  public void setCecbTexto7columna(BigDecimal cecbTexto7columna) {
    this.cecbTexto7columna = cecbTexto7columna;
  }

  public BigDecimal getCecbTexto7largo() {
    return cecbTexto7largo;
  }

  public void setCecbTexto7largo(BigDecimal cecbTexto7largo) {
    this.cecbTexto7largo = cecbTexto7largo;
  }

  public BigDecimal getCecbTexto7tamano() {
    return cecbTexto7tamano;
  }

  public void setCecbTexto7tamano(BigDecimal cecbTexto7tamano) {
    this.cecbTexto7tamano = cecbTexto7tamano;
  }

  public String getCecbActivotexto7() {
    return cecbActivotexto7;
  }

  public void setCecbActivotexto7(String cecbActivotexto7) {
    this.cecbActivotexto7 = cecbActivotexto7;
  }

  public String getCecbNegrita7() {
    return cecbNegrita7;
  }

  public void setCecbNegrita7(String cecbNegrita7) {
    this.cecbNegrita7 = cecbNegrita7;
  }

  public BigDecimal getCecbTexto8fila() {
    return cecbTexto8fila;
  }

  public void setCecbTexto8fila(BigDecimal cecbTexto8fila) {
    this.cecbTexto8fila = cecbTexto8fila;
  }

  public BigDecimal getCecbTexto8columna() {
    return cecbTexto8columna;
  }

  public void setCecbTexto8columna(BigDecimal cecbTexto8columna) {
    this.cecbTexto8columna = cecbTexto8columna;
  }

  public BigDecimal getCecbTexto8largo() {
    return cecbTexto8largo;
  }

  public void setCecbTexto8largo(BigDecimal cecbTexto8largo) {
    this.cecbTexto8largo = cecbTexto8largo;
  }

  public BigDecimal getCecbTexto8tamano() {
    return cecbTexto8tamano;
  }

  public void setCecbTexto8tamano(BigDecimal cecbTexto8tamano) {
    this.cecbTexto8tamano = cecbTexto8tamano;
  }

  public String getCecbActivotexto8() {
    return cecbActivotexto8;
  }

  public void setCecbActivotexto8(String cecbActivotexto8) {
    this.cecbActivotexto8 = cecbActivotexto8;
  }

  public String getCecbNegrita8() {
    return cecbNegrita8;
  }

  public void setCecbNegrita8(String cecbNegrita8) {
    this.cecbNegrita8 = cecbNegrita8;
  }

  public BigDecimal getCecbTexto9fila() {
    return cecbTexto9fila;
  }

  public void setCecbTexto9fila(BigDecimal cecbTexto9fila) {
    this.cecbTexto9fila = cecbTexto9fila;
  }

  public BigDecimal getCecbTexto9columna() {
    return cecbTexto9columna;
  }

  public void setCecbTexto9columna(BigDecimal cecbTexto9columna) {
    this.cecbTexto9columna = cecbTexto9columna;
  }

  public BigDecimal getCecbTexto9largo() {
    return cecbTexto9largo;
  }

  public void setCecbTexto9largo(BigDecimal cecbTexto9largo) {
    this.cecbTexto9largo = cecbTexto9largo;
  }

  public BigDecimal getCecbTexto9tamano() {
    return cecbTexto9tamano;
  }

  public void setCecbTexto9tamano(BigDecimal cecbTexto9tamano) {
    this.cecbTexto9tamano = cecbTexto9tamano;
  }

  public String getCecbActivotexto9() {
    return cecbActivotexto9;
  }

  public void setCecbActivotexto9(String cecbActivotexto9) {
    this.cecbActivotexto9 = cecbActivotexto9;
  }

  public String getCecbNegrita9() {
    return cecbNegrita9;
  }

  public void setCecbNegrita9(String cecbNegrita9) {
    this.cecbNegrita9 = cecbNegrita9;
  }

  public BigDecimal getCecbTexto10fila() {
    return cecbTexto10fila;
  }

  public void setCecbTexto10fila(BigDecimal cecbTexto10fila) {
    this.cecbTexto10fila = cecbTexto10fila;
  }

  public BigDecimal getCecbTexto10columna() {
    return cecbTexto10columna;
  }

  public void setCecbTexto10columna(BigDecimal cecbTexto10columna) {
    this.cecbTexto10columna = cecbTexto10columna;
  }

  public BigDecimal getCecbTexto10largo() {
    return cecbTexto10largo;
  }

  public void setCecbTexto10largo(BigDecimal cecbTexto10largo) {
    this.cecbTexto10largo = cecbTexto10largo;
  }

  public BigDecimal getCecbTexto10tamano() {
    return cecbTexto10tamano;
  }

  public void setCecbTexto10tamano(BigDecimal cecbTexto10tamano) {
    this.cecbTexto10tamano = cecbTexto10tamano;
  }

  public String getCecbActivotexto10() {
    return cecbActivotexto10;
  }

  public void setCecbActivotexto10(String cecbActivotexto10) {
    this.cecbActivotexto10 = cecbActivotexto10;
  }

  public String getCecbNegrita10() {
    return cecbNegrita10;
  }

  public void setCecbNegrita10(String cecbNegrita10) {
    this.cecbNegrita10 = cecbNegrita10;
  }

  public BigDecimal getCecbTexto11fila() {
    return cecbTexto11fila;
  }

  public void setCecbTexto11fila(BigDecimal cecbTexto11fila) {
    this.cecbTexto11fila = cecbTexto11fila;
  }

  public BigDecimal getCecbTexto11columna() {
    return cecbTexto11columna;
  }

  public void setCecbTexto11columna(BigDecimal cecbTexto11columna) {
    this.cecbTexto11columna = cecbTexto11columna;
  }

  public BigDecimal getCecbTexto11largo() {
    return cecbTexto11largo;
  }

  public void setCecbTexto11largo(BigDecimal cecbTexto11largo) {
    this.cecbTexto11largo = cecbTexto11largo;
  }

  public BigDecimal getCecbTexto11tamano() {
    return cecbTexto11tamano;
  }

  public void setCecbTexto11tamano(BigDecimal cecbTexto11tamano) {
    this.cecbTexto11tamano = cecbTexto11tamano;
  }

  public String getCecbActivotexto11() {
    return cecbActivotexto11;
  }

  public void setCecbActivotexto11(String cecbActivotexto11) {
    this.cecbActivotexto11 = cecbActivotexto11;
  }

  public String getCecbNegrita11() {
    return cecbNegrita11;
  }

  public void setCecbNegrita11(String cecbNegrita11) {
    this.cecbNegrita11 = cecbNegrita11;
  }

  public BigDecimal getCecbTexto12fila() {
    return cecbTexto12fila;
  }

  public void setCecbTexto12fila(BigDecimal cecbTexto12fila) {
    this.cecbTexto12fila = cecbTexto12fila;
  }

  public BigDecimal getCecbTexto12columna() {
    return cecbTexto12columna;
  }

  public void setCecbTexto12columna(BigDecimal cecbTexto12columna) {
    this.cecbTexto12columna = cecbTexto12columna;
  }

  public BigDecimal getCecbTexto12largo() {
    return cecbTexto12largo;
  }

  public void setCecbTexto12largo(BigDecimal cecbTexto12largo) {
    this.cecbTexto12largo = cecbTexto12largo;
  }

  public BigDecimal getCecbTexto12tamano() {
    return cecbTexto12tamano;
  }

  public void setCecbTexto12tamano(BigDecimal cecbTexto12tamano) {
    this.cecbTexto12tamano = cecbTexto12tamano;
  }

  public String getCecbActivotexto12() {
    return cecbActivotexto12;
  }

  public void setCecbActivotexto12(String cecbActivotexto12) {
    this.cecbActivotexto12 = cecbActivotexto12;
  }

  public String getCecbNegrita12() {
    return cecbNegrita12;
  }

  public void setCecbNegrita12(String cecbNegrita12) {
    this.cecbNegrita12 = cecbNegrita12;
  }

  public BigDecimal getCecbSort() {
    return cecbSort;
  }

  public void setCecbSort(BigDecimal cecbSort) {
    this.cecbSort = cecbSort;
  }

  public String getCecbNota() {
    return cecbNota;
  }

  public void setCecbNota(String cecbNota) {
    this.cecbNota = cecbNota;
  }

  public String getCecbUsuarioregistro() {
    return cecbUsuarioregistro;
  }

  public void setCecbUsuarioregistro(String cecbUsuarioregistro) {
    this.cecbUsuarioregistro = cecbUsuarioregistro;
  }

  public Date getCecbFecharegistro() {
    return cecbFecharegistro;
  }

  public void setCecbFecharegistro(Date cecbFecharegistro) {
    this.cecbFecharegistro = cecbFecharegistro;
  }

  public String getCecbProcedencia() {
    return cecbProcedencia;
  }

  public void setCecbProcedencia(String cecbProcedencia) {
    this.cecbProcedencia = cecbProcedencia;
  }

  public String getCecbServicio() {
    return cecbServicio;
  }

  public void setCecbServicio(String cecbServicio) {
    this.cecbServicio = cecbServicio;
  }

  public String getCecbTipopacprefijo() {
    return cecbTipopacprefijo;
  }

  public void setCecbTipopacprefijo(String cecbTipopacprefijo) {
    this.cecbTipopacprefijo = cecbTipopacprefijo;
  }

  public String getCecbTipopacsufijo() {
    return cecbTipopacsufijo;
  }

  public void setCecbTipopacsufijo(String cecbTipopacsufijo) {
    this.cecbTipopacsufijo = cecbTipopacsufijo;
  }

  public String getCecbProceprefijo() {
    return cecbProceprefijo;
  }

  public void setCecbProceprefijo(String cecbProceprefijo) {
    this.cecbProceprefijo = cecbProceprefijo;
  }

  public String getCecbProcesufijo() {
    return cecbProcesufijo;
  }

  public void setCecbProcesufijo(String cecbProcesufijo) {
    this.cecbProcesufijo = cecbProcesufijo;
  }

  public String getCecbServprefijo() {
    return cecbServprefijo;
  }

  public void setCecbServprefijo(String cecbServprefijo) {
    this.cecbServprefijo = cecbServprefijo;
  }

  public String getCecbServsufijo() {
    return cecbServsufijo;
  }

  public void setCecbServsufijo(String cecbServsufijo) {
    this.cecbServsufijo = cecbServsufijo;
  }

  public String getCecbNombprefijo() {
    return cecbNombprefijo;
  }

  public void setCecbNombprefijo(String cecbNombprefijo) {
    this.cecbNombprefijo = cecbNombprefijo;
  }

  public String getCecbNombsufijo() {
    return cecbNombsufijo;
  }

  public void setCecbNombsufijo(String cecbNombsufijo) {
    this.cecbNombsufijo = cecbNombsufijo;
  }

  public String getCecbSexoprefijo() {
    return cecbSexoprefijo;
  }

  public void setCecbSexoprefijo(String cecbSexoprefijo) {
    this.cecbSexoprefijo = cecbSexoprefijo;
  }

  public String getCecbSexosufijo() {
    return cecbSexosufijo;
  }

  public void setCecbSexosufijo(String cecbSexosufijo) {
    this.cecbSexosufijo = cecbSexosufijo;
  }

  public String getCecbEdadprefijo() {
    return cecbEdadprefijo;
  }

  public void setCecbEdadprefijo(String cecbEdadprefijo) {
    this.cecbEdadprefijo = cecbEdadprefijo;
  }

  public String getCecbEdadsufijo() {
    return cecbEdadsufijo;
  }

  public void setCecbEdadsufijo(String cecbEdadsufijo) {
    this.cecbEdadsufijo = cecbEdadsufijo;
  }

  public String getCecbTipmueprefijo() {
    return cecbTipmueprefijo;
  }

  public void setCecbTipmueprefijo(String cecbTipmueprefijo) {
    this.cecbTipmueprefijo = cecbTipmueprefijo;
  }

  public String getCecbTipmuesufijo() {
    return cecbTipmuesufijo;
  }

  public void setCecbTipmuesufijo(String cecbTipmuesufijo) {
    this.cecbTipmuesufijo = cecbTipmuesufijo;
  }

  public String getCecbEnvaprefijo() {
    return cecbEnvaprefijo;
  }

  public void setCecbEnvaprefijo(String cecbEnvaprefijo) {
    this.cecbEnvaprefijo = cecbEnvaprefijo;
  }

  public String getCecbEnvasufijo() {
    return cecbEnvasufijo;
  }

  public void setCecbEnvasufijo(String cecbEnvasufijo) {
    this.cecbEnvasufijo = cecbEnvasufijo;
  }

  public String getCecbFechaprefijo() {
    return cecbFechaprefijo;
  }

  public void setCecbFechaprefijo(String cecbFechaprefijo) {
    this.cecbFechaprefijo = cecbFechaprefijo;
  }

  public String getCecbFechasufijo() {
    return cecbFechasufijo;
  }

  public void setCecbFechasufijo(String cecbFechasufijo) {
    this.cecbFechasufijo = cecbFechasufijo;
  }

  public String getCecbParametrizada() {
    return cecbParametrizada;
  }

  public void setCecbParametrizada(String cecbParametrizada) {
    this.cecbParametrizada = cecbParametrizada;
  }

  public String getCecbRutprefijo() {
    return cecbRutprefijo;
  }

  public void setCecbRutprefijo(String cecbRutprefijo) {
    this.cecbRutprefijo = cecbRutprefijo;
  }

  public String getCecbRutsufijo() {
    return cecbRutsufijo;
  }

  public void setCecbRutsufijo(String cecbRutsufijo) {
    this.cecbRutsufijo = cecbRutsufijo;
  }

}
