package com.grupobios.bioslis.entity;
// Generated 21-10-2022 12:21:09 by Hibernate Tools 4.3.1



/**
 * CfgExamenesindicacionestm generated by hbm2java
 */
public class CfgExamenesindicacionestm  implements java.io.Serializable {


     private CfgExamenesindicacionestmId id;
     private LdvIndicacionestm ldvIndicacionestm;

    public CfgExamenesindicacionestm() {
    }

    public CfgExamenesindicacionestm(CfgExamenesindicacionestmId id, LdvIndicacionestm ldvIndicacionestm) {
       this.id = id;
       this.ldvIndicacionestm = ldvIndicacionestm;
    }
   
    public CfgExamenesindicacionestmId getId() {
        return this.id;
    }
    
    public void setId(CfgExamenesindicacionestmId id) {
        this.id = id;
    }
    public LdvIndicacionestm getLdvIndicacionestm() {
        return this.ldvIndicacionestm;
    }
    
    public void setLdvIndicacionestm(LdvIndicacionestm ldvIndicacionestm) {
        this.ldvIndicacionestm = ldvIndicacionestm;
    }




}


