package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgExamenesconjuntodetalleId generated by hbm2java
 */
public class CfgExamenesconjuntodetalleId  implements java.io.Serializable {


     private long cecdIdexamenesconjuntos;
     private long cecdIdexamen;

    public CfgExamenesconjuntodetalleId() {
    }

    public CfgExamenesconjuntodetalleId(long cecdIdexamenesconjuntos, long cecdIdexamen) {
       this.cecdIdexamenesconjuntos = cecdIdexamenesconjuntos;
       this.cecdIdexamen = cecdIdexamen;
    }
   
    public long getCecdIdexamenesconjuntos() {
        return this.cecdIdexamenesconjuntos;
    }
    
    public void setCecdIdexamenesconjuntos(long cecdIdexamenesconjuntos) {
        this.cecdIdexamenesconjuntos = cecdIdexamenesconjuntos;
    }
    public long getCecdIdexamen() {
        return this.cecdIdexamen;
    }
    
    public void setCecdIdexamen(long cecdIdexamen) {
        this.cecdIdexamen = cecdIdexamen;
    }




}


