package com.grupobios.bioslis.entity;


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;



// Generated Jun 26, 2020 11:17:59 AM by Hibernate Tools 4.3.1

/**
 * CfgExamenes generated by hbm2java
 */

public class CfgExamenes {


  private long ceIdexamen;
  @JsonIgnore
  private CfgGruposmuestras cfgGruposmuestras;
  @JsonIgnore
  private LdvLoinc ldvLoinc;
  @JsonIgnore
  private CfgGruposexamenesfonasa cfgGruposexamenesfonasa;
  @JsonIgnore
  private CfgMuestras cfgMuestras;
  @JsonIgnore
  private LdvGruposexamenes ldvGruposexamenes;
  @JsonIgnore
  private CfgPesquisas cfgPesquisas;
  @JsonIgnore
  private CfgDerivadores cfgDerivadores;
  @JsonIgnore
  private LdvTiposexamenes ldvTiposexamenes;
  @JsonIgnore
  private CfgSecciones cfgSecciones;
  @JsonIgnore
  private LdvFormatos ldvFormatos;
  @JsonIgnore
  private CfgExamenesconjuntos cfgExamenesconjuntos;
  @JsonIgnore
  private LdvIndicacionesexamenes ldvIndicacionesexamenes;
  @JsonIgnore
  private CfgMetodos cfgMetodos;
  private String ceCodigoexamen;
  private String ceDescripcion;
  private String ceAbreviado;
  private String ceAbreviado2;
  private String ceActivo;
  private String ceImprimirseparado;
  private String ceImprimirdescripcion;
  private String ceImprimirporseccion;
  private String ceImprimirtabla;
  private String ceMultiformato;
  private byte ceTipoexamensort;
  private Short ceIdtablareferenciaexamen;
  private String ceSeleccionable;
  private String ceHost;
  private String ceHostmicro;
  private String ceHost2;
  private String ceHost3;
  private String ceCodigofonasa;
  private Short ceSortseccion;
  private String ceEstadisticas;
  private String ceNota;
  private String ceEspesquisa;
  private String cePesquisaobligatoria;
  private String ceDatosmuestra;
  private Integer ceTiempoentreganormal;
  private Integer ceTiempoentregaurgente;
  private Integer ceTiempoentregahospitalizado;
  private String ceDiaprocesolunes;
  private String ceDiaprocesomartes;
  private String ceDiaprocesomiercoles;
  private String ceDiaprocesojueves;
  private String ceDiaprocesoviernes;
  private String ceDiaprocesosabado;
  private String ceDiaprocesodomingo;
  private float ceVolumenmuestraadulto;
  private float ceVolumenmuestrapediatrica;
  private String ceEstabilidadambiental;
  private String ceEstabilidadrefrigerado;
  private String ceEstabilidadcongelado;
  private Short ceContablecantidad;
  private String ceEsexamen;
  private String ceTienetestopcionales;
  private String ceEsurgente;
  private String ceEscultivo;
  private Byte ceNumerodeetiquetas;
  private String ceEsconfidencial;
  private String ceEsindicador;
  private String ceNombreweb;
  private String ceDisponibleweb;
  private String ceDiagnosticoobligatorio;
  private String ceHojatrabajo;
  private String ceEscurvatolerancia;
  private String cePlanillahistorica;
  private Integer ceDiasdevalidez;
  private Short ceDiasvalidezhospitalizado;
  private String ceDiasvalidezambulatorioblq;
  private String ceDiasvalidezhospitalizadoblq;
  private String ceEsexamenmultiseccion;
  private String ceAutovalidar;
  private String ceCompartemuestra;
  private String ceTienegrupomuestra;
  private String ceCellcounter;
  // @JsonIgnore
  // private CfgExamenesindicacionestm cfgExamenesindicacionestm;
  @JsonIgnore
  private Set cfgSeccionesexamenes = new HashSet(0);

  public String getCeCellcounter() {
    return ceCellcounter;
  }

  public void setCeCellcounter(String ceCellcounter) {
    this.ceCellcounter = ceCellcounter;
  }

  public CfgExamenes() {
  }

  public long getCeIdexamen() {
    return this.ceIdexamen;
  }

  public void setCeIdexamen(long ceIdexamen) {
    this.ceIdexamen = ceIdexamen;
  }

  public CfgGruposmuestras getCfgGruposmuestras() {
    return this.cfgGruposmuestras;
  }

  public void setCfgGruposmuestras(CfgGruposmuestras cfgGruposmuestras) {
    this.cfgGruposmuestras = cfgGruposmuestras;
  }

  public LdvLoinc getLdvLoinc() {
    return this.ldvLoinc;
  }

  public void setLdvLoinc(LdvLoinc ldvLoinc) {
    this.ldvLoinc = ldvLoinc;
  }

  public CfgGruposexamenesfonasa getCfgGruposexamenesfonasa() {
    return this.cfgGruposexamenesfonasa;
  }

  public void setCfgGruposexamenesfonasa(CfgGruposexamenesfonasa cfgGruposexamenesfonasa) {
    this.cfgGruposexamenesfonasa = cfgGruposexamenesfonasa;
  }

  public CfgMuestras getCfgMuestras() {
    return this.cfgMuestras;
  }

  public void setCfgMuestras(CfgMuestras cfgMuestras) {
    this.cfgMuestras = cfgMuestras;
  }

  public LdvGruposexamenes getLdvGruposexamenes() {
    return this.ldvGruposexamenes;
  }

  public void setLdvGruposexamenes(LdvGruposexamenes ldvGruposexamenes) {
    this.ldvGruposexamenes = ldvGruposexamenes;
  }

  public CfgPesquisas getCfgPesquisas() {
    return this.cfgPesquisas;
  }

  public void setCfgPesquisas(CfgPesquisas cfgPesquisas) {
    this.cfgPesquisas = cfgPesquisas;
  }

  public CfgDerivadores getCfgDerivadores() {
    return this.cfgDerivadores;
  }

  public void setCfgDerivadores(CfgDerivadores cfgDerivadores) {
    this.cfgDerivadores = cfgDerivadores;
  }

  public LdvTiposexamenes getLdvTiposexamenes() {
    return this.ldvTiposexamenes;
  }

  public void setLdvTiposexamenes(LdvTiposexamenes ldvTiposexamenes) {
    this.ldvTiposexamenes = ldvTiposexamenes;
  }

  public CfgSecciones getCfgSecciones() {
    return this.cfgSecciones;
  }

  public void setCfgSecciones(CfgSecciones cfgSecciones) {
    this.cfgSecciones = cfgSecciones;
  }

  public LdvFormatos getLdvFormatos() {
    return this.ldvFormatos;
  }

  public void setLdvFormatos(LdvFormatos ldvFormatos) {
    this.ldvFormatos = ldvFormatos;
  }

  public CfgExamenesconjuntos getCfgExamenesconjuntos() {
    return this.cfgExamenesconjuntos;
  }

  public void setCfgExamenesconjuntos(CfgExamenesconjuntos cfgExamenesconjuntos) {
    this.cfgExamenesconjuntos = cfgExamenesconjuntos;
  }

  public LdvIndicacionesexamenes getLdvIndicacionesexamenes() {
    return this.ldvIndicacionesexamenes;
  }

  public void setLdvIndicacionesexamenes(LdvIndicacionesexamenes ldvIndicacionesexamenes) {
    this.ldvIndicacionesexamenes = ldvIndicacionesexamenes;
  }

  public String getCeCodigoexamen() {
    return this.ceCodigoexamen;
  }

  public void setCeCodigoexamen(String ceCodigoexamen) {
    this.ceCodigoexamen = ceCodigoexamen;
  }

  public String getCeDescripcion() {
    return this.ceDescripcion;
  }

  public void setCeDescripcion(String ceDescripcion) {
    this.ceDescripcion = ceDescripcion;
  }

  public String getCeAbreviado() {
    return this.ceAbreviado;
  }

  public void setCeAbreviado(String ceAbreviado) {
    this.ceAbreviado = ceAbreviado;
  }

  public String getCeAbreviado2() {
    return this.ceAbreviado2;
  }

  public void setCeAbreviado2(String ceAbreviado2) {
    this.ceAbreviado2 = ceAbreviado2;
  }

  public String getCeActivo() {
    return this.ceActivo;
  }

  public void setCeActivo(String ceActivo) {
    this.ceActivo = ceActivo;
  }

  public String getCeImprimirseparado() {
    return this.ceImprimirseparado;
  }

  public void setCeImprimirseparado(String ceImprimirseparado) {
    this.ceImprimirseparado = ceImprimirseparado;
  }

  public String getCeImprimirdescripcion() {
    return this.ceImprimirdescripcion;
  }

  public void setCeImprimirdescripcion(String ceImprimirdescripcion) {
    this.ceImprimirdescripcion = ceImprimirdescripcion;
  }

  public String getCeImprimirporseccion() {
    return this.ceImprimirporseccion;
  }

  public void setCeImprimirporseccion(String ceImprimirporseccion) {
    this.ceImprimirporseccion = ceImprimirporseccion;
  }

  public String getCeImprimirtabla() {
    return this.ceImprimirtabla;
  }

  public void setCeImprimirtabla(String ceImprimirtabla) {
    this.ceImprimirtabla = ceImprimirtabla;
  }

  public String getCeMultiformato() {
    return this.ceMultiformato;
  }

  public void setCeMultiformato(String ceMultiformato) {
    this.ceMultiformato = ceMultiformato;
  }

  public byte getCeTipoexamensort() {
    return this.ceTipoexamensort;
  }

  public void setCeTipoexamensort(byte ceTipoexamensort) {
    this.ceTipoexamensort = ceTipoexamensort;
  }

  public Short getCeIdtablareferenciaexamen() {
    return this.ceIdtablareferenciaexamen;
  }

  public void setCeIdtablareferenciaexamen(Short ceIdtablareferenciaexamen) {
    this.ceIdtablareferenciaexamen = ceIdtablareferenciaexamen;
  }

  public String getCeSeleccionable() {
    return this.ceSeleccionable;
  }

  public void setCeSeleccionable(String ceSeleccionable) {
    this.ceSeleccionable = ceSeleccionable;
  }

  public String getCeHost() {
    return this.ceHost;
  }

  public void setCeHost(String ceHost) {
    this.ceHost = ceHost;
  }

  public String getCeHostmicro() {
    return this.ceHostmicro;
  }

  public void setCeHostmicro(String ceHostmicro) {
    this.ceHostmicro = ceHostmicro;
  }

  public String getCeHost2() {
    return this.ceHost2;
  }

  public void setCeHost2(String ceHost2) {
    this.ceHost2 = ceHost2;
  }

  public String getCeHost3() {
    return this.ceHost3;
  }

  public void setCeHost3(String ceHost3) {
    this.ceHost3 = ceHost3;
  }

  public String getCeCodigofonasa() {
    return this.ceCodigofonasa;
  }

  public void setCeCodigofonasa(String ceCodigofonasa) {
    this.ceCodigofonasa = ceCodigofonasa;
  }

  public Short getCeSortseccion() {
    return this.ceSortseccion;
  }

  public void setCeSortseccion(Short ceSortseccion) {
    this.ceSortseccion = ceSortseccion;
  }

  public String getCeEstadisticas() {
    return this.ceEstadisticas;
  }

  public void setCeEstadisticas(String ceEstadisticas) {
    this.ceEstadisticas = ceEstadisticas;
  }

  public String getCeNota() {
    return this.ceNota;
  }

  public void setCeNota(String ceNota) {
    this.ceNota = ceNota;
  }

  public String getCeEspesquisa() {
    return this.ceEspesquisa;
  }

  public void setCeEspesquisa(String ceEspesquisa) {
    this.ceEspesquisa = ceEspesquisa;
  }

  public String getCePesquisaobligatoria() {
    return this.cePesquisaobligatoria;
  }

  public void setCePesquisaobligatoria(String cePesquisaobligatoria) {
    this.cePesquisaobligatoria = cePesquisaobligatoria;
  }

  public String getCeDatosmuestra() {
    return this.ceDatosmuestra;
  }

  public void setCeDatosmuestra(String ceDatosmuestra) {
    this.ceDatosmuestra = ceDatosmuestra;
  }

  public Integer getCeTiempoentreganormal() {
    return this.ceTiempoentreganormal;
  }

  public void setCeTiempoentreganormal(Integer ceTiempoentreganormal) {
    this.ceTiempoentreganormal = ceTiempoentreganormal;
  }

  public Integer getCeTiempoentregaurgente() {
    return this.ceTiempoentregaurgente;
  }

  public void setCeTiempoentregaurgente(Integer ceTiempoentregaurgente) {
    this.ceTiempoentregaurgente = ceTiempoentregaurgente;
  }

  public Integer getCeTiempoentregahospitalizado() {
    return this.ceTiempoentregahospitalizado;
  }

  public void setCeTiempoentregahospitalizado(Integer ceTiempoentregahospitalizado) {
    this.ceTiempoentregahospitalizado = ceTiempoentregahospitalizado;
  }

  public String getCeDiaprocesolunes() {
    return this.ceDiaprocesolunes;
  }

  public void setCeDiaprocesolunes(String ceDiaprocesolunes) {
    this.ceDiaprocesolunes = ceDiaprocesolunes;
  }

  public String getCeDiaprocesomartes() {
    return this.ceDiaprocesomartes;
  }

  public void setCeDiaprocesomartes(String ceDiaprocesomartes) {
    this.ceDiaprocesomartes = ceDiaprocesomartes;
  }

  public String getCeDiaprocesomiercoles() {
    return this.ceDiaprocesomiercoles;
  }

  public void setCeDiaprocesomiercoles(String ceDiaprocesomiercoles) {
    this.ceDiaprocesomiercoles = ceDiaprocesomiercoles;
  }

  public String getCeDiaprocesojueves() {
    return this.ceDiaprocesojueves;
  }

  public void setCeDiaprocesojueves(String ceDiaprocesojueves) {
    this.ceDiaprocesojueves = ceDiaprocesojueves;
  }

  public String getCeDiaprocesoviernes() {
    return this.ceDiaprocesoviernes;
  }

  public void setCeDiaprocesoviernes(String ceDiaprocesoviernes) {
    this.ceDiaprocesoviernes = ceDiaprocesoviernes;
  }

  public String getCeDiaprocesosabado() {
    return this.ceDiaprocesosabado;
  }

  public void setCeDiaprocesosabado(String ceDiaprocesosabado) {
    this.ceDiaprocesosabado = ceDiaprocesosabado;
  }

  public String getCeDiaprocesodomingo() {
    return this.ceDiaprocesodomingo;
  }

  public void setCeDiaprocesodomingo(String ceDiaprocesodomingo) {
    this.ceDiaprocesodomingo = ceDiaprocesodomingo;
  }

  public float getCeVolumenmuestraadulto() {
    return ceVolumenmuestraadulto;
  }

  public void setCeVolumenmuestraadulto(float ceVolumenmuestraadulto) {
    this.ceVolumenmuestraadulto = ceVolumenmuestraadulto;
  }

  public float getCeVolumenmuestrapediatrica() {
    return ceVolumenmuestrapediatrica;
  }

  public void setCeVolumenmuestrapediatrica(float ceVolumenmuestrapediatrica) {
    this.ceVolumenmuestrapediatrica = ceVolumenmuestrapediatrica;
  }

  public String getCeEstabilidadambiental() {
    return this.ceEstabilidadambiental;
  }

  public void setCeEstabilidadambiental(String ceEstabilidadambiental) {
    this.ceEstabilidadambiental = ceEstabilidadambiental;
  }

  public String getCeEstabilidadrefrigerado() {
    return this.ceEstabilidadrefrigerado;
  }

  public void setCeEstabilidadrefrigerado(String ceEstabilidadrefrigerado) {
    this.ceEstabilidadrefrigerado = ceEstabilidadrefrigerado;
  }

  public String getCeEstabilidadcongelado() {
    return this.ceEstabilidadcongelado;
  }

  public void setCeEstabilidadcongelado(String ceEstabilidadcongelado) {
    this.ceEstabilidadcongelado = ceEstabilidadcongelado;
  }

  public Short getCeContablecantidad() {
    return this.ceContablecantidad;
  }

  public void setCeContablecantidad(Short ceContablecantidad) {
    this.ceContablecantidad = ceContablecantidad;
  }

  public String getCeEsexamen() {
    return this.ceEsexamen;
  }

  public void setCeEsexamen(String ceEsexamen) {
    this.ceEsexamen = ceEsexamen;
  }

  public String getCeTienetestopcionales() {
    return this.ceTienetestopcionales;
  }

  public void setCeTienetestopcionales(String ceTienetestopcionales) {
    this.ceTienetestopcionales = ceTienetestopcionales;
  }

  public String getCeEsurgente() {
    return this.ceEsurgente;
  }

  public void setCeEsurgente(String ceEsurgente) {
    this.ceEsurgente = ceEsurgente;
  }

  public String getCeEscultivo() {
    return this.ceEscultivo;
  }

  public void setCeEscultivo(String ceEscultivo) {
    this.ceEscultivo = ceEscultivo;
  }

  public Byte getCeNumerodeetiquetas() {
    return this.ceNumerodeetiquetas;
  }

  public void setCeNumerodeetiquetas(Byte ceNumerodeetiquetas) {
    this.ceNumerodeetiquetas = ceNumerodeetiquetas;
  }

  public String getCeEsconfidencial() {
    return this.ceEsconfidencial;
  }

  public void setCeEsconfidencial(String ceEsconfidencial) {
    this.ceEsconfidencial = ceEsconfidencial;
  }

  public String getCeEsindicador() {
    return this.ceEsindicador;
  }

  public void setCeEsindicador(String ceEsindicador) {
    this.ceEsindicador = ceEsindicador;
  }

  public String getCeNombreweb() {
    return this.ceNombreweb;
  }

  public void setCeNombreweb(String ceNombreweb) {
    this.ceNombreweb = ceNombreweb;
  }

  public String getCeDisponibleweb() {
    return this.ceDisponibleweb;
  }

  public void setCeDisponibleweb(String ceDisponibleweb) {
    this.ceDisponibleweb = ceDisponibleweb;
  }

  public String getCeDiagnosticoobligatorio() {
    return this.ceDiagnosticoobligatorio;
  }

  public void setCeDiagnosticoobligatorio(String ceDiagnosticoobligatorio) {
    this.ceDiagnosticoobligatorio = ceDiagnosticoobligatorio;
  }

  public String getCeHojatrabajo() {
    return this.ceHojatrabajo;
  }

  public void setCeHojatrabajo(String ceHojatrabajo) {
    this.ceHojatrabajo = ceHojatrabajo;
  }

  public String getCeEscurvatolerancia() {
    return this.ceEscurvatolerancia;
  }

  public void setCeEscurvatolerancia(String ceEscurvatolerancia) {
    this.ceEscurvatolerancia = ceEscurvatolerancia;
  }

  public String getCePlanillahistorica() {
    return this.cePlanillahistorica;
  }

  public void setCePlanillahistorica(String cePlanillahistorica) {
    this.cePlanillahistorica = cePlanillahistorica;
  }

  public Integer getCeDiasdevalidez() {
    return this.ceDiasdevalidez;
  }

  public void setCeDiasdevalidez(Integer ceDiasdevalidez) {
    this.ceDiasdevalidez = ceDiasdevalidez;
  }

  public Short getCeDiasvalidezhospitalizado() {
    return this.ceDiasvalidezhospitalizado;
  }

  public void setCeDiasvalidezhospitalizado(Short ceDiasvalidezhospitalizado) {
    this.ceDiasvalidezhospitalizado = ceDiasvalidezhospitalizado;
  }

  public String getCeDiasvalidezambulatorioblq() {
    return this.ceDiasvalidezambulatorioblq;
  }

  public void setCeDiasvalidezambulatorioblq(String ceDiasvalidezambulatorioblq) {
    this.ceDiasvalidezambulatorioblq = ceDiasvalidezambulatorioblq;
  }

  public String getCeDiasvalidezhospitalizadoblq() {
    return this.ceDiasvalidezhospitalizadoblq;
  }

  public void setCeDiasvalidezhospitalizadoblq(String ceDiasvalidezhospitalizadoblq) {
    this.ceDiasvalidezhospitalizadoblq = ceDiasvalidezhospitalizadoblq;
  }

  public String getCeEsexamenmultiseccion() {
    return this.ceEsexamenmultiseccion;
  }

  public void setCeEsexamenmultiseccion(String ceEsexamenmultiseccion) {
    this.ceEsexamenmultiseccion = ceEsexamenmultiseccion;
  }

  public String getCeAutovalidar() {
    return this.ceAutovalidar;
  }

  public void setCeAutovalidar(String ceAutovalidar) {
    this.ceAutovalidar = ceAutovalidar;
  }

  public String getCeCompartemuestra() {
    return this.ceCompartemuestra;
  }

  public void setCeCompartemuestra(String ceCompartemuestra) {
    this.ceCompartemuestra = ceCompartemuestra;
  }

  public CfgMetodos getCfgMetodos() {
    return cfgMetodos;
  }

  public void setCfgMetodos(CfgMetodos cfgMetodos) {
    this.cfgMetodos = cfgMetodos;
  }

  public String getCeTienegrupomuestra() {
    return ceTienegrupomuestra;
  }

  public void setCeTienegrupomuestra(String ceTienegrupomuestra) {
    this.ceTienegrupomuestra = ceTienegrupomuestra;
  }

  /*
   * public CfgExamenesindicacionestm getCfgExamenesindicacionestm() { return
   * cfgExamenesindicacionestm; }
   * 
   * public void setCfgExamenesindicacionestm(CfgExamenesindicacionestm
   * cfgExamenesindicacionestm) { this.cfgExamenesindicacionestm =
   * cfgExamenesindicacionestm; }
   */
  public Set getCfgSeccionesexameneses() {
    return cfgSeccionesexamenes;
  }

  public void setCfgSeccionesexameneses(Set cfgSeccionesexameneses) {
    this.cfgSeccionesexamenes = cfgSeccionesexameneses;
  }


	@Override
	public String toString() {
		return "CfgExamenes [ceIdexamen=" + ceIdexamen + ", ceCodigoexamen=" + ceCodigoexamen + ", ceDescripcion=" + ceDescripcion + ", ceAbreviado="
				+ ceAbreviado + ", ceAbreviado2=" + ceAbreviado2 + ", ceActivo=" + ceActivo + ", ceImprimirseparado="
				+ ceImprimirseparado + ", ceImprimirdescripcion=" + ceImprimirdescripcion + ", ceImprimirporseccion="
				+ ceImprimirporseccion + ", ceImprimirtabla=" + ceImprimirtabla + ", ceMultiformato=" + ceMultiformato
				+ ", ceTipoexamensort=" + ceTipoexamensort + ", ceIdtablareferenciaexamen=" + ceIdtablareferenciaexamen
				+ ", ceSeleccionable=" + ceSeleccionable + ", ceHost=" + ceHost + ", ceHostmicro=" + ceHostmicro
				+ ", ceHost2=" + ceHost2 + ", ceHost3=" + ceHost3 + ", ceCodigofonasa=" + ceCodigofonasa
				+ ", ceSortseccion=" + ceSortseccion + ", ceEstadisticas=" + ceEstadisticas + ", ceNota=" + ceNota
				+ ", ceEspesquisa=" + ceEspesquisa + ", cePesquisaobligatoria=" + cePesquisaobligatoria
				+ ", ceDatosmuestra=" + ceDatosmuestra + ", ceTiempoentreganormal=" + ceTiempoentreganormal
				+ ", ceTiempoentregaurgente=" + ceTiempoentregaurgente + ", ceTiempoentregahospitalizado="
				+ ceTiempoentregahospitalizado + ", ceDiaprocesolunes=" + ceDiaprocesolunes + ", ceDiaprocesomartes="
				+ ceDiaprocesomartes + ", ceDiaprocesomiercoles=" + ceDiaprocesomiercoles + ", ceDiaprocesojueves="
				+ ceDiaprocesojueves + ", ceDiaprocesoviernes=" + ceDiaprocesoviernes + ", ceDiaprocesosabado="
				+ ceDiaprocesosabado + ", ceDiaprocesodomingo=" + ceDiaprocesodomingo + ", ceVolumenmuestraadulto="
				+ ceVolumenmuestraadulto + ", ceVolumenmuestrapediatrica=" + ceVolumenmuestrapediatrica
				+ ", ceEstabilidadambiental=" + ceEstabilidadambiental + ", ceEstabilidadrefrigerado="
				+ ceEstabilidadrefrigerado + ", ceEstabilidadcongelado=" + ceEstabilidadcongelado
				+ ", ceContablecantidad=" + ceContablecantidad + ", ceEsexamen=" + ceEsexamen
				+ ", ceTienetestopcionales=" + ceTienetestopcionales + ", ceEsurgente=" + ceEsurgente + ", ceEscultivo="
				+ ceEscultivo + ", ceNumerodeetiquetas=" + ceNumerodeetiquetas + ", ceEsconfidencial="
				+ ceEsconfidencial + ", ceEsindicador=" + ceEsindicador + ", ceNombreweb=" + ceNombreweb
				+ ", ceDisponibleweb=" + ceDisponibleweb + ", ceDiagnosticoobligatorio=" + ceDiagnosticoobligatorio
				+ ", ceHojatrabajo=" + ceHojatrabajo + ", ceEscurvatolerancia=" + ceEscurvatolerancia
				+ ", cePlanillahistorica=" + cePlanillahistorica + ", ceDiasdevalidez=" + ceDiasdevalidez
				+ ", ceDiasvalidezhospitalizado=" + ceDiasvalidezhospitalizado + ", ceDiasvalidezambulatorioblq="
				+ ceDiasvalidezambulatorioblq + ", ceDiasvalidezhospitalizadoblq=" + ceDiasvalidezhospitalizadoblq
				+ ", ceEsexamenmultiseccion=" + ceEsexamenmultiseccion + ", ceAutovalidar=" + ceAutovalidar
				+ ", ceCompartemuestra=" + ceCompartemuestra + ", ceTienegrupomuestra=" + ceTienegrupomuestra
				+ ", ceCellcounter=" + ceCellcounter +  "]";
	}

    
}
