package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;




/**
 * CfgExamenesconjuntodetalle generated by hbm2java
 */
public class CfgExamenesconjuntodetalle  implements java.io.Serializable {


     private CfgExamenesconjuntodetalleId id;
     @JsonIgnore
     private CfgExamenesconjuntos cfgExamenesconjuntos;
     private Short cecdOrden;

    public CfgExamenesconjuntodetalle() {
    }

	
    public CfgExamenesconjuntodetalle(CfgExamenesconjuntodetalleId id, CfgExamenesconjuntos cfgExamenesconjuntos) {
        this.id = id;
        this.cfgExamenesconjuntos = cfgExamenesconjuntos;
    }
    public CfgExamenesconjuntodetalle(CfgExamenesconjuntodetalleId id, CfgExamenesconjuntos cfgExamenesconjuntos, Short cecdOrden) {
       this.id = id;
       this.cfgExamenesconjuntos = cfgExamenesconjuntos;
       this.cecdOrden = cecdOrden;
    }
   
    public CfgExamenesconjuntodetalleId getId() {
        return this.id;
    }
    
    public void setId(CfgExamenesconjuntodetalleId id) {
        this.id = id;
    }
    public CfgExamenesconjuntos getCfgExamenesconjuntos() {
        return this.cfgExamenesconjuntos;
    }
    
    public void setCfgExamenesconjuntos(CfgExamenesconjuntos cfgExamenesconjuntos) {
        this.cfgExamenesconjuntos = cfgExamenesconjuntos;
    }
    public Short getCecdOrden() {
        return this.cecdOrden;
    }
    
    public void setCecdOrden(Short cecdOrden) {
        this.cecdOrden = cecdOrden;
    }




}


