package com.grupobios.bioslis.entity;
// Generated 20-10-2022 1:24:13 by Hibernate Tools 4.3.1



/**
 * CfgExamenesindicacionestmId generated by hbm2java
 */
public class CfgExamenesindicacionestmId  implements java.io.Serializable {


     private long ceitmIdexamen;
     private short ceitmIdindicaciontm;

    public CfgExamenesindicacionestmId() {
    }

    public CfgExamenesindicacionestmId(long ceitmIdexamen, short ceitmIdindicaciontm) {
       this.ceitmIdexamen = ceitmIdexamen;
       this.ceitmIdindicaciontm = ceitmIdindicaciontm;
    }
   
    public long getCeitmIdexamen() {
        return this.ceitmIdexamen;
    }
    
    public void setCeitmIdexamen(long ceitmIdexamen) {
        this.ceitmIdexamen = ceitmIdexamen;
    }
    public short getCeitmIdindicaciontm() {
        return this.ceitmIdindicaciontm;
    }
    
    public void setCeitmIdindicaciontm(short ceitmIdindicaciontm) {
        this.ceitmIdindicaciontm = ceitmIdindicaciontm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CfgExamenesindicacionestmId) ) return false;
		 CfgExamenesindicacionestmId castOther = ( CfgExamenesindicacionestmId ) other; 
         
		 return (this.getCeitmIdexamen()==castOther.getCeitmIdexamen())
 && (this.getCeitmIdindicaciontm()==castOther.getCeitmIdindicaciontm());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCeitmIdexamen();
         result = 37 * result + this.getCeitmIdindicaciontm();
         return result;
   }   


}


