package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgExamenesconjuntos generated by hbm2java
 */
public class CfgExamenesconjuntos  implements java.io.Serializable {


     private long cecIdexamenesconjuntos;
     private Long cecCodigoexamenesconjuntos;
     private String cecDescripcion;
     @JsonIgnore
     private Set cfgExameneses = new HashSet(0);
     @JsonIgnore
     private Set cfgExamenesconjuntodetalles = new HashSet(0);

    public CfgExamenesconjuntos() {
    }

	
    public CfgExamenesconjuntos(long cecIdexamenesconjuntos) {
        this.cecIdexamenesconjuntos = cecIdexamenesconjuntos;
    }
    public CfgExamenesconjuntos(long cecIdexamenesconjuntos, Long cecCodigoexamenesconjuntos, String cecDescripcion, Set cfgExameneses, Set cfgExamenesconjuntodetalles) {
       this.cecIdexamenesconjuntos = cecIdexamenesconjuntos;
       this.cecCodigoexamenesconjuntos = cecCodigoexamenesconjuntos;
       this.cecDescripcion = cecDescripcion;
       this.cfgExameneses = cfgExameneses;
       this.cfgExamenesconjuntodetalles = cfgExamenesconjuntodetalles;
    }
   
    public long getCecIdexamenesconjuntos() {
        return this.cecIdexamenesconjuntos;
    }
    
    public void setCecIdexamenesconjuntos(long cecIdexamenesconjuntos) {
        this.cecIdexamenesconjuntos = cecIdexamenesconjuntos;
    }
    public Long getCecCodigoexamenesconjuntos() {
        return this.cecCodigoexamenesconjuntos;
    }
    
    public void setCecCodigoexamenesconjuntos(Long cecCodigoexamenesconjuntos) {
        this.cecCodigoexamenesconjuntos = cecCodigoexamenesconjuntos;
    }
    public String getCecDescripcion() {
        return this.cecDescripcion;
    }
    
    public void setCecDescripcion(String cecDescripcion) {
        this.cecDescripcion = cecDescripcion;
    }
    public Set getCfgExameneses() {
        return this.cfgExameneses;
    }
    
    public void setCfgExameneses(Set cfgExameneses) {
        this.cfgExameneses = cfgExameneses;
    }
    public Set getCfgExamenesconjuntodetalles() {
        return this.cfgExamenesconjuntodetalles;
    }
    
    public void setCfgExamenesconjuntodetalles(Set cfgExamenesconjuntodetalles) {
        this.cfgExamenesconjuntodetalles = cfgExamenesconjuntodetalles;
    }




}


