package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Set;

/**
 * CfgExamenestest generated by hbm2java
 */
public class CfgExamenestest implements java.io.Serializable {
        @JsonIgnore
	private CfgExamenestestId id;
	private CfgTest cfgTest;
        @JsonIgnore
	private CfgEnvases cfgEnvases;
	private Short cetPosicion;
        @JsonIgnore
	private Set datosFichasexamenestests;

	public CfgExamenestest() {
	}

	public CfgExamenestestId getId() {
		return this.id;
	}

	public void setId(CfgExamenestestId id) {
		this.id = id;
	}

	public CfgTest getCfgTest() {
		return this.cfgTest;
	}

	public void setCfgTest(CfgTest cfgTest) {
		this.cfgTest = cfgTest;
	}

	public CfgEnvases getCfgEnvases() {
		return this.cfgEnvases;
	}

	public void setCfgEnvases(CfgEnvases cfgEnvases) {
		this.cfgEnvases = cfgEnvases;
	}

	public Short getCetPosicion() {
		return this.cetPosicion;
	}

	public void setCetPosicion(Short cetPosicion) {
		this.cetPosicion = cetPosicion;
	}

	public Set getDatosFichasexamenestests() {
		return this.datosFichasexamenestests;
	}

	public void setDatosFichasexamenestests(Set datosFichasexamenestests) {
		this.datosFichasexamenestests = datosFichasexamenestests;
	}

	@Override
	public String toString() {
		return "CfgExamenestest [id=" + id + ", cfgTest=" + cfgTest + ", cfgEnvases=" + cfgEnvases + ", cetPosicion="
				+ cetPosicion + "]";
	}

}

//public CfgExamenestest(CfgExamenestestId id, CfgTest cfgTest, CfgEnvases cfgEnvases) {
//this.id = id;
//this.cfgTest = cfgTest;
//this.cfgEnvases = cfgEnvases;
//}
//public CfgExamenestest(CfgExamenestestId id, CfgTest cfgTest, CfgEnvases cfgEnvases, Short cetPosicion, Set datosFichasexamenestests) {
//this.id = id;
//this.cfgTest = cfgTest;
//this.cfgEnvases = cfgEnvases;
//this.cetPosicion = cetPosicion;
//this.datosFichasexamenestests = datosFichasexamenestests;
//}
