package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.sql.Blob;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.math.BigDecimal;

/**
 * CfgEnvases generated by hbm2java
 */
public class CfgEnvases implements java.io.Serializable {

	private int cenvIdenvase;
	private String cenvCodigo;
	private String cenvDescripcion;
	private int cenvIdtipomuestra;
	private String cenvActivo;
	private int cenvSort;
	private String cenvHost;
	@JsonIgnore
	private Blob cenvImagenenvase;
        private BigDecimal cenvVolumenml;
	private Integer cenvVolumenutilmicrolt;
        private String cenvColor;
	@JsonIgnore
	private Set cfgTests;

	public CfgEnvases() {
	}

	public CfgEnvases(int cenvIdenvase) {
		this.cenvIdenvase = cenvIdenvase;
	}

	public int getCenvIdenvase() {
		return this.cenvIdenvase;
	}

	public void setCenvIdenvase(int cenvIdenvase) {
		this.cenvIdenvase = cenvIdenvase;
	}

	public String getCenvCodigo() {
		return this.cenvCodigo;
	}

	public void setCenvCodigo(String cenvCodigo) {
		this.cenvCodigo = cenvCodigo;
	}

	public String getCenvDescripcion() {
		return this.cenvDescripcion;
	}

	public void setCenvDescripcion(String cenvDescripcion) {
		this.cenvDescripcion = cenvDescripcion;
	}

	public int getCenvIdtipomuestra() {
		return this.cenvIdtipomuestra;
	}

	public void setCenvIdtipomuestra(int cenvIdtipomuestra) {
		this.cenvIdtipomuestra = cenvIdtipomuestra;
	}

	public String getCenvActivo() {
		return this.cenvActivo;
	}

	public void setCenvActivo(String cenvActivo) {
		this.cenvActivo = cenvActivo;
	}

	public int getCenvSort() {
		return this.cenvSort;
	}

	public void setCenvSort(int cenvSort) {
		this.cenvSort = cenvSort;
	}

	public String getCenvHost() {
		return this.cenvHost;
	}

	public void setCenvHost(String cenvHost) {
		this.cenvHost = cenvHost;
	}

	public Blob getCenvImagenenvase() {
		return this.cenvImagenenvase;
	}

	public void setCenvImagenenvase(Blob cenvImagenenvase) {
		this.cenvImagenenvase = cenvImagenenvase;
	}

	public BigDecimal getCenvVolumenml() {
            return this.cenvVolumenml;
        }

        public void setCenvVolumenml(BigDecimal cenvVolumenml) {
            this.cenvVolumenml = cenvVolumenml;
        }

	public Integer getCenvVolumenutilmicrolt() {
		return this.cenvVolumenutilmicrolt;
	}

	public void setCenvVolumenutilmicrolt(Integer cenvVolumenutilmicrolt) {
		this.cenvVolumenutilmicrolt = cenvVolumenutilmicrolt;
	}

        public String getCenvColor() {
            return this.cenvColor;
        }

        public void setCenvColor(String cenvColor) {
            this.cenvColor = cenvColor;
        }
        
	public Set getCfgTests() {
		return this.cfgTests;
	}

	public void setCfgTests(Set cfgTests) {
		this.cfgTests = cfgTests;
	}

	@Override
	public String toString() {
		return "CfgEnvases [cenvIdenvase=" + cenvIdenvase + ", cenvCodigo=" + cenvCodigo + ", cenvDescripcion="
				+ cenvDescripcion + ", cenvIdtipomuestra=" + cenvIdtipomuestra + ", cenvActivo=" + cenvActivo
				+ ", cenvSort=" + cenvSort + ", cenvHost=" + cenvHost + ", cenvImagenenvase=" + cenvImagenenvase
				+ ", cenvVolumenml=" + cenvVolumenml + ", cenvVolumenutilmicrolt=" + cenvVolumenutilmicrolt
				+ ", cenvColor=" + cenvColor + ", cfgTests=" + cfgTests + "]";
	}

}
