package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * CfgEstadosexamenes generated by hbm2java
 */
public class CfgEstadosexamenes implements java.io.Serializable {

	private int ceeIdestadoexamen;
	private String ceeCodigoestadoexamen;
	private String ceeDescripcionestadoexamen;

	public CfgEstadosexamenes() {
	}

	public CfgEstadosexamenes(int ceeIdestadoexamen) {
		this.ceeIdestadoexamen = ceeIdestadoexamen;
	}

	public int isCeeIdestadoexamen() {
		return this.ceeIdestadoexamen;
	}

	public void setCeeIdestadoexamen(int ceeIdestadoexamen) {
		this.ceeIdestadoexamen = ceeIdestadoexamen;
	}

	public String getCeeCodigoestadoexamen() {
		return this.ceeCodigoestadoexamen;
	}

	public void setCeeCodigoestadoexamen(String ceeCodigoestadoexamen) {
		this.ceeCodigoestadoexamen = ceeCodigoestadoexamen;
	}

	public String getCeeDescripcionestadoexamen() {
		return this.ceeDescripcionestadoexamen;
	}

	public void setCeeDescripcionestadoexamen(String ceeDescripcionestadoexamen) {
		this.ceeDescripcionestadoexamen = ceeDescripcionestadoexamen;
	}

}
