package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CfgEstacionestrabajo generated by hbm2java
 */
public class CfgEstacionestrabajo  implements java.io.Serializable {


     private short cestIdestacion;
     private DatosUsuarios datosUsuarios;
     private String cestUbicacion;
     private Date cestFechaingreso;
     private String cestActivo;
     private String cestHostname;
     private String cestIpestacion;
     private String cestVersionbioslis;

    public CfgEstacionestrabajo() {
    }

	
    public CfgEstacionestrabajo(short cestIdestacion, DatosUsuarios datosUsuarios) {
        this.cestIdestacion = cestIdestacion;
        this.datosUsuarios = datosUsuarios;
    }
    public CfgEstacionestrabajo(short cestIdestacion, DatosUsuarios datosUsuarios, String cestUbicacion, Date cestFechaingreso, String cestActivo, String cestHostname, String cestIpestacion, String cestVersionbioslis) {
       this.cestIdestacion = cestIdestacion;
       this.datosUsuarios = datosUsuarios;
       this.cestUbicacion = cestUbicacion;
       this.cestFechaingreso = cestFechaingreso;
       this.cestActivo = cestActivo;
       this.cestHostname = cestHostname;
       this.cestIpestacion = cestIpestacion;
       this.cestVersionbioslis = cestVersionbioslis;
    }
   
    public short getCestIdestacion() {
        return this.cestIdestacion;
    }
    
    public void setCestIdestacion(short cestIdestacion) {
        this.cestIdestacion = cestIdestacion;
    }
    public DatosUsuarios getDatosUsuarios() {
        return this.datosUsuarios;
    }
    
    public void setDatosUsuarios(DatosUsuarios datosUsuarios) {
        this.datosUsuarios = datosUsuarios;
    }
    public String getCestUbicacion() {
        return this.cestUbicacion;
    }
    
    public void setCestUbicacion(String cestUbicacion) {
        this.cestUbicacion = cestUbicacion;
    }
    public Date getCestFechaingreso() {
        return this.cestFechaingreso;
    }
    
    public void setCestFechaingreso(Date cestFechaingreso) {
        this.cestFechaingreso = cestFechaingreso;
    }
    public String getCestActivo() {
        return this.cestActivo;
    }
    
    public void setCestActivo(String cestActivo) {
        this.cestActivo = cestActivo;
    }
    public String getCestHostname() {
        return this.cestHostname;
    }
    
    public void setCestHostname(String cestHostname) {
        this.cestHostname = cestHostname;
    }
    public String getCestIpestacion() {
        return this.cestIpestacion;
    }
    
    public void setCestIpestacion(String cestIpestacion) {
        this.cestIpestacion = cestIpestacion;
    }
    public String getCestVersionbioslis() {
        return this.cestVersionbioslis;
    }
    
    public void setCestVersionbioslis(String cestVersionbioslis) {
        this.cestVersionbioslis = cestVersionbioslis;
    }




}


