package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgFormularioexamenes generated by hbm2java
 */
public class CfgFormularioexamenes  implements java.io.Serializable {


     private byte cfeIdformulario;
     private String cfeColumna;
     private String cfeEtiqueta;

    public CfgFormularioexamenes() {
    }

	
    public CfgFormularioexamenes(byte cfeIdformulario) {
        this.cfeIdformulario = cfeIdformulario;
    }
    public CfgFormularioexamenes(byte cfeIdformulario, String cfeColumna, String cfeEtiqueta) {
       this.cfeIdformulario = cfeIdformulario;
       this.cfeColumna = cfeColumna;
       this.cfeEtiqueta = cfeEtiqueta;
    }
   
    public byte getCfeIdformulario() {
        return this.cfeIdformulario;
    }
    
    public void setCfeIdformulario(byte cfeIdformulario) {
        this.cfeIdformulario = cfeIdformulario;
    }
    public String getCfeColumna() {
        return this.cfeColumna;
    }
    
    public void setCfeColumna(String cfeColumna) {
        this.cfeColumna = cfeColumna;
    }
    public String getCfeEtiqueta() {
        return this.cfeEtiqueta;
    }
    
    public void setCfeEtiqueta(String cfeEtiqueta) {
        this.cfeEtiqueta = cfeEtiqueta;
    }




}


