package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CfgFeriados generated by hbm2java
 */
public class CfgFeriados  implements java.io.Serializable {


     private byte cfIdferiado;
     private Date cfFechaferiado;
     private String cfMotivoferiado;

    public CfgFeriados() {
    }

	
    public CfgFeriados(byte cfIdferiado) {
        this.cfIdferiado = cfIdferiado;
    }
    public CfgFeriados(byte cfIdferiado, Date cfFechaferiado, String cfMotivoferiado) {
       this.cfIdferiado = cfIdferiado;
       this.cfFechaferiado = cfFechaferiado;
       this.cfMotivoferiado = cfMotivoferiado;
    }
   
    public byte getCfIdferiado() {
        return this.cfIdferiado;
    }
    
    public void setCfIdferiado(byte cfIdferiado) {
        this.cfIdferiado = cfIdferiado;
    }
    public Date getCfFechaferiado() {
        return this.cfFechaferiado;
    }
    
    public void setCfFechaferiado(Date cfFechaferiado) {
        this.cfFechaferiado = cfFechaferiado;
    }
    public String getCfMotivoferiado() {
        return this.cfMotivoferiado;
    }
    
    public void setCfMotivoferiado(String cfMotivoferiado) {
        this.cfMotivoferiado = cfMotivoferiado;
    }




}


