package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgGruposexamenesfonasa generated by hbm2java
 */
public class CfgGruposexamenesfonasa  implements java.io.Serializable {


     private byte cgefIdgrupoexamenfonasa;
     private String cgefCodigo;
     private String cgefDescripcion;
     private Byte cgefSort;
     private String cgefActivo;
     @JsonIgnore
     private Set cfgExameneses = new HashSet(0);

    public CfgGruposexamenesfonasa() {
    }
    
    public CfgGruposexamenesfonasa(byte cgefIdgrupoexamenfonasa) {
        this.cgefIdgrupoexamenfonasa = cgefIdgrupoexamenfonasa;
    }
    
    public CfgGruposexamenesfonasa(byte cgefIdgrupoexamenfonasa, String cgefCodigo) {
        this.cgefIdgrupoexamenfonasa = cgefIdgrupoexamenfonasa;
        this.cgefCodigo = cgefCodigo;
    }
    
    public CfgGruposexamenesfonasa(byte cgefIdgrupoexamenfonasa, String cgefCodigo, String cgefDescripcion, Byte cgefSort, String cgefActivo, Set cfgExameneses) {
       this.cgefIdgrupoexamenfonasa = cgefIdgrupoexamenfonasa;
       this.cgefCodigo = cgefCodigo;
       this.cgefDescripcion = cgefDescripcion;
       this.cgefSort = cgefSort;
       this.cgefActivo = cgefActivo;
       this.cfgExameneses = cfgExameneses;
    }
   
    public byte getCgefIdgrupoexamenfonasa() {
        return this.cgefIdgrupoexamenfonasa;
    }
    
    public void setCgefIdgrupoexamenfonasa(byte cgefIdgrupoexamenfonasa) {
        this.cgefIdgrupoexamenfonasa = cgefIdgrupoexamenfonasa;
    }
    public String getCgefCodigo() {
        return this.cgefCodigo;
    }
    
    public void setCgefCodigo(String cgefCodigo) {
        this.cgefCodigo = cgefCodigo;
    }
    public String getCgefDescripcion() {
        return this.cgefDescripcion;
    }
    
    public void setCgefDescripcion(String cgefDescripcion) {
        this.cgefDescripcion = cgefDescripcion;
    }
    public Byte getCgefSort() {
        return this.cgefSort;
    }
    
    public void setCgefSort(Byte cgefSort) {
        this.cgefSort = cgefSort;
    }
    public String getCgefActivo() {
        return this.cgefActivo;
    }
    
    public void setCgefActivo(String cgefActivo) {
        this.cgefActivo = cgefActivo;
    }
    public Set getCfgExameneses() {
        return this.cfgExameneses;
    }
    
    public void setCfgExameneses(Set cfgExameneses) {
        this.cfgExameneses = cfgExameneses;
    }




}


