package com.grupobios.bioslis.entity;
// Generated 01-10-2022 1:06:52 by Hibernate Tools 4.3.1



/**
 * CfgGruposmuestrasexa generated by hbm2java
 */
public class CfgGruposmuestrasexa  implements java.io.Serializable {


     private CfgGruposmuestrasexaId id;

    public CfgGruposmuestrasexa() {
    }

    public CfgGruposmuestrasexa(CfgGruposmuestrasexaId id) {
       this.id = id;
    }
   
    public CfgGruposmuestrasexaId getId() {
        return this.id;
    }
    
    public void setId(CfgGruposmuestrasexaId id) {
        this.id = id;
    }




}


