package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * CfgGlosas generated by hbm2java
 */
public class CfgGlosas implements java.io.Serializable {

  private int cgIdglosa;
  private String cgCodigoglosa;
  private String cgDescripcion;
  private int cgSort;
  private String cgActivo;
  private int cgIdSeccion;
  private String cgHost;

  public CfgGlosas() {
  }

  public CfgGlosas(int cgIdglosa, String cgCodigoglosa) {

    this.cgIdglosa = cgIdglosa;
    this.cgCodigoglosa = cgCodigoglosa;
  }

  public int getCgIdglosa() {
    return this.cgIdglosa;
  }

  public void setCgIdglosa(int cgIdglosa) {
    this.cgIdglosa = cgIdglosa;
  }

  public String getCgCodigoglosa() {
    return this.cgCodigoglosa;
  }

  public void setCgCodigoglosa(String cgCodigoglosa) {
    this.cgCodigoglosa = cgCodigoglosa;
  }

  public String getCgDescripcion() {
    return this.cgDescripcion;
  }

  public void setCgDescripcion(String cgDescripcion) {
    this.cgDescripcion = cgDescripcion;
  }

  public int getCgSort() {
    return this.cgSort;
  }

  public void setCgSort(int cgSort) {
    this.cgSort = cgSort;
  }

  public String getCgActivo() {
    return this.cgActivo;
  }

  public void setCgActivo(String cgActivo) {
    this.cgActivo = cgActivo;
  }

  public int getCgIdSeccion() {
    return this.cgIdSeccion;
  }

  public void setCgIdSeccion(int cgIdSeccion) {
    this.cgIdSeccion = cgIdSeccion;
  }

  public String getCgHost() {
    return this.cgHost;
  }

  public void setCgHost(String cgHost) {
    this.cgHost = cgHost;
  }

}
