package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgGlosastest generated by hbm2java
 */
public class CfgGlosastest  implements java.io.Serializable {


     private short cgtIdglosatest;
     private CfgGlosas cfgGlosas;
     private CfgTest cfgTest;
     private String cgtEsglosacritica;
     private String cgtSefirmaporlotes;

    public CfgGlosastest() {
    }

	
    public CfgGlosastest(short cgtIdglosatest, CfgGlosas cfgGlosas, CfgTest cfgTest) {
        this.cgtIdglosatest = cgtIdglosatest;
        this.cfgGlosas = cfgGlosas;
        this.cfgTest = cfgTest;
    }
    public CfgGlosastest(short cgtIdglosatest, CfgGlosas cfgGlosas, CfgTest cfgTest, String cgtEsglosacritica, String cgtSefirmaporlotes) {
       this.cgtIdglosatest = cgtIdglosatest;
       this.cfgGlosas = cfgGlosas;
       this.cfgTest = cfgTest;
       this.cgtEsglosacritica = cgtEsglosacritica;
       this.cgtSefirmaporlotes = cgtSefirmaporlotes;
    }
   
    public short getCgtIdglosatest() {
        return this.cgtIdglosatest;
    }
    
    public void setCgtIdglosatest(short cgtIdglosatest) {
        this.cgtIdglosatest = cgtIdglosatest;
    }
    public CfgGlosas getCfgGlosas() {
        return this.cfgGlosas;
    }
    
    public void setCfgGlosas(CfgGlosas cfgGlosas) {
        this.cfgGlosas = cfgGlosas;
    }
    public CfgTest getCfgTest() {
        return this.cfgTest;
    }
    
    public void setCfgTest(CfgTest cfgTest) {
        this.cfgTest = cfgTest;
    }
    public String getCgtEsglosacritica() {
        return this.cgtEsglosacritica;
    }
    
    public void setCgtEsglosacritica(String cgtEsglosacritica) {
        this.cgtEsglosacritica = cgtEsglosacritica;
    }
    public String getCgtSefirmaporlotes() {
        return this.cgtSefirmaporlotes;
    }
    
    public void setCgtSefirmaporlotes(String cgtSefirmaporlotes) {
        this.cgtSefirmaporlotes = cgtSefirmaporlotes;
    }




}


