package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgGruposmuestras generated by hbm2java
 */
public class CfgGruposmuestras  implements java.io.Serializable {


     private short cgmIdgrupomuestra;
     private String cgmDescripcion;
     private String cgmActivo;
     private Set cfgMuestrases = new HashSet(0);
     private Set cfgExameneses = new HashSet(0);

    public CfgGruposmuestras() {
    }

	
    public CfgGruposmuestras(short cgmIdgrupomuestra) {
        this.cgmIdgrupomuestra = cgmIdgrupomuestra;
    }
    public CfgGruposmuestras(short cgmIdgrupomuestra, String cgmDescripcion, String cgmActivo, Set cfgMuestrases, Set cfgExameneses) {
       this.cgmIdgrupomuestra = cgmIdgrupomuestra;
       this.cgmDescripcion = cgmDescripcion;
       this.cgmActivo = cgmActivo;
       this.cfgMuestrases = cfgMuestrases;
       this.cfgExameneses = cfgExameneses;
    }
   
    public short getCgmIdgrupomuestra() {
        return this.cgmIdgrupomuestra;
    }
    
    public void setCgmIdgrupomuestra(short cgmIdgrupomuestra) {
        this.cgmIdgrupomuestra = cgmIdgrupomuestra;
    }
    public String getCgmDescripcion() {
        return this.cgmDescripcion;
    }
    
    public void setCgmDescripcion(String cgmDescripcion) {
        this.cgmDescripcion = cgmDescripcion;
    }
    public String getCgmActivo() {
        return this.cgmActivo;
    }
    
    public void setCgmActivo(String cgmActivo) {
        this.cgmActivo = cgmActivo;
    }
    public Set getCfgMuestrases() {
        return this.cfgMuestrases;
    }
    
    public void setCfgMuestrases(Set cfgMuestrases) {
        this.cfgMuestrases = cfgMuestrases;
    }
    public Set getCfgExameneses() {
        return this.cfgExameneses;
    }
    
    public void setCfgExameneses(Set cfgExameneses) {
        this.cfgExameneses = cfgExameneses;
    }




}


