package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgInstitucionesdesalud generated by hbm2java
 */
public class CfgInstitucionesdesalud  implements java.io.Serializable {


     private int cidsIdinstituciondesalud;
     private String cidsCodigo;
     private String cidsDescripcion;
     private String cidsDireccion;
     private String cidsTelefono;
     private String cidsActiva;

    public CfgInstitucionesdesalud() {
    }

	
    public CfgInstitucionesdesalud(int cidsIdinstituciondesalud) {
        this.cidsIdinstituciondesalud = cidsIdinstituciondesalud;
    }
    public CfgInstitucionesdesalud(int cidsIdinstituciondesalud, String cidsCodigo, String cidsDescripcion, String cidsDireccion, String cidsTelefono, String cidsActiva) {
       this.cidsIdinstituciondesalud = cidsIdinstituciondesalud;
       this.cidsCodigo = cidsCodigo;
       this.cidsDescripcion = cidsDescripcion;
       this.cidsDireccion = cidsDireccion;
       this.cidsTelefono = cidsTelefono;
       this.cidsActiva = cidsActiva;
    }
   
    public int getCidsIdinstituciondesalud() {
        return this.cidsIdinstituciondesalud;
    }
    
    public void setCidsIdinstituciondesalud(int cidsIdinstituciondesalud) {
        this.cidsIdinstituciondesalud = cidsIdinstituciondesalud;
    }
    public String getCidsCodigo() {
        return this.cidsCodigo;
    }
    
    public void setCidsCodigo(String cidsCodigo) {
        this.cidsCodigo = cidsCodigo;
    }
    public String getCidsDescripcion() {
        return this.cidsDescripcion;
    }
    
    public void setCidsDescripcion(String cidsDescripcion) {
        this.cidsDescripcion = cidsDescripcion;
    }
    public String getCidsDireccion() {
        return this.cidsDireccion;
    }
    
    public void setCidsDireccion(String cidsDireccion) {
        this.cidsDireccion = cidsDireccion;
    }
    public String getCidsTelefono() {
        return this.cidsTelefono;
    }
    
    public void setCidsTelefono(String cidsTelefono) {
        this.cidsTelefono = cidsTelefono;
    }
    public String getCidsActiva() {
        return this.cidsActiva;
    }
    
    public void setCidsActiva(String cidsActiva) {
        this.cidsActiva = cidsActiva;
    }




}


