package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgLocalizaciones generated by hbm2java
 */
public class CfgLocalizaciones  implements java.io.Serializable {


     private int clIdlocalizacion;
     private String clCodigolocalizacion;
     private Integer clIdservicio;
     private Integer clIdsala;
     private Integer clIdcama;
     //clIdcentrodesalud agregado por Marco Caracciolo
     private Integer clIdcentrodesalud;
     @JsonIgnore
     private Set datosFichases = new HashSet(0);

    public CfgLocalizaciones() {
    }

	
    public CfgLocalizaciones(int clIdlocalizacion, Integer clIdservicio) {
        this.clIdlocalizacion = clIdlocalizacion;
        this.clIdservicio = clIdservicio;
    }
    public CfgLocalizaciones(int clIdlocalizacion, String clCodigolocalizacion, Integer clIdservicio, Integer clIdsala, Integer clIdcama, Set datosFichases) {
       this.clIdlocalizacion = clIdlocalizacion;
       this.clCodigolocalizacion = clCodigolocalizacion;
       this.clIdservicio = clIdservicio;
       this.clIdsala = clIdsala;
       this.clIdcama = clIdcama;
       this.datosFichases = datosFichases;
    }
   
    public int getClIdlocalizacion() {
        return this.clIdlocalizacion;
    }
    
    public void setClIdlocalizacion(int clIdlocalizacion) {
        this.clIdlocalizacion = clIdlocalizacion;
    }
    public String getClCodigolocalizacion() {
        return this.clCodigolocalizacion;
    }
    
    public void setClCodigolocalizacion(String clCodigolocalizacion) {
        this.clCodigolocalizacion = clCodigolocalizacion;
    }
    public Integer getClIdservicio() {
        return this.clIdservicio;
    }
    
    public void setClIdservicio(Integer clIdservicio) {
        this.clIdservicio = clIdservicio;
    }
    public Integer getClIdsala() {
        return this.clIdsala;
    }
    
    public void setClIdsala(Integer clIdsala) {
        this.clIdsala = clIdsala;
    }
    public Integer getClIdcama() {
        return this.clIdcama;
    }
    
    public void setClIdcama(Integer clIdcama) {
        this.clIdcama = clIdcama;
    }
    public Set getDatosFichases() {
        return this.datosFichases;
    }
    
    public void setDatosFichases(Set datosFichases) {
        this.datosFichases = datosFichases;
    }

    public Integer getClIdcentrodesalud() {
        return clIdcentrodesalud;
    }

    public void setClIdcentrodesalud(Integer clIdcentrodesalud) {
        this.clIdcentrodesalud = clIdcentrodesalud;
    }




}


