package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgMedicos generated by hbm2java
 */
public class CfgMedicos  implements java.io.Serializable {


     private int cmIdmedico;
     private Integer ldvSexo;
     private Integer ldvEspecialidadesmedicas;
     private Integer cfgInstitucionesdesalud;
     private String cmRun;
     private String cmNombres;
     private String cmPrimerapellido;
     private String cmSegundoapellido;
     private String cmTelefono;
     private String cmEmail;
     private String cmActivo;
     private String cmHost;
     private String cmRegistrodesalud;

    public CfgMedicos() {
    }

	
    public CfgMedicos(int cmIdmedico, String cmRun, String cmNombres, String cmPrimerapellido) {
        this.cmIdmedico = cmIdmedico;
        this.cmRun = cmRun;
        this.cmNombres = cmNombres;
        this.cmPrimerapellido = cmPrimerapellido;
    }
    public CfgMedicos(int cmIdmedico, Integer ldvSexo, Integer ldvEspecialidadesmedicas, Integer cfgInstitucionesdesalud, String cmRun, String cmNombres, String cmPrimerapellido, String cmSegundoapellido, String cmTelefono, String cmEmail, String cmActivo, String cmHost, String cmRegistrodesalud) {
       this.cmIdmedico = cmIdmedico;
       this.ldvSexo = ldvSexo;
       this.ldvEspecialidadesmedicas = ldvEspecialidadesmedicas;
       this.cfgInstitucionesdesalud = cfgInstitucionesdesalud;
       this.cmRun = cmRun;
       this.cmNombres = cmNombres;
       this.cmPrimerapellido = cmPrimerapellido;
       this.cmSegundoapellido = cmSegundoapellido;
       this.cmTelefono = cmTelefono;
       this.cmEmail = cmEmail;
       this.cmActivo = cmActivo;
       this.cmHost = cmHost;
       this.cmRegistrodesalud = cmRegistrodesalud;
    }
   
    public int getCmIdmedico() {
        return this.cmIdmedico;
    }
    
    public void setCmIdmedico(int cmIdmedico) {
        this.cmIdmedico = cmIdmedico;
    }
    public Integer getLdvSexo() {
        return this.ldvSexo;
    }
    
    public void setLdvSexo(Integer ldvSexo) {
        this.ldvSexo = ldvSexo;
    }
    public Integer getLdvEspecialidadesmedicas() {
        return this.ldvEspecialidadesmedicas;
    }
    
    public void setLdvEspecialidadesmedicas(Integer ldvEspecialidadesmedicas) {
        this.ldvEspecialidadesmedicas = ldvEspecialidadesmedicas;
    }
    public Integer getCfgInstitucionesdesalud() {
        return this.cfgInstitucionesdesalud;
    }
    
    public void setCfgInstitucionesdesalud(Integer cfgInstitucionesdesalud) {
        this.cfgInstitucionesdesalud = cfgInstitucionesdesalud;
    }
    public String getCmRun() {
        return this.cmRun;
    }
    
    public void setCmRun(String cmRun) {
        this.cmRun = cmRun;
    }
    public String getCmNombres() {
        return this.cmNombres;
    }
    
    public void setCmNombres(String cmNombres) {
        this.cmNombres = cmNombres;
    }
    public String getCmPrimerapellido() {
        return this.cmPrimerapellido;
    }
    
    public void setCmPrimerapellido(String cmPrimerapellido) {
        this.cmPrimerapellido = cmPrimerapellido;
    }
    public String getCmSegundoapellido() {
        return this.cmSegundoapellido;
    }
    
    public void setCmSegundoapellido(String cmSegundoapellido) {
        this.cmSegundoapellido = cmSegundoapellido;
    }
    public String getCmTelefono() {
        return this.cmTelefono;
    }
    
    public void setCmTelefono(String cmTelefono) {
        this.cmTelefono = cmTelefono;
    }
    public String getCmEmail() {
        return this.cmEmail;
    }
    
    public void setCmEmail(String cmEmail) {
        this.cmEmail = cmEmail;
    }
    public String getCmActivo() {
        return this.cmActivo;
    }
    
    public void setCmActivo(String cmActivo) {
        this.cmActivo = cmActivo;
    }
    public String getCmHost() {
        return this.cmHost;
    }
    
    public void setCmHost(String cmHost) {
        this.cmHost = cmHost;
    }
    public String getCmRegistrodesalud() {
        return this.cmRegistrodesalud;
    }
    
    public void setCmRegistrodesalud(String cmRegistrodesalud) {
        this.cmRegistrodesalud = cmRegistrodesalud;
    }


	@Override
	public String toString() {
		return "CfgMedicos [cmIdmedico=" + cmIdmedico + ", ldvSexo=" + ldvSexo + ", ldvEspecialidadesmedicas="
				+ ldvEspecialidadesmedicas + ", cfgInstitucionesdesalud=" + cfgInstitucionesdesalud + ", cmRun=" + cmRun
				+ ", cmNombres=" + cmNombres + ", cmPrimerapellido=" + cmPrimerapellido + ", cmSegundoapellido="
				+ cmSegundoapellido + ", cmTelefono=" + cmTelefono + ", cmEmail=" + cmEmail + ", cmActivo=" + cmActivo
				+ ", cmHost=" + cmHost + ", cmRegistrodesalud=" + cmRegistrodesalud + "]";
	}




}


