package com.grupobios.bioslis.entity;


// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgMulticentros generated by hbm2java
 */
public class CfgMulticentros  implements java.io.Serializable {


     private byte cmcIdmcentro;
     private String cmcDescripcion;
     private short cmcIdinstituciondesalud;
     private String cmcCodigo;
     private String cmcActivo;
     private String cmcDireccion;
     private String cmcTelefono;

    public CfgMulticentros() {
    }

	
    public CfgMulticentros(byte cmcIdmcentro, short cmcIdinstituciondesalud) {
        this.cmcIdmcentro = cmcIdmcentro;
        this.cmcIdinstituciondesalud = cmcIdinstituciondesalud;
    }
    public CfgMulticentros(byte cmcIdmcentro, String cmcDescripcion, short cmcIdinstituciondesalud, String cmcCodigo, String cmcActivo, String cmcDireccion, String cmcTelefono) {
       this.cmcIdmcentro = cmcIdmcentro;
       this.cmcDescripcion = cmcDescripcion;
       this.cmcIdinstituciondesalud = cmcIdinstituciondesalud;
       this.cmcCodigo = cmcCodigo;
       this.cmcActivo = cmcActivo;
       this.cmcDireccion = cmcDireccion;
       this.cmcTelefono = cmcTelefono;
    }
   
    public byte getCmcIdmcentro() {
        return this.cmcIdmcentro;
    }
    
    public void setCmcIdmcentro(byte cmcIdmcentro) {
        this.cmcIdmcentro = cmcIdmcentro;
    }
    public String getCmcDescripcion() {
        return this.cmcDescripcion;
    }
    
    public void setCmcDescripcion(String cmcDescripcion) {
        this.cmcDescripcion = cmcDescripcion;
    }
    public short getCmcIdinstituciondesalud() {
        return this.cmcIdinstituciondesalud;
    }
    
    public void setCmcIdinstituciondesalud(short cmcIdinstituciondesalud) {
        this.cmcIdinstituciondesalud = cmcIdinstituciondesalud;
    }
    public String getCmcCodigo() {
        return this.cmcCodigo;
    }
    
    public void setCmcCodigo(String cmcCodigo) {
        this.cmcCodigo = cmcCodigo;
    }
    public String getCmcActivo() {
        return this.cmcActivo;
    }
    
    public void setCmcActivo(String cmcActivo) {
        this.cmcActivo = cmcActivo;
    }
    public String getCmcDireccion() {
        return this.cmcDireccion;
    }
    
    public void setCmcDireccion(String cmcDireccion) {
        this.cmcDireccion = cmcDireccion;
    }
    public String getCmcTelefono() {
        return this.cmcTelefono;
    }
    
    public void setCmcTelefono(String cmcTelefono) {
        this.cmcTelefono = cmcTelefono;
    }




}


