package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * CfgMetodos generated by hbm2java
 */
public class CfgMetodos implements java.io.Serializable {

    private int cmetIdmetodo;
    private String cmetDescripcion;
    private String cmetActivo;
    private String cmetColor;

    public CfgMetodos() {
    }

    public CfgMetodos(int cmetIdmetodo, String cmetActivo) {
        this.cmetIdmetodo = cmetIdmetodo;
        this.cmetActivo = cmetActivo;
    }

    public CfgMetodos(int cmetIdmetodo, String cmetDescripcion, String cmetActivo) {
        this.cmetIdmetodo = cmetIdmetodo;
        this.cmetDescripcion = cmetDescripcion;
        this.cmetActivo = cmetActivo;
    }

    public int getCmetIdmetodo() {
        return this.cmetIdmetodo;
    }

    public void setCmetIdmetodo(int cmetIdmetodo) {
        this.cmetIdmetodo = cmetIdmetodo;
    }

    public String getCmetDescripcion() {
        return this.cmetDescripcion;
    }

    public void setCmetDescripcion(String cmetDescripcion) {
        this.cmetDescripcion = cmetDescripcion;
    }

    public String getCmetActivo() {
        return this.cmetActivo;
    }

    public void setCmetActivo(String cmetActivo) {
        this.cmetActivo = cmetActivo;
    }

    public String getCmetColor() {
        return cmetColor;
    }

    public void setCmetColor(String cmetColor) {
        this.cmetColor = cmetColor;
    }

    @Override
    public String toString() {
        return "CfgMetodos [cmetIdmetodo=" + cmetIdmetodo + ", cmetDescripcion=" + cmetDescripcion + ", cmetActivo="
                + cmetActivo + "]";
    }

}
