package com.grupobios.bioslis.entity;
// Generated 17-10-2022 22:44:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgMuestrasprefijos generated by hbm2java
 */
public class CfgMuestrasprefijos  implements java.io.Serializable {


     private String cmuepPrefijotipomuestra;
     private Short cmuepIdtipomuestra;
     private Set sigmaProcesostests = new HashSet(0);

    public CfgMuestrasprefijos() {
    }

	
    public CfgMuestrasprefijos(String cmuepPrefijotipomuestra) {
        this.cmuepPrefijotipomuestra = cmuepPrefijotipomuestra;
    }
    public CfgMuestrasprefijos(String cmuepPrefijotipomuestra, Short cmuepIdtipomuestra, Set sigmaProcesostests) {
       this.cmuepPrefijotipomuestra = cmuepPrefijotipomuestra;
       this.cmuepIdtipomuestra = cmuepIdtipomuestra;
       this.sigmaProcesostests = sigmaProcesostests;
    }
   
    public String getCmuepPrefijotipomuestra() {
        return this.cmuepPrefijotipomuestra;
    }
    
    public void setCmuepPrefijotipomuestra(String cmuepPrefijotipomuestra) {
        this.cmuepPrefijotipomuestra = cmuepPrefijotipomuestra;
    }
    public Short getCmuepIdtipomuestra() {
        return this.cmuepIdtipomuestra;
    }
    
    public void setCmuepIdtipomuestra(Short cmuepIdtipomuestra) {
        this.cmuepIdtipomuestra = cmuepIdtipomuestra;
    }
    public Set getSigmaProcesostests() {
        return this.sigmaProcesostests;
    }
    
    public void setSigmaProcesostests(Set sigmaProcesostests) {
        this.sigmaProcesostests = sigmaProcesostests;
    }




}


