package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;




/**
 * CfgMetodostest generated by hbm2java
 */
public class CfgMetodostest  implements java.io.Serializable {


     private CfgMetodostestId id;
     @JsonIgnore
     private CfgTest cfgTest;
     private byte cmtNrometodo;
     private String cmtActivo;
     private String cmtEsvalorpordefecto;
     private String cmtComentario;
     private String cmtImprimecomentario;

    public CfgMetodostest() {
    }

    public CfgMetodostestId getId() {
        return id;
    }

    public void setId(CfgMetodostestId id) {
        this.id = id;
    }

    public CfgTest getCfgTest() {
        return cfgTest;
    }

    public void setCfgTest(CfgTest cfgTest) {
        this.cfgTest = cfgTest;
    }

    public byte getCmtNrometodo() {
        return cmtNrometodo;
    }

    public void setCmtNrometodo(byte cmtNrometodo) {
        this.cmtNrometodo = cmtNrometodo;
    }

    public String getCmtActivo() {
        return cmtActivo;
    }

    public void setCmtActivo(String cmtActivo) {
        this.cmtActivo = cmtActivo;
    }

    public String getCmtEsvalorpordefecto() {
        return cmtEsvalorpordefecto;
    }

    public void setCmtEsvalorpordefecto(String cmtEsvalorpordefecto) {
        this.cmtEsvalorpordefecto = cmtEsvalorpordefecto;
    }

    public String getCmtComentario() {
        return cmtComentario;
    }

    public void setCmtComentario(String cmtComentario) {
        this.cmtComentario = cmtComentario;
    }

    public String getCmtImprimecomentario() {
        return cmtImprimecomentario;
    }

    public void setCmtImprimecomentario(String cmtImprimecomentario) {
        this.cmtImprimecomentario = cmtImprimecomentario;
    }

	
}


