package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgMetodostestId generated by hbm2java
 */
public class CfgMetodostestId  implements java.io.Serializable {


     private long cmtIdtest;
     private short cmtIdmetodo;

    public CfgMetodostestId() {
    }

    public CfgMetodostestId(long cmtIdtest, short cmtIdmetodo) {
       this.cmtIdtest = cmtIdtest;
       this.cmtIdmetodo = cmtIdmetodo;
    }
   
    public long getCmtIdtest() {
        return this.cmtIdtest;
    }
    
    public void setCmtIdtest(long cmtIdtest) {
        this.cmtIdtest = cmtIdtest;
    }
    public short getCmtIdmetodo() {
        return this.cmtIdmetodo;
    }
    
    public void setCmtIdmetodo(short cmtIdmetodo) {
        this.cmtIdmetodo = cmtIdmetodo;
    }




}


