package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgNotas generated by hbm2java
 */
public class CfgNotas  implements java.io.Serializable {


     private short cnIdnota;
     private String cnDescripcionnota;
     private String cnActiva;
     private Short cnSort;
     private Set cfgTiposnotases = new HashSet(0);

    public CfgNotas() {
    }

	
    public CfgNotas(short cnIdnota) {
        this.cnIdnota = cnIdnota;
    }
    public CfgNotas(short cnIdnota, String cnDescripcionnota, String cnActiva, Short cnSort, Set cfgTiposnotases) {
       this.cnIdnota = cnIdnota;
       this.cnDescripcionnota = cnDescripcionnota;
       this.cnActiva = cnActiva;
       this.cnSort = cnSort;
       this.cfgTiposnotases = cfgTiposnotases;
    }
   
    public short getCnIdnota() {
        return this.cnIdnota;
    }
    
    public void setCnIdnota(short cnIdnota) {
        this.cnIdnota = cnIdnota;
    }
    public String getCnDescripcionnota() {
        return this.cnDescripcionnota;
    }
    
    public void setCnDescripcionnota(String cnDescripcionnota) {
        this.cnDescripcionnota = cnDescripcionnota;
    }
    public String getCnActiva() {
        return this.cnActiva;
    }
    
    public void setCnActiva(String cnActiva) {
        this.cnActiva = cnActiva;
    }
    public Short getCnSort() {
        return this.cnSort;
    }
    
    public void setCnSort(Short cnSort) {
        this.cnSort = cnSort;
    }
    public Set getCfgTiposnotases() {
        return this.cfgTiposnotases;
    }
    
    public void setCfgTiposnotases(Set cfgTiposnotases) {
        this.cfgTiposnotases = cfgTiposnotases;
    }




}


