package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgPesquisas generated by hbm2java
 */
public class CfgPesquisas  implements java.io.Serializable {


     private short cpeIdpesquisa;
     private String cpeDescripcion;
     private Short cpeAnchohoja;
     private Short cpeLargohoja;
     private String cpeActiva;
     private String cpeEsopcional;
     @JsonIgnore
     private Set cfgPesquisasinfos = new HashSet(0);
     @JsonIgnore
     private Set cfgExameneses = new HashSet(0);

    public CfgPesquisas() {
    }

	
    public CfgPesquisas(short cpeIdpesquisa) {
        this.cpeIdpesquisa = cpeIdpesquisa;
    }
    public CfgPesquisas(short cpeIdpesquisa, String cpeDescripcion, Short cpeAnchohoja, Short cpeLargohoja, String cpeActiva, String cpeEsopcional, Set cfgPesquisasinfos, Set cfgExameneses) {
       this.cpeIdpesquisa = cpeIdpesquisa;
       this.cpeDescripcion = cpeDescripcion;
       this.cpeAnchohoja = cpeAnchohoja;
       this.cpeLargohoja = cpeLargohoja;
       this.cpeActiva = cpeActiva;
       this.cpeEsopcional = cpeEsopcional;
       this.cfgPesquisasinfos = cfgPesquisasinfos;
       this.cfgExameneses = cfgExameneses;
    }
   
    public short getCpeIdpesquisa() {
        return this.cpeIdpesquisa;
    }
    
    public void setCpeIdpesquisa(short cpeIdpesquisa) {
        this.cpeIdpesquisa = cpeIdpesquisa;
    }
    public String getCpeDescripcion() {
        return this.cpeDescripcion;
    }
    
    public void setCpeDescripcion(String cpeDescripcion) {
        this.cpeDescripcion = cpeDescripcion;
    }
    public Short getCpeAnchohoja() {
        return this.cpeAnchohoja;
    }
    
    public void setCpeAnchohoja(Short cpeAnchohoja) {
        this.cpeAnchohoja = cpeAnchohoja;
    }
    public Short getCpeLargohoja() {
        return this.cpeLargohoja;
    }
    
    public void setCpeLargohoja(Short cpeLargohoja) {
        this.cpeLargohoja = cpeLargohoja;
    }
    public String getCpeActiva() {
        return this.cpeActiva;
    }
    
    public void setCpeActiva(String cpeActiva) {
        this.cpeActiva = cpeActiva;
    }
    public String getCpeEsopcional() {
        return this.cpeEsopcional;
    }
    
    public void setCpeEsopcional(String cpeEsopcional) {
        this.cpeEsopcional = cpeEsopcional;
    }
    public Set getCfgPesquisasinfos() {
        return this.cfgPesquisasinfos;
    }
    
    public void setCfgPesquisasinfos(Set cfgPesquisasinfos) {
        this.cfgPesquisasinfos = cfgPesquisasinfos;
    }
    public Set getCfgExameneses() {
        return this.cfgExameneses;
    }
    
    public void setCfgExameneses(Set cfgExameneses) {
        this.cfgExameneses = cfgExameneses;
    }




}


