package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgPesquisasformatos generated by hbm2java
 */
public class CfgPesquisasformatos  implements java.io.Serializable {


     private CfgPesquisasformatosId id;
     private CfgPesquisasinfo cfgPesquisasinfo;
     private LdvTiposdatospesquisas ldvTiposdatospesquisas;
     private String cpfDescripcion;
     private String cpfValor;
     private Short cpfPosicionx;
     private Short cpfPosiciony;
     private Short cpfAncho;
     private Short cpfAlto;
     private Byte cpfTamanofuente;

    public CfgPesquisasformatos() {
    }

	
    public CfgPesquisasformatos(CfgPesquisasformatosId id, CfgPesquisasinfo cfgPesquisasinfo, LdvTiposdatospesquisas ldvTiposdatospesquisas) {
        this.id = id;
        this.cfgPesquisasinfo = cfgPesquisasinfo;
        this.ldvTiposdatospesquisas = ldvTiposdatospesquisas;
    }
    public CfgPesquisasformatos(CfgPesquisasformatosId id, CfgPesquisasinfo cfgPesquisasinfo, LdvTiposdatospesquisas ldvTiposdatospesquisas, String cpfDescripcion, String cpfValor, Short cpfPosicionx, Short cpfPosiciony, Short cpfAncho, Short cpfAlto, Byte cpfTamanofuente) {
       this.id = id;
       this.cfgPesquisasinfo = cfgPesquisasinfo;
       this.ldvTiposdatospesquisas = ldvTiposdatospesquisas;
       this.cpfDescripcion = cpfDescripcion;
       this.cpfValor = cpfValor;
       this.cpfPosicionx = cpfPosicionx;
       this.cpfPosiciony = cpfPosiciony;
       this.cpfAncho = cpfAncho;
       this.cpfAlto = cpfAlto;
       this.cpfTamanofuente = cpfTamanofuente;
    }
   
    public CfgPesquisasformatosId getId() {
        return this.id;
    }
    
    public void setId(CfgPesquisasformatosId id) {
        this.id = id;
    }
    public CfgPesquisasinfo getCfgPesquisasinfo() {
        return this.cfgPesquisasinfo;
    }
    
    public void setCfgPesquisasinfo(CfgPesquisasinfo cfgPesquisasinfo) {
        this.cfgPesquisasinfo = cfgPesquisasinfo;
    }
    public LdvTiposdatospesquisas getLdvTiposdatospesquisas() {
        return this.ldvTiposdatospesquisas;
    }
    
    public void setLdvTiposdatospesquisas(LdvTiposdatospesquisas ldvTiposdatospesquisas) {
        this.ldvTiposdatospesquisas = ldvTiposdatospesquisas;
    }
    public String getCpfDescripcion() {
        return this.cpfDescripcion;
    }
    
    public void setCpfDescripcion(String cpfDescripcion) {
        this.cpfDescripcion = cpfDescripcion;
    }
    public String getCpfValor() {
        return this.cpfValor;
    }
    
    public void setCpfValor(String cpfValor) {
        this.cpfValor = cpfValor;
    }
    public Short getCpfPosicionx() {
        return this.cpfPosicionx;
    }
    
    public void setCpfPosicionx(Short cpfPosicionx) {
        this.cpfPosicionx = cpfPosicionx;
    }
    public Short getCpfPosiciony() {
        return this.cpfPosiciony;
    }
    
    public void setCpfPosiciony(Short cpfPosiciony) {
        this.cpfPosiciony = cpfPosiciony;
    }
    public Short getCpfAncho() {
        return this.cpfAncho;
    }
    
    public void setCpfAncho(Short cpfAncho) {
        this.cpfAncho = cpfAncho;
    }
    public Short getCpfAlto() {
        return this.cpfAlto;
    }
    
    public void setCpfAlto(Short cpfAlto) {
        this.cpfAlto = cpfAlto;
    }
    public Byte getCpfTamanofuente() {
        return this.cpfTamanofuente;
    }
    
    public void setCpfTamanofuente(Byte cpfTamanofuente) {
        this.cpfTamanofuente = cpfTamanofuente;
    }




}


