package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgProgramasdesalud generated by hbm2java
 */
public class CfgProgramasdesalud  implements java.io.Serializable {


     private int cpdsIdprogramasalud;
     private CfgProcedencias cfgProcedencias;
     private CfgInstitucionesdesalud cfgInstitucionesdesalud;
     private String cpdsCodigo;
     private String cpdsDescripcion;
     private String cpdsActivo;
     private Integer cpdsSort;
     private String cpdsActivacuposcitas;
     private Short cpdsCitascuposlunes;
     private Short cpdsCitascuposmartes;
     private Short cpdsCitascuposmiercoles;
     private Short cpdsCitascuposjueves;
     private Short cpdsCitascuposviernes;
     private Short cpdsCitascupossabado;
     private Short cpdsCitascuposdomingo;

    public CfgProgramasdesalud() {
    }

	
    public CfgProgramasdesalud(int cpdsIdprogramasalud, CfgProcedencias cfgProcedencias, CfgInstitucionesdesalud cfgInstitucionesdesalud) {
        this.cpdsIdprogramasalud = cpdsIdprogramasalud;
        this.cfgProcedencias = cfgProcedencias;
        this.cfgInstitucionesdesalud = cfgInstitucionesdesalud;
    }
    public CfgProgramasdesalud(int cpdsIdprogramasalud, CfgProcedencias cfgProcedencias, CfgInstitucionesdesalud cfgInstitucionesdesalud, String cpdsCodigo, String cpdsDescripcion, String cpdsActivo, Integer cpdsSort, String cpdsActivacuposcitas, Short cpdsCitascuposlunes, Short cpdsCitascuposmartes, Short cpdsCitascuposmiercoles, Short cpdsCitascuposjueves, Short cpdsCitascuposviernes, Short cpdsCitascupossabado, Short cpdsCitascuposdomingo) {
       this.cpdsIdprogramasalud = cpdsIdprogramasalud;
       this.cfgProcedencias = cfgProcedencias;
       this.cfgInstitucionesdesalud = cfgInstitucionesdesalud;
       this.cpdsCodigo = cpdsCodigo;
       this.cpdsDescripcion = cpdsDescripcion;
       this.cpdsActivo = cpdsActivo;
       this.cpdsSort = cpdsSort;
       this.cpdsActivacuposcitas = cpdsActivacuposcitas;
       this.cpdsCitascuposlunes = cpdsCitascuposlunes;
       this.cpdsCitascuposmartes = cpdsCitascuposmartes;
       this.cpdsCitascuposmiercoles = cpdsCitascuposmiercoles;
       this.cpdsCitascuposjueves = cpdsCitascuposjueves;
       this.cpdsCitascuposviernes = cpdsCitascuposviernes;
       this.cpdsCitascupossabado = cpdsCitascupossabado;
       this.cpdsCitascuposdomingo = cpdsCitascuposdomingo;
    }
   
    public int getCpdsIdprogramasalud() {
        return this.cpdsIdprogramasalud;
    }
    
    public void setCpdsIdprogramasalud(int cpdsIdprogramasalud) {
        this.cpdsIdprogramasalud = cpdsIdprogramasalud;
    }
    public CfgProcedencias getCfgProcedencias() {
        return this.cfgProcedencias;
    }
    
    public void setCfgProcedencias(CfgProcedencias cfgProcedencias) {
        this.cfgProcedencias = cfgProcedencias;
    }
    public CfgInstitucionesdesalud getCfgInstitucionesdesalud() {
        return this.cfgInstitucionesdesalud;
    }
    
    public void setCfgInstitucionesdesalud(CfgInstitucionesdesalud cfgInstitucionesdesalud) {
        this.cfgInstitucionesdesalud = cfgInstitucionesdesalud;
    }
    public String getCpdsCodigo() {
        return this.cpdsCodigo;
    }
    
    public void setCpdsCodigo(String cpdsCodigo) {
        this.cpdsCodigo = cpdsCodigo;
    }
    public String getCpdsDescripcion() {
        return this.cpdsDescripcion;
    }
    
    public void setCpdsDescripcion(String cpdsDescripcion) {
        this.cpdsDescripcion = cpdsDescripcion;
    }
    public String getCpdsActivo() {
        return this.cpdsActivo;
    }
    
    public void setCpdsActivo(String cpdsActivo) {
        this.cpdsActivo = cpdsActivo;
    }
    public Integer getCpdsSort() {
        return this.cpdsSort;
    }
    
    public void setCpdsSort(Integer cpdsSort) {
        this.cpdsSort = cpdsSort;
    }
    public String getCpdsActivacuposcitas() {
        return this.cpdsActivacuposcitas;
    }
    
    public void setCpdsActivacuposcitas(String cpdsActivacuposcitas) {
        this.cpdsActivacuposcitas = cpdsActivacuposcitas;
    }
    public Short getCpdsCitascuposlunes() {
        return this.cpdsCitascuposlunes;
    }
    
    public void setCpdsCitascuposlunes(Short cpdsCitascuposlunes) {
        this.cpdsCitascuposlunes = cpdsCitascuposlunes;
    }
    public Short getCpdsCitascuposmartes() {
        return this.cpdsCitascuposmartes;
    }
    
    public void setCpdsCitascuposmartes(Short cpdsCitascuposmartes) {
        this.cpdsCitascuposmartes = cpdsCitascuposmartes;
    }
    public Short getCpdsCitascuposmiercoles() {
        return this.cpdsCitascuposmiercoles;
    }
    
    public void setCpdsCitascuposmiercoles(Short cpdsCitascuposmiercoles) {
        this.cpdsCitascuposmiercoles = cpdsCitascuposmiercoles;
    }
    public Short getCpdsCitascuposjueves() {
        return this.cpdsCitascuposjueves;
    }
    
    public void setCpdsCitascuposjueves(Short cpdsCitascuposjueves) {
        this.cpdsCitascuposjueves = cpdsCitascuposjueves;
    }
    public Short getCpdsCitascuposviernes() {
        return this.cpdsCitascuposviernes;
    }
    
    public void setCpdsCitascuposviernes(Short cpdsCitascuposviernes) {
        this.cpdsCitascuposviernes = cpdsCitascuposviernes;
    }
    public Short getCpdsCitascupossabado() {
        return this.cpdsCitascupossabado;
    }
    
    public void setCpdsCitascupossabado(Short cpdsCitascupossabado) {
        this.cpdsCitascupossabado = cpdsCitascupossabado;
    }
    public Short getCpdsCitascuposdomingo() {
        return this.cpdsCitascuposdomingo;
    }
    
    public void setCpdsCitascuposdomingo(Short cpdsCitascuposdomingo) {
        this.cpdsCitascuposdomingo = cpdsCitascuposdomingo;
    }




}


