package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgPesquisasinfo generated by hbm2java
 */
public class CfgPesquisasinfo  implements java.io.Serializable {


     private CfgPesquisasinfoId id;
     private CfgPesquisas cfgPesquisas;
     private String cpiCodigo;
     private String cpiDescripcion;
     private String cpiEsopcional;
     private Short cpiSort;
     private String cpiActiva;
     private Set cfgPesquisasformatoses = new HashSet(0);

    public CfgPesquisasinfo() {
    }

	
    public CfgPesquisasinfo(CfgPesquisasinfoId id, CfgPesquisas cfgPesquisas) {
        this.id = id;
        this.cfgPesquisas = cfgPesquisas;
    }
    public CfgPesquisasinfo(CfgPesquisasinfoId id, CfgPesquisas cfgPesquisas, String cpiCodigo, String cpiDescripcion, String cpiEsopcional, Short cpiSort, String cpiActiva, Set cfgPesquisasformatoses) {
       this.id = id;
       this.cfgPesquisas = cfgPesquisas;
       this.cpiCodigo = cpiCodigo;
       this.cpiDescripcion = cpiDescripcion;
       this.cpiEsopcional = cpiEsopcional;
       this.cpiSort = cpiSort;
       this.cpiActiva = cpiActiva;
       this.cfgPesquisasformatoses = cfgPesquisasformatoses;
    }
   
    public CfgPesquisasinfoId getId() {
        return this.id;
    }
    
    public void setId(CfgPesquisasinfoId id) {
        this.id = id;
    }
    public CfgPesquisas getCfgPesquisas() {
        return this.cfgPesquisas;
    }
    
    public void setCfgPesquisas(CfgPesquisas cfgPesquisas) {
        this.cfgPesquisas = cfgPesquisas;
    }
    public String getCpiCodigo() {
        return this.cpiCodigo;
    }
    
    public void setCpiCodigo(String cpiCodigo) {
        this.cpiCodigo = cpiCodigo;
    }
    public String getCpiDescripcion() {
        return this.cpiDescripcion;
    }
    
    public void setCpiDescripcion(String cpiDescripcion) {
        this.cpiDescripcion = cpiDescripcion;
    }
    public String getCpiEsopcional() {
        return this.cpiEsopcional;
    }
    
    public void setCpiEsopcional(String cpiEsopcional) {
        this.cpiEsopcional = cpiEsopcional;
    }
    public Short getCpiSort() {
        return this.cpiSort;
    }
    
    public void setCpiSort(Short cpiSort) {
        this.cpiSort = cpiSort;
    }
    public String getCpiActiva() {
        return this.cpiActiva;
    }
    
    public void setCpiActiva(String cpiActiva) {
        this.cpiActiva = cpiActiva;
    }
    public Set getCfgPesquisasformatoses() {
        return this.cfgPesquisasformatoses;
    }
    
    public void setCfgPesquisasformatoses(Set cfgPesquisasformatoses) {
        this.cfgPesquisasformatoses = cfgPesquisasformatoses;
    }




}


