package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgPesquisasinfoId generated by hbm2java
 */
public class CfgPesquisasinfoId  implements java.io.Serializable {


     private short cpiIdpesquisa;
     private byte cpiIddato;

    public CfgPesquisasinfoId() {
    }

    public CfgPesquisasinfoId(short cpiIdpesquisa, byte cpiIddato) {
       this.cpiIdpesquisa = cpiIdpesquisa;
       this.cpiIddato = cpiIddato;
    }
   
    public short getCpiIdpesquisa() {
        return this.cpiIdpesquisa;
    }
    
    public void setCpiIdpesquisa(short cpiIdpesquisa) {
        this.cpiIdpesquisa = cpiIdpesquisa;
    }
    public byte getCpiIddato() {
        return this.cpiIddato;
    }
    
    public void setCpiIddato(byte cpiIddato) {
        this.cpiIddato = cpiIddato;
    }




}


