package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgPesquisasformatosId generated by hbm2java
 */
public class CfgPesquisasformatosId  implements java.io.Serializable {


     private short cpfIdpesquisa;
     private byte cpfIddato;
     private byte cpfIdpesquisaformato;

    public CfgPesquisasformatosId() {
    }

    public CfgPesquisasformatosId(short cpfIdpesquisa, byte cpfIddato, byte cpfIdpesquisaformato) {
       this.cpfIdpesquisa = cpfIdpesquisa;
       this.cpfIddato = cpfIddato;
       this.cpfIdpesquisaformato = cpfIdpesquisaformato;
    }
   
    public short getCpfIdpesquisa() {
        return this.cpfIdpesquisa;
    }
    
    public void setCpfIdpesquisa(short cpfIdpesquisa) {
        this.cpfIdpesquisa = cpfIdpesquisa;
    }
    public byte getCpfIddato() {
        return this.cpfIddato;
    }
    
    public void setCpfIddato(byte cpfIddato) {
        this.cpfIddato = cpfIddato;
    }
    public byte getCpfIdpesquisaformato() {
        return this.cpfIdpesquisaformato;
    }
    
    public void setCpfIdpesquisaformato(byte cpfIdpesquisaformato) {
        this.cpfIdpesquisaformato = cpfIdpesquisaformato;
    }




}


