package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgReglasprocesosejecutanen generated by hbm2java
 */
public class CfgReglasprocesosejecutanen  implements java.io.Serializable {


     private byte crpeeIdejecutaen;
     private String crpeeCodigo;
     private String crpeeDescripcion;
     private Byte crpeeSort;
     private Set cfgReglasprocesoses = new HashSet(0);

    public CfgReglasprocesosejecutanen() {
    }

	
    public CfgReglasprocesosejecutanen(byte crpeeIdejecutaen) {
        this.crpeeIdejecutaen = crpeeIdejecutaen;
    }
    public CfgReglasprocesosejecutanen(byte crpeeIdejecutaen, String crpeeCodigo, String crpeeDescripcion, Byte crpeeSort, Set cfgReglasprocesoses) {
       this.crpeeIdejecutaen = crpeeIdejecutaen;
       this.crpeeCodigo = crpeeCodigo;
       this.crpeeDescripcion = crpeeDescripcion;
       this.crpeeSort = crpeeSort;
       this.cfgReglasprocesoses = cfgReglasprocesoses;
    }
   
    public byte getCrpeeIdejecutaen() {
        return this.crpeeIdejecutaen;
    }
    
    public void setCrpeeIdejecutaen(byte crpeeIdejecutaen) {
        this.crpeeIdejecutaen = crpeeIdejecutaen;
    }
    public String getCrpeeCodigo() {
        return this.crpeeCodigo;
    }
    
    public void setCrpeeCodigo(String crpeeCodigo) {
        this.crpeeCodigo = crpeeCodigo;
    }
    public String getCrpeeDescripcion() {
        return this.crpeeDescripcion;
    }
    
    public void setCrpeeDescripcion(String crpeeDescripcion) {
        this.crpeeDescripcion = crpeeDescripcion;
    }
    public Byte getCrpeeSort() {
        return this.crpeeSort;
    }
    
    public void setCrpeeSort(Byte crpeeSort) {
        this.crpeeSort = crpeeSort;
    }
    public Set getCfgReglasprocesoses() {
        return this.cfgReglasprocesoses;
    }
    
    public void setCfgReglasprocesoses(Set cfgReglasprocesoses) {
        this.cfgReglasprocesoses = cfgReglasprocesoses;
    }




}


