package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * CfgReglasprocesos generated by hbm2java
 */
public class CfgReglasprocesos  implements java.io.Serializable {


     private short crpIdreglaproceso;
     private CfgReglasprocesosejecutanen cfgReglasprocesosejecutanen;
     private String crpNombreregla;
     private String crpModulo;
     private String crpActivo;
     private String crpCondicion;
     private String crpAccion;
     private Short crpSort;

    public CfgReglasprocesos() {
    }

	
    public CfgReglasprocesos(short crpIdreglaproceso, CfgReglasprocesosejecutanen cfgReglasprocesosejecutanen) {
        this.crpIdreglaproceso = crpIdreglaproceso;
        this.cfgReglasprocesosejecutanen = cfgReglasprocesosejecutanen;
    }
    public CfgReglasprocesos(short crpIdreglaproceso, CfgReglasprocesosejecutanen cfgReglasprocesosejecutanen, String crpNombreregla, String crpModulo, String crpActivo, String crpCondicion, String crpAccion, Short crpSort) {
       this.crpIdreglaproceso = crpIdreglaproceso;
       this.cfgReglasprocesosejecutanen = cfgReglasprocesosejecutanen;
       this.crpNombreregla = crpNombreregla;
       this.crpModulo = crpModulo;
       this.crpActivo = crpActivo;
       this.crpCondicion = crpCondicion;
       this.crpAccion = crpAccion;
       this.crpSort = crpSort;
    }
   
    public short getCrpIdreglaproceso() {
        return this.crpIdreglaproceso;
    }
    
    public void setCrpIdreglaproceso(short crpIdreglaproceso) {
        this.crpIdreglaproceso = crpIdreglaproceso;
    }
    public CfgReglasprocesosejecutanen getCfgReglasprocesosejecutanen() {
        return this.cfgReglasprocesosejecutanen;
    }
    
    public void setCfgReglasprocesosejecutanen(CfgReglasprocesosejecutanen cfgReglasprocesosejecutanen) {
        this.cfgReglasprocesosejecutanen = cfgReglasprocesosejecutanen;
    }
    public String getCrpNombreregla() {
        return this.crpNombreregla;
    }
    
    public void setCrpNombreregla(String crpNombreregla) {
        this.crpNombreregla = crpNombreregla;
    }
    public String getCrpModulo() {
        return this.crpModulo;
    }
    
    public void setCrpModulo(String crpModulo) {
        this.crpModulo = crpModulo;
    }
    public String getCrpActivo() {
        return this.crpActivo;
    }
    
    public void setCrpActivo(String crpActivo) {
        this.crpActivo = crpActivo;
    }
    public String getCrpCondicion() {
        return this.crpCondicion;
    }
    
    public void setCrpCondicion(String crpCondicion) {
        this.crpCondicion = crpCondicion;
    }
    public String getCrpAccion() {
        return this.crpAccion;
    }
    
    public void setCrpAccion(String crpAccion) {
        this.crpAccion = crpAccion;
    }
    public Short getCrpSort() {
        return this.crpSort;
    }
    
    public void setCrpSort(Short crpSort) {
        this.crpSort = crpSort;
    }




}


