package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;


/**
 * CfgServicios generated by hbm2java
 */
public class CfgServicios implements java.io.Serializable {

	private int csIdservicio;
        @JsonIgnore
        private CfgCentrosdesalud cfgCentrosdesalud;
	private String csCodigo;
	private String csDescripcion;
	private String csEmail;
	private String csActivo;
	private int csSort;
	private String csHost;
	private String csHostmicro;
	private String csHost2;
	private String csHost3;
	private String csGrupo;
	private String csGrupo2;
	private String csUrgente;
	private String csIndicador;
	private String csImpresora;
	private String csImprimeconfidenciales;


	public CfgServicios() {
	}

	public CfgServicios(int csIdservicio) {
		this.csIdservicio = csIdservicio;
	}

	public int getCsIdservicio() {
		return this.csIdservicio;
	}

	public void setCsIdservicio(int csIdservicio) {
		this.csIdservicio = csIdservicio;
	}

        public CfgCentrosdesalud getCfgCentrosdesalud() {
            return this.cfgCentrosdesalud;
        }

        public void setCfgCentrosdesalud(CfgCentrosdesalud cfgCentrosdesalud) {
            this.cfgCentrosdesalud = cfgCentrosdesalud;
        }

	public String getCsCodigo() {
		return this.csCodigo;
	}

	public void setCsCodigo(String csCodigo) {
		this.csCodigo = csCodigo;
	}

	public String getCsDescripcion() {
		return this.csDescripcion;
	}

	public void setCsDescripcion(String csDescripcion) {
		this.csDescripcion = csDescripcion;
	}

	public String getCsEmail() {
		return this.csEmail;
	}

	public void setCsEmail(String csEmail) {
		this.csEmail = csEmail;
	}

	public String getCsActivo() {
		return this.csActivo;
	}

	public void setCsActivo(String csActivo) {
		this.csActivo = csActivo;
	}

	public int getCsSort() {
		return this.csSort;
	}

	public void setCsSort(int csSort) {
		this.csSort = csSort;
	}

	public String getCsHost() {
		return this.csHost;
	}

	public void setCsHost(String csHost) {
		this.csHost = csHost;
	}

	public String getCsHostmicro() {
		return this.csHostmicro;
	}

	public void setCsHostmicro(String csHostmicro) {
		this.csHostmicro = csHostmicro;
	}

	public String getCsHost2() {
		return this.csHost2;
	}

	public void setCsHost2(String csHost2) {
		this.csHost2 = csHost2;
	}

	public String getCsHost3() {
		return this.csHost3;
	}

	public void setCsHost3(String csHost3) {
		this.csHost3 = csHost3;
	}

	public String getCsGrupo() {
		return this.csGrupo;
	}

	public void setCsGrupo(String csGrupo) {
		this.csGrupo = csGrupo;
	}

	public String getCsGrupo2() {
		return this.csGrupo2;
	}

	public void setCsGrupo2(String csGrupo2) {
		this.csGrupo2 = csGrupo2;
	}

	public String getCsUrgente() {
		return this.csUrgente;
	}

	public void setCsUrgente(String csUrgente) {
		this.csUrgente = csUrgente;
	}

	public String getCsIndicador() {
		return this.csIndicador;
	}

	public void setCsIndicador(String csIndicador) {
		this.csIndicador = csIndicador;
	}

	public String getCsImpresora() {
		return this.csImpresora;
	}

	public void setCsImpresora(String csImpresora) {
		this.csImpresora = csImpresora;
	}

	public String getCsImprimeconfidenciales() {
		return this.csImprimeconfidenciales;
	}

	public void setCsImprimeconfidenciales(String csImprimeconfidenciales) {
		this.csImprimeconfidenciales = csImprimeconfidenciales;
	}

}
