package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgSalasservicios generated by hbm2java
 */
public class CfgSalasservicios  implements java.io.Serializable {


     private int cssIdsalaservicio;
     private CfgServicios cfgServicios;
     private String cssCodigosala;
     private String cssDescripcion;
     private Set cfgCamassalases = new HashSet(0);

    public CfgSalasservicios() {
    }

    public CfgSalasservicios(int cssIdsalaservicio) {
        this.cssIdsalaservicio = cssIdsalaservicio;
    }

	
    public CfgSalasservicios(int cssIdsalaservicio, CfgServicios cfgServicios) {
        this.cssIdsalaservicio = cssIdsalaservicio;
        this.cfgServicios = cfgServicios;
    }
    public CfgSalasservicios(int cssIdsalaservicio, CfgServicios cfgServicios, String cssCodigosala, String cssDescripcion, Set cfgCamassalases) {
       this.cssIdsalaservicio = cssIdsalaservicio;
       this.cfgServicios = cfgServicios;
       this.cssCodigosala = cssCodigosala;
       this.cssDescripcion = cssDescripcion;
       this.cfgCamassalases = cfgCamassalases;
    }
   
    public int getCssIdsalaservicio() {
        return this.cssIdsalaservicio;
    }
    
    public void setCssIdsalaservicio(int cssIdsalaservicio) {
        this.cssIdsalaservicio = cssIdsalaservicio;
    }
    public CfgServicios getCfgServicios() {
        return this.cfgServicios;
    }
    
    public void setCfgServicios(CfgServicios cfgServicios) {
        this.cfgServicios = cfgServicios;
    }
    public String getCssCodigosala() {
        return this.cssCodigosala;
    }
    
    public void setCssCodigosala(String cssCodigosala) {
        this.cssCodigosala = cssCodigosala;
    }
    public String getCssDescripcion() {
        return this.cssDescripcion;
    }
    
    public void setCssDescripcion(String cssDescripcion) {
        this.cssDescripcion = cssDescripcion;
    }
    public Set getCfgCamassalases() {
        return this.cfgCamassalases;
    }
    
    public void setCfgCamassalases(Set cfgCamassalases) {
        this.cfgCamassalases = cfgCamassalases;
    }




}


