package com.grupobios.bioslis.entity;
// Generated 17-10-2022 22:44:33 by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgSigmaimagenes generated by hbm2java
 */
public class CfgSigmaimagenes  implements java.io.Serializable {


     private short csiIdimagen;
     private String csiDescripcion;
     private Blob csiImagen;
     private Set sigmaAnalizadoreses = new HashSet(0);

    public CfgSigmaimagenes() {
    }

	
    public CfgSigmaimagenes(short csiIdimagen) {
        this.csiIdimagen = csiIdimagen;
    }
    public CfgSigmaimagenes(short csiIdimagen, String csiDescripcion, Blob csiImagen, Set sigmaAnalizadoreses) {
       this.csiIdimagen = csiIdimagen;
       this.csiDescripcion = csiDescripcion;
       this.csiImagen = csiImagen;
       this.sigmaAnalizadoreses = sigmaAnalizadoreses;
    }
   
    public short getCsiIdimagen() {
        return this.csiIdimagen;
    }
    
    public void setCsiIdimagen(short csiIdimagen) {
        this.csiIdimagen = csiIdimagen;
    }
    public String getCsiDescripcion() {
        return this.csiDescripcion;
    }
    
    public void setCsiDescripcion(String csiDescripcion) {
        this.csiDescripcion = csiDescripcion;
    }
    public Blob getCsiImagen() {
        return this.csiImagen;
    }
    
    public void setCsiImagen(Blob csiImagen) {
        this.csiImagen = csiImagen;
    }
    public Set getSigmaAnalizadoreses() {
        return this.sigmaAnalizadoreses;
    }
    
    public void setSigmaAnalizadoreses(Set sigmaAnalizadoreses) {
        this.sigmaAnalizadoreses = sigmaAnalizadoreses;
    }




}


