package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * CfgSeccionesexamenes generated by hbm2java
 */
public class CfgSeccionesexamenes {

  private int cseIdseccionexamen;
  private long cseIdexamen;

  public CfgSeccionesexamenes() {
  }

  public int getCseIdseccionexamen() {
    return this.cseIdseccionexamen;
  }

  public void setCseIdseccionexamen(int cseIdseccionexamen) {
    this.cseIdseccionexamen = cseIdseccionexamen;
  }

  public long getCseIdexamen() {
    return this.cseIdexamen;
  }

  public void setCseIdexamen(long cseIdexamen) {
    this.cseIdexamen = cseIdexamen;
  }

}
