package com.grupobios.bioslis.entity;
// Generated 22-04-2020 16:13:26 by Hibernate Tools 4.3.1

import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CfgSecciones generated by hbm2java
 */
public class CfgSecciones {

  private int csecIdseccion;
  //@JsonIgnore
  private CfgLaboratorios cfgLaboratorios;
  private String csecCodigo;
  private String csecDescripcion;
  private String csecActiva;
  private short csecSort;
  private String csecColor;
  @JsonIgnore
  private Set cfgTests;
  @JsonIgnore
  private Set cfgSeccionesexameneses;
  @JsonIgnore
  private Set cfgSeccionestests;
  @JsonIgnore
  private Set cfgExamenes;
  //private Integer cfgLaboratorio;
  // Agregado x jan 15-05
  private String csecEsMicrobiologia;
  // private Integer clabIdCentroSalud;
  // private String clabDescripcion;

  // public Integer getClabIdCentroSalud() {
  // return clabIdCentroSalud;
  // }
  //
  // public void setClabIdCentroSalud(Integer clabIdCentroSalud) {
  // this.clabIdCentroSalud = clabIdCentroSalud;
  // }
  //
  // public String getClabDescripcion() {
  // return clabDescripcion;
  // }
  //
  // public void setClabDescripcion(String clabDescripcion) {
  // this.clabDescripcion = clabDescripcion;
  // }

  public CfgSecciones() {

  }

  public String getCsecDescripcion() {
    return this.csecDescripcion;
  }

  public void setCsecDescripcion(String csecDescripcion) {
    this.csecDescripcion = csecDescripcion;
  }

  public String getCsecActiva() {
    return this.csecActiva;
  }

  public void setCsecActiva(String csecActiva) {
    this.csecActiva = csecActiva;
  }

  public short getCsecSort() {
    return this.csecSort;
  }

  public void setCsecSort(short csecSort) {
    this.csecSort = csecSort;
  }

  public String getCsecColor() {
    return this.csecColor;
  }

  public void setCsecColor(String csecColor) {
    this.csecColor = csecColor;
  }

  public Set getCfgTests() {
    return this.cfgTests;
  }

  public void setCfgTests(Set cfgTests) {
    this.cfgTests = cfgTests;
  }

  public Set getCfgSeccionesexameneses() {
    return this.cfgSeccionesexameneses;
  }

  public void setCfgSeccionesexameneses(Set cfgSeccionesexameneses) {
    this.cfgSeccionesexameneses = cfgSeccionesexameneses;
  }

  public Set getCfgSeccionestests() {
    return this.cfgSeccionestests;
  }

  public void setCfgSeccionestests(Set cfgSeccionestests) {
    this.cfgSeccionestests = cfgSeccionestests;
  }

  public Set getCfgExamenes() {
    return this.cfgExamenes;
  }

  public void setCfgExamenes(Set cfgExameneses) {
    this.cfgExamenes = cfgExameneses;
  }

  public int getCsecIdseccion() {
    return csecIdseccion;
  }

  public void setCsecIdseccion(int csecIdseccion) {
    this.csecIdseccion = csecIdseccion;
  }

  public String getCsecCodigo() {
    return csecCodigo;
  }

  public void setCsecCodigo(String csecCodigo) {
    this.csecCodigo = csecCodigo;
  }

  public CfgLaboratorios getCfgLaboratorios() {
    return cfgLaboratorios;
  }

  public void setCfgLaboratorios(CfgLaboratorios cfgLaboratorios) {
    this.cfgLaboratorios = cfgLaboratorios;
  }

  public String getCsecEsMicrobiologia() {
    return csecEsMicrobiologia;
  }

  public void setCsecEsMicrobiologia(String csecEsMicrobiologia) {
    this.csecEsMicrobiologia = 
    		csecEsMicrobiologia;
  }
}
