package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * CfgSeccionestest generated by hbm2java
 */
public class CfgSeccionestest {

  private int cstIdsecciontest;
  private CfgSecciones cfgSecciones;
  private CfgTest cfgTest;
  private Short cstIdmetodo;

  public CfgSeccionestest() {
  }

  public int getCstIdsecciontest() {
    return this.cstIdsecciontest;
  }

  public void setCstIdsecciontest(int cstIdsecciontest) {
    this.cstIdsecciontest = cstIdsecciontest;
  }

  public CfgSecciones getCfgSecciones() {
    return this.cfgSecciones;
  }

  public void setCfgSecciones(CfgSecciones cfgSecciones) {
    this.cfgSecciones = cfgSecciones;
  }

  public CfgTest getCfgTest() {
    return this.cfgTest;
  }

  public void setCfgTest(CfgTest cfgTest) {
    this.cfgTest = cfgTest;
  }

  public Short getCstIdmetodo() {
    return this.cstIdmetodo;
  }

  public void setCstIdmetodo(Short cstIdmetodo) {
    this.cstIdmetodo = cstIdmetodo;
  }

}
