package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.beans.Transient;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.grupobios.bioslis.cfg.cache.CfgAbstracto;

/**
 * CfgTipoatencion generated by hbm2java
 */
public class CfgTipoatencion extends CfgAbstracto {

  private int ctaIdtipoatencion;
  private String ctaCodigo;
  private String ctaDescripcion;
  private String ctaActivo;
  private int ctaSort;
  private String ctaHost;
  @JsonIgnore
  private Set datosFichases;

  public CfgTipoatencion() {
  }

  public int getCtaIdtipoatencion() {
    return this.ctaIdtipoatencion;
  }

  public void setCtaIdtipoatencion(int ctaIdtipoatencion) {
    this.ctaIdtipoatencion = ctaIdtipoatencion;
  }

  public String getCtaCodigo() {
    return this.ctaCodigo;
  }

  public void setCtaCodigo(String ctaCodigo) {
    this.ctaCodigo = ctaCodigo;
  }

  public String getCtaDescripcion() {
    return this.ctaDescripcion;
  }

  public void setCtaDescripcion(String ctaDescripcion) {
    this.ctaDescripcion = ctaDescripcion;
  }

  public String getCtaActivo() {
    return this.ctaActivo;
  }

  public void setCtaActivo(String ctaActivo) {
    this.ctaActivo = ctaActivo;
  }

  public int getCtaSort() {
    return this.ctaSort;
  }

  public void setCtaSort(int ctaSort) {
    this.ctaSort = ctaSort;
  }

  public String getCtaHost() {
    return this.ctaHost;
  }

  public void setCtaHost(String ctaHost) {
    this.ctaHost = ctaHost;
  }

  public Set getDatosFichases() {
    return this.datosFichases;
  }

  public void setDatosFichases(Set datosFichases) {
    this.datosFichases = datosFichases;
  }

  @Transient
  @Override
  public Integer getId() {
    return this.ctaIdtipoatencion;
  }

  @Override
  @Transient
  public String getDescripcion() {
    return this.ctaDescripcion;

  }

}
