package com.grupobios.bioslis.entity;
// Generated 04-12-2020 16:59:50 by Hibernate Tools 4.3.1



/**
 * CfgTablasreferenciasexamenesId generated by hbm2java
 */
public class CfgTablasreferenciasexamenesId  implements java.io.Serializable {


     private short ctreIdtablareferenciaexamen;
     private String ctreCampo;

    public CfgTablasreferenciasexamenesId() {
    }

    public CfgTablasreferenciasexamenesId(short ctreIdtablareferenciaexamen, String ctreCampo) {
       this.ctreIdtablareferenciaexamen = ctreIdtablareferenciaexamen;
       this.ctreCampo = ctreCampo;
    }
   
    public short getCtreIdtablareferenciaexamen() {
        return this.ctreIdtablareferenciaexamen;
    }
    
    public void setCtreIdtablareferenciaexamen(short ctreIdtablareferenciaexamen) {
        this.ctreIdtablareferenciaexamen = ctreIdtablareferenciaexamen;
    }
    public String getCtreCampo() {
        return this.ctreCampo;
    }
    
    public void setCtreCampo(String ctreCampo) {
        this.ctreCampo = ctreCampo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CfgTablasreferenciasexamenesId) ) return false;
		 CfgTablasreferenciasexamenesId castOther = ( CfgTablasreferenciasexamenesId ) other; 
         
		 return (this.getCtreIdtablareferenciaexamen()==castOther.getCtreIdtablareferenciaexamen())
 && ( (this.getCtreCampo()==castOther.getCtreCampo()) || ( this.getCtreCampo()!=null && castOther.getCtreCampo()!=null && this.getCtreCampo().equals(castOther.getCtreCampo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCtreIdtablareferenciaexamen();
         result = 37 * result + ( getCtreCampo() == null ? 0 : this.getCtreCampo().hashCode() );
         return result;
   }   


}


