package com.grupobios.bioslis.entity;
// Generated 22-04-2020 16:13:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CfgTest generated by hbm2java
 */
public class CfgTest implements java.io.Serializable {

  private Integer ctIdtest;
  @JsonIgnore
  private CfgBacgrupostest cfgBacgrupostest;
  @JsonIgnore
  private CfgMuestras cfgMuestras;
  @JsonIgnore
  private CfgTiposderesultado cfgTiposderesultado;
  @JsonIgnore
  private CfgUnidadesdemedida cfgUnidadesdemedida;
  @JsonIgnore
  private CfgEnvases cfgEnvases;
  private Integer cfgSecciones;
  private String ctCodigo;
  private String ctDescripcion;
  private String ctAbreviado;
  private String ctResultadoobligado;
  private String ctResultadoomision;
  private Integer ctDecimales;
  private String ctFormula;
  private String ctFormulaexamendependiente;
  private String ctCondicion;
  private Integer ctIdgrupoglosas;
  private String ctOpcional;
  private String ctTieneantecedentes;
  private Short ctTestreporte;
  private String ctHost;
  private String ctHostmicro;
  private Integer ctSort;
  private String ctActivo;
  private String ctSeparadormil;
  private String ctTesthojatrabajo;
  private String ctCodigoloinc;
  private String ctPlanillahistorica;
  private Float ctVolumenmuestra;
  private Integer ctIdgrupoexamenesfonasa;
  private Float ctValorinferior;
  private Float ctValorsuperior;
  private Integer ctDeltacantidad;
  private Integer ctDeltaporcentaje;
  private Integer ctDiasevaluables;
  private String ctEscultivo;
  @JsonIgnore
  private Set<CfgExamenestest> cfgExamenestests = new HashSet<CfgExamenestest>(0);

  public CfgTest() {
  }

  public Integer getCtIdtest() {
    return ctIdtest;
  }

  public void setCtIdtest(Integer ctIdtest) {
    this.ctIdtest = ctIdtest;
  }

  public CfgBacgrupostest getCfgBacgrupostest() {
    return this.cfgBacgrupostest;
  }

  public void setCfgBacgrupostest(CfgBacgrupostest cfgBacgrupostest) {
    this.cfgBacgrupostest = cfgBacgrupostest;
  }

  public CfgMuestras getCfgMuestras() {
    return cfgMuestras;
  }

  public void setCfgMuestras(CfgMuestras cfgMuestras) {
    this.cfgMuestras = cfgMuestras;
  }

  public CfgTiposderesultado getCfgTiposderesultado() {
    return cfgTiposderesultado;
  }

  public void setCfgTiposderesultado(CfgTiposderesultado cfgTiposderesultado) {
    this.cfgTiposderesultado = cfgTiposderesultado;
  }

  public CfgUnidadesdemedida getCfgUnidadesdemedida() {
    return cfgUnidadesdemedida;
  }

  public void setCfgUnidadesdemedida(CfgUnidadesdemedida cfgUnidadesdemedida) {
    this.cfgUnidadesdemedida = cfgUnidadesdemedida;
  }

  public Integer getCfgSecciones() {
    return cfgSecciones;
  }

  public void setCfgSecciones(Integer cfgSecciones) {
    this.cfgSecciones = cfgSecciones;
  }

  public CfgEnvases getCfgEnvases() {
    return cfgEnvases;
  }

  public void setCfgEnvases(CfgEnvases cfgEnvases) {
    this.cfgEnvases = cfgEnvases;
  }

  public String getCtCodigo() {
    return ctCodigo;
  }

  public void setCtCodigo(String ctCodigo) {
    this.ctCodigo = ctCodigo;
  }

  public String getCtDescripcion() {
    return ctDescripcion;
  }

  public void setCtDescripcion(String ctDescripcion) {
    this.ctDescripcion = ctDescripcion;
  }

  public String getCtAbreviado() {
    return ctAbreviado;
  }

  public void setCtAbreviado(String ctAbreviado) {
    this.ctAbreviado = ctAbreviado;
  }

  public String getCtResultadoobligado() {
    return ctResultadoobligado;
  }

  public void setCtResultadoobligado(String ctResultadoobligado) {
    this.ctResultadoobligado = ctResultadoobligado;
  }

  public String getCtResultadoomision() {
    return ctResultadoomision;
  }

  public void setCtResultadoomision(String ctResultadoomision) {
    this.ctResultadoomision = ctResultadoomision;
  }

  public Integer getCtDecimales() {
    return ctDecimales;
  }

  public void setCtDecimales(Integer ctDecimales) {
    this.ctDecimales = ctDecimales;
  }

  public String getCtFormula() {
    return ctFormula;
  }

  public void setCtFormula(String ctFormula) {
    this.ctFormula = ctFormula;
  }

  public String getCtFormulaexamendependiente() {
    return ctFormulaexamendependiente;
  }

  public void setCtFormulaexamendependiente(String ctFormulaexamendependiente) {
    this.ctFormulaexamendependiente = ctFormulaexamendependiente;
  }

  public String getCtCondicion() {
    return ctCondicion;
  }

  public void setCtCondicion(String ctCondicion) {
    this.ctCondicion = ctCondicion;
  }

  public Integer getCtIdgrupoglosas() {
    return ctIdgrupoglosas;
  }

  public void setCtIdgrupoglosas(Integer ctIdgrupoglosas) {
    this.ctIdgrupoglosas = ctIdgrupoglosas;
  }

  public String getCtOpcional() {
    return ctOpcional;
  }

  public void setCtOpcional(String ctOpcional) {
    this.ctOpcional = ctOpcional;
  }

  public String getCtTieneantecedentes() {
    return ctTieneantecedentes;
  }

  public void setCtTieneantecedentes(String ctTieneantecedentes) {
    this.ctTieneantecedentes = ctTieneantecedentes;
  }

  public Short getCtTestreporte() {
    return ctTestreporte;
  }

  public void setCtTestreporte(Short ctTestreporte) {
    this.ctTestreporte = ctTestreporte;
  }

  public String getCtHost() {
    return ctHost;
  }

  public void setCtHost(String ctHost) {
    this.ctHost = ctHost;
  }

  public String getCtHostmicro() {
    return ctHostmicro;
  }

  public void setCtHostmicro(String ctHostmicro) {
    this.ctHostmicro = ctHostmicro;
  }

  public Integer getCtSort() {
    return ctSort;
  }

  public void setCtSort(Integer ctSort) {
    this.ctSort = ctSort;
  }

  public String getCtActivo() {
    return ctActivo;
  }

  public void setCtActivo(String ctActivo) {
    this.ctActivo = ctActivo;
  }

  public String getCtSeparadormil() {
    return ctSeparadormil;
  }

  public void setCtSeparadormil(String ctSeparadormil) {
    this.ctSeparadormil = ctSeparadormil;
  }

  public String getCtTesthojatrabajo() {
    return ctTesthojatrabajo;
  }

  public void setCtTesthojatrabajo(String ctTesthojatrabajo) {
    this.ctTesthojatrabajo = ctTesthojatrabajo;
  }

  public String getCtCodigoloinc() {
    return ctCodigoloinc;
  }

  public void setCtCodigoloinc(String ctCodigoloinc) {
    this.ctCodigoloinc = ctCodigoloinc;
  }

  public String getCtPlanillahistorica() {
    return ctPlanillahistorica;
  }

  public void setCtPlanillahistorica(String ctPlanillahistorica) {
    this.ctPlanillahistorica = ctPlanillahistorica;
  }

  public Float getCtVolumenmuestra() {
    return ctVolumenmuestra;
  }

  public void setCtVolumenmuestra(Float ctVolumenmuestra) {
    this.ctVolumenmuestra = ctVolumenmuestra;
  }

  public Integer getCtIdgrupoexamenesfonasa() {
    return ctIdgrupoexamenesfonasa;
  }

  public void setCtIdgrupoexamenesfonasa(Integer ctIdgrupoexamenesfonasa) {
    this.ctIdgrupoexamenesfonasa = ctIdgrupoexamenesfonasa;
  }

  public Float getCtValorinferior() {
    return ctValorinferior;
  }

  public void setCtValorinferior(Float ctValorinferior) {
    this.ctValorinferior = ctValorinferior;
  }

  public Float getCtValorsuperior() {
    return ctValorsuperior;
  }

  public void setCtValorsuperior(Float ctValorsuperior) {
    this.ctValorsuperior = ctValorsuperior;
  }

  public Integer getCtDeltacantidad() {
    return ctDeltacantidad;
  }

  public void setCtDeltacantidad(Integer ctDeltacantidad) {
    this.ctDeltacantidad = ctDeltacantidad;
  }

  public Integer getCtDeltaporcentaje() {
    return ctDeltaporcentaje;
  }

  public void setCtDeltaporcentaje(Integer ctDeltaporcentaje) {
    this.ctDeltaporcentaje = ctDeltaporcentaje;
  }

  public Integer getCtDiasevaluables() {
    return ctDiasevaluables;
  }

  public void setCtDiasevaluables(Integer ctDiasevaluables) {
    this.ctDiasevaluables = ctDiasevaluables;
  }

  public String getCtEscultivo() {
    return this.ctEscultivo;
  }

  public void setCtEscultivo(String ctEscultivo) {
    this.ctEscultivo = ctEscultivo;
  }

  public Set<CfgExamenestest> getCfgExamenestests() {
    return this.cfgExamenestests;
  }

  public void setCfgExamenestests(Set<CfgExamenestest> cfgExamenestests) {
    this.cfgExamenestests = cfgExamenestests;
  }

  @Override
  public int hashCode() {
    return Objects.hash(ctIdtest);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    CfgTest other = (CfgTest) obj;
    return Objects.equals(ctIdtest, other.ctIdtest);
  }

@Override
public String toString() {
    return "CfgTest [ctIdtest=" + ctIdtest + ", ctFormula=" + ctFormula + "]";
}


  
}
