package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CfgTiposnotas generated by hbm2java
 */
public class CfgTiposnotas  implements java.io.Serializable {


     private byte ctnIdtiponota;
     private String ctnDescripciontiponota;
     private String ctnActivo;
     private Byte ctnSort;
     private Set cfgNotases = new HashSet(0);

    public CfgTiposnotas() {
    }

	
    public CfgTiposnotas(byte ctnIdtiponota) {
        this.ctnIdtiponota = ctnIdtiponota;
    }
    public CfgTiposnotas(byte ctnIdtiponota, String ctnDescripciontiponota, String ctnActivo, Byte ctnSort, Set cfgNotases) {
       this.ctnIdtiponota = ctnIdtiponota;
       this.ctnDescripciontiponota = ctnDescripciontiponota;
       this.ctnActivo = ctnActivo;
       this.ctnSort = ctnSort;
       this.cfgNotases = cfgNotases;
    }
   
    public byte getCtnIdtiponota() {
        return this.ctnIdtiponota;
    }
    
    public void setCtnIdtiponota(byte ctnIdtiponota) {
        this.ctnIdtiponota = ctnIdtiponota;
    }
    public String getCtnDescripciontiponota() {
        return this.ctnDescripciontiponota;
    }
    
    public void setCtnDescripciontiponota(String ctnDescripciontiponota) {
        this.ctnDescripciontiponota = ctnDescripciontiponota;
    }
    public String getCtnActivo() {
        return this.ctnActivo;
    }
    
    public void setCtnActivo(String ctnActivo) {
        this.ctnActivo = ctnActivo;
    }
    public Byte getCtnSort() {
        return this.ctnSort;
    }
    
    public void setCtnSort(Byte ctnSort) {
        this.ctnSort = ctnSort;
    }
    public Set getCfgNotases() {
        return this.cfgNotases;
    }
    
    public void setCfgNotases(Set cfgNotases) {
        this.cfgNotases = cfgNotases;
    }




}


