package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CfgUnidadesdemedida generated by hbm2java
 */
public class CfgUnidadesdemedida  implements java.io.Serializable {


     private int cumIdunidadmedida;
     private String cumCodigo;
     private String cumDescripcion;
     private String cumActivo;
     private String cumSort;
     @JsonIgnore
     private Set cfgTests = new HashSet(0);

    public CfgUnidadesdemedida() {
    }

	
    public CfgUnidadesdemedida(int cumIdunidadmedida, String cumCodigo, String cumActivo) {
        this.cumIdunidadmedida = cumIdunidadmedida;
        this.cumCodigo = cumCodigo;
        this.cumActivo = cumActivo;
    }
    public CfgUnidadesdemedida(int cumIdunidadmedida, String cumCodigo, String cumDescripcion, String cumActivo, String cumSort, Set cfgTests) {
       this.cumIdunidadmedida = cumIdunidadmedida;
       this.cumCodigo = cumCodigo;
       this.cumDescripcion = cumDescripcion;
       this.cumActivo = cumActivo;
       this.cumSort = cumSort;
       this.cfgTests = cfgTests;
    }
   
    public int getCumIdunidadmedida() {
        return this.cumIdunidadmedida;
    }
    
    public void setCumIdunidadmedida(int cumIdunidadmedida) {
        this.cumIdunidadmedida = cumIdunidadmedida;
    }
    public String getCumCodigo() {
        return this.cumCodigo;
    }
    
    public void setCumCodigo(String cumCodigo) {
        this.cumCodigo = cumCodigo;
    }
    public String getCumDescripcion() {
        return this.cumDescripcion;
    }
    
    public void setCumDescripcion(String cumDescripcion) {
        this.cumDescripcion = cumDescripcion;
    }
    public String getCumActivo() {
        return this.cumActivo;
    }
    
    public void setCumActivo(String cumActivo) {
        this.cumActivo = cumActivo;
    }
    public String getCumSort() {
        return this.cumSort;
    }
    
    public void setCumSort(String cumSort) {
        this.cumSort = cumSort;
    }
    public Set getCfgTests() {
        return this.cfgTests;
    }
    
    public void setCfgTests(Set cfgTests) {
        this.cfgTests = cfgTests;
    }




}


