package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigDecimal;

/**
 * CfgValoresreferencia generated by hbm2java
 */
public class CfgValoresreferencia implements java.io.Serializable {

	private int cvrIdvalorreferencia;
        private CfgMetodos cfgMetodos;
	private long cvrIdtest;
	private String cvrSexo;
	private Integer cvrAnosdesde;
	private Integer cvrMesesdesde;
	private Integer cvrDiasdesde;
	private Integer cvrAnoshasta;
	private Integer cvrMeseshasta;
	private Integer cvrDiashasta;
	private BigDecimal cvrValorcriticobajo;
	private BigDecimal cvrValorbajo;
	private BigDecimal cvrValoralto;
	private BigDecimal cvrValorcriticoalto;
	private String cvrValortexto;

	public CfgValoresreferencia() {
	}

	public int getCvrIdvalorreferencia() {
		return this.cvrIdvalorreferencia;
	}

	public void setCvrIdvalorreferencia(int cvrIdvalorreferencia) {
		this.cvrIdvalorreferencia = cvrIdvalorreferencia;
	}

	public CfgMetodos getCfgMetodos() {
		return this.cfgMetodos;
	}

	public void setCfgMetodos(CfgMetodos cfgMetodos) {
		this.cfgMetodos = cfgMetodos;
	}

	public long getCvrIdtest() {
		return this.cvrIdtest;
	}

	public void setCvrIdtest(long cvrIdtest) {
		this.cvrIdtest = cvrIdtest;
	}

	public String getCvrSexo() {
		return this.cvrSexo;
	}

	public void setCvrSexo(String cvrSexo) {
		this.cvrSexo = cvrSexo;
	}

	public Integer getCvrAnosdesde() {
		return this.cvrAnosdesde;
	}

	public void setCvrAnosdesde(Integer cvrAnosdesde) {
		this.cvrAnosdesde = cvrAnosdesde;
	}

	public Integer getCvrMesesdesde() {
		return this.cvrMesesdesde;
	}

	public void setCvrMesesdesde(Integer cvrMesesdesde) {
		this.cvrMesesdesde = cvrMesesdesde;
	}

	public Integer getCvrDiasdesde() {
		return this.cvrDiasdesde;
	}

	public void setCvrDiasdesde(Integer cvrDiasdesde) {
		this.cvrDiasdesde = cvrDiasdesde;
	}

	public Integer getCvrAnoshasta() {
		return this.cvrAnoshasta;
	}

	public void setCvrAnoshasta(Integer cvrAnoshasta) {
		this.cvrAnoshasta = cvrAnoshasta;
	}

	public Integer getCvrMeseshasta() {
		return this.cvrMeseshasta;
	}

	public void setCvrMeseshasta(Integer cvrMeseshasta) {
		this.cvrMeseshasta = cvrMeseshasta;
	}

	public Integer getCvrDiashasta() {
		return this.cvrDiashasta;
	}

	public void setCvrDiashasta(Integer cvrDiashasta) {
		this.cvrDiashasta = cvrDiashasta;
	}

	public BigDecimal getCvrValorcriticobajo() {
		return this.cvrValorcriticobajo;
	}

	public void setCvrValorcriticobajo(BigDecimal cvrValorcriticobajo) {
		this.cvrValorcriticobajo = cvrValorcriticobajo;
	}

	public BigDecimal getCvrValorbajo() {
		return this.cvrValorbajo;
	}

	public void setCvrValorbajo(BigDecimal cvrValorbajo) {
		this.cvrValorbajo = cvrValorbajo;
	}

	public BigDecimal getCvrValoralto() {
		return this.cvrValoralto;
	}

	public void setCvrValoralto(BigDecimal cvrValoralto) {
		this.cvrValoralto = cvrValoralto;
	}

	public BigDecimal getCvrValorcriticoalto() {
		return this.cvrValorcriticoalto;
	}

	public void setCvrValorcriticoalto(BigDecimal cvrValorcriticoalto) {
		this.cvrValorcriticoalto = cvrValorcriticoalto;
	}

	public String getCvrValortexto() {
		return this.cvrValortexto;
	}

	public void setCvrValortexto(String cvrValortexto) {
		this.cvrValortexto = cvrValortexto;
	}

	@Override
	public String toString() {
		return "CfgValoresreferencia [cvrIdvalorreferencia=" + cvrIdvalorreferencia + ", cfgMetodos=" + cfgMetodos
				+ ", cvrIdtest=" + cvrIdtest + ", cvrSexo=" + cvrSexo + ", cvrAnosdesde=" + cvrAnosdesde
				+ ", cvrMesesdesde=" + cvrMesesdesde + ", cvrDiasdesde=" + cvrDiasdesde + ", cvrAnoshasta="
				+ cvrAnoshasta + ", cvrMeseshasta=" + cvrMeseshasta + ", cvrDiashasta=" + cvrDiashasta
				+ ", cvrValorcriticobajo=" + cvrValorcriticobajo + ", cvrValorbajo=" + cvrValorbajo + ", cvrValoralto="
				+ cvrValoralto + ", cvrValorcriticoalto=" + cvrValorcriticoalto + ", cvrValortexto=" + cvrValortexto
				+ "]";
	}

}
