package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * DatosFichasexamenespesquisasId generated by hbm2java
 */
public class DatosFichasexamenespesquisasId  implements java.io.Serializable {


     private long dfepNorden;
     private long dfepIdexamen;

    public DatosFichasexamenespesquisasId() {
    }

    public DatosFichasexamenespesquisasId(long dfepNorden, long dfepIdexamen) {
       this.dfepNorden = dfepNorden;
       this.dfepIdexamen = dfepIdexamen;
    }
   
    public long getDfepNorden() {
        return this.dfepNorden;
    }
    
    public void setDfepNorden(long dfepNorden) {
        this.dfepNorden = dfepNorden;
    }
    public long getDfepIdexamen() {
        return this.dfepIdexamen;
    }
    
    public void setDfepIdexamen(long dfepIdexamen) {
        this.dfepIdexamen = dfepIdexamen;
    }




}


