package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * DatosFichasantecedentes generated by hbm2java
 */
public class DatosFichasantecedentes  implements java.io.Serializable {


     private DatosFichasantecedentesId id;
     private CfgAntecedentes cfgAntecedentes;
     private String dfaValorantecedente;

    public DatosFichasantecedentes() {
    }

	
    public DatosFichasantecedentes(DatosFichasantecedentesId id, CfgAntecedentes cfgAntecedentes) {
        this.id = id;
        this.cfgAntecedentes = cfgAntecedentes;
    }
    public DatosFichasantecedentes(DatosFichasantecedentesId id, CfgAntecedentes cfgAntecedentes, String dfaValorantecedente) {
       this.id = id;
       this.cfgAntecedentes = cfgAntecedentes;
       this.dfaValorantecedente = dfaValorantecedente;
    }
   
    public DatosFichasantecedentesId getId() {
        return this.id;
    }
    
    public void setId(DatosFichasantecedentesId id) {
        this.id = id;
    }
    public CfgAntecedentes getCfgAntecedentes() {
        return this.cfgAntecedentes;
    }
    
    public void setCfgAntecedentes(CfgAntecedentes cfgAntecedentes) {
        this.cfgAntecedentes = cfgAntecedentes;
    }
    public String getDfaValorantecedente() {
        return this.dfaValorantecedente;
    }
    
    public void setDfaValorantecedente(String dfaValorantecedente) {
        this.dfaValorantecedente = dfaValorantecedente;
    }


	@Override
	public String toString() {
		return "DatosFichasantecedentes [id=" + id + "]";
	}

    

}


