package com.grupobios.bioslis.entity;

// Generated 22-04-2020 16:13:26 by Hibernate Tools 4.3.1
import java.util.Date;
import java.util.Set;

import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DatosFichasexamenes generated by hbm2java
 */
public class DatosFichasexamenes implements java.io.Serializable {

  private DatosFichasexamenesId IddatosFichasExamenes;
  private CfgBacestados cfgBacestados;
  private Byte dfeSort;
  private Date dfeFechacreacion;
  private long dfeIdusuario;
  private String dfeCodigoestadoexamen;
  private String dfeImpreso;
  private String dfeAutorizado;
  private String dfeListatrabajogenerada;
  private Long dfeListatrabajonumero;
  private Date dfeListatrabajofecha;
  private Long dfeIdusuariolistatrabajo;
  private Date dfeFechaentrega;
  private Long dfeIdusuariofirma;
  private Date dfeFechafirma;
  private Long dfeIdusuarioimprime;
  private Date dfeFechaimpresion;
  private Short dfeNumerocopias;
  private String dfeNotainterna;
  private String dfeNotaexamen;
  private String dfeNotainforme;
  private String dfeNota;
  private Date dfeBacfechainicio;
  private Date dfeBacfecharesultado;
  private String dfeBaclis;
  private Date dfeBaclisfecha;
  private Byte dfeCantidad;
  private String dfeExamenretirado;
  private String dfeRutretiraexamen;
  private String dfeNombreretiraexamen;
  private Date dfeFecharetiraexamen;
  private Long dfeIdusuarioautoriza;
  private Date dfeFechaautoriza;
  private String dfeEnviadoporemail;
  private Long dfeIdusuarioemail;
  private Date dfeFechaemail;
  private Short dfeIdderivador;
  private String dfeEnviadoahost;
  private Date dfeFechaenviadoahost;
  private String dfeWebdisponible;
  private Date dfeWebdisponiblefecha;
  private String dfePdfenviado;
  private Date dfePdffechaenvio;
  private String dfeTienepreinforme;
  private String dfePdfenviareproceso;
  private String dfeWebfechaimpresion;
  private Long dfeIdusuariodt;
  private String dfeRechazoexamen;
  private Long dfeIdusuariorechazo;
  private String dfeExamenesurgente;
  private DatosFichasexamenespesquisas datosFichasexamenespesquisas;
  @JsonIgnore
  private Set datosFichasexamenesarchivoses;
  @JsonIgnore
  private Set datosFichasexamenestests;
  private String dfeExamenAnulado;
  //agregado x jan 20-12-22
  private Date dfeBacfechainicio2;

  public String getDfeExamenAnulado() {
    return dfeExamenAnulado;
  }

  public void setDfeExamenAnulado(String dfeExamenAnulado) {
    this.dfeExamenAnulado = dfeExamenAnulado;
  }

  public Long getDfeIdusuarioAnula() {
    return dfeIdusuarioAnula;
  }

  public void setDfeIdusuarioAnula(Long dfeIdusuarioAnula) {
    this.dfeIdusuarioAnula = dfeIdusuarioAnula;
  }

  private Long dfeIdusuarioAnula;

  public DatosFichasexamenes() {
  }

  public DatosFichasexamenesId getIddatosFichasExamenes() {
    return this.IddatosFichasExamenes;
  }

  public void setIddatosFichasExamenes(DatosFichasexamenesId IddatosFichasExamenes) {
    this.IddatosFichasExamenes = IddatosFichasExamenes;
  }

  public CfgBacestados getCfgBacestados() {
    return this.cfgBacestados;
  }

  public void setCfgBacestados(CfgBacestados cfgBacestados) {
    this.cfgBacestados = cfgBacestados;
  }

  public Byte getDfeSort() {
    return this.dfeSort;
  }

  public void setDfeSort(Byte dfeSort) {
    this.dfeSort = dfeSort;
  }

  public Date getDfeFechacreacion() {
    return this.dfeFechacreacion;
  }

  public void setDfeFechacreacion(Date dfeFechacreacion) {
    this.dfeFechacreacion = dfeFechacreacion;
  }

  public long getDfeIdusuario() {
    return this.dfeIdusuario;
  }

  public void setDfeIdusuario(long dfeIdusuario) {
    this.dfeIdusuario = dfeIdusuario;
  }

  public String getDfeCodigoestadoexamen() {
    return this.dfeCodigoestadoexamen;
  }

  public void setDfeCodigoestadoexamen(String dfeCodigoestadoexamen) {
    this.dfeCodigoestadoexamen = dfeCodigoestadoexamen;
  }

  public String getDfeImpreso() {
    return this.dfeImpreso;
  }

  public void setDfeImpreso(String dfeImpreso) {
    this.dfeImpreso = dfeImpreso;
  }

  public String getDfeAutorizado() {
    return this.dfeAutorizado;
  }

  public void setDfeAutorizado(String dfeAutorizado) {
    this.dfeAutorizado = dfeAutorizado;
  }

  public String getDfeListatrabajogenerada() {
    return this.dfeListatrabajogenerada;
  }

  public void setDfeListatrabajogenerada(String dfeListatrabajogenerada) {
    this.dfeListatrabajogenerada = dfeListatrabajogenerada;
  }

  public Long getDfeListatrabajonumero() {
    return this.dfeListatrabajonumero;
  }

  public void setDfeListatrabajonumero(Long dfeListatrabajonumero) {
    this.dfeListatrabajonumero = dfeListatrabajonumero;
  }

  public Date getDfeListatrabajofecha() {
    return this.dfeListatrabajofecha;
  }

  public void setDfeListatrabajofecha(Date dfeListatrabajofecha) {
    this.dfeListatrabajofecha = dfeListatrabajofecha;
  }

  public Long getDfeIdusuariolistatrabajo() {
    return this.dfeIdusuariolistatrabajo;
  }

  public void setDfeIdusuariolistatrabajo(Long dfeIdusuariolistatrabajo) {
    this.dfeIdusuariolistatrabajo = dfeIdusuariolistatrabajo;
  }

  public Date getDfeFechaentrega() {
    return this.dfeFechaentrega;
  }

  public void setDfeFechaentrega(Date dfeFechaentrega) {
    this.dfeFechaentrega = dfeFechaentrega;
  }

  public Long getDfeIdusuariofirma() {
    return this.dfeIdusuariofirma;
  }

  public void setDfeIdusuariofirma(Long dfeIdusuariofirma) {
    this.dfeIdusuariofirma = dfeIdusuariofirma;
  }

  public Date getDfeFechafirma() {
    return this.dfeFechafirma;
  }

  public void setDfeFechafirma(Date dfeFechafirma) {
    this.dfeFechafirma = dfeFechafirma;
  }

  public Long getDfeIdusuarioimprime() {
    return this.dfeIdusuarioimprime;
  }

  public void setDfeIdusuarioimprime(Long dfeIdusuarioimprime) {
    this.dfeIdusuarioimprime = dfeIdusuarioimprime;
  }

  public Date getDfeFechaimpresion() {
    return this.dfeFechaimpresion;
  }

  public void setDfeFechaimpresion(Date dfeFechaimpresion) {
    this.dfeFechaimpresion = dfeFechaimpresion;
  }

  public Short getDfeNumerocopias() {
    return this.dfeNumerocopias;
  }

  public void setDfeNumerocopias(Short dfeNumerocopias) {
    this.dfeNumerocopias = dfeNumerocopias;
  }

  public String getDfeNotainterna() {
    return this.dfeNotainterna;
  }

  public void setDfeNotainterna(String dfeNotainterna) {
    this.dfeNotainterna = dfeNotainterna;
  }

  public String getDfeNotaexamen() {
    return this.dfeNotaexamen;
  }

  public void setDfeNotaexamen(String dfeNotaexamen) {
    this.dfeNotaexamen = dfeNotaexamen;
  }

  public String getDfeNotainforme() {
    return this.dfeNotainforme;
  }

  public void setDfeNotainforme(String dfeNotainforme) {
    this.dfeNotainforme = dfeNotainforme;
  }

  public String getDfeNota() {
    return this.dfeNota;
  }

  public void setDfeNota(String dfeNota) {
    this.dfeNota = dfeNota;
  }

  public Date getDfeBacfechainicio() {
    return this.dfeBacfechainicio;
  }

  public void setDfeBacfechainicio(Date dfeBacfechainicio) {
    this.dfeBacfechainicio = dfeBacfechainicio;
  }

  public Date getDfeBacfecharesultado() {
    return this.dfeBacfecharesultado;
  }

  public void setDfeBacfecharesultado(Date dfeBacfecharesultado) {
    this.dfeBacfecharesultado = dfeBacfecharesultado;
  }

  public String getDfeBaclis() {
    return this.dfeBaclis;
  }

  public void setDfeBaclis(String dfeBaclis) {
    this.dfeBaclis = dfeBaclis;
  }

  public Date getDfeBaclisfecha() {
    return this.dfeBaclisfecha;
  }

  public void setDfeBaclisfecha(Date dfeBaclisfecha) {
    this.dfeBaclisfecha = dfeBaclisfecha;
  }

  public Byte getDfeCantidad() {
    return this.dfeCantidad;
  }

  public void setDfeCantidad(Byte dfeCantidad) {
    this.dfeCantidad = dfeCantidad;
  }

  public String getDfeExamenretirado() {
    return this.dfeExamenretirado;
  }

  public void setDfeExamenretirado(String dfeExamenretirado) {
    this.dfeExamenretirado = dfeExamenretirado;
  }

  public String getDfeRutretiraexamen() {
    return this.dfeRutretiraexamen;
  }

  public void setDfeRutretiraexamen(String dfeRutretiraexamen) {
    this.dfeRutretiraexamen = dfeRutretiraexamen;
  }

  public String getDfeNombreretiraexamen() {
    return this.dfeNombreretiraexamen;
  }

  public void setDfeNombreretiraexamen(String dfeNombreretiraexamen) {
    this.dfeNombreretiraexamen = dfeNombreretiraexamen;
  }

  public Date getDfeFecharetiraexamen() {
    return this.dfeFecharetiraexamen;
  }

  public void setDfeFecharetiraexamen(Date dfeFecharetiraexamen) {
    this.dfeFecharetiraexamen = dfeFecharetiraexamen;
  }

  public Long getDfeIdusuarioautoriza() {
    return this.dfeIdusuarioautoriza;
  }

  public void setDfeIdusuarioautoriza(Long dfeIdusuarioautoriza) {
    this.dfeIdusuarioautoriza = dfeIdusuarioautoriza;
  }

  public Date getDfeFechaautoriza() {
    return this.dfeFechaautoriza;
  }

  public void setDfeFechaautoriza(Date dfeFechaautoriza) {
    this.dfeFechaautoriza = dfeFechaautoriza;
  }

  public String getDfeEnviadoporemail() {
    return this.dfeEnviadoporemail;
  }

  public void setDfeEnviadoporemail(String dfeEnviadoporemail) {
    this.dfeEnviadoporemail = dfeEnviadoporemail;
  }

  public Long getDfeIdusuarioemail() {
    return this.dfeIdusuarioemail;
  }

  public void setDfeIdusuarioemail(Long dfeIdusuarioemail) {
    this.dfeIdusuarioemail = dfeIdusuarioemail;
  }

  public Date getDfeFechaemail() {
    return this.dfeFechaemail;
  }

  public void setDfeFechaemail(Date dfeFechaemail) {
    this.dfeFechaemail = dfeFechaemail;
  }

  public Short getDfeIdderivador() {
    return this.dfeIdderivador;
  }

  public void setDfeIdderivador(Short dfeIdderivador) {
    this.dfeIdderivador = dfeIdderivador;
  }

  public String getDfeEnviadoahost() {
    return this.dfeEnviadoahost;
  }

  public void setDfeEnviadoahost(String dfeEnviadoahost) {
    this.dfeEnviadoahost = dfeEnviadoahost;
  }

  public Date getDfeFechaenviadoahost() {
    return this.dfeFechaenviadoahost;
  }

  public void setDfeFechaenviadoahost(Date dfeFechaenviadoahost) {
    this.dfeFechaenviadoahost = dfeFechaenviadoahost;
  }

  public String getDfeWebdisponible() {
    return this.dfeWebdisponible;
  }

  public void setDfeWebdisponible(String dfeWebdisponible) {
    this.dfeWebdisponible = dfeWebdisponible;
  }

  public Date getDfeWebdisponiblefecha() {
    return this.dfeWebdisponiblefecha;
  }

  public void setDfeWebdisponiblefecha(Date dfeWebdisponiblefecha) {
    this.dfeWebdisponiblefecha = dfeWebdisponiblefecha;
  }

  public String getDfePdfenviado() {
    return this.dfePdfenviado;
  }

  public void setDfePdfenviado(String dfePdfenviado) {
    this.dfePdfenviado = dfePdfenviado;
  }

  public Date getDfePdffechaenvio() {
    return this.dfePdffechaenvio;
  }

  public void setDfePdffechaenvio(Date dfePdffechaenvio) {
    this.dfePdffechaenvio = dfePdffechaenvio;
  }

  public String getDfeTienepreinforme() {
    return this.dfeTienepreinforme;
  }

  public void setDfeTienepreinforme(String dfeTienepreinforme) {
    this.dfeTienepreinforme = dfeTienepreinforme;
  }

  public String getDfePdfenviareproceso() {
    return this.dfePdfenviareproceso;
  }

  public void setDfePdfenviareproceso(String dfePdfenviareproceso) {
    this.dfePdfenviareproceso = dfePdfenviareproceso;
  }

  public String getDfeWebfechaimpresion() {
    return this.dfeWebfechaimpresion;
  }

  public void setDfeWebfechaimpresion(String dfeWebfechaimpresion) {
    this.dfeWebfechaimpresion = dfeWebfechaimpresion;
  }

  public Long getDfeIdusuariodt() {
    return this.dfeIdusuariodt;
  }

  public void setDfeIdusuariodt(Long dfeIdusuariodt) {
    this.dfeIdusuariodt = dfeIdusuariodt;
  }

  public String getDfeRechazoexamen() {
    return this.dfeRechazoexamen;
  }

  public void setDfeRechazoexamen(String dfeRechazoexamen) {
    this.dfeRechazoexamen = dfeRechazoexamen;
  }

  public Long getDfeIdusuariorechazo() {
    return this.dfeIdusuariorechazo;
  }

  public void setDfeIdusuariorechazo(Long dfeIdusuariorechazo) {
    this.dfeIdusuariorechazo = dfeIdusuariorechazo;
  }

  public DatosFichasexamenespesquisas getDatosFichasexamenespesquisas() {
    return this.datosFichasexamenespesquisas;
  }

  public void setDatosFichasexamenespesquisas(DatosFichasexamenespesquisas datosFichasexamenespesquisas) {
    this.datosFichasexamenespesquisas = datosFichasexamenespesquisas;
  }

  public Set getDatosFichasexamenesarchivoses() {
    return this.datosFichasexamenesarchivoses;
  }

  @Transient
  public void setDatosFichasexamenesarchivoses(Set datosFichasexamenesarchivoses) {
    this.datosFichasexamenesarchivoses = datosFichasexamenesarchivoses;
  }

  public Set getDatosFichasexamenestests() {
    return this.datosFichasexamenestests;
  }

  public void setDatosFichasexamenestests(Set datosFichasexamenestests) {
    this.datosFichasexamenestests = datosFichasexamenestests;
  }

  /**
   * @return the dfeExamenesurgente
   */
  public String getDfeExamenesurgente() {
    return dfeExamenesurgente;
  }

  /**
   * @param dfeExamenesurgente the dfeExamenesurgente to set
   */
  public void setDfeExamenesurgente(String dfeExamenesurgente) {
    this.dfeExamenesurgente = dfeExamenesurgente;
  }

  @Override
  public String toString() {
    return "DatosFichasexamenes{" + "IddatosFichasExamenes=" + IddatosFichasExamenes.toString() + " dfeExamenesurgente :  " + dfeExamenesurgente.toString()+ '}';
  }

public Date getDfeBacfechainicio2() {
	return dfeBacfechainicio2;
}

public void setDfeBacfechainicio2(Date dfeBacfechainicio2) {
	this.dfeBacfechainicio2 = dfeBacfechainicio2;
}


}
