package com.grupobios.bioslis.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

// Generated 22-04-2020 16:13:26 by Hibernate Tools 4.3.1

/**
 * DatosContactos generated by hbm2java
 */
@SuppressWarnings("serial")
public class DatosContactos implements java.io.Serializable {

  private int dcIdcontacto;
  private DatosPacientes datosPacientes;
  private Integer dcIdsexo;
 @JsonInclude(content = Include.NON_NULL)
  private LdvContactospacientesrelacion ldvContactospacientesrelacion;
  private String dcNombre;
  private String dcTelefono;

  public Integer getDcIdsexo() {
    return dcIdsexo;
  }

  public void setDcIdsexo(Integer dcSexo) {
    this.dcIdsexo = dcSexo;
  }

  public DatosContactos() {
  }

  public int getDcIdcontacto() {
    return dcIdcontacto;
  }

  public void setDcIdcontacto(int dcIdcontacto) {
    this.dcIdcontacto = dcIdcontacto;
  }

  public DatosPacientes getDatosPacientes() {
    return this.datosPacientes;
  }

  public void setDatosPacientes(DatosPacientes datosPacientes) {
    this.datosPacientes = datosPacientes;
  }

  public LdvContactospacientesrelacion getLdvContactospacientesrelacion() {
    return this.ldvContactospacientesrelacion;
  }

  public void setLdvContactospacientesrelacion(LdvContactospacientesrelacion ldvContactospacientesrelacion) {
    this.ldvContactospacientesrelacion = ldvContactospacientesrelacion;
  }

  public String getDcNombre() {
    return this.dcNombre;
  }

  public void setDcNombre(String dcNombre) {
    this.dcNombre = dcNombre;
  }

  public String getDcTelefono() {
    return this.dcTelefono;
  }

  public void setDcTelefono(String dcTelefono) {
    this.dcTelefono = dcTelefono;
  }

  @Override
  public String toString() {
    return "DatosContactos [dcIdcontacto=" + dcIdcontacto + " dcIdsexo="
        + dcIdsexo + ", ldvContactospacientesrelacion=" + ldvContactospacientesrelacion + ", dcNombre=" + dcNombre
        + ", dcTelefono=" + dcTelefono + "]";
  }

}
