package com.grupobios.bioslis.entity;

import java.io.Serializable;

// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * DatosFichasexamenestestId generated by hbm2java
 */
public class DatosFichasexamenestestId implements Serializable {

	private long dfetNorden;
	private long dfetIdexamen;
	private long dfetIdtest;

	public DatosFichasexamenestestId() {
	}

	public DatosFichasexamenestestId(long dfetNorden, long dfetIdexamen, long dfetIdtest) {
		this.dfetNorden = dfetNorden;
		this.dfetIdexamen = dfetIdexamen;
		this.dfetIdtest = dfetIdtest;
	}

	public long getDfetNorden() {
		return this.dfetNorden;
	}

	public void setDfetNorden(long dfetNorden) {
		this.dfetNorden = dfetNorden;
	}

	public long getDfetIdexamen() {
		return this.dfetIdexamen;
	}

	public void setDfetIdexamen(long dfetIdexamen) {
		this.dfetIdexamen = dfetIdexamen;
	}

	public long getDfetIdtest() {
		return this.dfetIdtest;
	}

	public void setDfetIdtest(long dfetIdtest) {
		this.dfetIdtest = dfetIdtest;
	}

	@Override
	public String toString() {
		return "DatosFichasexamenestestId [dfetNorden=" + dfetNorden + ", dfetIdexamen=" + dfetIdexamen
				+ ", dfetIdtest=" + dfetIdtest + "]";
	}

}
