package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * DatosFichasexamenesmicroorgId generated by hbm2java
 */
public class DatosFichasexamenesmicroorgId  implements java.io.Serializable {


     private long dfemoNorden;
     private long dfemoIdexamen;

    public DatosFichasexamenesmicroorgId() {
    }

    public DatosFichasexamenesmicroorgId(long dfemoNorden, long dfemoIdexamen) {
       this.dfemoNorden = dfemoNorden;
       this.dfemoIdexamen = dfemoIdexamen;
    }
   
    public long getDfemoNorden() {
        return this.dfemoNorden;
    }
    
    public void setDfemoNorden(long dfemoNorden) {
        this.dfemoNorden = dfemoNorden;
    }
    public long getDfemoIdexamen() {
        return this.dfemoIdexamen;
    }
    
    public void setDfemoIdexamen(long dfemoIdexamen) {
        this.dfemoIdexamen = dfemoIdexamen;
    }




}


