package com.grupobios.bioslis.entity;
// Generated 22-04-2020 16:13:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 *      private Set datosFichasdocumentoses = new HashSet(0);
     private Set datosFichasexamenestests = new HashSet(0);
 * DatosFichas generated by hbm2java
 */

public class DatosFichas  implements java.io.Serializable {


     private int dfNorden;
     private int datosPacientes;
     private Integer cfgServicios;
     private Integer cfgLocalizaciones;
     private int cfgDiagnosticos;
     private int cfgConvenios;
     private int cfgProcedencias;
     private int ldvFichasestadostm;
     private int cfgPrioridadatencion;
     private Integer cfgTipoatencion;
     private int cfgInstitucionesdesalud;
     private Date dfFechaorden;
     private Short dfIdprevision;
     private Integer dfIdmedico;
     private String dfCodigolocalizacion;
     private String dfObservacion;
     private String dfHost;
     private String dfEnviarresultadosemail;
     private String dfTmclick;

    public DatosFichas() {
    }

    public int getDfNorden() {
        return this.dfNorden;
    }
    
    public void setDfNorden(int dfNorden) {
        this.dfNorden = dfNorden;
    }
    public int getDatosPacientes() {
        return this.datosPacientes;
    }
    
    public void setDatosPacientes(int datosPacientes) {
        this.datosPacientes = datosPacientes;
    }
    public Integer getCfgServicios() {
        return this.cfgServicios;
    }
    
    public void setCfgServicios(Integer cfgServicios) {
        this.cfgServicios = cfgServicios;
    }
    public int getCfgDiagnosticos() {
        return this.cfgDiagnosticos;
    }
    
    public void setCfgDiagnosticos(int cfgDiagnosticos) {
        this.cfgDiagnosticos = cfgDiagnosticos;
    }
    public int getCfgConvenios() {
        return this.cfgConvenios;
    }
    
    public void setCfgConvenios(int cfgConvenios) {
        this.cfgConvenios = cfgConvenios;
    }
    public int getCfgProcedencias() {
        return this.cfgProcedencias;
    }
    
    public void setCfgProcedencias(int cfgProcedencias) {
        this.cfgProcedencias = cfgProcedencias;
    }
    public int getLdvFichasestadostm() {
        return this.ldvFichasestadostm;
    }
    
    public void setLdvFichasestadostm(int ldvFichasestadostm) {
        this.ldvFichasestadostm = ldvFichasestadostm;
    }
    public int getCfgPrioridadatencion() {
        return this.cfgPrioridadatencion;
    }
    
    public void setCfgPrioridadatencion(int cfgPrioridadatencion) {
        this.cfgPrioridadatencion = cfgPrioridadatencion;
    }
    public int getCfgTipoatencion() {
        return this.cfgTipoatencion;
    }
    
    public void setCfgTipoatencion(int cfgTipoatencion) {
        this.cfgTipoatencion = cfgTipoatencion;
    }
    public int getCfgInstitucionesdesalud() {
        return this.cfgInstitucionesdesalud;
    }
    
    public void setCfgInstitucionesdesalud(int cfgInstitucionesdesalud) {
        this.cfgInstitucionesdesalud = cfgInstitucionesdesalud;
    }
    public Date getDfFechaorden() {
        return this.dfFechaorden;
    }
    
    public void setDfFechaorden(Date dfFechaorden) {
        this.dfFechaorden = dfFechaorden;
    }
    public Short getDfIdprevision() {
        return this.dfIdprevision;
    }
    
    public void setDfIdprevision(Short dfIdprevision) {
        this.dfIdprevision = dfIdprevision;
    }
    public Integer getDfIdmedico() {
        return this.dfIdmedico;
    }
    
    public void setDfIdmedico(Integer dfIdmedico) {

        this.dfIdmedico = dfIdmedico;
    }
    
    
    public String getDfCodigolocalizacion() {
        return this.dfCodigolocalizacion;
    }
    
    public void setDfCodigolocalizacion(String dfCodigolocalizacion) {
        this.dfCodigolocalizacion = dfCodigolocalizacion;
    }
    public String getDfObservacion() {
        return this.dfObservacion;
    }
    
    public void setDfObservacion(String dfObservacion) {
        this.dfObservacion = dfObservacion;
    }
    public String getDfHost() {
        return this.dfHost;
    }
    
    public void setDfHost(String dfHost) {
        this.dfHost = dfHost;
    }
    public String getDfEnviarresultadosemail() {
        return this.dfEnviarresultadosemail;
    }
    
    public void setDfEnviarresultadosemail(String dfEnviarresultadosemail) {
        this.dfEnviarresultadosemail = dfEnviarresultadosemail;
    }
    public String getDfTmclick() {
        return this.dfTmclick;
    }
    
    public void setDfTmclick(String dfTmclick) {
        this.dfTmclick = dfTmclick;
    }

	@Override
	public String toString() {
		return "DatosFichas [dfNorden=" + dfNorden + ", datosPacientes=" + datosPacientes + ", cfgServicios="
				+ cfgServicios + ", cfgDiagnosticos=" + cfgDiagnosticos + ", cfgConvenios=" + cfgConvenios
				+ ", cfgProcedencias=" + cfgProcedencias + ", ldvFichasestadostm=" + ldvFichasestadostm
				+ ", cfgPrioridadatencion=" + cfgPrioridadatencion + ", cfgTipoatencion=" + cfgTipoatencion
				+ ", cfgInstitucionesdesalud=" + cfgInstitucionesdesalud + ", dfFechaorden=" + dfFechaorden
				+ ", dfIdprevision=" + dfIdprevision + ", dfIdmedico=" + dfIdmedico + ", dfCodigolocalizacion="
				+ dfCodigolocalizacion + ", dfObservacion=" + dfObservacion + ", dfHost=" + dfHost
				+ ", dfEnviarresultadosemail=" + dfEnviarresultadosemail + ", dfTmclick=" + dfTmclick + "]";
	}

	public Integer getCfgLocalizaciones() {
		return cfgLocalizaciones;
	}

	public void setCfgLocalizaciones(Integer cfgLocalizaciones) {
		this.cfgLocalizaciones = cfgLocalizaciones;
	}
    
    

}


