package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * DatosFichasexamenesId generated by hbm2java
 */
public class DatosFichasexamenesId implements java.io.Serializable {

	private long dfeNorden;
	private long dfeIdexamen;

	public DatosFichasexamenesId() {
	}

	public DatosFichasexamenesId(long dfeNorden, long dfeIdexamen) {
        this.dfeNorden = dfeNorden;
        this.dfeIdexamen = dfeIdexamen;
    }

	public long getDfeNorden() {
		return this.dfeNorden;
	}

	public void setDfeNorden(long dfeNorden) {
		this.dfeNorden = dfeNorden;
	}

	public long getDfeIdexamen() {
		return this.dfeIdexamen;
	}

	public void setDfeIdexamen(long dfeIdexamen) {
		this.dfeIdexamen = dfeIdexamen;
	}

        @Override
        public String toString() {
            return "DatosFichasexamenesId{" + "dfeNorden=" + dfeNorden + ", dfeIdexamen=" + dfeIdexamen + '}';
        }

}
