package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DatosFichasexamenesmicroorg generated by hbm2java
 */
public class DatosFichasexamenesmicroorgold implements java.io.Serializable {

	private DatosFichasexamenesId id;
	private CfgBacmicroorganismos cfgBacmicroorganismos;
	private CfgBacrecuentocolonias cfgBacrecuentocolonias;
	private DatosFichasexamenes datosFichasexamenes;
	private Date dfemoFechaorden;
	private Byte dfemoCantidadmicroorg;
	private Byte dfemoIdbacantibiograma;
	private byte dfemoIdbacmarcadorderesistenc;
	private byte dfemoIdbactipoinfeccion;
	private String dfemoComentario;

	public DatosFichasexamenesmicroorgold() {
	}

	public CfgBacmicroorganismos getCfgBacmicroorganismos() {
		return this.cfgBacmicroorganismos;
	}

	public void setCfgBacmicroorganismos(CfgBacmicroorganismos cfgBacmicroorganismos) {
		this.cfgBacmicroorganismos = cfgBacmicroorganismos;
	}

	public CfgBacrecuentocolonias getCfgBacrecuentocolonias() {
		return this.cfgBacrecuentocolonias;
	}

	public void setCfgBacrecuentocolonias(CfgBacrecuentocolonias cfgBacrecuentocolonias) {
		this.cfgBacrecuentocolonias = cfgBacrecuentocolonias;
	}

	public DatosFichasexamenes getDatosFichasexamenes() {
		return this.datosFichasexamenes;
	}

	public void setDatosFichasexamenes(DatosFichasexamenes datosFichasexamenes) {
		this.datosFichasexamenes = datosFichasexamenes;
	}

	public Date getDfemoFechaorden() {
		return this.dfemoFechaorden;
	}

	public void setDfemoFechaorden(Date dfemoFechaorden) {
		this.dfemoFechaorden = dfemoFechaorden;
	}

	public Byte getDfemoCantidadmicroorg() {
		return this.dfemoCantidadmicroorg;
	}

	public void setDfemoCantidadmicroorg(Byte dfemoCantidadmicroorg) {
		this.dfemoCantidadmicroorg = dfemoCantidadmicroorg;
	}

	public Byte getDfemoIdbacantibiograma() {
		return this.dfemoIdbacantibiograma;
	}

	public void setDfemoIdbacantibiograma(Byte dfemoIdbacantibiograma) {
		this.dfemoIdbacantibiograma = dfemoIdbacantibiograma;
	}

	public byte getDfemoIdbacmarcadorderesistenc() {
		return this.dfemoIdbacmarcadorderesistenc;
	}

	public void setDfemoIdbacmarcadorderesistenc(byte dfemoIdbacmarcadorderesistenc) {
		this.dfemoIdbacmarcadorderesistenc = dfemoIdbacmarcadorderesistenc;
	}

	public byte getDfemoIdbactipoinfeccion() {
		return this.dfemoIdbactipoinfeccion;
	}

	public void setDfemoIdbactipoinfeccion(byte dfemoIdbactipoinfeccion) {
		this.dfemoIdbactipoinfeccion = dfemoIdbactipoinfeccion;
	}

	public String getDfemoComentario() {
		return this.dfemoComentario;
	}

	public void setDfemoComentario(String dfemoComentario) {
		this.dfemoComentario = dfemoComentario;
	}

	/**
	 * @return the id
	 */
	public DatosFichasexamenesId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(DatosFichasexamenesId id) {
		this.id = id;
	}

}
