package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * DatosFichasexamenespesquisas generated by hbm2java
 */
public class DatosFichasexamenespesquisas implements java.io.Serializable {

	private DatosFichasexamenesId id;
	private DatosFichasexamenes datosFichasexamenes;
	private Short dfepIdpesquisa;
	private Byte dfepIddato;
	private String dfepResultadocheck;
	private String dfepResultadotexto;

	public DatosFichasexamenespesquisas() {
	}

	public DatosFichasexamenes getDatosFichasexamenes() {
		return this.datosFichasexamenes;
	}

	public void setDatosFichasexamenes(DatosFichasexamenes datosFichasexamenes) {
		this.datosFichasexamenes = datosFichasexamenes;
	}

	public Short getDfepIdpesquisa() {
		return this.dfepIdpesquisa;
	}

	public void setDfepIdpesquisa(Short dfepIdpesquisa) {
		this.dfepIdpesquisa = dfepIdpesquisa;
	}

	public Byte getDfepIddato() {
		return this.dfepIddato;
	}

	public void setDfepIddato(Byte dfepIddato) {
		this.dfepIddato = dfepIddato;
	}

	public String getDfepResultadocheck() {
		return this.dfepResultadocheck;
	}

	public void setDfepResultadocheck(String dfepResultadocheck) {
		this.dfepResultadocheck = dfepResultadocheck;
	}

	public String getDfepResultadotexto() {
		return this.dfepResultadotexto;
	}

	public void setDfepResultadotexto(String dfepResultadotexto) {
		this.dfepResultadotexto = dfepResultadotexto;
	}

	/**
	 * @return the id
	 */
	public DatosFichasexamenesId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(DatosFichasexamenesId id) {
		this.id = id;
	}

}
