package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.sql.Blob;

/**
 * DatosFichasdocumentos generated by hbm2java
 */
public class DatosFichasdocumentos  implements java.io.Serializable {

    @JsonInclude(value = JsonInclude.Include.NON_NULL)
     private long dfdIddocumentoficha;
     @JsonIgnore
     private DatosFichas datosFichas;
     private LdvTiposdocumentosanexos ldvTiposdocumentosanexos;
     @JsonIgnore
     private LdvTiposarchivos ldvTiposarchivos;
     private String dfdNota;
     private Blob dfdDocumento;

    public DatosFichasdocumentos() {
    }

	
    public DatosFichasdocumentos(long dfdIddocumentoficha, DatosFichas datosFichas) {
        this.dfdIddocumentoficha = dfdIddocumentoficha;
        this.datosFichas = datosFichas;
    }
    public DatosFichasdocumentos(long dfdIddocumentoficha, DatosFichas datosFichas, LdvTiposdocumentosanexos ldvTiposdocumentosanexos, LdvTiposarchivos ldvTiposarchivos, String dfdNota, Blob dfdDocumento) {
       this.dfdIddocumentoficha = dfdIddocumentoficha;
       this.datosFichas = datosFichas;
       this.ldvTiposdocumentosanexos = ldvTiposdocumentosanexos;
       this.ldvTiposarchivos = ldvTiposarchivos;
       this.dfdNota = dfdNota;
       this.dfdDocumento = dfdDocumento;
    }
   
    public long getDfdIddocumentoficha() {
        return this.dfdIddocumentoficha;
    }
    
    public void setDfdIddocumentoficha(long dfdIddocumentoficha) {
        this.dfdIddocumentoficha = dfdIddocumentoficha;
    }
    public DatosFichas getDatosFichas() {
        return this.datosFichas;
    }
    
    public void setDatosFichas(DatosFichas datosFichas) {
        this.datosFichas = datosFichas;
    }
    public LdvTiposdocumentosanexos getLdvTiposdocumentosanexos() {
        return this.ldvTiposdocumentosanexos;
    }
    
    public void setLdvTiposdocumentosanexos(LdvTiposdocumentosanexos ldvTiposdocumentosanexos) {
        this.ldvTiposdocumentosanexos = ldvTiposdocumentosanexos;
    }
    public LdvTiposarchivos getLdvTiposarchivos() {
        return this.ldvTiposarchivos;
    }
    
    public void setLdvTiposarchivos(LdvTiposarchivos ldvTiposarchivos) {
        this.ldvTiposarchivos = ldvTiposarchivos;
    }
    public String getDfdNota() {
        return this.dfdNota;
    }
    
    public void setDfdNota(String dfdNota) {
        this.dfdNota = dfdNota;
    }
    public Blob getDfdDocumento() {
        return this.dfdDocumento;
    }
    
    public void setDfdDocumento(Blob dfdDocumento) {
        this.dfdDocumento = dfdDocumento;
    }




}


