package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * DatosFichasexamenesantibiog generated by hbm2java
 */
public class DatosFichasexamenesantibiog  implements java.io.Serializable {


     private DatosFichasexamenesantibiogId id;
     private long dfeaIdpaciente;
     private Byte dfeaNromicroorganismo;
     private Byte dfeaIdmicroorganismo;
     private Byte dfeaIdantibiograma;
     private Short dfeaIdantibiotico;
     private String dfeaCmi;
     private Short dfeaDiametromilimetros;
     private String dfeaInterpretacion;

    public DatosFichasexamenesantibiog() {
    }

	
    public DatosFichasexamenesantibiog(DatosFichasexamenesantibiogId id, long dfeaIdpaciente) {
        this.id = id;
        this.dfeaIdpaciente = dfeaIdpaciente;
    }
    public DatosFichasexamenesantibiog(DatosFichasexamenesantibiogId id, long dfeaIdpaciente, Byte dfeaNromicroorganismo, Byte dfeaIdmicroorganismo, Byte dfeaIdantibiograma, Short dfeaIdantibiotico, String dfeaCmi, Short dfeaDiametromilimetros, String dfeaInterpretacion) {
       this.id = id;
       this.dfeaIdpaciente = dfeaIdpaciente;
       this.dfeaNromicroorganismo = dfeaNromicroorganismo;
       this.dfeaIdmicroorganismo = dfeaIdmicroorganismo;
       this.dfeaIdantibiograma = dfeaIdantibiograma;
       this.dfeaIdantibiotico = dfeaIdantibiotico;
       this.dfeaCmi = dfeaCmi;
       this.dfeaDiametromilimetros = dfeaDiametromilimetros;
       this.dfeaInterpretacion = dfeaInterpretacion;
    }
   
    public DatosFichasexamenesantibiogId getId() {
        return this.id;
    }
    
    public void setId(DatosFichasexamenesantibiogId id) {
        this.id = id;
    }
    public long getDfeaIdpaciente() {
        return this.dfeaIdpaciente;
    }
    
    public void setDfeaIdpaciente(long dfeaIdpaciente) {
        this.dfeaIdpaciente = dfeaIdpaciente;
    }
    public Byte getDfeaNromicroorganismo() {
        return this.dfeaNromicroorganismo;
    }
    
    public void setDfeaNromicroorganismo(Byte dfeaNromicroorganismo) {
        this.dfeaNromicroorganismo = dfeaNromicroorganismo;
    }
    public Byte getDfeaIdmicroorganismo() {
        return this.dfeaIdmicroorganismo;
    }
    
    public void setDfeaIdmicroorganismo(Byte dfeaIdmicroorganismo) {
        this.dfeaIdmicroorganismo = dfeaIdmicroorganismo;
    }
    public Byte getDfeaIdantibiograma() {
        return this.dfeaIdantibiograma;
    }
    
    public void setDfeaIdantibiograma(Byte dfeaIdantibiograma) {
        this.dfeaIdantibiograma = dfeaIdantibiograma;
    }
    public Short getDfeaIdantibiotico() {
        return this.dfeaIdantibiotico;
    }
    
    public void setDfeaIdantibiotico(Short dfeaIdantibiotico) {
        this.dfeaIdantibiotico = dfeaIdantibiotico;
    }
    public String getDfeaCmi() {
        return this.dfeaCmi;
    }
    
    public void setDfeaCmi(String dfeaCmi) {
        this.dfeaCmi = dfeaCmi;
    }
    public Short getDfeaDiametromilimetros() {
        return this.dfeaDiametromilimetros;
    }
    
    public void setDfeaDiametromilimetros(Short dfeaDiametromilimetros) {
        this.dfeaDiametromilimetros = dfeaDiametromilimetros;
    }
    public String getDfeaInterpretacion() {
        return this.dfeaInterpretacion;
    }
    
    public void setDfeaInterpretacion(String dfeaInterpretacion) {
        this.dfeaInterpretacion = dfeaInterpretacion;
    }




}


