package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.sql.Blob;

/**
 * DatosFichasexamenesarchivos generated by hbm2java
 */
public class DatosFichasexamenesarchivos implements java.io.Serializable {

  private long dfeaIdfichaexamenarchivo;
  private DatosFichasexamenes datosFichasexamenes;
  private LdvTiposarchivos ldvTiposarchivos;
  private long dfeaIdpaciente;
  private Blob dfeaDocumento;
  private String dfeaDescripcion;

  public DatosFichasexamenesarchivos() {
  }

  public DatosFichasexamenesarchivos(long dfeaIdfichaexamenarchivo, DatosFichasexamenes datosFichasexamenes,
      LdvTiposarchivos ldvTiposarchivos, long dfeaIdpaciente) {
    this.dfeaIdfichaexamenarchivo = dfeaIdfichaexamenarchivo;
    this.datosFichasexamenes = datosFichasexamenes;
    this.ldvTiposarchivos = ldvTiposarchivos;
    this.dfeaIdpaciente = dfeaIdpaciente;
  }

  public DatosFichasexamenesarchivos(long dfeaIdfichaexamenarchivo, DatosFichasexamenes datosFichasexamenes,
      LdvTiposarchivos ldvTiposarchivos, long dfeaIdpaciente, Blob dfeaDocumento, String dfeaDescripcion) {
    this.dfeaIdfichaexamenarchivo = dfeaIdfichaexamenarchivo;
    this.datosFichasexamenes = datosFichasexamenes;
    this.ldvTiposarchivos = ldvTiposarchivos;
    this.dfeaIdpaciente = dfeaIdpaciente;
    this.dfeaDocumento = dfeaDocumento;
    this.dfeaDescripcion = dfeaDescripcion;
  }

  public long getDfeaIdfichaexamenarchivo() {
    return this.dfeaIdfichaexamenarchivo;
  }

  public void setDfeaIdfichaexamenarchivo(long dfeaIdfichaexamenarchivo) {
    this.dfeaIdfichaexamenarchivo = dfeaIdfichaexamenarchivo;
  }

  public DatosFichasexamenes getDatosFichasexamenes() {
    return this.datosFichasexamenes;
  }

  public void setDatosFichasexamenes(DatosFichasexamenes datosFichasexamenes) {
    this.datosFichasexamenes = datosFichasexamenes;
  }

  public LdvTiposarchivos getLdvTiposarchivos() {
    return this.ldvTiposarchivos;
  }

  public void setLdvTiposarchivos(LdvTiposarchivos ldvTiposarchivos) {
    this.ldvTiposarchivos = ldvTiposarchivos;
  }

  public long getDfeaIdpaciente() {
    return this.dfeaIdpaciente;
  }

  public void setDfeaIdpaciente(long dfeaIdpaciente) {
    this.dfeaIdpaciente = dfeaIdpaciente;
  }

  public Blob getDfeaDocumento() {
    return this.dfeaDocumento;
  }

  public void setDfeaDocumento(Blob dfeaDocumento) {
    this.dfeaDocumento = dfeaDocumento;
  }

  public String getDfeaDescripcion() {
    return this.dfeaDescripcion;
  }

  public void setDfeaDescripcion(String dfeaDescripcion) {
    this.dfeaDescripcion = dfeaDescripcion;
  }

}
