package com.grupobios.bioslis.entity;




/**
 * LdvBacestadostest generated by hbm2java
 */
public class LdvBacestadostest  implements java.io.Serializable {


     private boolean ldvbetIdbacestadotest;
     private String ldvbetDescripcion;

    public LdvBacestadostest() {
    }

	
    public LdvBacestadostest(boolean ldvbetIdbacestadotest) {
        this.ldvbetIdbacestadotest = ldvbetIdbacestadotest;
    }
    public LdvBacestadostest(boolean ldvbetIdbacestadotest, String ldvbetDescripcion) {
       this.ldvbetIdbacestadotest = ldvbetIdbacestadotest;
       this.ldvbetDescripcion = ldvbetDescripcion;
    }
   
    public boolean isLdvbetIdbacestadotest() {
        return this.ldvbetIdbacestadotest;
    }
    
    public void setLdvbetIdbacestadotest(boolean ldvbetIdbacestadotest) {
        this.ldvbetIdbacestadotest = ldvbetIdbacestadotest;
    }
    public String getLdvbetDescripcion() {
        return this.ldvbetDescripcion;
    }
    
    public void setLdvbetDescripcion(String ldvbetDescripcion) {
        this.ldvbetDescripcion = ldvbetDescripcion;
    }




}


