package com.grupobios.bioslis.entity;


// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * LdvBacantibioticosclases generated by hbm2java
 */
public class LdvBacantibioticosclases  implements java.io.Serializable {


     private byte ldvacIdantibioticoclase;
     private String ldvacDescripcion;

    public LdvBacantibioticosclases() {
    }

	
    public LdvBacantibioticosclases(byte ldvacIdantibioticoclase) {
        this.ldvacIdantibioticoclase = ldvacIdantibioticoclase;
    }
    public LdvBacantibioticosclases(byte ldvacIdantibioticoclase, String ldvacDescripcion) {
       this.ldvacIdantibioticoclase = ldvacIdantibioticoclase;
       this.ldvacDescripcion = ldvacDescripcion;
    }
   
    public byte getLdvacIdantibioticoclase() {
        return this.ldvacIdantibioticoclase;
    }
    
    public void setLdvacIdantibioticoclase(byte ldvacIdantibioticoclase) {
        this.ldvacIdantibioticoclase = ldvacIdantibioticoclase;
    }
    public String getLdvacDescripcion() {
        return this.ldvacDescripcion;
    }
    
    public void setLdvacDescripcion(String ldvacDescripcion) {
        this.ldvacDescripcion = ldvacDescripcion;
    }




}


