package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * LdvCargosusuarios generated by hbm2java
 */
public class LdvCargosusuarios  implements java.io.Serializable {


     private short ldvcuIdcargo;
     private String ldvcuDescripcion;
     @JsonIgnore
     private Set datosUsuarioses = new HashSet(0);

    public LdvCargosusuarios() {
    }

	
    public LdvCargosusuarios(short ldvcuIdcargo) {
        this.ldvcuIdcargo = ldvcuIdcargo;
    }
    public LdvCargosusuarios(short ldvcuIdcargo, String ldvcuDescripcion, Set datosUsuarioses) {
       this.ldvcuIdcargo = ldvcuIdcargo;
       this.ldvcuDescripcion = ldvcuDescripcion;
       this.datosUsuarioses = datosUsuarioses;
    }
   
    public short getLdvcuIdcargo() {
        return this.ldvcuIdcargo;
    }
    
    public void setLdvcuIdcargo(short ldvcuIdcargo) {
        this.ldvcuIdcargo = ldvcuIdcargo;
    }
    public String getLdvcuDescripcion() {
        return this.ldvcuDescripcion;
    }
    
    public void setLdvcuDescripcion(String ldvcuDescripcion) {
        this.ldvcuDescripcion = ldvcuDescripcion;
    }
    public Set getDatosUsuarioses() {
        return this.datosUsuarioses;
    }
    
    public void setDatosUsuarioses(Set datosUsuarioses) {
        this.datosUsuarioses = datosUsuarioses;
    }




}


