package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * LdvContactospacientesrelacion generated by hbm2java
 */
public class LdvContactospacientesrelacion implements java.io.Serializable {

  private int ldvcprIdcontactopacienterel;
  private String ldvcprDescripcion;
 @JsonIgnore
 private Set datosContactoses = new HashSet(0);

  public LdvContactospacientesrelacion() {     
  }

  public LdvContactospacientesrelacion(int ldvcprIdcontactopacienterel) {
    this.ldvcprIdcontactopacienterel = ldvcprIdcontactopacienterel;
  }

  public LdvContactospacientesrelacion(int ldvcprIdcontactopacienterel, String ldvcprDescripcion,
      Set datosContactoses) {
    this.ldvcprIdcontactopacienterel = ldvcprIdcontactopacienterel;
    this.ldvcprDescripcion = ldvcprDescripcion;
   this.datosContactoses = datosContactoses;
  }

  public int getLdvcprIdcontactopacienterel() {
    return this.ldvcprIdcontactopacienterel;
  }

  public void setLdvcprIdcontactopacienterel(int ldvcprIdcontactopacienterel) {
    this.ldvcprIdcontactopacienterel = ldvcprIdcontactopacienterel;
  }

  public String getLdvcprDescripcion() {
    return this.ldvcprDescripcion;
  }

  public void setLdvcprDescripcion(String ldvcprDescripcion) {
    this.ldvcprDescripcion = ldvcprDescripcion;
  }

  public Set getDatosContactoses() {
    return this.datosContactoses;
  }

  public void setDatosContactoses(Set datosContactoses) {
    this.datosContactoses = datosContactoses;
  }

@Override
public String toString() {
    return "LdvContactospacientesrelacion [ldvcprIdcontactopacienterel=" + ldvcprIdcontactopacienterel
            + ", ldvcprDescripcion=" + ldvcprDescripcion + " ]";
}




}
