package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * LdvEstadosciviles generated by hbm2java
 */
public class LdvEstadosciviles  implements java.io.Serializable {


     private int ldvecIdestadocivil;
     private String ldvecDescripcion;

    public LdvEstadosciviles() {
    }

    public LdvEstadosciviles(int ldvecIdestadocivil, String ldvecDescripcion) {
       this.ldvecIdestadocivil = ldvecIdestadocivil;
       this.ldvecDescripcion = ldvecDescripcion;
    }
   
    public int getLdvecIdestadocivil() {
        return this.ldvecIdestadocivil;
    }
    
    public void setLdvecIdestadocivil(int ldvecIdestadocivil) {
        this.ldvecIdestadocivil = ldvecIdestadocivil;
    }
    public String getLdvecDescripcion() {
        return this.ldvecDescripcion;
    }
    
    public void setLdvecDescripcion(String ldvecDescripcion) {
        this.ldvecDescripcion = ldvecDescripcion;
    }




}


