package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * LdvEspecialidadesmedicas generated by hbm2java
 */
public class LdvEspecialidadesmedicas  implements java.io.Serializable {


     private int ldvemIdespecialidadmedica;
     private String ldvemDescripcion;

    public LdvEspecialidadesmedicas() {
    }

	
    public LdvEspecialidadesmedicas(int ldvemIdespecialidadmedica) {
        this.ldvemIdespecialidadmedica = ldvemIdespecialidadmedica;
    }
    public LdvEspecialidadesmedicas(int ldvemIdespecialidadmedica, String ldvemDescripcion) {
       this.ldvemIdespecialidadmedica = ldvemIdespecialidadmedica;
       this.ldvemDescripcion = ldvemDescripcion;
    }
   
    public int getLdvemIdespecialidadmedica() {
        return this.ldvemIdespecialidadmedica;
    }
    
    public void setLdvemIdespecialidadmedica(int ldvemIdespecialidadmedica) {
        this.ldvemIdespecialidadmedica = ldvemIdespecialidadmedica;
    }
    public String getLdvemDescripcion() {
        return this.ldvemDescripcion;
    }
    
    public void setLdvemDescripcion(String ldvemDescripcion) {
        this.ldvemDescripcion = ldvemDescripcion;
    }




}


