package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * LdvFormatosimagenes generated by hbm2java
 */
public class LdvFormatosimagenes  implements java.io.Serializable {


     private byte ldvfiIdformatoimagen;
     private String ldvfiDescripcion;

    public LdvFormatosimagenes() {
    }

    public LdvFormatosimagenes(byte ldvfiIdformatoimagen, String ldvfiDescripcion) {
       this.ldvfiIdformatoimagen = ldvfiIdformatoimagen;
       this.ldvfiDescripcion = ldvfiDescripcion;
    }
   
    public byte getLdvfiIdformatoimagen() {
        return this.ldvfiIdformatoimagen;
    }
    
    public void setLdvfiIdformatoimagen(byte ldvfiIdformatoimagen) {
        this.ldvfiIdformatoimagen = ldvfiIdformatoimagen;
    }
    public String getLdvfiDescripcion() {
        return this.ldvfiDescripcion;
    }
    
    public void setLdvfiDescripcion(String ldvfiDescripcion) {
        this.ldvfiDescripcion = ldvfiDescripcion;
    }




}


