package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * LdvFichasestadostm generated by hbm2java
 */
public class LdvFichasestadostm  implements java.io.Serializable {


     private byte ldvfetIdfichaestadotm;
     private String ldvfetDescripcion;
     @JsonIgnore
     private Set datosFichases = new HashSet(0);

    public LdvFichasestadostm() {
    }

	
    public LdvFichasestadostm(byte ldvfetIdfichaestadotm) {
        this.ldvfetIdfichaestadotm = ldvfetIdfichaestadotm;
    }
    public LdvFichasestadostm(byte ldvfetIdfichaestadotm, String ldvfetDescripcion, Set datosFichases) {
       this.ldvfetIdfichaestadotm = ldvfetIdfichaestadotm;
       this.ldvfetDescripcion = ldvfetDescripcion;
       this.datosFichases = datosFichases;
    }
   
    public byte getLdvfetIdfichaestadotm() {
        return this.ldvfetIdfichaestadotm;
    }
    
    public void setLdvfetIdfichaestadotm(byte ldvfetIdfichaestadotm) {
        this.ldvfetIdfichaestadotm = ldvfetIdfichaestadotm;
    }
    public String getLdvfetDescripcion() {
        return this.ldvfetDescripcion;
    }
    
    public void setLdvfetDescripcion(String ldvfetDescripcion) {
        this.ldvfetDescripcion = ldvfetDescripcion;
    }
    public Set getDatosFichases() {
        return this.datosFichases;
    }
    
    public void setDatosFichases(Set datosFichases) {
        this.datosFichases = datosFichases;
    }




}


