package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * LdvGruposexamenes generated by hbm2java
 */
public class LdvGruposexamenes  implements java.io.Serializable {


     private Long ldvgeIdgrupoexamen;
     private String ldvgeDescripcion;
     @JsonIgnore
     private Set cfgExameneses = new HashSet(0);

    public LdvGruposexamenes() {
    }

	
    public LdvGruposexamenes(Long ldvgeIdgrupoexamen) {
        this.ldvgeIdgrupoexamen = ldvgeIdgrupoexamen;
    }
    public LdvGruposexamenes(Long ldvgeIdgrupoexamen, String ldvgeDescripcion, Set cfgExameneses) {
       this.ldvgeIdgrupoexamen = ldvgeIdgrupoexamen;
       this.ldvgeDescripcion = ldvgeDescripcion;
       this.cfgExameneses = cfgExameneses;
    }
   
    public Long getLdvgeIdgrupoexamen() {
        return this.ldvgeIdgrupoexamen;
    }
    
    public void setLdvgeIdgrupoexamen(Long ldvgeIdgrupoexamen) {
        this.ldvgeIdgrupoexamen = ldvgeIdgrupoexamen;
    }
    public String getLdvgeDescripcion() {
        return this.ldvgeDescripcion;
    }
    
    public void setLdvgeDescripcion(String ldvgeDescripcion) {
        this.ldvgeDescripcion = ldvgeDescripcion;
    }
    public Set getCfgExameneses() {
        return this.cfgExameneses;
    }
    
    public void setCfgExameneses(Set cfgExameneses) {
        this.cfgExameneses = cfgExameneses;
    }


	@Override
	public String toString() {
		return "LdvGruposexamenes [ldvgeIdgrupoexamen=" + ldvgeIdgrupoexamen + ", ldvgeDescripcion=" + ldvgeDescripcion
				+ "]";
	}




}


