package com.grupobios.bioslis.entity;
// Generated 17-10-2022 22:44:33 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * LdvOperacionesmath generated by hbm2java
 */
public class LdvOperacionesmath  implements java.io.Serializable {


     private byte ldvomIdoperadormath;
     private String ldvomDescripcion;
     @JsonIgnore
     private Set sigmaProcesotestconversions = new HashSet(0);

    public LdvOperacionesmath() {
    }

	
    public LdvOperacionesmath(byte ldvomIdoperadormath, String ldvomDescripcion) {
        this.ldvomIdoperadormath = ldvomIdoperadormath;
        this.ldvomDescripcion = ldvomDescripcion;
    }
    public LdvOperacionesmath(byte ldvomIdoperadormath, String ldvomDescripcion, Set sigmaProcesotestconversions) {
       this.ldvomIdoperadormath = ldvomIdoperadormath;
       this.ldvomDescripcion = ldvomDescripcion;
       this.sigmaProcesotestconversions = sigmaProcesotestconversions;
    }
   
    public byte getLdvomIdoperadormath() {
        return this.ldvomIdoperadormath;
    }
    
    public void setLdvomIdoperadormath(byte ldvomIdoperadormath) {
        this.ldvomIdoperadormath = ldvomIdoperadormath;
    }
    public String getLdvomDescripcion() {
        return this.ldvomDescripcion;
    }
    
    public void setLdvomDescripcion(String ldvomDescripcion) {
        this.ldvomDescripcion = ldvomDescripcion;
    }
    public Set getSigmaProcesotestconversions() {
        return this.sigmaProcesotestconversions;
    }
    
    public void setSigmaProcesotestconversions(Set sigmaProcesotestconversions) {
        this.sigmaProcesotestconversions = sigmaProcesotestconversions;
    }




}


