package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

/**
 * LdvPatologias generated by hbm2java
 */
public class LdvPatologias implements java.io.Serializable {

  private int ldvpatIdpatologia;
  private String ldvpatDescripcion;

  public LdvPatologias() {
  }

  public LdvPatologias(int ldvpatIdpatologia, String ldvpatDescripcion) {
    this.ldvpatIdpatologia = ldvpatIdpatologia;
    this.ldvpatDescripcion = ldvpatDescripcion;
  }

  public int getLdvpatIdpatologia() {
    return this.ldvpatIdpatologia;
  }

  public void setLdvpatIdpatologia(int ldvpatIdpatologia) {
    this.ldvpatIdpatologia = ldvpatIdpatologia;
  }

  public String getLdvpatDescripcion() {
    return this.ldvpatDescripcion;
  }

  public void setLdvpatDescripcion(String ldvpatDescripcion) {
    this.ldvpatDescripcion = ldvpatDescripcion;
  }

@Override
public String toString() {
    return "LdvPatologias [ldvpatIdpatologia=" + ldvpatIdpatologia + ", ldvpatDescripcion=" + ldvpatDescripcion + "]";
}

}
