package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * LdvPaises generated by hbm2java
 */
public class LdvPaises  implements java.io.Serializable {


     private int ldvpIdpais;
     private String ldvpDescripcion;

    public LdvPaises() {
    }

    public LdvPaises(int ldvpIdpais, String ldvpDescripcion) {
       this.ldvpIdpais = ldvpIdpais;
       this.ldvpDescripcion = ldvpDescripcion;
    }
   
    public int getLdvpIdpais() {
        return this.ldvpIdpais;
    }
    
    public void setLdvpIdpais(int ldvpIdpais) {
        this.ldvpIdpais = ldvpIdpais;
    }
    public String getLdvpDescripcion() {
        return this.ldvpDescripcion;
    }
    
    public void setLdvpDescripcion(String ldvpDescripcion) {
        this.ldvpDescripcion = ldvpDescripcion;
    }




}


