package com.grupobios.bioslis.entity;
// Generated 17-10-2022 22:44:33 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * LdvTipocomunicacion generated by hbm2java
 */
public class LdvTipocomunicacion  implements java.io.Serializable {


     private byte ldvtcIdtipocomunicacion;
     private String ldvtcDescripcion;
     @JsonIgnore
     private Set sigmaProcesoses = new HashSet(0);

    public LdvTipocomunicacion() {
    }

	
    public LdvTipocomunicacion(byte ldvtcIdtipocomunicacion) {
        this.ldvtcIdtipocomunicacion = ldvtcIdtipocomunicacion;
    }
    public LdvTipocomunicacion(byte ldvtcIdtipocomunicacion, String ldvtcDescripcion, Set sigmaProcesoses) {
       this.ldvtcIdtipocomunicacion = ldvtcIdtipocomunicacion;
       this.ldvtcDescripcion = ldvtcDescripcion;
       this.sigmaProcesoses = sigmaProcesoses;
    }
   
    public byte getLdvtcIdtipocomunicacion() {
        return this.ldvtcIdtipocomunicacion;
    }
    
    public void setLdvtcIdtipocomunicacion(byte ldvtcIdtipocomunicacion) {
        this.ldvtcIdtipocomunicacion = ldvtcIdtipocomunicacion;
    }
    public String getLdvtcDescripcion() {
        return this.ldvtcDescripcion;
    }
    
    public void setLdvtcDescripcion(String ldvtcDescripcion) {
        this.ldvtcDescripcion = ldvtcDescripcion;
    }
    public Set getSigmaProcesoses() {
        return this.sigmaProcesoses;
    }
    
    public void setSigmaProcesoses(Set sigmaProcesoses) {
        this.sigmaProcesoses = sigmaProcesoses;
    }




}


