package com.grupobios.bioslis.entity;
// Generated 17-10-2022 22:44:33 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * LdvTiposcondicion generated by hbm2java
 */
public class LdvTiposcondicion  implements java.io.Serializable {


     private byte ldvtcondIdtipocondicion;
     private String ldvtcondDescripcion;
     @JsonIgnore
     private Set sigmaProcesotestconversions = new HashSet(0);

    public LdvTiposcondicion() {
    }

	
    public LdvTiposcondicion(byte ldvtcondIdtipocondicion) {
        this.ldvtcondIdtipocondicion = ldvtcondIdtipocondicion;
    }
    public LdvTiposcondicion(byte ldvtcondIdtipocondicion, String ldvtcondDescripcion, Set sigmaProcesotestconversions) {
       this.ldvtcondIdtipocondicion = ldvtcondIdtipocondicion;
       this.ldvtcondDescripcion = ldvtcondDescripcion;
       this.sigmaProcesotestconversions = sigmaProcesotestconversions;
    }
   
    public byte getLdvtcondIdtipocondicion() {
        return this.ldvtcondIdtipocondicion;
    }
    
    public void setLdvtcondIdtipocondicion(byte ldvtcondIdtipocondicion) {
        this.ldvtcondIdtipocondicion = ldvtcondIdtipocondicion;
    }
    public String getLdvtcondDescripcion() {
        return this.ldvtcondDescripcion;
    }
    
    public void setLdvtcondDescripcion(String ldvtcondDescripcion) {
        this.ldvtcondDescripcion = ldvtcondDescripcion;
    }
    public Set getSigmaProcesotestconversions() {
        return this.sigmaProcesotestconversions;
    }
    
    public void setSigmaProcesotestconversions(Set sigmaProcesotestconversions) {
        this.sigmaProcesotestconversions = sigmaProcesotestconversions;
    }




}


