package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LdvTiposdatospesquisas generated by hbm2java
 */
public class LdvTiposdatospesquisas  implements java.io.Serializable {


     private boolean ldvtdpIdtipodatopesquisa;
     private String ldvtdpDescripcion;
     private Set cfgPesquisasformatoses = new HashSet(0);

    public LdvTiposdatospesquisas() {
    }

	
    public LdvTiposdatospesquisas(boolean ldvtdpIdtipodatopesquisa) {
        this.ldvtdpIdtipodatopesquisa = ldvtdpIdtipodatopesquisa;
    }
    public LdvTiposdatospesquisas(boolean ldvtdpIdtipodatopesquisa, String ldvtdpDescripcion, Set cfgPesquisasformatoses) {
       this.ldvtdpIdtipodatopesquisa = ldvtdpIdtipodatopesquisa;
       this.ldvtdpDescripcion = ldvtdpDescripcion;
       this.cfgPesquisasformatoses = cfgPesquisasformatoses;
    }
   
    public boolean isLdvtdpIdtipodatopesquisa() {
        return this.ldvtdpIdtipodatopesquisa;
    }
    
    public void setLdvtdpIdtipodatopesquisa(boolean ldvtdpIdtipodatopesquisa) {
        this.ldvtdpIdtipodatopesquisa = ldvtdpIdtipodatopesquisa;
    }
    public String getLdvtdpDescripcion() {
        return this.ldvtdpDescripcion;
    }
    
    public void setLdvtdpDescripcion(String ldvtdpDescripcion) {
        this.ldvtdpDescripcion = ldvtdpDescripcion;
    }
    public Set getCfgPesquisasformatoses() {
        return this.cfgPesquisasformatoses;
    }
    
    public void setCfgPesquisasformatoses(Set cfgPesquisasformatoses) {
        this.cfgPesquisasformatoses = cfgPesquisasformatoses;
    }




}


