package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * LdvTiposdocumentosanexos generated by hbm2java
 */
public class LdvTiposdocumentosanexos  implements java.io.Serializable {


     private byte ldvtdaIdtipodocumentoanexo;
     private String ldvtdaDescripcion;
     @JsonIgnore
     private Set datosFichasdocumentoses = new HashSet(0);

    public LdvTiposdocumentosanexos() {
    }

	
    public LdvTiposdocumentosanexos(byte ldvtdaIdtipodocumentoanexo) {
        this.ldvtdaIdtipodocumentoanexo = ldvtdaIdtipodocumentoanexo;
    }
    public LdvTiposdocumentosanexos(byte ldvtdaIdtipodocumentoanexo, String ldvtdaDescripcion, Set datosFichasdocumentoses) {
       this.ldvtdaIdtipodocumentoanexo = ldvtdaIdtipodocumentoanexo;
       this.ldvtdaDescripcion = ldvtdaDescripcion;
       this.datosFichasdocumentoses = datosFichasdocumentoses;
    }

    public byte getLdvtdaIdtipodocumentoanexo() {
        return ldvtdaIdtipodocumentoanexo;
    }

    public void setLdvtdaIdtipodocumentoanexo(byte ldvtdaIdtipodocumentoanexo) {
        this.ldvtdaIdtipodocumentoanexo = ldvtdaIdtipodocumentoanexo;
    }
   
    
    public String getLdvtdaDescripcion() {
        return this.ldvtdaDescripcion;
    }
    
    public void setLdvtdaDescripcion(String ldvtdaDescripcion) {
        this.ldvtdaDescripcion = ldvtdaDescripcion;
    }
    public Set getDatosFichasdocumentoses() {
        return this.datosFichasdocumentoses;
    }
    
    public void setDatosFichasdocumentoses(Set datosFichasdocumentoses) {
        this.datosFichasdocumentoses = datosFichasdocumentoses;
    }




}


