package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * LdvTiposexamenes generated by hbm2java
 */
public class LdvTiposexamenes  implements java.io.Serializable {


     private byte ldvteIdtipoexamen;
     private String ldvteDescripcion;
     @JsonIgnore
     private Set cfgExameneses = new HashSet(0);

    public LdvTiposexamenes() {
    }

	
    public LdvTiposexamenes(byte ldvteIdtipoexamen, String ldvteDescripcion) {
        this.ldvteIdtipoexamen = ldvteIdtipoexamen;
        this.ldvteDescripcion = ldvteDescripcion;
    }
    public LdvTiposexamenes(byte ldvteIdtipoexamen, String ldvteDescripcion, Set cfgExameneses) {
       this.ldvteIdtipoexamen = ldvteIdtipoexamen;
       this.ldvteDescripcion = ldvteDescripcion;
       this.cfgExameneses = cfgExameneses;
    }
   
    public byte getLdvteIdtipoexamen() {
        return this.ldvteIdtipoexamen;
    }
    
    public void setLdvteIdtipoexamen(byte ldvteIdtipoexamen) {
        this.ldvteIdtipoexamen = ldvteIdtipoexamen;
    }
    public String getLdvteDescripcion() {
        return this.ldvteDescripcion;
    }
    
    public void setLdvteDescripcion(String ldvteDescripcion) {
        this.ldvteDescripcion = ldvteDescripcion;
    }
    public Set getCfgExameneses() {
        return this.cfgExameneses;
    }
    
    public void setCfgExameneses(Set cfgExameneses) {
        this.cfgExameneses = cfgExameneses;
    }




}


