package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LdvTiposarchivos generated by hbm2java
 */
public class LdvTiposarchivos  implements java.io.Serializable {


     private byte ldvtaIdtipoarchivo;
     private String ldvtaDescripcion;
     private Set datosFichasdocumentoses = new HashSet(0);
     private Set datosFichasexamenesarchivoses = new HashSet(0);

    public LdvTiposarchivos() {
    }

	
    public LdvTiposarchivos(byte ldvtaIdtipoarchivo) {
        this.ldvtaIdtipoarchivo = ldvtaIdtipoarchivo;
    }
    public LdvTiposarchivos(byte ldvtaIdtipoarchivo, String ldvtaDescripcion, Set datosFichasdocumentoses, Set datosFichasexamenesarchivoses) {
       this.ldvtaIdtipoarchivo = ldvtaIdtipoarchivo;
       this.ldvtaDescripcion = ldvtaDescripcion;
       this.datosFichasdocumentoses = datosFichasdocumentoses;
       this.datosFichasexamenesarchivoses = datosFichasexamenesarchivoses;
    }
   
    public byte getLdvtaIdtipoarchivo() {
        return this.ldvtaIdtipoarchivo;
    }
    
    public void setLdvtaIdtipoarchivo(byte ldvtaIdtipoarchivo) {
        this.ldvtaIdtipoarchivo = ldvtaIdtipoarchivo;
    }
    public String getLdvtaDescripcion() {
        return this.ldvtaDescripcion;
    }
    
    public void setLdvtaDescripcion(String ldvtaDescripcion) {
        this.ldvtaDescripcion = ldvtaDescripcion;
    }
    public Set getDatosFichasdocumentoses() {
        return this.datosFichasdocumentoses;
    }
    
    public void setDatosFichasdocumentoses(Set datosFichasdocumentoses) {
        this.datosFichasdocumentoses = datosFichasdocumentoses;
    }
    public Set getDatosFichasexamenesarchivoses() {
        return this.datosFichasexamenesarchivoses;
    }
    
    public void setDatosFichasexamenesarchivoses(Set datosFichasexamenesarchivoses) {
        this.datosFichasexamenesarchivoses = datosFichasexamenesarchivoses;
    }




}


