package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * LogCfgtablas generated by hbm2java
 */
public class LogCfgtablas {

	private int lctIdlogcfg;
	private int cfgAccionesdatos;
	private String lctNombretabla;
	private String lctNombrecampo;
	private String lctValoranterior;
	private String lctValornuevo;
	private int lctIdusuario;
	private Date lctFechamodificacion;
	private String lctIpusuario;
	private String lctNombreequipo;
	private int lctIdtabla;
	private String lctDescripcion;

	public LogCfgtablas() {
	}

	public int getLctIdlogcfg() {
		return this.lctIdlogcfg;
	}

	public void setLctIdlogcfg(int lctIdlogcfg) {
		this.lctIdlogcfg = lctIdlogcfg;
	}

	public int getCfgAccionesdatos() {
		return this.cfgAccionesdatos;
	}

	public void setCfgAccionesdatos(int cfgAccionesdatos) {
		this.cfgAccionesdatos = cfgAccionesdatos;
	}

	public String getLctNombretabla() {
		return this.lctNombretabla;
	}

	public void setLctNombretabla(String lctNombretabla) {
		this.lctNombretabla = lctNombretabla;
	}

	public String getLctNombrecampo() {
		return this.lctNombrecampo;
	}

	public void setLctNombrecampo(String lctNombrecampo) {
		this.lctNombrecampo = lctNombrecampo;
	}

	public String getLctValoranterior() {
		return this.lctValoranterior;
	}

	public void setLctValoranterior(String lctValoranterior) {
		this.lctValoranterior = lctValoranterior;
	}

	public String getLctValornuevo() {
		return this.lctValornuevo;
	}

	public void setLctValornuevo(String lctValornuevo) {
		this.lctValornuevo = lctValornuevo;
	}

	public int getLctIdusuario() {
		return this.lctIdusuario;
	}

	public void setLctIdusuario(int lctIdusuario) {
		this.lctIdusuario = lctIdusuario;
	}

	public Date getLctFechamodificacion() {
		return this.lctFechamodificacion;
	}

	public void setLctFechamodificacion(Date lctFechamodificacion) {
		this.lctFechamodificacion = lctFechamodificacion;
	}

	public String getLctIpusuario() {
		return this.lctIpusuario;
	}

	public void setLctIpusuario(String lctIpusuario) {
		this.lctIpusuario = lctIpusuario;
	}

	public String getLctNombreequipo() {
		return this.lctNombreequipo;
	}

	public void setLctNombreequipo(String lctNombreequipo) {
		this.lctNombreequipo = lctNombreequipo;
	}

	public int getLctIdtabla() {
		return this.lctIdtabla;
	}

	public void setLctIdtabla(int lctIdtabla) {
		this.lctIdtabla = lctIdtabla;
	}

	
	
    public String getLctDescripcion() {
		return lctDescripcion;
	}

	public void setLctDescripcion(String lctDescripcion) {
		this.lctDescripcion = lctDescripcion;
	}

	@Override
    public String toString() {
        return "LogCfgtablas [lctIdlogcfg=" + lctIdlogcfg + ", cfgAccionesdatos=" + cfgAccionesdatos
                + ", lctNombretabla=" + lctNombretabla + ", lctNombrecampo=" + lctNombrecampo + ", lctValoranterior="
                + lctValoranterior + ", lctValornuevo=" + lctValornuevo + ", lctIdusuario=" + lctIdusuario
                + ", lctFechamodificacion=" + lctFechamodificacion + ", lctIpusuario=" + lctIpusuario
                + ", lctNombreequipo=" + lctNombreequipo + ", lctIdtabla=" + lctIdtabla + "]";
    }

}
