package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LogCfgbactablas generated by hbm2java
 */
public class LogCfgbactablas  implements java.io.Serializable {


     private long lcbtIdlogcfgbactabla;
     private String lcbtNombretabla;
     private String lcbtNombrecampo;
     private Boolean lcbtIdacciondato;
     private String lcbtValoranterior;
     private String lcbtValornuevo;
     private Long lcbtIdusuario;
     private Date lcbtFechamodificacion;
     private String lcbtIpusuario;
     private String lcbtNombreequipo;

    public LogCfgbactablas() {
    }

	
    public LogCfgbactablas(long lcbtIdlogcfgbactabla) {
        this.lcbtIdlogcfgbactabla = lcbtIdlogcfgbactabla;
    }
    public LogCfgbactablas(long lcbtIdlogcfgbactabla, String lcbtNombretabla, String lcbtNombrecampo, Boolean lcbtIdacciondato, String lcbtValoranterior, String lcbtValornuevo, Long lcbtIdusuario, Date lcbtFechamodificacion, String lcbtIpusuario, String lcbtNombreequipo) {
       this.lcbtIdlogcfgbactabla = lcbtIdlogcfgbactabla;
       this.lcbtNombretabla = lcbtNombretabla;
       this.lcbtNombrecampo = lcbtNombrecampo;
       this.lcbtIdacciondato = lcbtIdacciondato;
       this.lcbtValoranterior = lcbtValoranterior;
       this.lcbtValornuevo = lcbtValornuevo;
       this.lcbtIdusuario = lcbtIdusuario;
       this.lcbtFechamodificacion = lcbtFechamodificacion;
       this.lcbtIpusuario = lcbtIpusuario;
       this.lcbtNombreequipo = lcbtNombreequipo;
    }
   
    public long getLcbtIdlogcfgbactabla() {
        return this.lcbtIdlogcfgbactabla;
    }
    
    public void setLcbtIdlogcfgbactabla(long lcbtIdlogcfgbactabla) {
        this.lcbtIdlogcfgbactabla = lcbtIdlogcfgbactabla;
    }
    public String getLcbtNombretabla() {
        return this.lcbtNombretabla;
    }
    
    public void setLcbtNombretabla(String lcbtNombretabla) {
        this.lcbtNombretabla = lcbtNombretabla;
    }
    public String getLcbtNombrecampo() {
        return this.lcbtNombrecampo;
    }
    
    public void setLcbtNombrecampo(String lcbtNombrecampo) {
        this.lcbtNombrecampo = lcbtNombrecampo;
    }
    public Boolean getLcbtIdacciondato() {
        return this.lcbtIdacciondato;
    }
    
    public void setLcbtIdacciondato(Boolean lcbtIdacciondato) {
        this.lcbtIdacciondato = lcbtIdacciondato;
    }
    public String getLcbtValoranterior() {
        return this.lcbtValoranterior;
    }
    
    public void setLcbtValoranterior(String lcbtValoranterior) {
        this.lcbtValoranterior = lcbtValoranterior;
    }
    public String getLcbtValornuevo() {
        return this.lcbtValornuevo;
    }
    
    public void setLcbtValornuevo(String lcbtValornuevo) {
        this.lcbtValornuevo = lcbtValornuevo;
    }
    public Long getLcbtIdusuario() {
        return this.lcbtIdusuario;
    }
    
    public void setLcbtIdusuario(Long lcbtIdusuario) {
        this.lcbtIdusuario = lcbtIdusuario;
    }
    public Date getLcbtFechamodificacion() {
        return this.lcbtFechamodificacion;
    }
    
    public void setLcbtFechamodificacion(Date lcbtFechamodificacion) {
        this.lcbtFechamodificacion = lcbtFechamodificacion;
    }
    public String getLcbtIpusuario() {
        return this.lcbtIpusuario;
    }
    
    public void setLcbtIpusuario(String lcbtIpusuario) {
        this.lcbtIpusuario = lcbtIpusuario;
    }
    public String getLcbtNombreequipo() {
        return this.lcbtNombreequipo;
    }
    
    public void setLcbtNombreequipo(String lcbtNombreequipo) {
        this.lcbtNombreequipo = lcbtNombreequipo;
    }




}


