package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LogContactospacientes generated by hbm2java
 */
public class LogContactospacientes  implements java.io.Serializable {


     private long lcpIdlogcontactopaciente;
     private DatosPacientes datosPacientes;
     private DatosContactos datosContactos;
     private CfgAccionesdatos cfgAccionesdatos;
     private DatosUsuarios datosUsuarios;
     private Date lcpFechamodificacion;
     private String lcpValoranterior;
     private String lcpValornuevo;
     private String lcpCampomodificado;
     private String lcpIpusuario;
     private String lcpNombreequipo;

    public LogContactospacientes() {
    }

	
    public LogContactospacientes(long lcpIdlogcontactopaciente, DatosPacientes datosPacientes, DatosContactos datosContactos, CfgAccionesdatos cfgAccionesdatos, DatosUsuarios datosUsuarios, Date lcpFechamodificacion) {
        this.lcpIdlogcontactopaciente = lcpIdlogcontactopaciente;
        this.datosPacientes = datosPacientes;
        this.datosContactos = datosContactos;
        this.cfgAccionesdatos = cfgAccionesdatos;
        this.datosUsuarios = datosUsuarios;
        this.lcpFechamodificacion = lcpFechamodificacion;
    }
    public LogContactospacientes(long lcpIdlogcontactopaciente, DatosPacientes datosPacientes, DatosContactos datosContactos, CfgAccionesdatos cfgAccionesdatos, DatosUsuarios datosUsuarios, Date lcpFechamodificacion, String lcpValoranterior, String lcpValornuevo, String lcpCampomodificado, String lcpIpusuario, String lcpNombreequipo) {
       this.lcpIdlogcontactopaciente = lcpIdlogcontactopaciente;
       this.datosPacientes = datosPacientes;
       this.datosContactos = datosContactos;
       this.cfgAccionesdatos = cfgAccionesdatos;
       this.datosUsuarios = datosUsuarios;
       this.lcpFechamodificacion = lcpFechamodificacion;
       this.lcpValoranterior = lcpValoranterior;
       this.lcpValornuevo = lcpValornuevo;
       this.lcpCampomodificado = lcpCampomodificado;
       this.lcpIpusuario = lcpIpusuario;
       this.lcpNombreequipo = lcpNombreequipo;
    }
   
    public long getLcpIdlogcontactopaciente() {
        return this.lcpIdlogcontactopaciente;
    }
    
    public void setLcpIdlogcontactopaciente(long lcpIdlogcontactopaciente) {
        this.lcpIdlogcontactopaciente = lcpIdlogcontactopaciente;
    }
    public DatosPacientes getDatosPacientes() {
        return this.datosPacientes;
    }
    
    public void setDatosPacientes(DatosPacientes datosPacientes) {
        this.datosPacientes = datosPacientes;
    }
    public DatosContactos getDatosContactos() {
        return this.datosContactos;
    }
    
    public void setDatosContactos(DatosContactos datosContactos) {
        this.datosContactos = datosContactos;
    }
    public CfgAccionesdatos getCfgAccionesdatos() {
        return this.cfgAccionesdatos;
    }
    
    public void setCfgAccionesdatos(CfgAccionesdatos cfgAccionesdatos) {
        this.cfgAccionesdatos = cfgAccionesdatos;
    }
    public DatosUsuarios getDatosUsuarios() {
        return this.datosUsuarios;
    }
    
    public void setDatosUsuarios(DatosUsuarios datosUsuarios) {
        this.datosUsuarios = datosUsuarios;
    }
    public Date getLcpFechamodificacion() {
        return this.lcpFechamodificacion;
    }
    
    public void setLcpFechamodificacion(Date lcpFechamodificacion) {
        this.lcpFechamodificacion = lcpFechamodificacion;
    }
    public String getLcpValoranterior() {
        return this.lcpValoranterior;
    }
    
    public void setLcpValoranterior(String lcpValoranterior) {
        this.lcpValoranterior = lcpValoranterior;
    }
    public String getLcpValornuevo() {
        return this.lcpValornuevo;
    }
    
    public void setLcpValornuevo(String lcpValornuevo) {
        this.lcpValornuevo = lcpValornuevo;
    }
    public String getLcpCampomodificado() {
        return this.lcpCampomodificado;
    }
    
    public void setLcpCampomodificado(String lcpCampomodificado) {
        this.lcpCampomodificado = lcpCampomodificado;
    }
    public String getLcpIpusuario() {
        return this.lcpIpusuario;
    }
    
    public void setLcpIpusuario(String lcpIpusuario) {
        this.lcpIpusuario = lcpIpusuario;
    }
    public String getLcpNombreequipo() {
        return this.lcpNombreequipo;
    }
    
    public void setLcpNombreequipo(String lcpNombreequipo) {
        this.lcpNombreequipo = lcpNombreequipo;
    }




}


