package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * LogEventosusuarios generated by hbm2java
 */
public class LogEventosusuarios  implements java.io.Serializable {


     private long leuIdeventousuario;
     private DatosUsuarios datosUsuarios;
     private CfgEventos cfgEventos;
     private Short leuIdestacion;
     private Date leuFechaevento;
     private Boolean leuIdacciondato;
     private String leuNombretabla;
     private String leuNombrecampo;
     private String leuValoranterior;
     private String leuValornuevo;

    public LogEventosusuarios() {
    }

	
    public LogEventosusuarios(long leuIdeventousuario, DatosUsuarios datosUsuarios, CfgEventos cfgEventos) {
        this.leuIdeventousuario = leuIdeventousuario;
        this.datosUsuarios = datosUsuarios;
        this.cfgEventos = cfgEventos;
    }
    public LogEventosusuarios(long leuIdeventousuario, DatosUsuarios datosUsuarios, CfgEventos cfgEventos, Short leuIdestacion, Date leuFechaevento, Boolean leuIdacciondato, String leuNombretabla, String leuNombrecampo, String leuValoranterior, String leuValornuevo) {
       this.leuIdeventousuario = leuIdeventousuario;
       this.datosUsuarios = datosUsuarios;
       this.cfgEventos = cfgEventos;
       this.leuIdestacion = leuIdestacion;
       this.leuFechaevento = leuFechaevento;
       this.leuIdacciondato = leuIdacciondato;
       this.leuNombretabla = leuNombretabla;
       this.leuNombrecampo = leuNombrecampo;
       this.leuValoranterior = leuValoranterior;
       this.leuValornuevo = leuValornuevo;
    }
   
    public long getLeuIdeventousuario() {
        return this.leuIdeventousuario;
    }
    
    public void setLeuIdeventousuario(long leuIdeventousuario) {
        this.leuIdeventousuario = leuIdeventousuario;
    }
    public DatosUsuarios getDatosUsuarios() {
        return this.datosUsuarios;
    }
    
    public void setDatosUsuarios(DatosUsuarios datosUsuarios) {
        this.datosUsuarios = datosUsuarios;
    }
    public CfgEventos getCfgEventos() {
        return this.cfgEventos;
    }
    
    public void setCfgEventos(CfgEventos cfgEventos) {
        this.cfgEventos = cfgEventos;
    }
    public Short getLeuIdestacion() {
        return this.leuIdestacion;
    }
    
    public void setLeuIdestacion(Short leuIdestacion) {
        this.leuIdestacion = leuIdestacion;
    }
    public Date getLeuFechaevento() {
        return this.leuFechaevento;
    }
    
    public void setLeuFechaevento(Date leuFechaevento) {
        this.leuFechaevento = leuFechaevento;
    }
    public Boolean getLeuIdacciondato() {
        return this.leuIdacciondato;
    }
    
    public void setLeuIdacciondato(Boolean leuIdacciondato) {
        this.leuIdacciondato = leuIdacciondato;
    }
    public String getLeuNombretabla() {
        return this.leuNombretabla;
    }
    
    public void setLeuNombretabla(String leuNombretabla) {
        this.leuNombretabla = leuNombretabla;
    }
    public String getLeuNombrecampo() {
        return this.leuNombrecampo;
    }
    
    public void setLeuNombrecampo(String leuNombrecampo) {
        this.leuNombrecampo = leuNombrecampo;
    }
    public String getLeuValoranterior() {
        return this.leuValoranterior;
    }
    
    public void setLeuValoranterior(String leuValoranterior) {
        this.leuValoranterior = leuValoranterior;
    }
    public String getLeuValornuevo() {
        return this.leuValornuevo;
    }
    
    public void setLeuValornuevo(String leuValornuevo) {
        this.leuValornuevo = leuValornuevo;
    }




}


