package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * LogPacientes generated by hbm2java
 */
public class LogPacientes implements java.io.Serializable {

	private int lpId;
	private DatosPacientes datosPacientes;
	private int lpIdusuario;
	private Date lpFechamodificacion;
	private int lpIdacciondato;
	private String lpValoranterior;
	private String lpValornuevo;
	private String lpCampomodificado;
	private String lpIpusuario;
	private String lpNombreequipo;

	public LogPacientes() {
	}

//    public LogPacientes(int lpId) {
//        this.lpId = lpId;
//    }
	

   public LogPacientes(int lpId, DatosPacientes datosPacientes, int lpIdusuario, Date lpFechamodificacion, int lpIdacciondato, String lpValoranterior, String lpValornuevo, String lpCampomodificado, String lpIpusuario, String lpNombreequipo) {
       this.lpId = lpId;
       this.datosPacientes = datosPacientes;
       this.lpIdusuario = lpIdusuario;
       this.lpFechamodificacion = lpFechamodificacion;
       this.lpIdacciondato = lpIdacciondato;
       this.lpValoranterior = lpValoranterior;
       this.lpValornuevo = lpValornuevo;
       this.lpCampomodificado = lpCampomodificado;
       this.lpIpusuario = lpIpusuario;
       this.lpNombreequipo = lpNombreequipo;
    }

	
	public int getLpId() {
    return lpId;
}

public void setLpId(int lpId) {
    this.lpId = lpId;
}

    public DatosPacientes getDatosPacientes() {
		return this.datosPacientes;
	}

	public void setDatosPacientes(DatosPacientes datosPacientes) {
		this.datosPacientes = datosPacientes;
	}

	public int getLpIdusuario() {
		return this.lpIdusuario;
	}

	public void setLpIdusuario(int lpIdusuario) {
		this.lpIdusuario = lpIdusuario;
	}

	public Date getLpFechamodificacion() {
		return this.lpFechamodificacion;
	}

	public void setLpFechamodificacion(Date lpFechamodificacion) {
		this.lpFechamodificacion = lpFechamodificacion;
	}

	public int getLpIdacciondato() {
		return this.lpIdacciondato;
	}

	public void setLpIdacciondato(int lpIdacciondato) {
		this.lpIdacciondato = lpIdacciondato;
	}

	public String getLpValoranterior() {
		return this.lpValoranterior;
	}

	public void setLpValoranterior(String lpValoranterior) {
		this.lpValoranterior = lpValoranterior;
	}

	public String getLpValornuevo() {
		return this.lpValornuevo;
	}

	public void setLpValornuevo(String lpValornuevo) {
		this.lpValornuevo = lpValornuevo;
	}

	public String getLpCampomodificado() {
		return this.lpCampomodificado;
	}

	public void setLpCampomodificado(String lpCampomodificado) {
		this.lpCampomodificado = lpCampomodificado;
	}

	public String getLpIpusuario() {
		return this.lpIpusuario;
	}

	public void setLpIpusuario(String lpIpusuario) {
		this.lpIpusuario = lpIpusuario;
	}

	public String getLpNombreequipo() {
		return this.lpNombreequipo;
	}

	public void setLpNombreequipo(String lpNombreequipo) {
		this.lpNombreequipo = lpNombreequipo;
	}

    @Override
    public String toString() {
        return "LogPacientes [lpId=" + lpId + ", datosPacientes=" + datosPacientes + ", lpIdusuario=" + lpIdusuario
                + ", lpFechamodificacion=" + lpFechamodificacion + ", lpIdacciondato=" + lpIdacciondato
                + ", lpValoranterior=" + lpValoranterior + ", lpValornuevo=" + lpValornuevo + ", lpCampomodificado="
                + lpCampomodificado + ", lpIpusuario=" + lpIpusuario + ", lpNombreequipo=" + lpNombreequipo + "]";
    }

}
