package com.grupobios.bioslis.entity;
// Generated 22-04-2020 16:13:26 by Hibernate Tools 4.3.1



/**
 * LogPacientesId generated by hbm2java
 */
public class LogPacientesId  implements java.io.Serializable {


     private long lpIdpaciente;
     private long lpIdlogpacientes;

    public LogPacientesId() {
    }

    public LogPacientesId(long lpIdpaciente, long lpIdlogpacientes) {
       this.lpIdpaciente = lpIdpaciente;
       this.lpIdlogpacientes = lpIdlogpacientes;
    }
   
    public long getLpIdpaciente() {
        return this.lpIdpaciente;
    }
    
    public void setLpIdpaciente(long lpIdpaciente) {
        this.lpIdpaciente = lpIdpaciente;
    }
    public long getLpIdlogpacientes() {
        return this.lpIdlogpacientes;
    }
    
    public void setLpIdlogpacientes(long lpIdlogpacientes) {
        this.lpIdlogpacientes = lpIdlogpacientes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogPacientesId) ) return false;
		 LogPacientesId castOther = ( LogPacientesId ) other; 
         
		 return (this.getLpIdpaciente()==castOther.getLpIdpaciente())
 && (this.getLpIdlogpacientes()==castOther.getLpIdlogpacientes());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getLpIdpaciente();
         result = 37 * result + (int) this.getLpIdlogpacientes();
         return result;
   }   


}


