package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LogSistematablas generated by hbm2java
 */
public class LogSistematablas  implements java.io.Serializable {


     private long lstIdlogsistema;
     private CfgAccionesdatos cfgAccionesdatos;
     private String lstNombretabla;
     private String lstNombrecampo;
     private String lstValoranterior;
     private String lstValornuevo;
     private Long lstIdusuario;
     private Date lstFechamodificacion;
     private String lstIpusuario;
     private String lstNombreequipo;

    public LogSistematablas() {
    }

	
    public LogSistematablas(long lstIdlogsistema) {
        this.lstIdlogsistema = lstIdlogsistema;
    }
    public LogSistematablas(long lstIdlogsistema, CfgAccionesdatos cfgAccionesdatos, String lstNombretabla, String lstNombrecampo, String lstValoranterior, String lstValornuevo, Long lstIdusuario, Date lstFechamodificacion, String lstIpusuario, String lstNombreequipo) {
       this.lstIdlogsistema = lstIdlogsistema;
       this.cfgAccionesdatos = cfgAccionesdatos;
       this.lstNombretabla = lstNombretabla;
       this.lstNombrecampo = lstNombrecampo;
       this.lstValoranterior = lstValoranterior;
       this.lstValornuevo = lstValornuevo;
       this.lstIdusuario = lstIdusuario;
       this.lstFechamodificacion = lstFechamodificacion;
       this.lstIpusuario = lstIpusuario;
       this.lstNombreequipo = lstNombreequipo;
    }
   
    public long getLstIdlogsistema() {
        return this.lstIdlogsistema;
    }
    
    public void setLstIdlogsistema(long lstIdlogsistema) {
        this.lstIdlogsistema = lstIdlogsistema;
    }
    public CfgAccionesdatos getCfgAccionesdatos() {
        return this.cfgAccionesdatos;
    }
    
    public void setCfgAccionesdatos(CfgAccionesdatos cfgAccionesdatos) {
        this.cfgAccionesdatos = cfgAccionesdatos;
    }
    public String getLstNombretabla() {
        return this.lstNombretabla;
    }
    
    public void setLstNombretabla(String lstNombretabla) {
        this.lstNombretabla = lstNombretabla;
    }
    public String getLstNombrecampo() {
        return this.lstNombrecampo;
    }
    
    public void setLstNombrecampo(String lstNombrecampo) {
        this.lstNombrecampo = lstNombrecampo;
    }
    public String getLstValoranterior() {
        return this.lstValoranterior;
    }
    
    public void setLstValoranterior(String lstValoranterior) {
        this.lstValoranterior = lstValoranterior;
    }
    public String getLstValornuevo() {
        return this.lstValornuevo;
    }
    
    public void setLstValornuevo(String lstValornuevo) {
        this.lstValornuevo = lstValornuevo;
    }
    public Long getLstIdusuario() {
        return this.lstIdusuario;
    }
    
    public void setLstIdusuario(Long lstIdusuario) {
        this.lstIdusuario = lstIdusuario;
    }
    public Date getLstFechamodificacion() {
        return this.lstFechamodificacion;
    }
    
    public void setLstFechamodificacion(Date lstFechamodificacion) {
        this.lstFechamodificacion = lstFechamodificacion;
    }
    public String getLstIpusuario() {
        return this.lstIpusuario;
    }
    
    public void setLstIpusuario(String lstIpusuario) {
        this.lstIpusuario = lstIpusuario;
    }
    public String getLstNombreequipo() {
        return this.lstNombreequipo;
    }
    
    public void setLstNombreequipo(String lstNombreequipo) {
        this.lstNombreequipo = lstNombreequipo;
    }




}


