package com.grupobios.bioslis.entity;
// Generated 22-04-2020 16:13:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Testeojan generated by hbm2java
 */
public class PDF  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal edad;
     private String nombreExamen;
     private String nombreExamenTest;

    public PDF() {
    }

	
    public PDF(BigDecimal id) {
        this.id = id;
    }
    public PDF(BigDecimal id, BigDecimal edad, String nombreExamen, String nombreExamenTest) {
       this.id = id;
       this.edad = edad;
       this.nombreExamen = nombreExamen;
       this.nombreExamenTest = nombreExamenTest;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public BigDecimal getEdad() {
        return this.edad;
    }
    
    public void setEdad(BigDecimal edad) {
        this.edad = edad;
    }
    public String getnombreExamen() {
        return this.nombreExamen;
    }
    
    public void setnombreExamen(String nombreExamen) {
        this.nombreExamen = nombreExamen;
    }
    public String getnombreExamenTest() {
        return this.nombreExamenTest;
    }
    
    public void setnombreExamenTest(String nombreExamenTest) {
        this.nombreExamenTest = nombreExamenTest;
    }




}


