package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SigmaPrefijostest generated by hbm2java
 */
public class SigmaPrefijostest  implements java.io.Serializable {


     private int sptIdprefijostest;
     private String sptPrefijotest;
     private Set sigmaProcesosanalizadorestests = new HashSet(0);

    public SigmaPrefijostest() {
    }

	
    public SigmaPrefijostest(int sptIdprefijostest, String sptPrefijotest) {
        this.sptIdprefijostest = sptIdprefijostest;
        this.sptPrefijotest = sptPrefijotest;
    }
    public SigmaPrefijostest(int sptIdprefijostest, String sptPrefijotest, Set sigmaProcesosanalizadorestests) {
       this.sptIdprefijostest = sptIdprefijostest;
       this.sptPrefijotest = sptPrefijotest;
       this.sigmaProcesosanalizadorestests = sigmaProcesosanalizadorestests;
    }
   
    public int getSptIdprefijostest() {
        return this.sptIdprefijostest;
    }
    
    public void setSptIdprefijostest(int sptIdprefijostest) {
        this.sptIdprefijostest = sptIdprefijostest;
    }
    public String getSptPrefijotest() {
        return this.sptPrefijotest;
    }
    
    public void setSptPrefijotest(String sptPrefijotest) {
        this.sptPrefijotest = sptPrefijotest;
    }
    public Set getSigmaProcesosanalizadorestests() {
        return this.sigmaProcesosanalizadorestests;
    }
    
    public void setSigmaProcesosanalizadorestests(Set sigmaProcesosanalizadorestests) {
        this.sigmaProcesosanalizadorestests = sigmaProcesosanalizadorestests;
    }




}


