package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * SigmaTiposmuestras generated by hbm2java
 */
public class SigmaTiposmuestras  implements java.io.Serializable {


     private byte stmIdsigmatipomuestra;
     private String stmCodigo;
     private String stmDescripcion;
     private Byte stmSort;
     private String stmActivo;
     @JsonIgnore
     private Set sigmaProcesostests = new HashSet(0);

    public SigmaTiposmuestras() {
    }

	
    public SigmaTiposmuestras(byte stmIdsigmatipomuestra) {
        this.stmIdsigmatipomuestra = stmIdsigmatipomuestra;
    }
    public SigmaTiposmuestras(byte stmIdsigmatipomuestra, String stmCodigo, String stmDescripcion, Byte stmSort, String stmActivo, Set sigmaProcesostests) {
       this.stmIdsigmatipomuestra = stmIdsigmatipomuestra;
       this.stmCodigo = stmCodigo;
       this.stmDescripcion = stmDescripcion;
       this.stmSort = stmSort;
       this.stmActivo = stmActivo;
       this.sigmaProcesostests = sigmaProcesostests;
    }
   
    public byte getStmIdsigmatipomuestra() {
        return this.stmIdsigmatipomuestra;
    }
    
    public void setStmIdsigmatipomuestra(byte stmIdsigmatipomuestra) {
        this.stmIdsigmatipomuestra = stmIdsigmatipomuestra;
    }
    public String getStmCodigo() {
        return this.stmCodigo;
    }
    
    public void setStmCodigo(String stmCodigo) {
        this.stmCodigo = stmCodigo;
    }
    public String getStmDescripcion() {
        return this.stmDescripcion;
    }
    
    public void setStmDescripcion(String stmDescripcion) {
        this.stmDescripcion = stmDescripcion;
    }
    public Byte getStmSort() {
        return this.stmSort;
    }
    
    public void setStmSort(Byte stmSort) {
        this.stmSort = stmSort;
    }
    public String getStmActivo() {
        return this.stmActivo;
    }
    
    public void setStmActivo(String stmActivo) {
        this.stmActivo = stmActivo;
    }
    public Set getSigmaProcesostests() {
        return this.sigmaProcesostests;
    }
    
    public void setSigmaProcesostests(Set sigmaProcesostests) {
        this.sigmaProcesostests = sigmaProcesostests;
    }




}


