package com.grupobios.bioslis.entity;
// Generated 08-11-2022 1:16:04 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;




/**
 * SigmaProcesosalarmas generated by hbm2java
 */
public class SigmaProcesosalarmas  implements java.io.Serializable {


     private short spaIdprocesoalarma;
     @JsonIgnore
     private SigmaProcesos sigmaProcesos;
     private String spaCodigoalarma;
     private String spaAlarmadescripcion;
     private String spaActivo;
     private String spaBloquear;

    public SigmaProcesosalarmas() {
    }

	
    public SigmaProcesosalarmas(short spaIdprocesoalarma, SigmaProcesos sigmaProcesos) {
        this.spaIdprocesoalarma = spaIdprocesoalarma;
        this.sigmaProcesos = sigmaProcesos;
    }
    public SigmaProcesosalarmas(short spaIdprocesoalarma, SigmaProcesos sigmaProcesos, String spaCodigoalarma, String spaAlarmadescripcion, String spaActivo, String spaBloquear) {
       this.spaIdprocesoalarma = spaIdprocesoalarma;
       this.sigmaProcesos = sigmaProcesos;
       this.spaCodigoalarma = spaCodigoalarma;
       this.spaAlarmadescripcion = spaAlarmadescripcion;
       this.spaActivo = spaActivo;
       this.spaBloquear = spaBloquear;
    }
   
    public short getSpaIdprocesoalarma() {
        return this.spaIdprocesoalarma;
    }
    
    public void setSpaIdprocesoalarma(short spaIdprocesoalarma) {
        this.spaIdprocesoalarma = spaIdprocesoalarma;
    }
    public SigmaProcesos getSigmaProcesos() {
        return this.sigmaProcesos;
    }
    
    public void setSigmaProcesos(SigmaProcesos sigmaProcesos) {
        this.sigmaProcesos = sigmaProcesos;
    }
    public String getSpaCodigoalarma() {
        return this.spaCodigoalarma;
    }
    
    public void setSpaCodigoalarma(String spaCodigoalarma) {
        this.spaCodigoalarma = spaCodigoalarma;
    }
    public String getSpaAlarmadescripcion() {
        return this.spaAlarmadescripcion;
    }
    
    public void setSpaAlarmadescripcion(String spaAlarmadescripcion) {
        this.spaAlarmadescripcion = spaAlarmadescripcion;
    }
    public String getSpaActivo() {
        return this.spaActivo;
    }
    
    public void setSpaActivo(String spaActivo) {
        this.spaActivo = spaActivo;
    }
    public String getSpaBloquear() {
        return this.spaBloquear;
    }
    
    public void setSpaBloquear(String spaBloquear) {
        this.spaBloquear = spaBloquear;
    }




}


