package com.grupobios.bioslis.entity;
// Generated 04-11-2022 0:44:44 by Hibernate Tools 4.3.1



/**
 * SigmaAnalizadores generated by hbm2java
 */
public class SigmaAnalizadores  implements java.io.Serializable {


     private short saIdanalizador;
     private String saCodigoanalizador;
     private String saDescripcion;
     private Short saIdimagen;
     private String saModelo;
     private String saEmpresa;
     private String saCodigoproceso1;
     private String saCodigoproceso2;
     private String saCodigoproceso3;

    public SigmaAnalizadores() {
    }

	
    public SigmaAnalizadores(short saIdanalizador) {
        this.saIdanalizador = saIdanalizador;
    }
    public SigmaAnalizadores(short saIdanalizador, String saCodigoanalizador, String saDescripcion, Short saIdimagen, String saModelo, String saEmpresa, String saCodigoproceso1, String saCodigoproceso2, String saCodigoproceso3) {
       this.saIdanalizador = saIdanalizador;
       this.saCodigoanalizador = saCodigoanalizador;
       this.saDescripcion = saDescripcion;
       this.saIdimagen = saIdimagen;
       this.saModelo = saModelo;
       this.saEmpresa = saEmpresa;
       this.saCodigoproceso1 = saCodigoproceso1;
       this.saCodigoproceso2 = saCodigoproceso2;
       this.saCodigoproceso3 = saCodigoproceso3;
    }
   
    public short getSaIdanalizador() {
        return this.saIdanalizador;
    }
    
    public void setSaIdanalizador(short saIdanalizador) {
        this.saIdanalizador = saIdanalizador;
    }
    public String getSaCodigoanalizador() {
        return this.saCodigoanalizador;
    }
    
    public void setSaCodigoanalizador(String saCodigoanalizador) {
        this.saCodigoanalizador = saCodigoanalizador;
    }
    public String getSaDescripcion() {
        return this.saDescripcion;
    }
    
    public void setSaDescripcion(String saDescripcion) {
        this.saDescripcion = saDescripcion;
    }
    public Short getSaIdimagen() {
        return this.saIdimagen;
    }
    
    public void setSaIdimagen(Short saIdimagen) {
        this.saIdimagen = saIdimagen;
    }
    public String getSaModelo() {
        return this.saModelo;
    }
    
    public void setSaModelo(String saModelo) {
        this.saModelo = saModelo;
    }
    public String getSaEmpresa() {
        return this.saEmpresa;
    }
    
    public void setSaEmpresa(String saEmpresa) {
        this.saEmpresa = saEmpresa;
    }
    public String getSaCodigoproceso1() {
        return this.saCodigoproceso1;
    }
    
    public void setSaCodigoproceso1(String saCodigoproceso1) {
        this.saCodigoproceso1 = saCodigoproceso1;
    }
    public String getSaCodigoproceso2() {
        return this.saCodigoproceso2;
    }
    
    public void setSaCodigoproceso2(String saCodigoproceso2) {
        this.saCodigoproceso2 = saCodigoproceso2;
    }
    public String getSaCodigoproceso3() {
        return this.saCodigoproceso3;
    }
    
    public void setSaCodigoproceso3(String saCodigoproceso3) {
        this.saCodigoproceso3 = saCodigoproceso3;
    }




}


