package com.grupobios.bioslis.entity;
// Generated 17-10-2022 22:44:33 by Hibernate Tools 4.3.1



/**
 * SigmaProcesotestconversionId generated by hbm2java
 */
public class SigmaProcesotestconversionId  implements java.io.Serializable {


     private short sptcIdproceso;
     private long sptcIdtest;
     private byte sptcNumerocondicion;

    public SigmaProcesotestconversionId() {
    }

    public SigmaProcesotestconversionId(short sptcIdproceso, long sptcIdtest, byte sptcNumerocondicion) {
       this.sptcIdproceso = sptcIdproceso;
       this.sptcIdtest = sptcIdtest;
       this.sptcNumerocondicion = sptcNumerocondicion;
    }
   
    public short getSptcIdproceso() {
        return this.sptcIdproceso;
    }
    
    public void setSptcIdproceso(short sptcIdproceso) {
        this.sptcIdproceso = sptcIdproceso;
    }
    public long getSptcIdtest() {
        return this.sptcIdtest;
    }
    
    public void setSptcIdtest(long sptcIdtest) {
        this.sptcIdtest = sptcIdtest;
    }
    public byte getSptcNumerocondicion() {
        return this.sptcNumerocondicion;
    }
    
    public void setSptcNumerocondicion(byte sptcNumerocondicion) {
        this.sptcNumerocondicion = sptcNumerocondicion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SigmaProcesotestconversionId) ) return false;
		 SigmaProcesotestconversionId castOther = ( SigmaProcesotestconversionId ) other; 
         
		 return (this.getSptcIdproceso()==castOther.getSptcIdproceso())
 && (this.getSptcIdtest()==castOther.getSptcIdtest())
 && (this.getSptcNumerocondicion()==castOther.getSptcNumerocondicion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSptcIdproceso();
         result = 37 * result + (int) this.getSptcIdtest();
         result = 37 * result + this.getSptcNumerocondicion();
         return result;
   }   


}


