package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * SigmaProcesosanalizadorestestId generated by hbm2java
 */
public class SigmaProcesosanalizadorestestId  implements java.io.Serializable {


     private short spatIdanalizador;
     private long spatIdtest;

    public SigmaProcesosanalizadorestestId() {
    }

    public SigmaProcesosanalizadorestestId(short spatIdanalizador, long spatIdtest) {
       this.spatIdanalizador = spatIdanalizador;
       this.spatIdtest = spatIdtest;
    }
   
    public short getSpatIdanalizador() {
        return this.spatIdanalizador;
    }
    
    public void setSpatIdanalizador(short spatIdanalizador) {
        this.spatIdanalizador = spatIdanalizador;
    }
    public long getSpatIdtest() {
        return this.spatIdtest;
    }
    
    public void setSpatIdtest(long spatIdtest) {
        this.spatIdtest = spatIdtest;
    }




}


