package com.grupobios.bioslis.entity;
// Generated 17-10-2022 22:44:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SigmaTablahost generated by hbm2java
 */
public class SigmaTablahost  implements java.io.Serializable {


     private long sthIdsigmatablahost;
     private Date sthHostdate;
     private String sthNorden;
     private String sthMuestra;
     private String sthRut;
     private String sthNombre;
     private String sthApellidopaterno;
     private String sthApellidomaterno;
     private String sthSexo;
     private Date sthFechanacimiento;
     private String sthTelefono;
     private String sthMail;
     private String sthDireccion;
     private String sthObservacionpaciente;
     private String sthPrioridadatencion;
     private String sthTipoatencion;
     private String sthProcedencia;
     private String sthServicio;
     private String sthPrevision;
     private String sthMedico;
     private String sthNficha1;
     private String sthNficha2;
     private String sthNficha3;
     private String sthNficha4;
     private String sthLocalizacion;
     private String sthDiagnostico;
     private String sthObservacionficha;
     private String sthExamen;
     private String sthBusqueda;
     private String sthEstado;

    public SigmaTablahost() {
    }

	
    public SigmaTablahost(long sthIdsigmatablahost) {
        this.sthIdsigmatablahost = sthIdsigmatablahost;
    }
    public SigmaTablahost(long sthIdsigmatablahost, Date sthHostdate, String sthNorden, String sthMuestra, String sthRut, String sthNombre, String sthApellidopaterno, String sthApellidomaterno, String sthSexo, Date sthFechanacimiento, String sthTelefono, String sthMail, String sthDireccion, String sthObservacionpaciente, String sthPrioridadatencion, String sthTipoatencion, String sthProcedencia, String sthServicio, String sthPrevision, String sthMedico, String sthNficha1, String sthNficha2, String sthNficha3, String sthNficha4, String sthLocalizacion, String sthDiagnostico, String sthObservacionficha, String sthExamen, String sthBusqueda, String sthEstado) {
       this.sthIdsigmatablahost = sthIdsigmatablahost;
       this.sthHostdate = sthHostdate;
       this.sthNorden = sthNorden;
       this.sthMuestra = sthMuestra;
       this.sthRut = sthRut;
       this.sthNombre = sthNombre;
       this.sthApellidopaterno = sthApellidopaterno;
       this.sthApellidomaterno = sthApellidomaterno;
       this.sthSexo = sthSexo;
       this.sthFechanacimiento = sthFechanacimiento;
       this.sthTelefono = sthTelefono;
       this.sthMail = sthMail;
       this.sthDireccion = sthDireccion;
       this.sthObservacionpaciente = sthObservacionpaciente;
       this.sthPrioridadatencion = sthPrioridadatencion;
       this.sthTipoatencion = sthTipoatencion;
       this.sthProcedencia = sthProcedencia;
       this.sthServicio = sthServicio;
       this.sthPrevision = sthPrevision;
       this.sthMedico = sthMedico;
       this.sthNficha1 = sthNficha1;
       this.sthNficha2 = sthNficha2;
       this.sthNficha3 = sthNficha3;
       this.sthNficha4 = sthNficha4;
       this.sthLocalizacion = sthLocalizacion;
       this.sthDiagnostico = sthDiagnostico;
       this.sthObservacionficha = sthObservacionficha;
       this.sthExamen = sthExamen;
       this.sthBusqueda = sthBusqueda;
       this.sthEstado = sthEstado;
    }
   
    public long getSthIdsigmatablahost() {
        return this.sthIdsigmatablahost;
    }
    
    public void setSthIdsigmatablahost(long sthIdsigmatablahost) {
        this.sthIdsigmatablahost = sthIdsigmatablahost;
    }
    public Date getSthHostdate() {
        return this.sthHostdate;
    }
    
    public void setSthHostdate(Date sthHostdate) {
        this.sthHostdate = sthHostdate;
    }
    public String getSthNorden() {
        return this.sthNorden;
    }
    
    public void setSthNorden(String sthNorden) {
        this.sthNorden = sthNorden;
    }
    public String getSthMuestra() {
        return this.sthMuestra;
    }
    
    public void setSthMuestra(String sthMuestra) {
        this.sthMuestra = sthMuestra;
    }
    public String getSthRut() {
        return this.sthRut;
    }
    
    public void setSthRut(String sthRut) {
        this.sthRut = sthRut;
    }
    public String getSthNombre() {
        return this.sthNombre;
    }
    
    public void setSthNombre(String sthNombre) {
        this.sthNombre = sthNombre;
    }
    public String getSthApellidopaterno() {
        return this.sthApellidopaterno;
    }
    
    public void setSthApellidopaterno(String sthApellidopaterno) {
        this.sthApellidopaterno = sthApellidopaterno;
    }
    public String getSthApellidomaterno() {
        return this.sthApellidomaterno;
    }
    
    public void setSthApellidomaterno(String sthApellidomaterno) {
        this.sthApellidomaterno = sthApellidomaterno;
    }
    public String getSthSexo() {
        return this.sthSexo;
    }
    
    public void setSthSexo(String sthSexo) {
        this.sthSexo = sthSexo;
    }
    public Date getSthFechanacimiento() {
        return this.sthFechanacimiento;
    }
    
    public void setSthFechanacimiento(Date sthFechanacimiento) {
        this.sthFechanacimiento = sthFechanacimiento;
    }
    public String getSthTelefono() {
        return this.sthTelefono;
    }
    
    public void setSthTelefono(String sthTelefono) {
        this.sthTelefono = sthTelefono;
    }
    public String getSthMail() {
        return this.sthMail;
    }
    
    public void setSthMail(String sthMail) {
        this.sthMail = sthMail;
    }
    public String getSthDireccion() {
        return this.sthDireccion;
    }
    
    public void setSthDireccion(String sthDireccion) {
        this.sthDireccion = sthDireccion;
    }
    public String getSthObservacionpaciente() {
        return this.sthObservacionpaciente;
    }
    
    public void setSthObservacionpaciente(String sthObservacionpaciente) {
        this.sthObservacionpaciente = sthObservacionpaciente;
    }
    public String getSthPrioridadatencion() {
        return this.sthPrioridadatencion;
    }
    
    public void setSthPrioridadatencion(String sthPrioridadatencion) {
        this.sthPrioridadatencion = sthPrioridadatencion;
    }
    public String getSthTipoatencion() {
        return this.sthTipoatencion;
    }
    
    public void setSthTipoatencion(String sthTipoatencion) {
        this.sthTipoatencion = sthTipoatencion;
    }
    public String getSthProcedencia() {
        return this.sthProcedencia;
    }
    
    public void setSthProcedencia(String sthProcedencia) {
        this.sthProcedencia = sthProcedencia;
    }
    public String getSthServicio() {
        return this.sthServicio;
    }
    
    public void setSthServicio(String sthServicio) {
        this.sthServicio = sthServicio;
    }
    public String getSthPrevision() {
        return this.sthPrevision;
    }
    
    public void setSthPrevision(String sthPrevision) {
        this.sthPrevision = sthPrevision;
    }
    public String getSthMedico() {
        return this.sthMedico;
    }
    
    public void setSthMedico(String sthMedico) {
        this.sthMedico = sthMedico;
    }
    public String getSthNficha1() {
        return this.sthNficha1;
    }
    
    public void setSthNficha1(String sthNficha1) {
        this.sthNficha1 = sthNficha1;
    }
    public String getSthNficha2() {
        return this.sthNficha2;
    }
    
    public void setSthNficha2(String sthNficha2) {
        this.sthNficha2 = sthNficha2;
    }
    public String getSthNficha3() {
        return this.sthNficha3;
    }
    
    public void setSthNficha3(String sthNficha3) {
        this.sthNficha3 = sthNficha3;
    }
    public String getSthNficha4() {
        return this.sthNficha4;
    }
    
    public void setSthNficha4(String sthNficha4) {
        this.sthNficha4 = sthNficha4;
    }
    public String getSthLocalizacion() {
        return this.sthLocalizacion;
    }
    
    public void setSthLocalizacion(String sthLocalizacion) {
        this.sthLocalizacion = sthLocalizacion;
    }
    public String getSthDiagnostico() {
        return this.sthDiagnostico;
    }
    
    public void setSthDiagnostico(String sthDiagnostico) {
        this.sthDiagnostico = sthDiagnostico;
    }
    public String getSthObservacionficha() {
        return this.sthObservacionficha;
    }
    
    public void setSthObservacionficha(String sthObservacionficha) {
        this.sthObservacionficha = sthObservacionficha;
    }
    public String getSthExamen() {
        return this.sthExamen;
    }
    
    public void setSthExamen(String sthExamen) {
        this.sthExamen = sthExamen;
    }
    public String getSthBusqueda() {
        return this.sthBusqueda;
    }
    
    public void setSthBusqueda(String sthBusqueda) {
        this.sthBusqueda = sthBusqueda;
    }
    public String getSthEstado() {
        return this.sthEstado;
    }
    
    public void setSthEstado(String sthEstado) {
        this.sthEstado = sthEstado;
    }




}


