package com.grupobios.bioslis.entity;
// Generated 17-10-2022 22:44:33 by Hibernate Tools 4.3.1



/**
 * SigmaProcesostestId generated by hbm2java
 */
public class SigmaProcesostestId  implements java.io.Serializable {


     private short sptIdproceso;
     private long sptIdtest;

    public SigmaProcesostestId() {
    }

    public SigmaProcesostestId(short sptIdproceso, long sptIdtest) {
       this.sptIdproceso = sptIdproceso;
       this.sptIdtest = sptIdtest;
    }
   
    public short getSptIdproceso() {
        return this.sptIdproceso;
    }
    
    public void setSptIdproceso(short sptIdproceso) {
        this.sptIdproceso = sptIdproceso;
    }
    public long getSptIdtest() {
        return this.sptIdtest;
    }
    
    public void setSptIdtest(long sptIdtest) {
        this.sptIdtest = sptIdtest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SigmaProcesostestId) ) return false;
		 SigmaProcesostestId castOther = ( SigmaProcesostestId ) other; 
         
		 return (this.getSptIdproceso()==castOther.getSptIdproceso())
 && (this.getSptIdtest()==castOther.getSptIdtest());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSptIdproceso();
         result = 37 * result + (int) this.getSptIdtest();
         return result;
   }   


}


