package com.grupobios.bioslis.entity;
// Generated 17-10-2022 22:44:33 by Hibernate Tools 4.3.1



/**
 * SigmaProcesotestconversion generated by hbm2java
 */
public class SigmaProcesotestconversion  implements java.io.Serializable {


     private SigmaProcesotestconversionId id;
     private SigmaProcesostest sigmaProcesostest;
     private LdvTiposcondicion ldvTiposcondicion;
     private LdvOperacionesmath ldvOperacionesmath;
     private String sptcValorentrada;
     private String sptcValorsalida;
     private String sptcCriticosn;
     private String sptcReprocesarsn;
     private String sptcBloquearsn;
     private String sptcFirmarsn;
     private String sptcCondicionalsn;
     private String sptcCalculosn;
     private Integer sptcValoroperando;

    public SigmaProcesotestconversion() {
    }

	
    public SigmaProcesotestconversion(SigmaProcesotestconversionId id, SigmaProcesostest sigmaProcesostest) {
        this.id = id;
        this.sigmaProcesostest = sigmaProcesostest;
    }
    public SigmaProcesotestconversion(SigmaProcesotestconversionId id, SigmaProcesostest sigmaProcesostest, LdvTiposcondicion ldvTiposcondicion, LdvOperacionesmath ldvOperacionesmath, String sptcValorentrada, String sptcValorsalida, String sptcCriticosn, String sptcReprocesarsn, String sptcBloquearsn, String sptcFirmarsn, String sptcCondicionalsn, String sptcCalculosn, Integer sptcValoroperando) {
       this.id = id;
       this.sigmaProcesostest = sigmaProcesostest;
       this.ldvTiposcondicion = ldvTiposcondicion;
       this.ldvOperacionesmath = ldvOperacionesmath;
       this.sptcValorentrada = sptcValorentrada;
       this.sptcValorsalida = sptcValorsalida;
       this.sptcCriticosn = sptcCriticosn;
       this.sptcReprocesarsn = sptcReprocesarsn;
       this.sptcBloquearsn = sptcBloquearsn;
       this.sptcFirmarsn = sptcFirmarsn;
       this.sptcCondicionalsn = sptcCondicionalsn;
       this.sptcCalculosn = sptcCalculosn;
       this.sptcValoroperando = sptcValoroperando;
    }
   
    public SigmaProcesotestconversionId getId() {
        return this.id;
    }
    
    public void setId(SigmaProcesotestconversionId id) {
        this.id = id;
    }
    public SigmaProcesostest getSigmaProcesostest() {
        return this.sigmaProcesostest;
    }
    
    public void setSigmaProcesostest(SigmaProcesostest sigmaProcesostest) {
        this.sigmaProcesostest = sigmaProcesostest;
    }
    public LdvTiposcondicion getLdvTiposcondicion() {
        return this.ldvTiposcondicion;
    }
    
    public void setLdvTiposcondicion(LdvTiposcondicion ldvTiposcondicion) {
        this.ldvTiposcondicion = ldvTiposcondicion;
    }
    public LdvOperacionesmath getLdvOperacionesmath() {
        return this.ldvOperacionesmath;
    }
    
    public void setLdvOperacionesmath(LdvOperacionesmath ldvOperacionesmath) {
        this.ldvOperacionesmath = ldvOperacionesmath;
    }
    public String getSptcValorentrada() {
        return this.sptcValorentrada;
    }
    
    public void setSptcValorentrada(String sptcValorentrada) {
        this.sptcValorentrada = sptcValorentrada;
    }
    public String getSptcValorsalida() {
        return this.sptcValorsalida;
    }
    
    public void setSptcValorsalida(String sptcValorsalida) {
        this.sptcValorsalida = sptcValorsalida;
    }
    public String getSptcCriticosn() {
        return this.sptcCriticosn;
    }
    
    public void setSptcCriticosn(String sptcCriticosn) {
        this.sptcCriticosn = sptcCriticosn;
    }
    public String getSptcReprocesarsn() {
        return this.sptcReprocesarsn;
    }
    
    public void setSptcReprocesarsn(String sptcReprocesarsn) {
        this.sptcReprocesarsn = sptcReprocesarsn;
    }
    public String getSptcBloquearsn() {
        return this.sptcBloquearsn;
    }
    
    public void setSptcBloquearsn(String sptcBloquearsn) {
        this.sptcBloquearsn = sptcBloquearsn;
    }
    public String getSptcFirmarsn() {
        return this.sptcFirmarsn;
    }
    
    public void setSptcFirmarsn(String sptcFirmarsn) {
        this.sptcFirmarsn = sptcFirmarsn;
    }
    public String getSptcCondicionalsn() {
        return this.sptcCondicionalsn;
    }
    
    public void setSptcCondicionalsn(String sptcCondicionalsn) {
        this.sptcCondicionalsn = sptcCondicionalsn;
    }
    public String getSptcCalculosn() {
        return this.sptcCalculosn;
    }
    
    public void setSptcCalculosn(String sptcCalculosn) {
        this.sptcCalculosn = sptcCalculosn;
    }
    public Integer getSptcValoroperando() {
        return this.sptcValoroperando;
    }
    
    public void setSptcValoroperando(Integer sptcValoroperando) {
        this.sptcValoroperando = sptcValoroperando;
    }




}


