package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1



/**
 * SigmaProcesosanalizadorestest generated by hbm2java
 */
public class SigmaProcesosanalizadorestest  implements java.io.Serializable {


     private SigmaProcesosanalizadorestestId id;
     private SigmaPrefijostest sigmaPrefijostest;
     private SigmaTiposmuestras sigmaTiposmuestras;
     private SigmaProcesosanalizadores sigmaProcesosanalizadores;
     private CfgTiposderesultado cfgTiposderesultado;
     private String spatCodigorecepcion;
     private String spatCodigoenvio;
     private String spatActivo;
     private String spatConversion;
     private String spatConversiondatos;

    public SigmaProcesosanalizadorestest() {
    }

	
    public SigmaProcesosanalizadorestest(SigmaProcesosanalizadorestestId id, SigmaPrefijostest sigmaPrefijostest, SigmaTiposmuestras sigmaTiposmuestras, SigmaProcesosanalizadores sigmaProcesosanalizadores, CfgTiposderesultado cfgTiposderesultado) {
        this.id = id;
        this.sigmaPrefijostest = sigmaPrefijostest;
        this.sigmaTiposmuestras = sigmaTiposmuestras;
        this.sigmaProcesosanalizadores = sigmaProcesosanalizadores;
        this.cfgTiposderesultado = cfgTiposderesultado;
    }
    public SigmaProcesosanalizadorestest(SigmaProcesosanalizadorestestId id, SigmaPrefijostest sigmaPrefijostest, SigmaTiposmuestras sigmaTiposmuestras, SigmaProcesosanalizadores sigmaProcesosanalizadores, CfgTiposderesultado cfgTiposderesultado, String spatCodigorecepcion, String spatCodigoenvio, String spatActivo, String spatConversion, String spatConversiondatos) {
       this.id = id;
       this.sigmaPrefijostest = sigmaPrefijostest;
       this.sigmaTiposmuestras = sigmaTiposmuestras;
       this.sigmaProcesosanalizadores = sigmaProcesosanalizadores;
       this.cfgTiposderesultado = cfgTiposderesultado;
       this.spatCodigorecepcion = spatCodigorecepcion;
       this.spatCodigoenvio = spatCodigoenvio;
       this.spatActivo = spatActivo;
       this.spatConversion = spatConversion;
       this.spatConversiondatos = spatConversiondatos;
    }
   
    public SigmaProcesosanalizadorestestId getId() {
        return this.id;
    }
    
    public void setId(SigmaProcesosanalizadorestestId id) {
        this.id = id;
    }
    public SigmaPrefijostest getSigmaPrefijostest() {
        return this.sigmaPrefijostest;
    }
    
    public void setSigmaPrefijostest(SigmaPrefijostest sigmaPrefijostest) {
        this.sigmaPrefijostest = sigmaPrefijostest;
    }
    public SigmaTiposmuestras getSigmaTiposmuestras() {
        return this.sigmaTiposmuestras;
    }
    
    public void setSigmaTiposmuestras(SigmaTiposmuestras sigmaTiposmuestras) {
        this.sigmaTiposmuestras = sigmaTiposmuestras;
    }
    public SigmaProcesosanalizadores getSigmaProcesosanalizadores() {
        return this.sigmaProcesosanalizadores;
    }
    
    public void setSigmaProcesosanalizadores(SigmaProcesosanalizadores sigmaProcesosanalizadores) {
        this.sigmaProcesosanalizadores = sigmaProcesosanalizadores;
    }
    public CfgTiposderesultado getCfgTiposderesultado() {
        return this.cfgTiposderesultado;
    }
    
    public void setCfgTiposderesultado(CfgTiposderesultado cfgTiposderesultado) {
        this.cfgTiposderesultado = cfgTiposderesultado;
    }
    public String getSpatCodigorecepcion() {
        return this.spatCodigorecepcion;
    }
    
    public void setSpatCodigorecepcion(String spatCodigorecepcion) {
        this.spatCodigorecepcion = spatCodigorecepcion;
    }
    public String getSpatCodigoenvio() {
        return this.spatCodigoenvio;
    }
    
    public void setSpatCodigoenvio(String spatCodigoenvio) {
        this.spatCodigoenvio = spatCodigoenvio;
    }
    public String getSpatActivo() {
        return this.spatActivo;
    }
    
    public void setSpatActivo(String spatActivo) {
        this.spatActivo = spatActivo;
    }
    public String getSpatConversion() {
        return this.spatConversion;
    }
    
    public void setSpatConversion(String spatConversion) {
        this.spatConversion = spatConversion;
    }
    public String getSpatConversiondatos() {
        return this.spatConversiondatos;
    }
    
    public void setSpatConversiondatos(String spatConversiondatos) {
        this.spatConversiondatos = spatConversiondatos;
    }




}


