package com.grupobios.bioslis.entity;
// Generated 16-08-2021 14:22:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SistemaConfiguracionestacion generated by hbm2java
 */
public class SistemaConfiguracionestacion  implements java.io.Serializable {


     private short sceIdestacion;
     private String sceNumeroestacion;
     private String sceDescripcion;
     private Integer sceIdprocedencia;
     private String sceUbicacion;
     private Byte sceIdtipoatencion;
     private Short sceIdconvenio;
     private String sceImpresorainformeresul;
     private String sceImpresoralistatrabajo;
     private String sceImpresoracomprobantes;
     private String sceImpresoralistaestadisticas;
     private String sceImpresoracodigobarras;
     private String sceRordenimprimecodigobarras;
     private String sceRordenimprimecomprobante;
     private String sceRordenimprimeordentrabajo;
     private String sceDirectorioreportes;
     private String sceDirectorioreportesservidor;
     private String sceCheckcriticos;
     private Short sceCheckcriticosseg;
     private String sceChecknormales;
     private Short sceChecknormalesseg;
     private String sceCheckexpirados;
     private Short sceCheckexpiradosseg;
     private String sceActualizahora;
     private String sceHostregorden;
     private String sceHostrecepcionmuestra;
     private String sceActualizareportes;
     private Date sceFechaultimaactualizacion;
     private String sceMensajeria;
     private Short sceMensajeriacheckeseg;
     private String sceInactividad;
     private Byte sceInactividadmin;
     private Byte sceInactividadfoto;
     private Short sceIdservicio;
     private String sceFijarservicio;
     private String sceBiometria;
     private String sceScanner;
     private String sceScannerrutaimagen;
     private String sceHosttomamuestra;
     private String sceComprobantevoucher;
     private String sceImpresoravoucher;
     private String sceRordenimprimecomprobemail;
     private Boolean sceRordenimprimecomprobcopia;
     private String sceRordenimprimecomprobgarant;
     private Boolean sceRordenimpcomprgarantcopias;
     private Long sceRordenimprime;
     private String sceTmactualizacion;
     private Short sceTmactualizacionseg;
     private String sceEtiquetaordenmedica;
     private Byte sceScannertiempocreacionseg;
     private String sceEtiquetadocumento;
     private String sceLicenciapersonaautoriza;
     private String sceLicenciamodo;
     private Integer sceLicencianumero;
     private Date sceLicenciafecha;
     private Short sceTicketbox;

    public SistemaConfiguracionestacion() {
    }

	
    public SistemaConfiguracionestacion(short sceIdestacion) {
        this.sceIdestacion = sceIdestacion;
    }
    public SistemaConfiguracionestacion(short sceIdestacion, String sceNumeroestacion, String sceDescripcion, Integer sceIdprocedencia, String sceUbicacion, Byte sceIdtipoatencion, Short sceIdconvenio, String sceImpresorainformeresul, String sceImpresoralistatrabajo, String sceImpresoracomprobantes, String sceImpresoralistaestadisticas, String sceImpresoracodigobarras, String sceRordenimprimecodigobarras, String sceRordenimprimecomprobante, String sceRordenimprimeordentrabajo, String sceDirectorioreportes, String sceDirectorioreportesservidor, String sceCheckcriticos, Short sceCheckcriticosseg, String sceChecknormales, Short sceChecknormalesseg, String sceCheckexpirados, Short sceCheckexpiradosseg, String sceActualizahora, String sceHostregorden, String sceHostrecepcionmuestra, String sceActualizareportes, Date sceFechaultimaactualizacion, String sceMensajeria, Short sceMensajeriacheckeseg, String sceInactividad, Byte sceInactividadmin, Byte sceInactividadfoto, Short sceIdservicio, String sceFijarservicio, String sceBiometria, String sceScanner, String sceScannerrutaimagen, String sceHosttomamuestra, String sceComprobantevoucher, String sceImpresoravoucher, String sceRordenimprimecomprobemail, Boolean sceRordenimprimecomprobcopia, String sceRordenimprimecomprobgarant, Boolean sceRordenimpcomprgarantcopias, Long sceRordenimprime, String sceTmactualizacion, Short sceTmactualizacionseg, String sceEtiquetaordenmedica, Byte sceScannertiempocreacionseg, String sceEtiquetadocumento, String sceLicenciapersonaautoriza, String sceLicenciamodo, Integer sceLicencianumero, Date sceLicenciafecha, Short sceTicketbox) {
       this.sceIdestacion = sceIdestacion;
       this.sceNumeroestacion = sceNumeroestacion;
       this.sceDescripcion = sceDescripcion;
       this.sceIdprocedencia = sceIdprocedencia;
       this.sceUbicacion = sceUbicacion;
       this.sceIdtipoatencion = sceIdtipoatencion;
       this.sceIdconvenio = sceIdconvenio;
       this.sceImpresorainformeresul = sceImpresorainformeresul;
       this.sceImpresoralistatrabajo = sceImpresoralistatrabajo;
       this.sceImpresoracomprobantes = sceImpresoracomprobantes;
       this.sceImpresoralistaestadisticas = sceImpresoralistaestadisticas;
       this.sceImpresoracodigobarras = sceImpresoracodigobarras;
       this.sceRordenimprimecodigobarras = sceRordenimprimecodigobarras;
       this.sceRordenimprimecomprobante = sceRordenimprimecomprobante;
       this.sceRordenimprimeordentrabajo = sceRordenimprimeordentrabajo;
       this.sceDirectorioreportes = sceDirectorioreportes;
       this.sceDirectorioreportesservidor = sceDirectorioreportesservidor;
       this.sceCheckcriticos = sceCheckcriticos;
       this.sceCheckcriticosseg = sceCheckcriticosseg;
       this.sceChecknormales = sceChecknormales;
       this.sceChecknormalesseg = sceChecknormalesseg;
       this.sceCheckexpirados = sceCheckexpirados;
       this.sceCheckexpiradosseg = sceCheckexpiradosseg;
       this.sceActualizahora = sceActualizahora;
       this.sceHostregorden = sceHostregorden;
       this.sceHostrecepcionmuestra = sceHostrecepcionmuestra;
       this.sceActualizareportes = sceActualizareportes;
       this.sceFechaultimaactualizacion = sceFechaultimaactualizacion;
       this.sceMensajeria = sceMensajeria;
       this.sceMensajeriacheckeseg = sceMensajeriacheckeseg;
       this.sceInactividad = sceInactividad;
       this.sceInactividadmin = sceInactividadmin;
       this.sceInactividadfoto = sceInactividadfoto;
       this.sceIdservicio = sceIdservicio;
       this.sceFijarservicio = sceFijarservicio;
       this.sceBiometria = sceBiometria;
       this.sceScanner = sceScanner;
       this.sceScannerrutaimagen = sceScannerrutaimagen;
       this.sceHosttomamuestra = sceHosttomamuestra;
       this.sceComprobantevoucher = sceComprobantevoucher;
       this.sceImpresoravoucher = sceImpresoravoucher;
       this.sceRordenimprimecomprobemail = sceRordenimprimecomprobemail;
       this.sceRordenimprimecomprobcopia = sceRordenimprimecomprobcopia;
       this.sceRordenimprimecomprobgarant = sceRordenimprimecomprobgarant;
       this.sceRordenimpcomprgarantcopias = sceRordenimpcomprgarantcopias;
       this.sceRordenimprime = sceRordenimprime;
       this.sceTmactualizacion = sceTmactualizacion;
       this.sceTmactualizacionseg = sceTmactualizacionseg;
       this.sceEtiquetaordenmedica = sceEtiquetaordenmedica;
       this.sceScannertiempocreacionseg = sceScannertiempocreacionseg;
       this.sceEtiquetadocumento = sceEtiquetadocumento;
       this.sceLicenciapersonaautoriza = sceLicenciapersonaautoriza;
       this.sceLicenciamodo = sceLicenciamodo;
       this.sceLicencianumero = sceLicencianumero;
       this.sceLicenciafecha = sceLicenciafecha;
       this.sceTicketbox = sceTicketbox;
    }
   
    public short getSceIdestacion() {
        return this.sceIdestacion;
    }
    
    public void setSceIdestacion(short sceIdestacion) {
        this.sceIdestacion = sceIdestacion;
    }
    public String getSceNumeroestacion() {
        return this.sceNumeroestacion;
    }
    
    public void setSceNumeroestacion(String sceNumeroestacion) {
        this.sceNumeroestacion = sceNumeroestacion;
    }
    public String getSceDescripcion() {
        return this.sceDescripcion;
    }
    
    public void setSceDescripcion(String sceDescripcion) {
        this.sceDescripcion = sceDescripcion;
    }
    public Integer getSceIdprocedencia() {
        return this.sceIdprocedencia;
    }
    
    public void setSceIdprocedencia(Integer sceIdprocedencia) {
        this.sceIdprocedencia = sceIdprocedencia;
    }
    public String getSceUbicacion() {
        return this.sceUbicacion;
    }
    
    public void setSceUbicacion(String sceUbicacion) {
        this.sceUbicacion = sceUbicacion;
    }
    public Byte getSceIdtipoatencion() {
        return this.sceIdtipoatencion;
    }
    
    public void setSceIdtipoatencion(Byte sceIdtipoatencion) {
        this.sceIdtipoatencion = sceIdtipoatencion;
    }
    public Short getSceIdconvenio() {
        return this.sceIdconvenio;
    }
    
    public void setSceIdconvenio(Short sceIdconvenio) {
        this.sceIdconvenio = sceIdconvenio;
    }
    public String getSceImpresorainformeresul() {
        return this.sceImpresorainformeresul;
    }
    
    public void setSceImpresorainformeresul(String sceImpresorainformeresul) {
        this.sceImpresorainformeresul = sceImpresorainformeresul;
    }
    public String getSceImpresoralistatrabajo() {
        return this.sceImpresoralistatrabajo;
    }
    
    public void setSceImpresoralistatrabajo(String sceImpresoralistatrabajo) {
        this.sceImpresoralistatrabajo = sceImpresoralistatrabajo;
    }
    public String getSceImpresoracomprobantes() {
        return this.sceImpresoracomprobantes;
    }
    
    public void setSceImpresoracomprobantes(String sceImpresoracomprobantes) {
        this.sceImpresoracomprobantes = sceImpresoracomprobantes;
    }
    public String getSceImpresoralistaestadisticas() {
        return this.sceImpresoralistaestadisticas;
    }
    
    public void setSceImpresoralistaestadisticas(String sceImpresoralistaestadisticas) {
        this.sceImpresoralistaestadisticas = sceImpresoralistaestadisticas;
    }
    public String getSceImpresoracodigobarras() {
        return this.sceImpresoracodigobarras;
    }
    
    public void setSceImpresoracodigobarras(String sceImpresoracodigobarras) {
        this.sceImpresoracodigobarras = sceImpresoracodigobarras;
    }
    public String getSceRordenimprimecodigobarras() {
        return this.sceRordenimprimecodigobarras;
    }
    
    public void setSceRordenimprimecodigobarras(String sceRordenimprimecodigobarras) {
        this.sceRordenimprimecodigobarras = sceRordenimprimecodigobarras;
    }
    public String getSceRordenimprimecomprobante() {
        return this.sceRordenimprimecomprobante;
    }
    
    public void setSceRordenimprimecomprobante(String sceRordenimprimecomprobante) {
        this.sceRordenimprimecomprobante = sceRordenimprimecomprobante;
    }
    public String getSceRordenimprimeordentrabajo() {
        return this.sceRordenimprimeordentrabajo;
    }
    
    public void setSceRordenimprimeordentrabajo(String sceRordenimprimeordentrabajo) {
        this.sceRordenimprimeordentrabajo = sceRordenimprimeordentrabajo;
    }
    public String getSceDirectorioreportes() {
        return this.sceDirectorioreportes;
    }
    
    public void setSceDirectorioreportes(String sceDirectorioreportes) {
        this.sceDirectorioreportes = sceDirectorioreportes;
    }
    public String getSceDirectorioreportesservidor() {
        return this.sceDirectorioreportesservidor;
    }
    
    public void setSceDirectorioreportesservidor(String sceDirectorioreportesservidor) {
        this.sceDirectorioreportesservidor = sceDirectorioreportesservidor;
    }
    public String getSceCheckcriticos() {
        return this.sceCheckcriticos;
    }
    
    public void setSceCheckcriticos(String sceCheckcriticos) {
        this.sceCheckcriticos = sceCheckcriticos;
    }
    public Short getSceCheckcriticosseg() {
        return this.sceCheckcriticosseg;
    }
    
    public void setSceCheckcriticosseg(Short sceCheckcriticosseg) {
        this.sceCheckcriticosseg = sceCheckcriticosseg;
    }
    public String getSceChecknormales() {
        return this.sceChecknormales;
    }
    
    public void setSceChecknormales(String sceChecknormales) {
        this.sceChecknormales = sceChecknormales;
    }
    public Short getSceChecknormalesseg() {
        return this.sceChecknormalesseg;
    }
    
    public void setSceChecknormalesseg(Short sceChecknormalesseg) {
        this.sceChecknormalesseg = sceChecknormalesseg;
    }
    public String getSceCheckexpirados() {
        return this.sceCheckexpirados;
    }
    
    public void setSceCheckexpirados(String sceCheckexpirados) {
        this.sceCheckexpirados = sceCheckexpirados;
    }
    public Short getSceCheckexpiradosseg() {
        return this.sceCheckexpiradosseg;
    }
    
    public void setSceCheckexpiradosseg(Short sceCheckexpiradosseg) {
        this.sceCheckexpiradosseg = sceCheckexpiradosseg;
    }
    public String getSceActualizahora() {
        return this.sceActualizahora;
    }
    
    public void setSceActualizahora(String sceActualizahora) {
        this.sceActualizahora = sceActualizahora;
    }
    public String getSceHostregorden() {
        return this.sceHostregorden;
    }
    
    public void setSceHostregorden(String sceHostregorden) {
        this.sceHostregorden = sceHostregorden;
    }
    public String getSceHostrecepcionmuestra() {
        return this.sceHostrecepcionmuestra;
    }
    
    public void setSceHostrecepcionmuestra(String sceHostrecepcionmuestra) {
        this.sceHostrecepcionmuestra = sceHostrecepcionmuestra;
    }
    public String getSceActualizareportes() {
        return this.sceActualizareportes;
    }
    
    public void setSceActualizareportes(String sceActualizareportes) {
        this.sceActualizareportes = sceActualizareportes;
    }
    public Date getSceFechaultimaactualizacion() {
        return this.sceFechaultimaactualizacion;
    }
    
    public void setSceFechaultimaactualizacion(Date sceFechaultimaactualizacion) {
        this.sceFechaultimaactualizacion = sceFechaultimaactualizacion;
    }
    public String getSceMensajeria() {
        return this.sceMensajeria;
    }
    
    public void setSceMensajeria(String sceMensajeria) {
        this.sceMensajeria = sceMensajeria;
    }
    public Short getSceMensajeriacheckeseg() {
        return this.sceMensajeriacheckeseg;
    }
    
    public void setSceMensajeriacheckeseg(Short sceMensajeriacheckeseg) {
        this.sceMensajeriacheckeseg = sceMensajeriacheckeseg;
    }
    public String getSceInactividad() {
        return this.sceInactividad;
    }
    
    public void setSceInactividad(String sceInactividad) {
        this.sceInactividad = sceInactividad;
    }
    public Byte getSceInactividadmin() {
        return this.sceInactividadmin;
    }
    
    public void setSceInactividadmin(Byte sceInactividadmin) {
        this.sceInactividadmin = sceInactividadmin;
    }
    public Byte getSceInactividadfoto() {
        return this.sceInactividadfoto;
    }
    
    public void setSceInactividadfoto(Byte sceInactividadfoto) {
        this.sceInactividadfoto = sceInactividadfoto;
    }
    public Short getSceIdservicio() {
        return this.sceIdservicio;
    }
    
    public void setSceIdservicio(Short sceIdservicio) {
        this.sceIdservicio = sceIdservicio;
    }
    public String getSceFijarservicio() {
        return this.sceFijarservicio;
    }
    
    public void setSceFijarservicio(String sceFijarservicio) {
        this.sceFijarservicio = sceFijarservicio;
    }
    public String getSceBiometria() {
        return this.sceBiometria;
    }
    
    public void setSceBiometria(String sceBiometria) {
        this.sceBiometria = sceBiometria;
    }
    public String getSceScanner() {
        return this.sceScanner;
    }
    
    public void setSceScanner(String sceScanner) {
        this.sceScanner = sceScanner;
    }
    public String getSceScannerrutaimagen() {
        return this.sceScannerrutaimagen;
    }
    
    public void setSceScannerrutaimagen(String sceScannerrutaimagen) {
        this.sceScannerrutaimagen = sceScannerrutaimagen;
    }
    public String getSceHosttomamuestra() {
        return this.sceHosttomamuestra;
    }
    
    public void setSceHosttomamuestra(String sceHosttomamuestra) {
        this.sceHosttomamuestra = sceHosttomamuestra;
    }
    public String getSceComprobantevoucher() {
        return this.sceComprobantevoucher;
    }
    
    public void setSceComprobantevoucher(String sceComprobantevoucher) {
        this.sceComprobantevoucher = sceComprobantevoucher;
    }
    public String getSceImpresoravoucher() {
        return this.sceImpresoravoucher;
    }
    
    public void setSceImpresoravoucher(String sceImpresoravoucher) {
        this.sceImpresoravoucher = sceImpresoravoucher;
    }
    public String getSceRordenimprimecomprobemail() {
        return this.sceRordenimprimecomprobemail;
    }
    
    public void setSceRordenimprimecomprobemail(String sceRordenimprimecomprobemail) {
        this.sceRordenimprimecomprobemail = sceRordenimprimecomprobemail;
    }
    public Boolean getSceRordenimprimecomprobcopia() {
        return this.sceRordenimprimecomprobcopia;
    }
    
    public void setSceRordenimprimecomprobcopia(Boolean sceRordenimprimecomprobcopia) {
        this.sceRordenimprimecomprobcopia = sceRordenimprimecomprobcopia;
    }
    public String getSceRordenimprimecomprobgarant() {
        return this.sceRordenimprimecomprobgarant;
    }
    
    public void setSceRordenimprimecomprobgarant(String sceRordenimprimecomprobgarant) {
        this.sceRordenimprimecomprobgarant = sceRordenimprimecomprobgarant;
    }
    public Boolean getSceRordenimpcomprgarantcopias() {
        return this.sceRordenimpcomprgarantcopias;
    }
    
    public void setSceRordenimpcomprgarantcopias(Boolean sceRordenimpcomprgarantcopias) {
        this.sceRordenimpcomprgarantcopias = sceRordenimpcomprgarantcopias;
    }
    public Long getSceRordenimprime() {
        return this.sceRordenimprime;
    }
    
    public void setSceRordenimprime(Long sceRordenimprime) {
        this.sceRordenimprime = sceRordenimprime;
    }
    public String getSceTmactualizacion() {
        return this.sceTmactualizacion;
    }
    
    public void setSceTmactualizacion(String sceTmactualizacion) {
        this.sceTmactualizacion = sceTmactualizacion;
    }
    public Short getSceTmactualizacionseg() {
        return this.sceTmactualizacionseg;
    }
    
    public void setSceTmactualizacionseg(Short sceTmactualizacionseg) {
        this.sceTmactualizacionseg = sceTmactualizacionseg;
    }
    public String getSceEtiquetaordenmedica() {
        return this.sceEtiquetaordenmedica;
    }
    
    public void setSceEtiquetaordenmedica(String sceEtiquetaordenmedica) {
        this.sceEtiquetaordenmedica = sceEtiquetaordenmedica;
    }
    public Byte getSceScannertiempocreacionseg() {
        return this.sceScannertiempocreacionseg;
    }
    
    public void setSceScannertiempocreacionseg(Byte sceScannertiempocreacionseg) {
        this.sceScannertiempocreacionseg = sceScannertiempocreacionseg;
    }
    public String getSceEtiquetadocumento() {
        return this.sceEtiquetadocumento;
    }
    
    public void setSceEtiquetadocumento(String sceEtiquetadocumento) {
        this.sceEtiquetadocumento = sceEtiquetadocumento;
    }
    public String getSceLicenciapersonaautoriza() {
        return this.sceLicenciapersonaautoriza;
    }
    
    public void setSceLicenciapersonaautoriza(String sceLicenciapersonaautoriza) {
        this.sceLicenciapersonaautoriza = sceLicenciapersonaautoriza;
    }
    public String getSceLicenciamodo() {
        return this.sceLicenciamodo;
    }
    
    public void setSceLicenciamodo(String sceLicenciamodo) {
        this.sceLicenciamodo = sceLicenciamodo;
    }
    public Integer getSceLicencianumero() {
        return this.sceLicencianumero;
    }
    
    public void setSceLicencianumero(Integer sceLicencianumero) {
        this.sceLicencianumero = sceLicencianumero;
    }
    public Date getSceLicenciafecha() {
        return this.sceLicenciafecha;
    }
    
    public void setSceLicenciafecha(Date sceLicenciafecha) {
        this.sceLicenciafecha = sceLicenciafecha;
    }
    public Short getSceTicketbox() {
        return this.sceTicketbox;
    }
    
    public void setSceTicketbox(Short sceTicketbox) {
        this.sceTicketbox = sceTicketbox;
    }




}


