package com.grupobios.bioslis.entity;
// Generated 22-04-2020 16:13:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Testeojan generated by hbm2java
 */
public class Testeojan  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal edad;
     private String nombre;
     private String apellido;

    public Testeojan() {
    }

	
    public Testeojan(BigDecimal id) {
        this.id = id;
    }
    public Testeojan(BigDecimal id, BigDecimal edad, String nombre, String apellido) {
       this.id = id;
       this.edad = edad;
       this.nombre = nombre;
       this.apellido = apellido;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public BigDecimal getEdad() {
        return this.edad;
    }
    
    public void setEdad(BigDecimal edad) {
        this.edad = edad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }




}


