package com.grupobios.bioslis.dto;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.grupobios.bioslis.entity.CfgCentrosdesalud;
import com.grupobios.bioslis.entity.CfgConvenios;
import com.grupobios.bioslis.entity.CfgDerivadores;
import com.grupobios.bioslis.entity.CfgExamenes;
import com.grupobios.bioslis.entity.CfgExamenesconjuntos;
import com.grupobios.bioslis.entity.CfgGruposexamenesfonasa;
import com.grupobios.bioslis.entity.CfgGruposmuestras;
import com.grupobios.bioslis.entity.CfgMuestras;
import com.grupobios.bioslis.entity.CfgPesquisas;
import com.grupobios.bioslis.entity.CfgSecciones;
import com.grupobios.bioslis.entity.LdvFormatos;
import com.grupobios.bioslis.entity.LdvGruposexamenes;
import com.grupobios.bioslis.entity.LdvIndicacionesexamenes;
import com.grupobios.bioslis.entity.LdvLoinc;
import com.grupobios.bioslis.entity.LdvTiposexamenes;

// Generated Jun 26, 2020 11:17:59 AM by Hibernate Tools 4.3.1

/**
 * CfgExamenes generated by hbm2java
 */
public class CfgProcedenciasDTO {
	private BigDecimal CP_IDPROCEDENCIA;

	private String CP_DESCRIPCION;
	//agregado x jan
	  private short cfgCentroDeSalud;
	  private short cfgConvenios;
	  private String cpCodigo;
	  private Integer cpSort;
	  private String cpActivo;
	  private String cpTextoInforme;
	  private String cpCodigoGrupo;
	  private String cpMembrete;
	  private String cpProcedenciarestringida;
	  private String cpHost;
	  private String cpHost2;
	  private String cpHost3;
	  private String cpEmail;
	  private String cpTomamuestraautomatica;
	  //se agrego nuevamente descp y id ya que el json no los tomaba
	  private BigDecimal cpidProcedencia;
	  private String cpDesc;

	  
	  
	public BigDecimal getCpidProcedencia() {
		return cpidProcedencia;
	}

	public void setCpidProcedencia(BigDecimal cpidProcedencia) {
		this.cpidProcedencia = cpidProcedencia;
	}

	public String getCpDesc() {
		return cpDesc;
	}

	public void setCpDesc(String cpDesc) {
		this.cpDesc = cpDesc;
	}

	public String getCpTomamuestraautomatica() {
		return cpTomamuestraautomatica;
	}

	public void setCpTomamuestraautomatica(String cpTomamuestraautomatica) {
		this.cpTomamuestraautomatica = cpTomamuestraautomatica;
	}

	public BigDecimal getCP_IDPROCEDENCIA() {
		return CP_IDPROCEDENCIA;
	}

	public void setCP_IDPROCEDENCIA(BigDecimal cP_IDPROCEDENCIA) {
		CP_IDPROCEDENCIA = cP_IDPROCEDENCIA;
	}

	public String getCP_DESCRIPCION() {
		return CP_DESCRIPCION;
	}

	public void setCP_DESCRIPCION(String cP_DESCRIPCION) {
		CP_DESCRIPCION = cP_DESCRIPCION;
	}

	public short getCfgCentroDeSalud() {
		return cfgCentroDeSalud;
	}

	public void setCfgCentroDeSalud(short cfgCentroDeSalud) {
		this.cfgCentroDeSalud = cfgCentroDeSalud;
	}

	public short getCfgConvenios() {
		return cfgConvenios;
	}

	public void setCfgConvenios(short cfgConvenios) {
		this.cfgConvenios = cfgConvenios;
	}

	public String getCpCodigo() {
		return cpCodigo;
	}

	public void setCpCodigo(String cpCodigo) {
		this.cpCodigo = cpCodigo;
	}

	public Integer getCpSort() {
		return cpSort;
	}

	public void setCpSort(Integer cpSort) {
		this.cpSort = cpSort;
	}

	public String getCpActivo() {
		return cpActivo;
	}

	public void setCpActivo(String cpActivo) {
		this.cpActivo = cpActivo;
	}

	public String getCpTextoInforme() {
		return cpTextoInforme;
	}

	public void setCpTextoInforme(String cpTextoInforme) {
		this.cpTextoInforme = cpTextoInforme;
	}

	public String getCpCodigoGrupo() {
		return cpCodigoGrupo;
	}

	public void setCpCodigoGrupo(String cpCodigoGrupo) {
		this.cpCodigoGrupo = cpCodigoGrupo;
	}

	public String getCpMembrete() {
		return cpMembrete;
	}

	public void setCpMembrete(String cpMembrete) {
		this.cpMembrete = cpMembrete;
	}

	public String getCpProcedenciarestringida() {
		return cpProcedenciarestringida;
	}

	public void setCpProcedenciarestringida(String cpProcedenciarestringida) {
		this.cpProcedenciarestringida = cpProcedenciarestringida;
	}

	public String getCpHost() {
		return cpHost;
	}

	public void setCpHost(String cpHost) {
		this.cpHost = cpHost;
	}

	public String getCpHost2() {
		return cpHost2;
	}

	public void setCpHost2(String cpHost2) {
		this.cpHost2 = cpHost2;
	}

	public String getCpHost3() {
		return cpHost3;
	}

	public void setCpHost3(String cpHost3) {
		this.cpHost3 = cpHost3;
	}

	public String getCpEmail() {
		return cpEmail;
	}

	public void setCpEmail(String cpEmail) {
		this.cpEmail = cpEmail;
	}

	
	
	
	

}
