package com.grupobios.bioslis.dto;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.grupobios.bioslis.entity.CfgCentrosdesalud;
import com.grupobios.bioslis.entity.CfgConvenios;
import com.grupobios.bioslis.entity.CfgDerivadores;
import com.grupobios.bioslis.entity.CfgExamenes;
import com.grupobios.bioslis.entity.CfgExamenesconjuntos;
import com.grupobios.bioslis.entity.CfgGruposexamenesfonasa;
import com.grupobios.bioslis.entity.CfgGruposmuestras;
import com.grupobios.bioslis.entity.CfgMuestras;
import com.grupobios.bioslis.entity.CfgPesquisas;
import com.grupobios.bioslis.entity.CfgSecciones;
import com.grupobios.bioslis.entity.LdvFormatos;
import com.grupobios.bioslis.entity.LdvGruposexamenes;
import com.grupobios.bioslis.entity.LdvIndicacionesexamenes;
import com.grupobios.bioslis.entity.LdvLoinc;
import com.grupobios.bioslis.entity.LdvTiposexamenes;

// Generated Jun 26, 2020 11:17:59 AM by Hibernate Tools 4.3.1

/**
 * CfgExamenes generated by hbm2java
 */
public class CfgServiciosDTO {
	private int csIdservicio;
    private int cfgCentrosdesalud;
	private String csCodigo;
	private String csDescripcion;
	private String csEmail;
	private String csActivo;
	private int csSort;
	private String csHost;
	private String csHostmicro;
	private String csHost2;
	private String csHost3;
	private String csGrupo;
	private String csGrupo2;
	private String csUrgente;
	private String csIndicador;
	private String csImpresora;
	private String csImprimeconfidenciales;
	public int getCsIdservicio() {
		return csIdservicio;
	}
	public void setCsIdservicio(int csIdservicio) {
		this.csIdservicio = csIdservicio;
	}
	public int getCfgCentrosdesalud() {
		return cfgCentrosdesalud;
	}
	public void setCfgCentrosdesalud(int cfgCentrosdesalud) {
		this.cfgCentrosdesalud = cfgCentrosdesalud;
	}
	public String getCsCodigo() {
		return csCodigo;
	}
	public void setCsCodigo(String csCodigo) {
		this.csCodigo = csCodigo;
	}
	public String getCsDescripcion() {
		return csDescripcion;
	}
	public void setCsDescripcion(String csDescripcion) {
		this.csDescripcion = csDescripcion;
	}
	public String getCsEmail() {
		return csEmail;
	}
	public void setCsEmail(String csEmail) {
		this.csEmail = csEmail;
	}
	public String getCsActivo() {
		return csActivo;
	}
	public void setCsActivo(String csActivo) {
		this.csActivo = csActivo;
	}
	public int getCsSort() {
		return csSort;
	}
	public void setCsSort(int csSort) {
		this.csSort = csSort;
	}
	public String getCsHost() {
		return csHost;
	}
	public void setCsHost(String csHost) {
		this.csHost = csHost;
	}
	public String getCsHostmicro() {
		return csHostmicro;
	}
	public void setCsHostmicro(String csHostmicro) {
		this.csHostmicro = csHostmicro;
	}
	public String getCsHost2() {
		return csHost2;
	}
	public void setCsHost2(String csHost2) {
		this.csHost2 = csHost2;
	}
	public String getCsHost3() {
		return csHost3;
	}
	public void setCsHost3(String csHost3) {
		this.csHost3 = csHost3;
	}
	public String getCsGrupo() {
		return csGrupo;
	}
	public void setCsGrupo(String csGrupo) {
		this.csGrupo = csGrupo;
	}
	public String getCsGrupo2() {
		return csGrupo2;
	}
	public void setCsGrupo2(String csGrupo2) {
		this.csGrupo2 = csGrupo2;
	}
	public String getCsUrgente() {
		return csUrgente;
	}
	public void setCsUrgente(String csUrgente) {
		this.csUrgente = csUrgente;
	}
	public String getCsIndicador() {
		return csIndicador;
	}
	public void setCsIndicador(String csIndicador) {
		this.csIndicador = csIndicador;
	}
	public String getCsImpresora() {
		return csImpresora;
	}
	public void setCsImpresora(String csImpresora) {
		this.csImpresora = csImpresora;
	}
	public String getCsImprimeconfidenciales() {
		return csImprimeconfidenciales;
	}
	public void setCsImprimeconfidenciales(String csImprimeconfidenciales) {
		this.csImprimeconfidenciales = csImprimeconfidenciales;
	}
}
