package com.grupobios.bioslis.dto;
// Generated 30-03-2020 9:50:08 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * DatosPacientes generated by hbm2java
 */
public class DatosPacienteOrdenDTO {

  private String DP_NOMBRES;
  private String DP_PRIMERAPELLIDO;
  private String DP_SEGUNDOAPELLIDO;
  private BigDecimal DP_IDSEXO;
  private Date DP_FNACIMIENTO;
  private String SDP_FNACIMIENTO;
  private String LDV_INISEXO;
  private String LDVS_CODIGO;

  public String getLDVS_CODIGO() {
    return LDVS_CODIGO;
  }

  public void setLDVS_CODIGO(String lDVS_CODIGO) {
    LDVS_CODIGO = lDVS_CODIGO;
  }

  /**
   * @return the dP_NOMBRES
   */
  public String getDP_NOMBRES() {
    return DP_NOMBRES;
  }

  /**
   * @param dP_NOMBRES the dP_NOMBRES to set
   */
  public void setDP_NOMBRES(String dP_NOMBRES) {
    DP_NOMBRES = dP_NOMBRES;
  }

  /**
   * @return the dP_PRIMERAPELLIDO
   */
  public String getDP_PRIMERAPELLIDO() {
    return DP_PRIMERAPELLIDO;
  }

  /**
   * @param dP_PRIMERAPELLIDO the dP_PRIMERAPELLIDO to set
   */
  public void setDP_PRIMERAPELLIDO(String dP_PRIMERAPELLIDO) {
    DP_PRIMERAPELLIDO = dP_PRIMERAPELLIDO;
  }

  /**
   * @return the dP_SEGUNDOAPELLIDO
   */
  public String getDP_SEGUNDOAPELLIDO() {
    return DP_SEGUNDOAPELLIDO;
  }

  /**
   * @param dP_SEGUNDOAPELLIDO the dP_SEGUNDOAPELLIDO to set
   */
  public void setDP_SEGUNDOAPELLIDO(String dP_SEGUNDOAPELLIDO) {
    DP_SEGUNDOAPELLIDO = dP_SEGUNDOAPELLIDO;
  }

  /**
   * @return the dP_IDSEXO
   */
  public BigDecimal getDP_IDSEXO() {
    return DP_IDSEXO;
  }

  /**
   * @param dP_IDSEXO the dP_IDSEXO to set
   */
  public void setDP_IDSEXO(BigDecimal dP_IDSEXO) {
    DP_IDSEXO = dP_IDSEXO;
  }

  /**
   * @return the dP_FNACIMIENTO
   */
  public Date getDP_FNACIMIENTO() {
    return DP_FNACIMIENTO;
  }

  /**
   * @param dP_FNACIMIENTO the dP_FNACIMIENTO to set
   */
  public void setDP_FNACIMIENTO(Date dP_FNACIMIENTO) {
    DP_FNACIMIENTO = dP_FNACIMIENTO;
  }

  @Override
  public String toString() {
    return "DatosPacienteOrdenDTO [DP_NOMBRES=" + DP_NOMBRES + ", DP_PRIMERAPELLIDO=" + DP_PRIMERAPELLIDO
        + ", DP_SEGUNDOAPELLIDO=" + DP_SEGUNDOAPELLIDO + ", DP_IDSEXO=" + DP_IDSEXO + ", DP_FNACIMIENTO="
        + DP_FNACIMIENTO + "]";
  }

  /**
   * @return the sDP_FNACIMIENTO
   */
  public String getSDP_FNACIMIENTO() {
    return SDP_FNACIMIENTO;
  }

  /**
   * @param sDP_FNACIMIENTO the sDP_FNACIMIENTO to set
   */
  public void setSDP_FNACIMIENTO(String sDP_FNACIMIENTO) {
    SDP_FNACIMIENTO = sDP_FNACIMIENTO;
  }

  /**
   * @return the lDV_INISEXO
   */
  public String getLDV_INISEXO() {
    return LDV_INISEXO;
  }

  /**
   * @param lDV_INISEXO the lDV_INISEXO to set
   */
  public void setLDV_INISEXO(String lDV_INISEXO) {
    LDV_INISEXO = lDV_INISEXO;
  }

}
