package com.grupobios.bioslis.dto;

import java.math.BigDecimal;
import java.util.Date;

public class EtiquetaCodigoBarraDTO {

  private String CECB_CODIGO;
  private String CECB_DESCRIPCION;
  private String CECB_FONTCODIGOBARRA;
  private BigDecimal CECB_TAMANOFONTCODIGOBARRAS;
  private BigDecimal CECB_FILACODIGOBARRAS;
  private BigDecimal CECB_COLUMNACODIGOBARRAS;
  private String CECB_ACTIVOCODIGOBARRAS;
  private BigDecimal CECB_TEXTO0FILA;
  private BigDecimal CECB_TEXTO0COLUMNA;
  private String CECB_ACTIVOTEXTO0;
  private String CECB_NEGRITA0;
  private String CECB_TAMANO0;
  private BigDecimal CECB_TEXTO1FILA;
  private BigDecimal CECB_TEXTO1COLUMNA;
  private BigDecimal CECB_TEXTO1LARGO;
  private BigDecimal CECB_TEXTO1TAMANO;
  private String CECB_ACTIVOTEXTO1;
  private String CECB_NEGRITA1;
  private BigDecimal CECB_TEXTO2FILA;
  private BigDecimal CECB_TEXTO2COLUMNA;
  private BigDecimal CECB_TEXTO2LARGO;
  private BigDecimal CECB_TEXTO2TAMANO;
  private String CECB_ACTIVOTEXTO2;
  private String CECB_NEGRITA2;
  private BigDecimal CECB_TEXTO3FILA;
  private BigDecimal CECB_TEXTO3COLUMNA;
  private BigDecimal CECB_TEXTO3LARGO;
  private BigDecimal CECB_TEXTO3TAMANO;
  private String CECB_ACTIVOTEXTO3;
  private String CECB_NEGRITA3;
  private BigDecimal CECB_TEXTO4FILA;
  private BigDecimal CECB_TEXTO4COLUMNA;
  private BigDecimal CECB_TEXTO4LARGO;
  private BigDecimal CECB_TEXTO4TAMANO;
  private String CECB_ACTIVOTEXTO4;
  private String CECB_NEGRITA4;
  private BigDecimal CECB_TEXTO5FILA;
  private BigDecimal CECB_TEXTO5COLUMNA;
  private BigDecimal CECB_TEXTO5LARGO;
  private BigDecimal CECB_TEXTO5TAMANO;
  private String CECB_ACTIVOTEXTO5;
  private String CECB_NEGRITA5;
  private BigDecimal CECB_TEXTO6FILA;
  private BigDecimal CECB_TEXTO6COLUMNA;
  private BigDecimal CECB_TEXTO6LARGO;
  private BigDecimal CECB_TEXTO6TAMANO;
  private String CECB_ACTIVOTEXTO6;
  private String CECB_NEGRITA6;
  private BigDecimal CECB_TEXTO7FILA;
  private BigDecimal CECB_TEXTO7COLUMNA;
  private BigDecimal CECB_TEXTO7LARGO;
  private BigDecimal CECB_TEXTO7TAMANO;
  private String CECB_ACTIVOTEXTO7;
  private String CECB_NEGRITA7;
  private BigDecimal CECB_TEXTO8FILA;
  private BigDecimal CECB_TEXTO8COLUMNA;
  private BigDecimal CECB_TEXTO8LARGO;
  private BigDecimal CECB_TEXTO8TAMANO;
  private String CECB_ACTIVOTEXTO8;
  private String CECB_NEGRITA8;
  private BigDecimal CECB_TEXTO9FILA;
  private BigDecimal CECB_TEXTO9COLUMNA;
  private BigDecimal CECB_TEXTO9LARGO;
  private BigDecimal CECB_TEXTO9TAMANO;
  private String CECB_ACTIVOTEXTO9;
  private String CECB_NEGRITA9;
  private BigDecimal CECB_TEXTO10FILA;
  private BigDecimal CECB_TEXTO10COLUMNA;
  private BigDecimal CECB_TEXTO10LARGO;
  private BigDecimal CECB_TEXTO10TAMANO;
  private String CECB_ACTIVOTEXTO10;
  private String CECB_NEGRITA10;
  private BigDecimal CECB_TEXTO11FILA;
  private BigDecimal CECB_TEXTO11COLUMNA;
  private BigDecimal CECB_TEXTO11LARGO;
  private BigDecimal CECB_TEXTO11TAMANO;
  private String CECB_ACTIVOTEXTO11;
  private String CECB_NEGRITA11;
  private BigDecimal CECB_TEXTO12FILA;
  private BigDecimal CECB_TEXTO12COLUMNA;
  private BigDecimal CECB_TEXTO12LARGO;
  private BigDecimal CECB_TEXTO12TAMANO;
  private String CECB_ACTIVOTEXTO12;
  private String CECB_NEGRITA12;
  private BigDecimal CECB_SORT;
  private String CECB_NOTA;
  private String CECB_USUARIOREGISTRO;
  private Date CECB_FECHAREGISTRO;
  private String CECB_PROCEDENCIA;
  private String CECB_SERVICIO;
  private String CECB_TIPOPACPREFIJO;
  private String CECB_TIPOPACSUFIJO;
  private String CECB_PROCEPREFIJO;
  private String CECB_PROCESUFIJO;
  private String CECB_SERVPREFIJO;
  private String CECB_SERVSUFIJO;
  private String CECB_NOMBPREFIJO;
  private String CECB_NOMBSUFIJO;
  private String CECB_SEXOPREFIJO;
  private String CECB_SEXOSUFIJO;
  private String CECB_EDADPREFIJO;
  private String CECB_EDADSUFIJO;
  private String CECB_TIPMUEPREFIJO;
  private String CECB_TIPMUESUFIJO;
  private String CECB_ENVAPREFIJO;
  private String CECB_ENVASUFIJO;
  private String CECB_FECHAPREFIJO;
  private String CECB_FECHASUFIJO;
  private String CECB_PARAMETRIZADA;
  private String CECB_RUTPREFIJO;
  private String CECB_RUTSUFIJO;
  private BigDecimal CECB_FILANORDEN;
  private BigDecimal CECB_COLUMNANORDEN;
  private BigDecimal CECB_TEXTONORDEN;
  private BigDecimal CECB_TAMANONORDEN;
  private String CECB_ACTIVONORDEN;
  private String CECB_NEGRITANORDEN;

  public BigDecimal getCECB_FILANORDEN() {
    return CECB_FILANORDEN;
  }

  public void setCECB_FILANORDEN(BigDecimal cECB_FILANORDEN) {
    CECB_FILANORDEN = cECB_FILANORDEN;
  }

  public BigDecimal getCECB_COLUMNANORDEN() {
    return CECB_COLUMNANORDEN;
  }

  public void setCECB_COLUMNANORDEN(BigDecimal cECB_COLUMNANORDEN) {
    CECB_COLUMNANORDEN = cECB_COLUMNANORDEN;
  }

  public BigDecimal getCECB_TEXTONORDEN() {
    return CECB_TEXTONORDEN;
  }

  public void setCECB_TEXTONORDEN(BigDecimal cECB_TEXTONORDEN) {
    CECB_TEXTONORDEN = cECB_TEXTONORDEN;
  }

  public BigDecimal getCECB_TAMANONORDEN() {
    return CECB_TAMANONORDEN;
  }

  public void setCECB_TAMANONORDEN(BigDecimal cECB_TAMANONORDEN) {
    CECB_TAMANONORDEN = cECB_TAMANONORDEN;
  }

  public String getCECB_ACTIVONORDEN() {
    return CECB_ACTIVONORDEN;
  }

  public void setCECB_ACTIVONORDEN(String cECB_ACTIVONORDEN) {
    CECB_ACTIVONORDEN = cECB_ACTIVONORDEN;
  }

  public String getCECB_NEGRITANORDEN() {
    return CECB_NEGRITANORDEN;
  }

  public void setCECB_NEGRITANORDEN(String cECB_NEGRITANORDEN) {
    CECB_NEGRITANORDEN = cECB_NEGRITANORDEN;
  }

  public EtiquetaCodigoBarraDTO() {
  }

  public String getCECB_CODIGO() {
    return CECB_CODIGO;
  }

  public void setCECB_CODIGO(String cECB_CODIGO) {
    CECB_CODIGO = cECB_CODIGO;
  }

  public String getCECB_DESCRIPCION() {
    return CECB_DESCRIPCION;
  }

  public void setCECB_DESCRIPCION(String cECB_DESCRIPCION) {
    CECB_DESCRIPCION = cECB_DESCRIPCION;
  }

  public String getCECB_FONTCODIGOBARRA() {
    return CECB_FONTCODIGOBARRA;
  }

  public void setCECB_FONTCODIGOBARRA(String cECB_FONTCODIGOBARRA) {
    CECB_FONTCODIGOBARRA = cECB_FONTCODIGOBARRA;
  }

  public BigDecimal getCECB_TAMANOFONTCODIGOBARRAS() {
    return CECB_TAMANOFONTCODIGOBARRAS;
  }

  public void setCECB_TAMANOFONTCODIGOBARRAS(BigDecimal cECB_TAMANOFONTCODIGOBARRAS) {
    CECB_TAMANOFONTCODIGOBARRAS = cECB_TAMANOFONTCODIGOBARRAS;
  }

  public BigDecimal getCECB_FILACODIGOBARRAS() {
    return CECB_FILACODIGOBARRAS;
  }

  public void setCECB_FILACODIGOBARRAS(BigDecimal cECB_FILACODIGOBARRAS) {
    CECB_FILACODIGOBARRAS = cECB_FILACODIGOBARRAS;
  }

  public BigDecimal getCECB_COLUMNACODIGOBARRAS() {
    return CECB_COLUMNACODIGOBARRAS;
  }

  public void setCECB_COLUMNACODIGOBARRAS(BigDecimal cECB_COLUMNACODIGOBARRAS) {
    CECB_COLUMNACODIGOBARRAS = cECB_COLUMNACODIGOBARRAS;
  }

  public String getCECB_ACTIVOCODIGOBARRAS() {
    return CECB_ACTIVOCODIGOBARRAS;
  }

  public void setCECB_ACTIVOCODIGOBARRAS(String cECB_ACTIVOCODIGOBARRAS) {
    CECB_ACTIVOCODIGOBARRAS = cECB_ACTIVOCODIGOBARRAS;
  }

  public BigDecimal getCECB_TEXTO0FILA() {
    return CECB_TEXTO0FILA;
  }

  public void setCECB_TEXTO0FILA(BigDecimal cECB_TEXTO0FILA) {
    CECB_TEXTO0FILA = cECB_TEXTO0FILA;
  }

  public BigDecimal getCECB_TEXTO0COLUMNA() {
    return CECB_TEXTO0COLUMNA;
  }

  public void setCECB_TEXTO0COLUMNA(BigDecimal cECB_TEXTO0COLUMNA) {
    CECB_TEXTO0COLUMNA = cECB_TEXTO0COLUMNA;
  }

  public String getCECB_ACTIVOTEXTO0() {
    return CECB_ACTIVOTEXTO0;
  }

  public void setCECB_ACTIVOTEXTO0(String cECB_ACTIVOTEXTO0) {
    CECB_ACTIVOTEXTO0 = cECB_ACTIVOTEXTO0;
  }

  public String getCECB_NEGRITA0() {
    return CECB_NEGRITA0;
  }

  public void setCECB_NEGRITA0(String cECB_NEGRITA0) {
    CECB_NEGRITA0 = cECB_NEGRITA0;
  }

  public String getCECB_TAMANO0() {
    return CECB_TAMANO0;
  }

  public void setCECB_TAMANO0(String cECB_TAMANO0) {
    CECB_TAMANO0 = cECB_TAMANO0;
  }

  public BigDecimal getCECB_TEXTO1FILA() {
    return CECB_TEXTO1FILA;
  }

  public void setCECB_TEXTO1FILA(BigDecimal cECB_TEXTO1FILA) {
    CECB_TEXTO1FILA = cECB_TEXTO1FILA;
  }

  public BigDecimal getCECB_TEXTO1COLUMNA() {
    return CECB_TEXTO1COLUMNA;
  }

  public void setCECB_TEXTO1COLUMNA(BigDecimal cECB_TEXTO1COLUMNA) {
    CECB_TEXTO1COLUMNA = cECB_TEXTO1COLUMNA;
  }

  public BigDecimal getCECB_TEXTO1LARGO() {
    return CECB_TEXTO1LARGO;
  }

  public void setCECB_TEXTO1LARGO(BigDecimal cECB_TEXTO1LARGO) {
    CECB_TEXTO1LARGO = cECB_TEXTO1LARGO;
  }

  public BigDecimal getCECB_TEXTO1TAMANO() {
    return CECB_TEXTO1TAMANO;
  }

  public void setCECB_TEXTO1TAMANO(BigDecimal cECB_TEXTO1TAMANO) {
    CECB_TEXTO1TAMANO = cECB_TEXTO1TAMANO;
  }

  public String getCECB_ACTIVOTEXTO1() {
    return CECB_ACTIVOTEXTO1;
  }

  public void setCECB_ACTIVOTEXTO1(String cECB_ACTIVOTEXTO1) {
    CECB_ACTIVOTEXTO1 = cECB_ACTIVOTEXTO1;
  }

  public String getCECB_NEGRITA1() {
    return CECB_NEGRITA1;
  }

  public void setCECB_NEGRITA1(String cECB_NEGRITA1) {
    CECB_NEGRITA1 = cECB_NEGRITA1;
  }

  public BigDecimal getCECB_TEXTO2FILA() {
    return CECB_TEXTO2FILA;
  }

  public void setCECB_TEXTO2FILA(BigDecimal cECB_TEXTO2FILA) {
    CECB_TEXTO2FILA = cECB_TEXTO2FILA;
  }

  public BigDecimal getCECB_TEXTO2COLUMNA() {
    return CECB_TEXTO2COLUMNA;
  }

  public void setCECB_TEXTO2COLUMNA(BigDecimal cECB_TEXTO2COLUMNA) {
    CECB_TEXTO2COLUMNA = cECB_TEXTO2COLUMNA;
  }

  public BigDecimal getCECB_TEXTO2LARGO() {
    return CECB_TEXTO2LARGO;
  }

  public void setCECB_TEXTO2LARGO(BigDecimal cECB_TEXTO2LARGO) {
    CECB_TEXTO2LARGO = cECB_TEXTO2LARGO;
  }

  public BigDecimal getCECB_TEXTO2TAMANO() {
    return CECB_TEXTO2TAMANO;
  }

  public void setCECB_TEXTO2TAMANO(BigDecimal cECB_TEXTO2TAMANO) {
    CECB_TEXTO2TAMANO = cECB_TEXTO2TAMANO;
  }

  public String getCECB_ACTIVOTEXTO2() {
    return CECB_ACTIVOTEXTO2;
  }

  public void setCECB_ACTIVOTEXTO2(String cECB_ACTIVOTEXTO2) {
    CECB_ACTIVOTEXTO2 = cECB_ACTIVOTEXTO2;
  }

  public String getCECB_NEGRITA2() {
    return CECB_NEGRITA2;
  }

  public void setCECB_NEGRITA2(String cECB_NEGRITA2) {
    CECB_NEGRITA2 = cECB_NEGRITA2;
  }

  public BigDecimal getCECB_TEXTO3FILA() {
    return CECB_TEXTO3FILA;
  }

  public void setCECB_TEXTO3FILA(BigDecimal cECB_TEXTO3FILA) {
    CECB_TEXTO3FILA = cECB_TEXTO3FILA;
  }

  public BigDecimal getCECB_TEXTO3COLUMNA() {
    return CECB_TEXTO3COLUMNA;
  }

  public void setCECB_TEXTO3COLUMNA(BigDecimal cECB_TEXTO3COLUMNA) {
    CECB_TEXTO3COLUMNA = cECB_TEXTO3COLUMNA;
  }

  public BigDecimal getCECB_TEXTO3LARGO() {
    return CECB_TEXTO3LARGO;
  }

  public void setCECB_TEXTO3LARGO(BigDecimal cECB_TEXTO3LARGO) {
    CECB_TEXTO3LARGO = cECB_TEXTO3LARGO;
  }

  public BigDecimal getCECB_TEXTO3TAMANO() {
    return CECB_TEXTO3TAMANO;
  }

  public void setCECB_TEXTO3TAMANO(BigDecimal cECB_TEXTO3TAMANO) {
    CECB_TEXTO3TAMANO = cECB_TEXTO3TAMANO;
  }

  public String getCECB_ACTIVOTEXTO3() {
    return CECB_ACTIVOTEXTO3;
  }

  public void setCECB_ACTIVOTEXTO3(String cECB_ACTIVOTEXTO3) {
    CECB_ACTIVOTEXTO3 = cECB_ACTIVOTEXTO3;
  }

  public String getCECB_NEGRITA3() {
    return CECB_NEGRITA3;
  }

  public void setCECB_NEGRITA3(String cECB_NEGRITA3) {
    CECB_NEGRITA3 = cECB_NEGRITA3;
  }

  public BigDecimal getCECB_TEXTO4FILA() {
    return CECB_TEXTO4FILA;
  }

  public void setCECB_TEXTO4FILA(BigDecimal cECB_TEXTO4FILA) {
    CECB_TEXTO4FILA = cECB_TEXTO4FILA;
  }

  public BigDecimal getCECB_TEXTO4COLUMNA() {
    return CECB_TEXTO4COLUMNA;
  }

  public void setCECB_TEXTO4COLUMNA(BigDecimal cECB_TEXTO4COLUMNA) {
    CECB_TEXTO4COLUMNA = cECB_TEXTO4COLUMNA;
  }

  public BigDecimal getCECB_TEXTO4LARGO() {
    return CECB_TEXTO4LARGO;
  }

  public void setCECB_TEXTO4LARGO(BigDecimal cECB_TEXTO4LARGO) {
    CECB_TEXTO4LARGO = cECB_TEXTO4LARGO;
  }

  public BigDecimal getCECB_TEXTO4TAMANO() {
    return CECB_TEXTO4TAMANO;
  }

  public void setCECB_TEXTO4TAMANO(BigDecimal cECB_TEXTO4TAMANO) {
    CECB_TEXTO4TAMANO = cECB_TEXTO4TAMANO;
  }

  public String getCECB_ACTIVOTEXTO4() {
    return CECB_ACTIVOTEXTO4;
  }

  public void setCECB_ACTIVOTEXTO4(String cECB_ACTIVOTEXTO4) {
    CECB_ACTIVOTEXTO4 = cECB_ACTIVOTEXTO4;
  }

  public String getCECB_NEGRITA4() {
    return CECB_NEGRITA4;
  }

  public void setCECB_NEGRITA4(String cECB_NEGRITA4) {
    CECB_NEGRITA4 = cECB_NEGRITA4;
  }

  public BigDecimal getCECB_TEXTO5FILA() {
    return CECB_TEXTO5FILA;
  }

  public void setCECB_TEXTO5FILA(BigDecimal cECB_TEXTO5FILA) {
    CECB_TEXTO5FILA = cECB_TEXTO5FILA;
  }

  public BigDecimal getCECB_TEXTO5COLUMNA() {
    return CECB_TEXTO5COLUMNA;
  }

  public void setCECB_TEXTO5COLUMNA(BigDecimal cECB_TEXTO5COLUMNA) {
    CECB_TEXTO5COLUMNA = cECB_TEXTO5COLUMNA;
  }

  public BigDecimal getCECB_TEXTO5LARGO() {
    return CECB_TEXTO5LARGO;
  }

  public void setCECB_TEXTO5LARGO(BigDecimal cECB_TEXTO5LARGO) {
    CECB_TEXTO5LARGO = cECB_TEXTO5LARGO;
  }

  public BigDecimal getCECB_TEXTO5TAMANO() {
    return CECB_TEXTO5TAMANO;
  }

  public void setCECB_TEXTO5TAMANO(BigDecimal cECB_TEXTO5TAMANO) {
    CECB_TEXTO5TAMANO = cECB_TEXTO5TAMANO;
  }

  public String getCECB_ACTIVOTEXTO5() {
    return CECB_ACTIVOTEXTO5;
  }

  public void setCECB_ACTIVOTEXTO5(String cECB_ACTIVOTEXTO5) {
    CECB_ACTIVOTEXTO5 = cECB_ACTIVOTEXTO5;
  }

  public String getCECB_NEGRITA5() {
    return CECB_NEGRITA5;
  }

  public void setCECB_NEGRITA5(String cECB_NEGRITA5) {
    CECB_NEGRITA5 = cECB_NEGRITA5;
  }

  public BigDecimal getCECB_TEXTO6FILA() {
    return CECB_TEXTO6FILA;
  }

  public void setCECB_TEXTO6FILA(BigDecimal cECB_TEXTO6FILA) {
    CECB_TEXTO6FILA = cECB_TEXTO6FILA;
  }

  public BigDecimal getCECB_TEXTO6COLUMNA() {
    return CECB_TEXTO6COLUMNA;
  }

  public void setCECB_TEXTO6COLUMNA(BigDecimal cECB_TEXTO6COLUMNA) {
    CECB_TEXTO6COLUMNA = cECB_TEXTO6COLUMNA;
  }

  public BigDecimal getCECB_TEXTO6LARGO() {
    return CECB_TEXTO6LARGO;
  }

  public void setCECB_TEXTO6LARGO(BigDecimal cECB_TEXTO6LARGO) {
    CECB_TEXTO6LARGO = cECB_TEXTO6LARGO;
  }

  public BigDecimal getCECB_TEXTO6TAMANO() {
    return CECB_TEXTO6TAMANO;
  }

  public void setCECB_TEXTO6TAMANO(BigDecimal cECB_TEXTO6TAMANO) {
    CECB_TEXTO6TAMANO = cECB_TEXTO6TAMANO;
  }

  public String getCECB_ACTIVOTEXTO6() {
    return CECB_ACTIVOTEXTO6;
  }

  public void setCECB_ACTIVOTEXTO6(String cECB_ACTIVOTEXTO6) {
    CECB_ACTIVOTEXTO6 = cECB_ACTIVOTEXTO6;
  }

  public String getCECB_NEGRITA6() {
    return CECB_NEGRITA6;
  }

  public void setCECB_NEGRITA6(String cECB_NEGRITA6) {
    CECB_NEGRITA6 = cECB_NEGRITA6;
  }

  public BigDecimal getCECB_TEXTO7FILA() {
    return CECB_TEXTO7FILA;
  }

  public void setCECB_TEXTO7FILA(BigDecimal cECB_TEXTO7FILA) {
    CECB_TEXTO7FILA = cECB_TEXTO7FILA;
  }

  public BigDecimal getCECB_TEXTO7COLUMNA() {
    return CECB_TEXTO7COLUMNA;
  }

  public void setCECB_TEXTO7COLUMNA(BigDecimal cECB_TEXTO7COLUMNA) {
    CECB_TEXTO7COLUMNA = cECB_TEXTO7COLUMNA;
  }

  public BigDecimal getCECB_TEXTO7LARGO() {
    return CECB_TEXTO7LARGO;
  }

  public void setCECB_TEXTO7LARGO(BigDecimal cECB_TEXTO7LARGO) {
    CECB_TEXTO7LARGO = cECB_TEXTO7LARGO;
  }

  public BigDecimal getCECB_TEXTO7TAMANO() {
    return CECB_TEXTO7TAMANO;
  }

  public void setCECB_TEXTO7TAMANO(BigDecimal cECB_TEXTO7TAMANO) {
    CECB_TEXTO7TAMANO = cECB_TEXTO7TAMANO;
  }

  public String getCECB_ACTIVOTEXTO7() {
    return CECB_ACTIVOTEXTO7;
  }

  public void setCECB_ACTIVOTEXTO7(String cECB_ACTIVOTEXTO7) {
    CECB_ACTIVOTEXTO7 = cECB_ACTIVOTEXTO7;
  }

  public String getCECB_NEGRITA7() {
    return CECB_NEGRITA7;
  }

  public void setCECB_NEGRITA7(String cECB_NEGRITA7) {
    CECB_NEGRITA7 = cECB_NEGRITA7;
  }

  public BigDecimal getCECB_TEXTO8FILA() {
    return CECB_TEXTO8FILA;
  }

  public void setCECB_TEXTO8FILA(BigDecimal cECB_TEXTO8FILA) {
    CECB_TEXTO8FILA = cECB_TEXTO8FILA;
  }

  public BigDecimal getCECB_TEXTO8COLUMNA() {
    return CECB_TEXTO8COLUMNA;
  }

  public void setCECB_TEXTO8COLUMNA(BigDecimal cECB_TEXTO8COLUMNA) {
    CECB_TEXTO8COLUMNA = cECB_TEXTO8COLUMNA;
  }

  public BigDecimal getCECB_TEXTO8LARGO() {
    return CECB_TEXTO8LARGO;
  }

  public void setCECB_TEXTO8LARGO(BigDecimal cECB_TEXTO8LARGO) {
    CECB_TEXTO8LARGO = cECB_TEXTO8LARGO;
  }

  public BigDecimal getCECB_TEXTO8TAMANO() {
    return CECB_TEXTO8TAMANO;
  }

  public void setCECB_TEXTO8TAMANO(BigDecimal cECB_TEXTO8TAMANO) {
    CECB_TEXTO8TAMANO = cECB_TEXTO8TAMANO;
  }

  public String getCECB_ACTIVOTEXTO8() {
    return CECB_ACTIVOTEXTO8;
  }

  public void setCECB_ACTIVOTEXTO8(String cECB_ACTIVOTEXTO8) {
    CECB_ACTIVOTEXTO8 = cECB_ACTIVOTEXTO8;
  }

  public String getCECB_NEGRITA8() {
    return CECB_NEGRITA8;
  }

  public void setCECB_NEGRITA8(String cECB_NEGRITA8) {
    CECB_NEGRITA8 = cECB_NEGRITA8;
  }

  public BigDecimal getCECB_TEXTO9FILA() {
    return CECB_TEXTO9FILA;
  }

  public void setCECB_TEXTO9FILA(BigDecimal cECB_TEXTO9FILA) {
    CECB_TEXTO9FILA = cECB_TEXTO9FILA;
  }

  public BigDecimal getCECB_TEXTO9COLUMNA() {
    return CECB_TEXTO9COLUMNA;
  }

  public void setCECB_TEXTO9COLUMNA(BigDecimal cECB_TEXTO9COLUMNA) {
    CECB_TEXTO9COLUMNA = cECB_TEXTO9COLUMNA;
  }

  public BigDecimal getCECB_TEXTO9LARGO() {
    return CECB_TEXTO9LARGO;
  }

  public void setCECB_TEXTO9LARGO(BigDecimal cECB_TEXTO9LARGO) {
    CECB_TEXTO9LARGO = cECB_TEXTO9LARGO;
  }

  public BigDecimal getCECB_TEXTO9TAMANO() {
    return CECB_TEXTO9TAMANO;
  }

  public void setCECB_TEXTO9TAMANO(BigDecimal cECB_TEXTO9TAMANO) {
    CECB_TEXTO9TAMANO = cECB_TEXTO9TAMANO;
  }

  public String getCECB_ACTIVOTEXTO9() {
    return CECB_ACTIVOTEXTO9;
  }

  public void setCECB_ACTIVOTEXTO9(String cECB_ACTIVOTEXTO9) {
    CECB_ACTIVOTEXTO9 = cECB_ACTIVOTEXTO9;
  }

  public String getCECB_NEGRITA9() {
    return CECB_NEGRITA9;
  }

  public void setCECB_NEGRITA9(String cECB_NEGRITA9) {
    CECB_NEGRITA9 = cECB_NEGRITA9;
  }

  public BigDecimal getCECB_TEXTO10FILA() {
    return CECB_TEXTO10FILA;
  }

  public void setCECB_TEXTO10FILA(BigDecimal cECB_TEXTO10FILA) {
    CECB_TEXTO10FILA = cECB_TEXTO10FILA;
  }

  public BigDecimal getCECB_TEXTO10COLUMNA() {
    return CECB_TEXTO10COLUMNA;
  }

  public void setCECB_TEXTO10COLUMNA(BigDecimal cECB_TEXTO10COLUMNA) {
    CECB_TEXTO10COLUMNA = cECB_TEXTO10COLUMNA;
  }

  public BigDecimal getCECB_TEXTO10LARGO() {
    return CECB_TEXTO10LARGO;
  }

  public void setCECB_TEXTO10LARGO(BigDecimal cECB_TEXTO10LARGO) {
    CECB_TEXTO10LARGO = cECB_TEXTO10LARGO;
  }

  public BigDecimal getCECB_TEXTO10TAMANO() {
    return CECB_TEXTO10TAMANO;
  }

  public void setCECB_TEXTO10TAMANO(BigDecimal cECB_TEXTO10TAMANO) {
    CECB_TEXTO10TAMANO = cECB_TEXTO10TAMANO;
  }

  public String getCECB_ACTIVOTEXTO10() {
    return CECB_ACTIVOTEXTO10;
  }

  public void setCECB_ACTIVOTEXTO10(String cECB_ACTIVOTEXTO10) {
    CECB_ACTIVOTEXTO10 = cECB_ACTIVOTEXTO10;
  }

  public String getCECB_NEGRITA10() {
    return CECB_NEGRITA10;
  }

  public void setCECB_NEGRITA10(String cECB_NEGRITA10) {
    CECB_NEGRITA10 = cECB_NEGRITA10;
  }

  public BigDecimal getCECB_TEXTO11FILA() {
    return CECB_TEXTO11FILA;
  }

  public void setCECB_TEXTO11FILA(BigDecimal cECB_TEXTO11FILA) {
    CECB_TEXTO11FILA = cECB_TEXTO11FILA;
  }

  public BigDecimal getCECB_TEXTO11COLUMNA() {
    return CECB_TEXTO11COLUMNA;
  }

  public void setCECB_TEXTO11COLUMNA(BigDecimal cECB_TEXTO11COLUMNA) {
    CECB_TEXTO11COLUMNA = cECB_TEXTO11COLUMNA;
  }

  public BigDecimal getCECB_TEXTO11LARGO() {
    return CECB_TEXTO11LARGO;
  }

  public void setCECB_TEXTO11LARGO(BigDecimal cECB_TEXTO11LARGO) {
    CECB_TEXTO11LARGO = cECB_TEXTO11LARGO;
  }

  public BigDecimal getCECB_TEXTO11TAMANO() {
    return CECB_TEXTO11TAMANO;
  }

  public void setCECB_TEXTO11TAMANO(BigDecimal cECB_TEXTO11TAMANO) {
    CECB_TEXTO11TAMANO = cECB_TEXTO11TAMANO;
  }

  public String getCECB_ACTIVOTEXTO11() {
    return CECB_ACTIVOTEXTO11;
  }

  public void setCECB_ACTIVOTEXTO11(String cECB_ACTIVOTEXTO11) {
    CECB_ACTIVOTEXTO11 = cECB_ACTIVOTEXTO11;
  }

  public String getCECB_NEGRITA11() {
    return CECB_NEGRITA11;
  }

  public void setCECB_NEGRITA11(String cECB_NEGRITA11) {
    CECB_NEGRITA11 = cECB_NEGRITA11;
  }

  public BigDecimal getCECB_TEXTO12FILA() {
    return CECB_TEXTO12FILA;
  }

  public void setCECB_TEXTO12FILA(BigDecimal cECB_TEXTO12FILA) {
    CECB_TEXTO12FILA = cECB_TEXTO12FILA;
  }

  public BigDecimal getCECB_TEXTO12COLUMNA() {
    return CECB_TEXTO12COLUMNA;
  }

  public void setCECB_TEXTO12COLUMNA(BigDecimal cECB_TEXTO12COLUMNA) {
    CECB_TEXTO12COLUMNA = cECB_TEXTO12COLUMNA;
  }

  public BigDecimal getCECB_TEXTO12LARGO() {
    return CECB_TEXTO12LARGO;
  }

  public void setCECB_TEXTO12LARGO(BigDecimal cECB_TEXTO12LARGO) {
    CECB_TEXTO12LARGO = cECB_TEXTO12LARGO;
  }

  public BigDecimal getCECB_TEXTO12TAMANO() {
    return CECB_TEXTO12TAMANO;
  }

  public void setCECB_TEXTO12TAMANO(BigDecimal cECB_TEXTO12TAMANO) {
    CECB_TEXTO12TAMANO = cECB_TEXTO12TAMANO;
  }

  public String getCECB_ACTIVOTEXTO12() {
    return CECB_ACTIVOTEXTO12;
  }

  public void setCECB_ACTIVOTEXTO12(String cECB_ACTIVOTEXTO12) {
    CECB_ACTIVOTEXTO12 = cECB_ACTIVOTEXTO12;
  }

  public String getCECB_NEGRITA12() {
    return CECB_NEGRITA12;
  }

  public void setCECB_NEGRITA12(String cECB_NEGRITA12) {
    CECB_NEGRITA12 = cECB_NEGRITA12;
  }

  public BigDecimal getCECB_SORT() {
    return CECB_SORT;
  }

  public void setCECB_SORT(BigDecimal cECB_SORT) {
    CECB_SORT = cECB_SORT;
  }

  public String getCECB_NOTA() {
    return CECB_NOTA;
  }

  public void setCECB_NOTA(String cECB_NOTA) {
    CECB_NOTA = cECB_NOTA;
  }

  public String getCECB_USUARIOREGISTRO() {
    return CECB_USUARIOREGISTRO;
  }

  public void setCECB_USUARIOREGISTRO(String cECB_USUARIOREGISTRO) {
    CECB_USUARIOREGISTRO = cECB_USUARIOREGISTRO;
  }

  public Date getCECB_FECHAREGISTRO() {
    return CECB_FECHAREGISTRO;
  }

  public void setCECB_FECHAREGISTRO(Date cECB_FECHAREGISTRO) {
    CECB_FECHAREGISTRO = cECB_FECHAREGISTRO;
  }

  public String getCECB_PROCEDENCIA() {
    return CECB_PROCEDENCIA;
  }

  public void setCECB_PROCEDENCIA(String cECB_PROCEDENCIA) {
    CECB_PROCEDENCIA = cECB_PROCEDENCIA;
  }

  public String getCECB_SERVICIO() {
    return CECB_SERVICIO;
  }

  public void setCECB_SERVICIO(String cECB_SERVICIO) {
    CECB_SERVICIO = cECB_SERVICIO;
  }

  public String getCECB_TIPOPACPREFIJO() {
    return CECB_TIPOPACPREFIJO;
  }

  public void setCECB_TIPOPACPREFIJO(String cECB_TIPOPACPREFIJO) {
    CECB_TIPOPACPREFIJO = cECB_TIPOPACPREFIJO;
  }

  public String getCECB_TIPOPACSUFIJO() {
    return CECB_TIPOPACSUFIJO;
  }

  public void setCECB_TIPOPACSUFIJO(String cECB_TIPOPACSUFIJO) {
    CECB_TIPOPACSUFIJO = cECB_TIPOPACSUFIJO;
  }

  public String getCECB_PROCEPREFIJO() {
    return CECB_PROCEPREFIJO;
  }

  public void setCECB_PROCEPREFIJO(String cECB_PROCEPREFIJO) {
    CECB_PROCEPREFIJO = cECB_PROCEPREFIJO;
  }

  public String getCECB_PROCESUFIJO() {
    return CECB_PROCESUFIJO;
  }

  public void setCECB_PROCESUFIJO(String cECB_PROCESUFIJO) {
    CECB_PROCESUFIJO = cECB_PROCESUFIJO;
  }

  public String getCECB_SERVPREFIJO() {
    return CECB_SERVPREFIJO;
  }

  public void setCECB_SERVPREFIJO(String cECB_SERVPREFIJO) {
    CECB_SERVPREFIJO = cECB_SERVPREFIJO;
  }

  public String getCECB_SERVSUFIJO() {
    return CECB_SERVSUFIJO;
  }

  public void setCECB_SERVSUFIJO(String cECB_SERVSUFIJO) {
    CECB_SERVSUFIJO = cECB_SERVSUFIJO;
  }

  public String getCECB_NOMBPREFIJO() {
    return CECB_NOMBPREFIJO;
  }

  public void setCECB_NOMBPREFIJO(String cECB_NOMBPREFIJO) {
    CECB_NOMBPREFIJO = cECB_NOMBPREFIJO;
  }

  public String getCECB_NOMBSUFIJO() {
    return CECB_NOMBSUFIJO;
  }

  public void setCECB_NOMBSUFIJO(String cECB_NOMBSUFIJO) {
    CECB_NOMBSUFIJO = cECB_NOMBSUFIJO;
  }

  public String getCECB_SEXOPREFIJO() {
    return CECB_SEXOPREFIJO;
  }

  public void setCECB_SEXOPREFIJO(String cECB_SEXOPREFIJO) {
    CECB_SEXOPREFIJO = cECB_SEXOPREFIJO;
  }

  public String getCECB_SEXOSUFIJO() {
    return CECB_SEXOSUFIJO;
  }

  public void setCECB_SEXOSUFIJO(String cECB_SEXOSUFIJO) {
    CECB_SEXOSUFIJO = cECB_SEXOSUFIJO;
  }

  public String getCECB_EDADPREFIJO() {
    return CECB_EDADPREFIJO;
  }

  public void setCECB_EDADPREFIJO(String cECB_EDADPREFIJO) {
    CECB_EDADPREFIJO = cECB_EDADPREFIJO;
  }

  public String getCECB_EDADSUFIJO() {
    return CECB_EDADSUFIJO;
  }

  public void setCECB_EDADSUFIJO(String cECB_EDADSUFIJO) {
    CECB_EDADSUFIJO = cECB_EDADSUFIJO;
  }

  public String getCECB_TIPMUEPREFIJO() {
    return CECB_TIPMUEPREFIJO;
  }

  public void setCECB_TIPMUEPREFIJO(String cECB_TIPMUEPREFIJO) {
    CECB_TIPMUEPREFIJO = cECB_TIPMUEPREFIJO;
  }

  public String getCECB_TIPMUESUFIJO() {
    return CECB_TIPMUESUFIJO;
  }

  public void setCECB_TIPMUESUFIJO(String cECB_TIPMUESUFIJO) {
    CECB_TIPMUESUFIJO = cECB_TIPMUESUFIJO;
  }

  public String getCECB_ENVAPREFIJO() {
    return CECB_ENVAPREFIJO;
  }

  public void setCECB_ENVAPREFIJO(String cECB_ENVAPREFIJO) {
    CECB_ENVAPREFIJO = cECB_ENVAPREFIJO;
  }

  public String getCECB_ENVASUFIJO() {
    return CECB_ENVASUFIJO;
  }

  public void setCECB_ENVASUFIJO(String cECB_ENVASUFIJO) {
    CECB_ENVASUFIJO = cECB_ENVASUFIJO;
  }

  public String getCECB_FECHAPREFIJO() {
    return CECB_FECHAPREFIJO;
  }

  public void setCECB_FECHAPREFIJO(String cECB_FECHAPREFIJO) {
    CECB_FECHAPREFIJO = cECB_FECHAPREFIJO;
  }

  public String getCECB_FECHASUFIJO() {
    return CECB_FECHASUFIJO;
  }

  public void setCECB_FECHASUFIJO(String cECB_FECHASUFIJO) {
    CECB_FECHASUFIJO = cECB_FECHASUFIJO;
  }

  public String getCECB_PARAMETRIZADA() {
    return CECB_PARAMETRIZADA;
  }

  public void setCECB_PARAMETRIZADA(String cECB_PARAMETRIZADA) {
    CECB_PARAMETRIZADA = cECB_PARAMETRIZADA;
  }

  public String getCECB_RUTPREFIJO() {
    return CECB_RUTPREFIJO;
  }

  public void setCECB_RUTPREFIJO(String cECB_RUTPREFIJO) {
    CECB_RUTPREFIJO = cECB_RUTPREFIJO;
  }

  public String getCECB_RUTSUFIJO() {
    return CECB_RUTSUFIJO;
  }

  public void setCECB_RUTSUFIJO(String cECB_RUTSUFIJO) {
    CECB_RUTSUFIJO = cECB_RUTSUFIJO;
  }

  public EtiquetaCodigoBarraDTO(String cECB_CODIGO, String cECB_DESCRIPCION, String cECB_FONTCODIGOBARRA,
      BigDecimal cECB_TAMANOFONTCODIGOBARRAS, BigDecimal cECB_FILACODIGOBARRAS, BigDecimal cECB_COLUMNACODIGOBARRAS,
      String cECB_ACTIVOCODIGOBARRAS, BigDecimal cECB_TEXTO0FILA, BigDecimal cECB_TEXTO0COLUMNA,
      String cECB_ACTIVOTEXTO0, String cECB_NEGRITA0, String cECB_TAMANO0, BigDecimal cECB_TEXTO1FILA,
      BigDecimal cECB_TEXTO1COLUMNA, BigDecimal cECB_TEXTO1LARGO, BigDecimal cECB_TEXTO1TAMANO,
      String cECB_ACTIVOTEXTO1, String cECB_NEGRITA1, BigDecimal cECB_TEXTO2FILA, BigDecimal cECB_TEXTO2COLUMNA,
      BigDecimal cECB_TEXTO2LARGO, BigDecimal cECB_TEXTO2TAMANO, String cECB_ACTIVOTEXTO2, String cECB_NEGRITA2,
      BigDecimal cECB_TEXTO3FILA, BigDecimal cECB_TEXTO3COLUMNA, BigDecimal cECB_TEXTO3LARGO,
      BigDecimal cECB_TEXTO3TAMANO, String cECB_ACTIVOTEXTO3, String cECB_NEGRITA3, BigDecimal cECB_TEXTO4FILA,
      BigDecimal cECB_TEXTO4COLUMNA, BigDecimal cECB_TEXTO4LARGO, BigDecimal cECB_TEXTO4TAMANO,
      String cECB_ACTIVOTEXTO4, String cECB_NEGRITA4, BigDecimal cECB_TEXTO5FILA, BigDecimal cECB_TEXTO5COLUMNA,
      BigDecimal cECB_TEXTO5LARGO, BigDecimal cECB_TEXTO5TAMANO, String cECB_ACTIVOTEXTO5, String cECB_NEGRITA5,
      BigDecimal cECB_TEXTO6FILA, BigDecimal cECB_TEXTO6COLUMNA, BigDecimal cECB_TEXTO6LARGO,
      BigDecimal cECB_TEXTO6TAMANO, String cECB_ACTIVOTEXTO6, String cECB_NEGRITA6, BigDecimal cECB_TEXTO7FILA,
      BigDecimal cECB_TEXTO7COLUMNA, BigDecimal cECB_TEXTO7LARGO, BigDecimal cECB_TEXTO7TAMANO,
      String cECB_ACTIVOTEXTO7, String cECB_NEGRITA7, BigDecimal cECB_TEXTO8FILA, BigDecimal cECB_TEXTO8COLUMNA,
      BigDecimal cECB_TEXTO8LARGO, BigDecimal cECB_TEXTO8TAMANO, String cECB_ACTIVOTEXTO8, String cECB_NEGRITA8,
      BigDecimal cECB_TEXTO9FILA, BigDecimal cECB_TEXTO9COLUMNA, BigDecimal cECB_TEXTO9LARGO,
      BigDecimal cECB_TEXTO9TAMANO, String cECB_ACTIVOTEXTO9, String cECB_NEGRITA9, BigDecimal cECB_TEXTO10FILA,
      BigDecimal cECB_TEXTO10COLUMNA, BigDecimal cECB_TEXTO10LARGO, BigDecimal cECB_TEXTO10TAMANO,
      String cECB_ACTIVOTEXTO10, String cECB_NEGRITA10, BigDecimal cECB_TEXTO11FILA, BigDecimal cECB_TEXTO11COLUMNA,
      BigDecimal cECB_TEXTO11LARGO, BigDecimal cECB_TEXTO11TAMANO, String cECB_ACTIVOTEXTO11, String cECB_NEGRITA11,
      BigDecimal cECB_TEXTO12FILA, BigDecimal cECB_TEXTO12COLUMNA, BigDecimal cECB_TEXTO12LARGO,
      BigDecimal cECB_TEXTO12TAMANO, String cECB_ACTIVOTEXTO12, String cECB_NEGRITA12, BigDecimal cECB_SORT,
      String cECB_NOTA, String cECB_USUARIOREGISTRO, Date cECB_FECHAREGISTRO, String cECB_PROCEDENCIA,
      String cECB_SERVICIO, String cECB_TIPOPACPREFIJO, String cECB_TIPOPACSUFIJO, String cECB_PROCEPREFIJO,
      String cECB_PROCESUFIJO, String cECB_SERVPREFIJO, String cECB_SERVSUFIJO, String cECB_NOMBPREFIJO,
      String cECB_NOMBSUFIJO, String cECB_SEXOPREFIJO, String cECB_SEXOSUFIJO, String cECB_EDADPREFIJO,
      String cECB_EDADSUFIJO, String cECB_TIPMUEPREFIJO, String cECB_TIPMUESUFIJO, String cECB_ENVAPREFIJO,
      String cECB_ENVASUFIJO, String cECB_FECHAPREFIJO, String cECB_FECHASUFIJO, String cECB_PARAMETRIZADA,
      String cECB_RUTPREFIJO, String cECB_RUTSUFIJO, BigDecimal cECB_FILANORDEN, BigDecimal cECB_COLUMNANORDEN,
      BigDecimal cECB_TEXTONORDEN, BigDecimal cECB_TAMANONORDEN, String cECB_ACTIVONORDEN, String cECB_NEGRITANORDEN) {
    super();
    CECB_CODIGO = cECB_CODIGO;
    CECB_DESCRIPCION = cECB_DESCRIPCION;
    CECB_FONTCODIGOBARRA = cECB_FONTCODIGOBARRA;
    CECB_TAMANOFONTCODIGOBARRAS = cECB_TAMANOFONTCODIGOBARRAS;
    CECB_FILACODIGOBARRAS = cECB_FILACODIGOBARRAS;
    CECB_COLUMNACODIGOBARRAS = cECB_COLUMNACODIGOBARRAS;
    CECB_ACTIVOCODIGOBARRAS = cECB_ACTIVOCODIGOBARRAS;
    CECB_TEXTO0FILA = cECB_TEXTO0FILA;
    CECB_TEXTO0COLUMNA = cECB_TEXTO0COLUMNA;
    CECB_ACTIVOTEXTO0 = cECB_ACTIVOTEXTO0;
    CECB_NEGRITA0 = cECB_NEGRITA0;
    CECB_TAMANO0 = cECB_TAMANO0;
    CECB_TEXTO1FILA = cECB_TEXTO1FILA;
    CECB_TEXTO1COLUMNA = cECB_TEXTO1COLUMNA;
    CECB_TEXTO1LARGO = cECB_TEXTO1LARGO;
    CECB_TEXTO1TAMANO = cECB_TEXTO1TAMANO;
    CECB_ACTIVOTEXTO1 = cECB_ACTIVOTEXTO1;
    CECB_NEGRITA1 = cECB_NEGRITA1;
    CECB_TEXTO2FILA = cECB_TEXTO2FILA;
    CECB_TEXTO2COLUMNA = cECB_TEXTO2COLUMNA;
    CECB_TEXTO2LARGO = cECB_TEXTO2LARGO;
    CECB_TEXTO2TAMANO = cECB_TEXTO2TAMANO;
    CECB_ACTIVOTEXTO2 = cECB_ACTIVOTEXTO2;
    CECB_NEGRITA2 = cECB_NEGRITA2;
    CECB_TEXTO3FILA = cECB_TEXTO3FILA;
    CECB_TEXTO3COLUMNA = cECB_TEXTO3COLUMNA;
    CECB_TEXTO3LARGO = cECB_TEXTO3LARGO;
    CECB_TEXTO3TAMANO = cECB_TEXTO3TAMANO;
    CECB_ACTIVOTEXTO3 = cECB_ACTIVOTEXTO3;
    CECB_NEGRITA3 = cECB_NEGRITA3;
    CECB_TEXTO4FILA = cECB_TEXTO4FILA;
    CECB_TEXTO4COLUMNA = cECB_TEXTO4COLUMNA;
    CECB_TEXTO4LARGO = cECB_TEXTO4LARGO;
    CECB_TEXTO4TAMANO = cECB_TEXTO4TAMANO;
    CECB_ACTIVOTEXTO4 = cECB_ACTIVOTEXTO4;
    CECB_NEGRITA4 = cECB_NEGRITA4;
    CECB_TEXTO5FILA = cECB_TEXTO5FILA;
    CECB_TEXTO5COLUMNA = cECB_TEXTO5COLUMNA;
    CECB_TEXTO5LARGO = cECB_TEXTO5LARGO;
    CECB_TEXTO5TAMANO = cECB_TEXTO5TAMANO;
    CECB_ACTIVOTEXTO5 = cECB_ACTIVOTEXTO5;
    CECB_NEGRITA5 = cECB_NEGRITA5;
    CECB_TEXTO6FILA = cECB_TEXTO6FILA;
    CECB_TEXTO6COLUMNA = cECB_TEXTO6COLUMNA;
    CECB_TEXTO6LARGO = cECB_TEXTO6LARGO;
    CECB_TEXTO6TAMANO = cECB_TEXTO6TAMANO;
    CECB_ACTIVOTEXTO6 = cECB_ACTIVOTEXTO6;
    CECB_NEGRITA6 = cECB_NEGRITA6;
    CECB_TEXTO7FILA = cECB_TEXTO7FILA;
    CECB_TEXTO7COLUMNA = cECB_TEXTO7COLUMNA;
    CECB_TEXTO7LARGO = cECB_TEXTO7LARGO;
    CECB_TEXTO7TAMANO = cECB_TEXTO7TAMANO;
    CECB_ACTIVOTEXTO7 = cECB_ACTIVOTEXTO7;
    CECB_NEGRITA7 = cECB_NEGRITA7;
    CECB_TEXTO8FILA = cECB_TEXTO8FILA;
    CECB_TEXTO8COLUMNA = cECB_TEXTO8COLUMNA;
    CECB_TEXTO8LARGO = cECB_TEXTO8LARGO;
    CECB_TEXTO8TAMANO = cECB_TEXTO8TAMANO;
    CECB_ACTIVOTEXTO8 = cECB_ACTIVOTEXTO8;
    CECB_NEGRITA8 = cECB_NEGRITA8;
    CECB_TEXTO9FILA = cECB_TEXTO9FILA;
    CECB_TEXTO9COLUMNA = cECB_TEXTO9COLUMNA;
    CECB_TEXTO9LARGO = cECB_TEXTO9LARGO;
    CECB_TEXTO9TAMANO = cECB_TEXTO9TAMANO;
    CECB_ACTIVOTEXTO9 = cECB_ACTIVOTEXTO9;
    CECB_NEGRITA9 = cECB_NEGRITA9;
    CECB_TEXTO10FILA = cECB_TEXTO10FILA;
    CECB_TEXTO10COLUMNA = cECB_TEXTO10COLUMNA;
    CECB_TEXTO10LARGO = cECB_TEXTO10LARGO;
    CECB_TEXTO10TAMANO = cECB_TEXTO10TAMANO;
    CECB_ACTIVOTEXTO10 = cECB_ACTIVOTEXTO10;
    CECB_NEGRITA10 = cECB_NEGRITA10;
    CECB_TEXTO11FILA = cECB_TEXTO11FILA;
    CECB_TEXTO11COLUMNA = cECB_TEXTO11COLUMNA;
    CECB_TEXTO11LARGO = cECB_TEXTO11LARGO;
    CECB_TEXTO11TAMANO = cECB_TEXTO11TAMANO;
    CECB_ACTIVOTEXTO11 = cECB_ACTIVOTEXTO11;
    CECB_NEGRITA11 = cECB_NEGRITA11;
    CECB_TEXTO12FILA = cECB_TEXTO12FILA;
    CECB_TEXTO12COLUMNA = cECB_TEXTO12COLUMNA;
    CECB_TEXTO12LARGO = cECB_TEXTO12LARGO;
    CECB_TEXTO12TAMANO = cECB_TEXTO12TAMANO;
    CECB_ACTIVOTEXTO12 = cECB_ACTIVOTEXTO12;
    CECB_NEGRITA12 = cECB_NEGRITA12;
    CECB_SORT = cECB_SORT;
    CECB_NOTA = cECB_NOTA;
    CECB_USUARIOREGISTRO = cECB_USUARIOREGISTRO;
    CECB_FECHAREGISTRO = cECB_FECHAREGISTRO;
    CECB_PROCEDENCIA = cECB_PROCEDENCIA;
    CECB_SERVICIO = cECB_SERVICIO;
    CECB_TIPOPACPREFIJO = cECB_TIPOPACPREFIJO;
    CECB_TIPOPACSUFIJO = cECB_TIPOPACSUFIJO;
    CECB_PROCEPREFIJO = cECB_PROCEPREFIJO;
    CECB_PROCESUFIJO = cECB_PROCESUFIJO;
    CECB_SERVPREFIJO = cECB_SERVPREFIJO;
    CECB_SERVSUFIJO = cECB_SERVSUFIJO;
    CECB_NOMBPREFIJO = cECB_NOMBPREFIJO;
    CECB_NOMBSUFIJO = cECB_NOMBSUFIJO;
    CECB_SEXOPREFIJO = cECB_SEXOPREFIJO;
    CECB_SEXOSUFIJO = cECB_SEXOSUFIJO;
    CECB_EDADPREFIJO = cECB_EDADPREFIJO;
    CECB_EDADSUFIJO = cECB_EDADSUFIJO;
    CECB_TIPMUEPREFIJO = cECB_TIPMUEPREFIJO;
    CECB_TIPMUESUFIJO = cECB_TIPMUESUFIJO;
    CECB_ENVAPREFIJO = cECB_ENVAPREFIJO;
    CECB_ENVASUFIJO = cECB_ENVASUFIJO;
    CECB_FECHAPREFIJO = cECB_FECHAPREFIJO;
    CECB_FECHASUFIJO = cECB_FECHASUFIJO;
    CECB_PARAMETRIZADA = cECB_PARAMETRIZADA;
    CECB_RUTPREFIJO = cECB_RUTPREFIJO;
    CECB_RUTSUFIJO = cECB_RUTSUFIJO;
    CECB_FILANORDEN = cECB_FILANORDEN;
    CECB_COLUMNANORDEN = cECB_COLUMNANORDEN;
    CECB_TEXTONORDEN = cECB_TEXTONORDEN;
    CECB_TAMANONORDEN = cECB_TAMANONORDEN;
    CECB_ACTIVONORDEN = cECB_ACTIVONORDEN;
    CECB_NEGRITANORDEN = cECB_NEGRITANORDEN;
  }

  @Override
  public String toString() {
    return "EtiquetaCodigoBarraDTO [CECB_CODIGO=" + CECB_CODIGO + ", CECB_DESCRIPCION=" + CECB_DESCRIPCION
        + ", CECB_FONTCODIGOBARRA=" + CECB_FONTCODIGOBARRA + ", CECB_TAMANOFONTCODIGOBARRAS="
        + CECB_TAMANOFONTCODIGOBARRAS + ", CECB_FILACODIGOBARRAS=" + CECB_FILACODIGOBARRAS
        + ", CECB_COLUMNACODIGOBARRAS=" + CECB_COLUMNACODIGOBARRAS + ", CECB_ACTIVOCODIGOBARRAS="
        + CECB_ACTIVOCODIGOBARRAS + ", CECB_TEXTO0FILA=" + CECB_TEXTO0FILA + ", CECB_TEXTO0COLUMNA="
        + CECB_TEXTO0COLUMNA + ", CECB_ACTIVOTEXTO0=" + CECB_ACTIVOTEXTO0 + ", CECB_NEGRITA0=" + CECB_NEGRITA0
        + ", CECB_TAMANO0=" + CECB_TAMANO0 + ", CECB_TEXTO1FILA=" + CECB_TEXTO1FILA + ", CECB_TEXTO1COLUMNA="
        + CECB_TEXTO1COLUMNA + ", CECB_TEXTO1LARGO=" + CECB_TEXTO1LARGO + ", CECB_TEXTO1TAMANO=" + CECB_TEXTO1TAMANO
        + ", CECB_ACTIVOTEXTO1=" + CECB_ACTIVOTEXTO1 + ", CECB_NEGRITA1=" + CECB_NEGRITA1 + ", CECB_TEXTO2FILA="
        + CECB_TEXTO2FILA + ", CECB_TEXTO2COLUMNA=" + CECB_TEXTO2COLUMNA + ", CECB_TEXTO2LARGO=" + CECB_TEXTO2LARGO
        + ", CECB_TEXTO2TAMANO=" + CECB_TEXTO2TAMANO + ", CECB_ACTIVOTEXTO2=" + CECB_ACTIVOTEXTO2 + ", CECB_NEGRITA2="
        + CECB_NEGRITA2 + ", CECB_TEXTO3FILA=" + CECB_TEXTO3FILA + ", CECB_TEXTO3COLUMNA=" + CECB_TEXTO3COLUMNA
        + ", CECB_TEXTO3LARGO=" + CECB_TEXTO3LARGO + ", CECB_TEXTO3TAMANO=" + CECB_TEXTO3TAMANO + ", CECB_ACTIVOTEXTO3="
        + CECB_ACTIVOTEXTO3 + ", CECB_NEGRITA3=" + CECB_NEGRITA3 + ", CECB_TEXTO4FILA=" + CECB_TEXTO4FILA
        + ", CECB_TEXTO4COLUMNA=" + CECB_TEXTO4COLUMNA + ", CECB_TEXTO4LARGO=" + CECB_TEXTO4LARGO
        + ", CECB_TEXTO4TAMANO=" + CECB_TEXTO4TAMANO + ", CECB_ACTIVOTEXTO4=" + CECB_ACTIVOTEXTO4 + ", CECB_NEGRITA4="
        + CECB_NEGRITA4 + ", CECB_TEXTO5FILA=" + CECB_TEXTO5FILA + ", CECB_TEXTO5COLUMNA=" + CECB_TEXTO5COLUMNA
        + ", CECB_TEXTO5LARGO=" + CECB_TEXTO5LARGO + ", CECB_TEXTO5TAMANO=" + CECB_TEXTO5TAMANO + ", CECB_ACTIVOTEXTO5="
        + CECB_ACTIVOTEXTO5 + ", CECB_NEGRITA5=" + CECB_NEGRITA5 + ", CECB_TEXTO6FILA=" + CECB_TEXTO6FILA
        + ", CECB_TEXTO6COLUMNA=" + CECB_TEXTO6COLUMNA + ", CECB_TEXTO6LARGO=" + CECB_TEXTO6LARGO
        + ", CECB_TEXTO6TAMANO=" + CECB_TEXTO6TAMANO + ", CECB_ACTIVOTEXTO6=" + CECB_ACTIVOTEXTO6 + ", CECB_NEGRITA6="
        + CECB_NEGRITA6 + ", CECB_TEXTO7FILA=" + CECB_TEXTO7FILA + ", CECB_TEXTO7COLUMNA=" + CECB_TEXTO7COLUMNA
        + ", CECB_TEXTO7LARGO=" + CECB_TEXTO7LARGO + ", CECB_TEXTO7TAMANO=" + CECB_TEXTO7TAMANO + ", CECB_ACTIVOTEXTO7="
        + CECB_ACTIVOTEXTO7 + ", CECB_NEGRITA7=" + CECB_NEGRITA7 + ", CECB_TEXTO8FILA=" + CECB_TEXTO8FILA
        + ", CECB_TEXTO8COLUMNA=" + CECB_TEXTO8COLUMNA + ", CECB_TEXTO8LARGO=" + CECB_TEXTO8LARGO
        + ", CECB_TEXTO8TAMANO=" + CECB_TEXTO8TAMANO + ", CECB_ACTIVOTEXTO8=" + CECB_ACTIVOTEXTO8 + ", CECB_NEGRITA8="
        + CECB_NEGRITA8 + ", CECB_TEXTO9FILA=" + CECB_TEXTO9FILA + ", CECB_TEXTO9COLUMNA=" + CECB_TEXTO9COLUMNA
        + ", CECB_TEXTO9LARGO=" + CECB_TEXTO9LARGO + ", CECB_TEXTO9TAMANO=" + CECB_TEXTO9TAMANO + ", CECB_ACTIVOTEXTO9="
        + CECB_ACTIVOTEXTO9 + ", CECB_NEGRITA9=" + CECB_NEGRITA9 + ", CECB_TEXTO10FILA=" + CECB_TEXTO10FILA
        + ", CECB_TEXTO10COLUMNA=" + CECB_TEXTO10COLUMNA + ", CECB_TEXTO10LARGO=" + CECB_TEXTO10LARGO
        + ", CECB_TEXTO10TAMANO=" + CECB_TEXTO10TAMANO + ", CECB_ACTIVOTEXTO10=" + CECB_ACTIVOTEXTO10
        + ", CECB_NEGRITA10=" + CECB_NEGRITA10 + ", CECB_TEXTO11FILA=" + CECB_TEXTO11FILA + ", CECB_TEXTO11COLUMNA="
        + CECB_TEXTO11COLUMNA + ", CECB_TEXTO11LARGO=" + CECB_TEXTO11LARGO + ", CECB_TEXTO11TAMANO="
        + CECB_TEXTO11TAMANO + ", CECB_ACTIVOTEXTO11=" + CECB_ACTIVOTEXTO11 + ", CECB_NEGRITA11=" + CECB_NEGRITA11
        + ", CECB_TEXTO12FILA=" + CECB_TEXTO12FILA + ", CECB_TEXTO12COLUMNA=" + CECB_TEXTO12COLUMNA
        + ", CECB_TEXTO12LARGO=" + CECB_TEXTO12LARGO + ", CECB_TEXTO12TAMANO=" + CECB_TEXTO12TAMANO
        + ", CECB_ACTIVOTEXTO12=" + CECB_ACTIVOTEXTO12 + ", CECB_NEGRITA12=" + CECB_NEGRITA12 + ", CECB_SORT="
        + CECB_SORT + ", CECB_NOTA=" + CECB_NOTA + ", CECB_USUARIOREGISTRO=" + CECB_USUARIOREGISTRO
        + ", CECB_FECHAREGISTRO=" + CECB_FECHAREGISTRO + ", CECB_PROCEDENCIA=" + CECB_PROCEDENCIA + ", CECB_SERVICIO="
        + CECB_SERVICIO + ", CECB_TIPOPACPREFIJO=" + CECB_TIPOPACPREFIJO + ", CECB_TIPOPACSUFIJO=" + CECB_TIPOPACSUFIJO
        + ", CECB_PROCEPREFIJO=" + CECB_PROCEPREFIJO + ", CECB_PROCESUFIJO=" + CECB_PROCESUFIJO + ", CECB_SERVPREFIJO="
        + CECB_SERVPREFIJO + ", CECB_SERVSUFIJO=" + CECB_SERVSUFIJO + ", CECB_NOMBPREFIJO=" + CECB_NOMBPREFIJO
        + ", CECB_NOMBSUFIJO=" + CECB_NOMBSUFIJO + ", CECB_SEXOPREFIJO=" + CECB_SEXOPREFIJO + ", CECB_SEXOSUFIJO="
        + CECB_SEXOSUFIJO + ", CECB_EDADPREFIJO=" + CECB_EDADPREFIJO + ", CECB_EDADSUFIJO=" + CECB_EDADSUFIJO
        + ", CECB_TIPMUEPREFIJO=" + CECB_TIPMUEPREFIJO + ", CECB_TIPMUESUFIJO=" + CECB_TIPMUESUFIJO
        + ", CECB_ENVAPREFIJO=" + CECB_ENVAPREFIJO + ", CECB_ENVASUFIJO=" + CECB_ENVASUFIJO + ", CECB_FECHAPREFIJO="
        + CECB_FECHAPREFIJO + ", CECB_FECHASUFIJO=" + CECB_FECHASUFIJO + ", CECB_PARAMETRIZADA=" + CECB_PARAMETRIZADA
        + ", CECB_RUTPREFIJO=" + CECB_RUTPREFIJO + ", CECB_RUTSUFIJO=" + CECB_RUTSUFIJO + ", CECB_FILANORDEN="
        + CECB_FILANORDEN + ", CECB_COLUMNANORDEN=" + CECB_COLUMNANORDEN + ", CECB_TEXTONORDEN=" + CECB_TEXTONORDEN
        + ", CECB_TAMANONORDEN=" + CECB_TAMANONORDEN + ", CECB_ACTIVONORDEN=" + CECB_ACTIVONORDEN
        + ", CECB_NEGRITANORDEN=" + CECB_NEGRITANORDEN + "]";
  }

}