/**
 * 
 */

 
DIURESIS = 'DIURESIS';
TEMPERATURA =  'TEMPERATURA';
FIO2 =  'FIO2';
FUR =  'FUR';
GESTACION =  'GESTACIÓN';
MEDICACION =  'MEDICACIÓN';
ULT_DOSIS =  'ULT DOSIS';
EDAD =  'EDAD';
PESO =  'PESO';
ESTATURA =  'ESTATURA';