mvn install:install-file -Dfile=com.azalea.ufl.barcode.1.0.jar -DgroupId=com.grupobios -DartifactId=barcode -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=CrystalCommon2.jar             -DgroupId=com.grupobios -DartifactId=CrystalCommon -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=CrystalReportsRuntime.jar      -DgroupId=com.grupobios -DartifactId=CrystalRT -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=cvom.jar                       -DgroupId=com.grupobios -DartifactId=cvom -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=DatabaseConnectors.jar         -DgroupId=com.grupobios -DartifactId=DBConnectors -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=icu4j.jar                      -DgroupId=com.grupobios -DartifactId=icu4 -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=jai_imageio.jar                -DgroupId=com.grupobios -DartifactId=jai_imageo -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=JDBInterface.jar               -DgroupId=com.grupobios -DartifactId=JDBInterface -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=jrcerom.jar                    -DgroupId=com.grupobios -DartifactId=jrcerom -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=keycodeDecoder.jar             -DgroupId=com.grupobios -DartifactId=keycodeDecoder -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=pfjgraphics.jar                -DgroupId=com.grupobios -DartifactId=pfjgraphics -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=QueryBuilder.jar               -DgroupId=com.grupobios -DartifactId=QueryBuilder -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=sap.com~tc~sec~csi.jar         -DgroupId=com.grupobios -DartifactId=sap.com~tc~sec~csi -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=webreporting-jsf.jar           -DgroupId=com.grupobios -DartifactId=webreporting-jsf -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=webreporting.jar               -DgroupId=com.grupobios -DartifactId=webreporting -Dversion=0.0 -Dpackaging=jar
mvn install:install-file -Dfile=xpp3.jar                       -DgroupId=com.grupobios -DartifactId=xpp3 -Dversion=0.0 -Dpackaging=jar